#!/usr/bin/env python3
r"""I55 -- P12's ATIYAH SEQUENCE, VERIFIED; AND WHY ITS OBSTRUCTION IS HOLONOMY AND NOT A CLASS.

** WHAT THE PAPER ASSERTS.  ** `algebroid_paper.tex` `sec:anchor` L186: *"at the symmetric cut
$\so(5,1)=\fh\oplus\fm$ with $\fh=\so(4,1)$ the cut-fixing isotropy and $\fm$ the cut-deforming coset,
and the symmetric-space relation $[\fm,\fm]\subset\fh$ holds; this grading is the Atiyah sequence of
the principal bundle $SO(5,1)\to\dS_5$"*, exact, *"with $\fh$ the kernel of the anchor -- the adjoint
bundle, ten-dimensional -- and $\fm$ its image, the five dimensions of the base, closing at
$10+5=15=\dim\so(5,1)$"*.  ** Three assertions: a dimension count, a direct sum, and
$[\fm,\fm]\subset\fh$. **  *All three are verified here on explicit matrices.*

⛭ ** AND THE ROW'S PREDICTION IS CONFIRMED ON THE ABSENCE AND REFUTED ON THE REASON, which is the
informative half. **  *The locator predicted that "the obstruction to a FLAT connection is a
characteristic class the paper does not name".  Measured: `characteristic class` x0, `Chern` x0,
`obstruction to` x0 -- the absence is real.*
  ⛔ ** But the paper's route is BETTER than the one it was predicted to be missing. **  *It reaches
  the obstruction through AMBROSE--SINGER: "the holonomy algebra is generated by the curvature, so a
  flat connection has discrete holonomy", `\ldg{cartan_holonomy}`.*
    ⇒ *** A characteristic class gives only a NECESSARY condition for flatness (Chern--Weil: a flat
        bundle has vanishing real classes) and never a sufficient one.  Holonomy decides it. ***

⛔⛭ ** AND A CLASS IS NOT MERELY UNNAMED HERE -- IT IS NOT COMPUTABLE, FOR A REASON WORTH RECORDING. **
*The bundle in question sits over the space of cuts $\C$, and* ** `algebroid_paper.tex` never fixes
$\C$'s topology: `simply connected` x0, `contractible` x0, `topology of` x0, `homotopy type` x0,
`fundamental group` x0, `pi_1` x0. **  *No characteristic class of a bundle can be evaluated over a
base whose homotopy type is unstated.*
  ⇒ ** So the paper's choice is forced rather than stylistic, and that is the answer to a reader who
    asks why it does not simply compute a class.  The holonomy route works precisely BECAUSE it is
    local-differential -- curvature-generated -- and needs no global topology. **

COMPUTES: scope.
  * ** The algebra is $\so(5,1)$ in the signature $(-,+,+,+,+,+)$ and the isotropy is the $\so(4,1)$
    fixing the first spatial axis. **  *The three assertions are algebraic identities and do not
    depend on the choice of that axis; the sweep over which axis is fixed is the control.*
  * ** NOT CLAIMED: anything about $\C$'s topology, or about whether a flat connection exists. **
    *This verifies the SEQUENCE the paper writes and measures the absence of the class vocabulary.
    The flatness question is the paper's own and rests on its structure-function argument.*

Written r3674 by node 60, pass B on row 9 of the index-theory locator (`P12`).
"""
import itertools

import numpy as np

np.random.seed(12)

ETA = np.diag([-1.0, 1.0, 1.0, 1.0, 1.0, 1.0])      # so(5,1)


def basis_so51():
    r"""a basis of $\so(5,1) = \{X : X^{T}\eta + \eta X = 0\}$, as $6\times6$ matrices"""
    B = []
    for i, j in itertools.combinations(range(6), 2):
        X = np.zeros((6, 6))
        # eta-antisymmetric generator in the (i,j) plane
        X[i, j] = ETA[j, j]
        X[j, i] = -ETA[i, i]
        B.append(X)
    return B


def in_algebra(X, tol=1e-12):
    return np.max(np.abs(X.T @ ETA + ETA @ X)) < tol


def split(fixed_axis):
    r"""$\fh$ = the $\so(4,1)$ fixing `fixed_axis`; $\fm$ = its complement in $\so(5,1)$"""
    h, m = [], []
    for X in basis_so51():
        # a generator lies in the isotropy iff it annihilates the fixed axis
        e = np.zeros(6); e[fixed_axis] = 1.0
        (h if np.max(np.abs(X @ e)) < 1e-12 else m).append(X)
    return h, m


def span_rank(mats):
    if not mats:
        return 0
    M = np.array([X.flatten() for X in mats])
    s = np.linalg.svd(M, compute_uv=False)
    return int(np.sum(s > max(M.shape) * s[0] * 1e-10))


def contained_in(mats, basis, tol=1e-9):
    """is every matrix in `mats` inside the span of `basis`?"""
    if not basis:
        return all(np.max(np.abs(X)) < tol for X in mats)
    B = np.array([X.flatten() for X in basis]).T
    worst = 0.0
    for X in mats:
        v = X.flatten()
        coef, *_ = np.linalg.lstsq(B, v, rcond=None)
        worst = max(worst, float(np.max(np.abs(B @ coef - v))))
    return worst < tol, worst


def brackets(A, B):
    return [a @ b - b @ a for a in A for b in B]


if __name__ == '__main__':
    print(__doc__)
    print('=' * 78)
    print("(A) THE PAPER'S THREE ASSERTIONS, on explicit matrices")
    print('=' * 78)
    h, m = split(1)
    dh, dm = span_rank(h), span_rank(m)
    dg = span_rank(basis_so51())
    ok_alg = all(in_algebra(X) for X in basis_so51())
    sym, worst = contained_in(brackets(m, m), h)
    print(f'    every basis element satisfies X^T eta + eta X = 0 : {ok_alg}')
    print(f'    dim h (the isotropy so(4,1), kernel of the anchor) = {dh}')
    print(f'    dim m (the coset, image of the anchor, the base)   = {dm}')
    print(f'    dim h + dim m = {dh + dm}    dim so(5,1) = {dg}')
    print(f'    [m,m] contained in h : {sym}   (worst residual {worst:.2e})')
    print()
    print("    ⇒ the paper's '10 + 5 = 15 = dim so(5,1)' and its symmetric-space")
    print('      relation both hold, so the exact sequence it writes is the one it has.')

    print()
    print('=' * 78)
    print('(B) THE CONTROL — the identities must not depend on which axis is fixed')
    print('=' * 78)
    rows = []
    for ax in (1, 2, 3, 4, 5):
        hh, mm = split(ax)
        s, _ = contained_in(brackets(mm, mm), hh)
        rows.append((span_rank(hh), span_rank(mm), s))
        print(f'    fixed axis {ax} :  dim h = {span_rank(hh)}  dim m = {span_rank(mm)}  '
              f'[m,m] in h : {s}')

    print()
    print('=' * 78)
    print('(C) THE CONTROL THAT CAN FAIL — a NON-symmetric split must break [m,m] in h')
    print('=' * 78)
    B = basis_so51()
    h_bad, m_bad = B[:10], B[10:]          # an arbitrary 10/5 split, not the isotropy
    s_bad, worst_bad = contained_in(brackets(m_bad, m_bad), h_bad)
    print(f'    arbitrary 10/5 split :  [m,m] in h : {s_bad}   (worst residual {worst_bad:.3f})')
    print('    ⇒ the relation is the SYMMETRIC-SPACE structure and not an accident of')
    print('      counting to ten and five, so (A) is a measurement and not arithmetic.')

    print()
    print('=' * 78)
    print("(D) THE CLASS VOCABULARY, AND THE BASE'S TOPOLOGY — both measured absent")
    print('=' * 78)
    import re
    src = open('corpus/algebroid_paper.tex', encoding='utf-8', errors='replace').read()
    counts = {w: len(re.findall(w, src, re.I)) for w in
              ['characteristic class', 'Chern', 'obstruction to', 'simply connected',
               'contractible', 'topology of', 'homotopy type', 'fundamental group']}
    for w, n in counts.items():
        print(f'    {w:<22} x{n}')
    print()
    print('    ⇒ no class is named, AND none could be evaluated: the bundle sits over the')
    print("      space of cuts C and the paper never fixes C's homotopy type.  The holonomy")
    print('      route is forced, not preferred.')

    # ⛔⛭ pinned to measured values -- never `expr == True`
    assert ok_alg
    assert (dh, dm, dg) == (10, 5, 15), (dh, dm, dg)
    assert sym and worst < 1e-9, (sym, worst)
    assert all(r == (10, 5, True) for r in rows), rows
    assert s_bad is False and worst_bad > 0.1, (s_bad, worst_bad)
    assert all(counts[w] == 0 for w in counts), counts
    print()
    print('  ALL PASS')
