#!/usr/bin/env python3
"""check_pin_board.py -- THE PIN-ADJUDICATION BOARD AGREES WITH THE RATCHET, AND NO RECEIPT HAS TWO CLAIMANTS.

** WHY. **  The quote-pin backlog is bounded -- r7247 measured 2,082 unverdicted keys in 342 receipts -- and every
unit of it reached a seat through an order, which made the gating seat the bottleneck.  The board lets seats PULL:
a seat claims a PREFIX (a `receipts/<dir>/` directory), reads its receipts, and verdicts their keys in
`quote_pin_baseline.tsv`.  Prefix granularity guarantees two seats never open the same receipt.

** TWO FILES, BECAUSE A GENERATED FILE CANNOT HOLD A CLAIM (66's named failure mode, r7247). **
    corpus/pin_claims.tsv               HAND-KEPT.  A seat claims by APPENDING a row and pushing before it reads:
                                            prefix <TAB> seat <TAB> CLAIM|RELEASE <TAB> rNNNN <TAB> note
    corpus/pin_adjudication_board.tsv   GENERATED (`scripts/gen_pin_board.py`) from the baseline with the ledger
                                        merged in.  Never hand-edited; a claim written into it would be erased.
  *A receipt leaves the board by having every key verdicted, never by being marked done.*

** THE CHECKS **
  (a) no prefix carries two LIVE claims -- a CLAIM is void if an earlier claim on the prefix is still live when it
      is made, so the first push wins; a seat gives a prefix up early with a RELEASE row.
  (b) the board's unverdicted total EQUALS the baseline's, and the committed board EQUALS a fresh generation --
      so the board can neither disagree with the instrument nor go stale.
  (c) a claim with no PROGRESS for `RELEASE_AFTER_CYCLES` order cycles is RELEASED, not held: the board prints the
      revision it expires after, this gate reports it RELEASED, and the prefix may be claimed again.  It does NOT
      turn the gate red -- a stalled seat must not redden everyone.
      ** The threshold is a STALL rule, not a completion rule. **  Progress -- any commit lowering the prefix's
      unverdicted count -- resets the window, so a 98-receipt prefix and a 3-receipt one stall alike; size sets
      completion time, not cadence.  Measured r7247+70.1 (computations/beyond_the_wall/r7247_70_board_and_claims):
      within a stretch of backlog work, seats lowered the count at gaps of 1, 2 and 3 cycles; the longer gaps (9,
      44) were seats ORDERED elsewhere, which the history cannot tell from a stall.  ⇒ flat, at 3 + 1.
      ⚠ Its cost, stated: a seat pulled onto another order for more than four cycles loses its claim and must
      re-claim.  No work is lost -- verdicts are in the baseline -- so the cost is one appended row.
  (d) seeded both ways on every run (`_seeds`).

    python3 corpus/check_pin_board.py
    python3 scripts/gen_pin_board.py          # regenerate the board after verdicting or claiming

Written r7247+70.1 (node 70) on 66's r7247 order.  Stated for reversal.
"""
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..'))
BASELINE = os.path.join(HERE, 'quote_pin_baseline.tsv')
CLAIMS = os.path.join(HERE, 'pin_claims.tsv')
BOARD = os.path.join(HERE, 'pin_adjudication_board.tsv')
UNVERDICTED = ('UNADJUDICATED', 'UNADJUDICATED-LIST', 'UNADJUDICATED-PINNED')
RELEASE_AFTER_CYCLES = 4          # measured, r7247+70.1 -- see (c) above
REVS_PER_CYCLE = 2                # the trunk numbers its order cycles by two (66 holds the odd half)
HEADER = ('# GENERATED by scripts/gen_pin_board.py from corpus/quote_pin_baseline.tsv and corpus/pin_claims.tsv -- '
          'DO NOT EDIT; claim in pin_claims.tsv.\n'
          '#   prefix <TAB> receipt <TAB> unverdicted <TAB> claimed_by <TAB> claimed_at <TAB> expires_after <TAB> state\n')


def prefix_of(receipt):
    p = receipt.split('/')
    return p[1] if len(p) > 2 and p[0] == 'receipts' else receipt


def counts(baseline_text):
    """{receipt: unverdicted keys}"""
    out = {}
    for ln in baseline_text.split('\n'):
        if ln.strip() and not ln.startswith('#'):
            f = ln.split('\t')
            if len(f) > 5 and f[5] in UNVERDICTED:
                out[f[0]] = out.get(f[0], 0) + 1
    return out


def by_prefix(c):
    out = {}
    for r, n in c.items():
        out[prefix_of(r)] = out.get(prefix_of(r), 0) + n
    return out


def read_claims(text):
    rows = []
    for ln in text.split('\n'):
        if ln.strip() and not ln.startswith('#'):
            f = ln.split('\t') + [''] * 5
            m = re.match(r'r(\d{4})', f[3].strip())
            rows.append(dict(prefix=f[0].strip(), seat=f[1].strip(), kind=f[2].strip().upper(),
                             rev=int(m.group(1)) if m else None, note=f[4].strip()))
    return rows


def progress_history(root=ROOT):
    """[(rev, {prefix: unverdicted})] for every commit touching the baseline, oldest first"""
    out = []
    log = subprocess.run(['git', '-C', root, 'log', '--reverse', '--format=%H%x09%s', '--',
                          'corpus/quote_pin_baseline.tsv'], capture_output=True, text=True).stdout
    for ln in log.split('\n'):
        if '\t' not in ln:
            continue
        h, s = ln.split('\t', 1)
        m = re.search(r'r(\d{4})', s)
        if not m:
            continue
        body = subprocess.run(['git', '-C', root, 'show', f'{h}:corpus/quote_pin_baseline.tsv'],
                              capture_output=True, text=True).stdout
        out.append((int(m.group(1)), by_prefix(counts(body))))
    return out


def last_progress(prefix, since, history):
    """the last revision at or after `since` whose commit LOWERED the prefix's unverdicted count, or `since`"""
    last, prev = since, None
    for rev, pc in history:
        n = pc.get(prefix, 0)
        if prev is not None and n < prev and rev >= since:
            last = max(last, rev)
        prev = n
    return last


def live_claims(claims, history):
    """{prefix: claim} with each claim's expiry, applying first-push-wins; and the list of VOID claims"""
    live, void = {}, []
    for c in claims:
        if c['rev'] is None or not c['prefix']:
            void.append((c, 'no revision id or no prefix'))
            continue
        cur = live.get(c['prefix'])
        if c['kind'] == 'RELEASE':
            if cur and cur['seat'] == c['seat']:
                del live[c['prefix']]
            continue
        if cur and c['rev'] <= cur['expires_after']:
            void.append((c, f"{cur['seat']} holds it until r{cur['expires_after']}"))
            continue
        c = dict(c)
        c['expires_after'] = last_progress(c['prefix'], c['rev'], history) + RELEASE_AFTER_CYCLES * REVS_PER_CYCLE
        live[c['prefix']] = c
    return live, void


def generate(baseline_text, claims_text, history):
    c = counts(baseline_text)
    live, _ = live_claims(read_claims(claims_text), history)
    lines = [HEADER.rstrip('\n')]
    for r in sorted(c, key=lambda r: (prefix_of(r), r)):
        cl = live.get(prefix_of(r))
        lines.append('\t'.join([prefix_of(r), r, str(c[r]), cl['seat'] if cl else '',
                                f"r{cl['rev']}" if cl else '', f"r{cl['expires_after']}" if cl else '',
                                'CLAIMED' if cl else 'OPEN']))
    return '\n'.join(lines) + '\n'


def current_revision(root=ROOT):
    s = subprocess.run(['git', '-C', root, 'log', '-300', '--format=%s', 'HEAD'], capture_output=True,
                       text=True).stdout
    ids = [int(m.group(1)) for m in (re.match(r'\s*r(\d{4})', x) for x in s.split('\n')) if m]
    return max(ids) if ids else 0


def _seeds():
    """(d): each seed must come out as stated, or the gate has lost a direction"""
    bl = ('receipts/A/x.py\tl\tT\tt\tf\tUNADJUDICATED\tw\n'
          'receipts/A/y.py\tl\tT\tt\tf\tDELIBERATE\tw\n'
          'receipts/B/z.py\tl\tT\tt\tf\tUNADJUDICATED-LIST\tw\n')
    hist_flat = [(7200, {'A': 1, 'B': 1}), (7210, {'A': 1, 'B': 1})]
    hist_prog = [(7200, {'A': 2, 'B': 1}), (7210, {'A': 1, 'B': 1})]
    bad = []
    _, void = live_claims(read_claims('A\t60\tCLAIM\tr7200\n' + 'A\t70\tCLAIM\tr7202\n'), hist_flat)
    if len(void) != 1:
        bad.append('a second claim on a held prefix must be void')
    _, void = live_claims(read_claims('A\t60\tCLAIM\tr7200\n' + 'A\t70\tCLAIM\tr7220\n'), hist_flat)
    if void:
        bad.append('a claim after the holder expired must stand')
    live, _ = live_claims(read_claims('A\t60\tCLAIM\tr7200\n'), hist_flat)
    if live['A']['expires_after'] != 7200 + RELEASE_AFTER_CYCLES * REVS_PER_CYCLE:
        bad.append('a stalled claim must expire RELEASE_AFTER_CYCLES after the claim')
    live, _ = live_claims(read_claims('A\t60\tCLAIM\tr7200\n'), hist_prog)
    if live['A']['expires_after'] != 7210 + RELEASE_AFTER_CYCLES * REVS_PER_CYCLE:
        bad.append('progress must reset the window')
    g = generate(bl, 'A\t60\tCLAIM\tr7200\n', hist_flat)
    if sum(int(x.split('\t')[2]) for x in g.split('\n') if x and not x.startswith('#')) != 2:
        bad.append('the board total must equal the unverdicted keys (2 here; DELIBERATE excluded)')
    if g == generate(bl.replace('UNADJUDICATED-LIST', 'DELIBERATE'), 'A\t60\tCLAIM\tr7200\n', hist_flat):
        bad.append('a verdict changing in the baseline must change the board, so a stale board is caught')
    return bad


def main(argv):
    print()
    print('  PIN BOARD -- does the board agree with the ratchet, and is every prefix held by at most one seat?')
    print()
    bad = _seeds()
    if bad:
        print('  ⛔ a seeded direction was lost:')
        for b in bad:
            print(f'      {b}')
        return 1
    print('    seeds hold: double claim void, expiry stands, stall expires, progress resets, totals and staleness')
    baseline = open(BASELINE, encoding='utf-8').read()
    claims_text = open(CLAIMS, encoding='utf-8').read() if os.path.exists(CLAIMS) else ''
    history = progress_history()
    fresh = generate(baseline, claims_text, history)
    rc = 0
    if not os.path.exists(BOARD):
        print(f'  ⛔ no board at {os.path.relpath(BOARD, ROOT)} -- run scripts/gen_pin_board.py')
        return 1
    committed = open(BOARD, encoding='utf-8').read()
    total_base = sum(counts(baseline).values())
    total_board = sum(int(x.split('\t')[2]) for x in committed.split('\n') if x and not x.startswith('#'))
    rows = [x for x in committed.split('\n') if x and not x.startswith('#')]
    print(f'    board: {len(rows)} receipt(s) in {len({x.split(chr(9))[0] for x in rows})} prefix(es), '
          f'{total_board} unverdicted; the baseline carries {total_base}')
    if total_board != total_base:
        rc = 1
        print(f'  ⛔ (b) the board says {total_board} and the ratchet says {total_base} -- regenerate the board')
    elif committed != fresh:
        rc = 1
        print('  ⛔ (b) the committed board is STALE against the baseline and the claims -- run scripts/gen_pin_board.py')
    live, void = live_claims(read_claims(claims_text), history)
    for c, why in void:
        rc = 1
        print(f"  ⛔ (a) VOID claim: {c['prefix']} by {c['seat']} at r{c['rev']} -- {why}")
    now = current_revision()
    held = {p: c for p, c in live.items() if c['expires_after'] >= now}
    released = {p: c for p, c in live.items() if c['expires_after'] < now}
    print(f'    claims: {len(held)} live, {len(released)} RELEASED (no progress for {RELEASE_AFTER_CYCLES} '
          f'cycles; trunk at r{now})')
    for p, c in sorted(released.items()):
        print(f"      RELEASED  {p}  ({c['seat']}, claimed r{c['rev']}, expired after r{c['expires_after']}) "
              '-- claimable again')
    if rc == 0:
        print('  the board agrees with the ratchet and no prefix has two claimants.')
    print()
    return rc


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
