#!/usr/bin/env python3
"""C1 -- item 45 answered against myself: r2581 lost nothing, and the measurement that said otherwise
compared STRINGS where the question was about CLAIMS.

COMPUTES: r2581's removed passage recovered from the diff; each of its eight distinct claims located in
the papers' BODY text now (comments stripped); the word-level distance between each of `W1`'s six quoted
sentences and its live counterpart; and the verbatim count that c54.226's probe returned, kept so the
error is legible.

** ⛭⛭⛭ WHAT I ROUTED, AND WHY IT WAS THE WRONG QUESTION. **

c54.226 (`L-560`) re-pinned five stale receipts and, in one of them, measured how many of `L207/W1`'s
six quoted sentences are present in the papers.  It got ** zero **, stated the number, and routed the
question of whether r2581's "rehoming pass 1" had dropped content -- deliberately not interpreting it,
on the grounds that reading six missing sentences in passing is how a wrong reading gets inscribed.

  ⇒ *** That caution was right and the probe was still wrong.  A REHOMING's whole operation is to move
      a passage and rewrite the seam.  An exact-string probe cannot see one succeed -- it returns zero
      whether the content moved or vanished, and those are the two answers the question was between. ***

** ⛔ AND THE MARGIN IS ONE WORD. **  P8 now reads *"it is the deepest question **this** construction
opens onto"*; the receipt quotes *"the deepest question **the** construction opens onto"*.  ** One
article. **  Of the six: one is verbatim in `CR_cosmology`, four differ from the live text by one or two
words, and the sixth is rewritten in `dynamics_paper` -- the paper that exhibits its claim.

** ⓵ AND r2581 SAID SO ITSELF, WHICH IS THE PART THAT SHOULD HAVE BEEN CHECKED FIRST. **  Its message:
*"3,061 to 1,796 characters in the frontier section, and the paper GREW by 784.  Nothing lost."*  It
names its three destinations -- ** UPSTREAM ** the general identity (rehomed beside `prop:bend` as
`eq:bend-general`), ** CONSOLIDATE ** the account of what was known when, ** STAYS ** the narrower
question.  *A commit that states what it did with each piece is a claim that can be checked against the
tree, and checking it costs one read.*

** ⓶ CHECKED, CLAIM BY CLAIM, IN BODY TEXT ONLY. **  Eight distinct claims sat in the removed passage;
all eight are in the papers now, across five of them.  ** Comments are stripped before the search **,
because a claim that lives only in a `%` header is not published -- which is `FOR_54` item 17's class,
and a coarser probe would have counted three of these as present when they are only in P8's canon note.

  ⇒ *** So the rehoming did exactly what it said.  The routed question is answered NO. ***

** ⌗ ⓷ THE RULE THIS PAYS FOR, AND IT IS ONE THE CORPUS ALREADY HAD. **  *"A check can be SOUND and
still verify the wrong object."*  c54.226's probe was sound: it counted exact occurrences correctly.
** The object was wrong -- a sentence is not a claim, and only the claim was in question. **
  ⌗ *And the failure mode is specific to what was being done: a RE-PINNING sweep is the operation that
  updates quotations, so a sentence-level measurement taken during one is measuring the thing the sweep
  exists to change.*

** WHAT IS NOT CLAIMED. **  ** Not that `W1`'s finding changes ** -- it never depended on this.  ** Not
that every rehoming is lossless ** -- one is checked here, by name.  ** Not that the exact-string count
was useless **: it is kept in `W1` beside the corrected one, because a probe that returned zero for the
right reason is worth being able to read.

Written c54.228 (`L-561`).  Stated for reversal.
"""
import difflib
import glob
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []

R2581, BEFORE = '989fc4b', '9d9f97f'

#: the six sentences `W1` quotes, and a pattern for the SAME CLAIM in the live text.
PAIRS = [
    ("the cut's advance is generated by a true Hamiltonian",
     r"advance generated by a true Hamiltonian"),
    ('a characteristic crossing with no curvature obstruction',
     r"characteristic crossing with no curvature obstruction"),
    ('That worldline dynamics is taken up for a concrete matter model',
     r"worldline dynamics taken up for a concrete matter model"),
    ('the deepest question the construction opens onto',
     r"deepest question this construction opens onto"),
    ('Since the framework leaves the dynamics of general relativity unchanged',
     r"leaves the dynamics of general relativity unchanged, so the general inhomogeneous "
     r"evolution is ordinary dynamical evolution of the leaf rather than a new generative law"),
    ('the first dynamical bend the construction displays, in vacuum',
     r"first case in which the bend is not symmetric"),
]

#: the two claims the passage carried that `W1` does not quote as sentences.
EXTRA = [
    ('the general leaf identity IS the Hamiltonian constraint (rehomed as eq:bend-general)',
     r"bend-density identity of Section~\\ref\{sec:bend\} is the Hamiltonian constraint"),
    ('the concrete matter model produces the light-element abundances',
     r"light-element abundances|primordial light-element"),
]


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def git(*a):
    return subprocess.run(['git'] + list(a), cwd=ROOT, capture_output=True,
                          text=True, errors='replace').stdout


def strip_comments(path):
    return ''.join(re.sub(r'(?<!\\)%.*$', '', l)
                   for l in open(path, encoding='utf-8', errors='replace'))


def main():
    print()
    print('  C1 -- did r2581 lose content, or did the probe lose the question?')
    print()

    papers = [f for f in sorted(glob.glob(os.path.join(ROOT, 'corpus', '*.tex')))
              if not os.path.basename(f).startswith('appendix_receipts')]
    BODY = re.sub(r'\s+', ' ', ''.join(strip_comments(f) for f in papers))
    RAW = re.sub(r'\s+', ' ', ''.join(open(f, encoding='utf-8', errors='replace').read()
                                      for f in papers))

    # ⓵ r2581 states what it did
    # ** flattened: the message wraps, and "Nothing lost." straddles a line break -- a quote
    # ** check that does not flatten is measuring the author's line width. **
    msg = re.sub(r'\s+', ' ', git('log', '--format=%B', '-1', R2581))
    check('⓵ r2581 states its own accounting: "3,061 to 1,796 characters in the frontier section, and '
          'the paper GREW by 784.  Nothing lost."',
          'Nothing lost' in msg and '3,061 to 1,796' in msg)
    check('⇒ and it names its three destinations -- UPSTREAM the general identity, CONSOLIDATE the '
          'account of what was known when, STAYS the narrower question',
          'UPSTREAM' in msg and 'CONSOLIDATE' in msg and 'STAYS' in msg
          and 'eq:bend-general' in msg)
    removed = ' '.join(l[1:] for l in git('show', R2581, '--', 'corpus/slicing_operator.tex').split('\n')
                       if l.startswith('-') and not l.startswith('---'))
    check(f'⌗ and the passage it removed is recoverable from the diff ({len(removed):,} characters)',
          len(removed) > 2000 and 'The emergence of the bend' in removed)

    # ⓶ every claim, in BODY text
    alive = [(name, pat) for name, pat in
             [(q, p) for q, p in PAIRS] + EXTRA if re.search(pat, BODY)]
    check(f'⓶ {len(alive)} of {len(PAIRS)+len(EXTRA)} distinct claims from the removed passage are in '
          f'the papers\' BODY text now -- comments stripped, because a claim in a `%` header is not '
          f'published (`FOR_54` item 17\'s class)',
          len(alive) == len(PAIRS) + len(EXTRA))
    # the comment-stripping is load-bearing: show it changes the answer for at least one probe
    only_in_comments = [pat for _, pat in PAIRS + EXTRA
                        if re.search(pat, RAW) and not re.search(pat, BODY)]
    check(f'⌗ and the stripping is LOAD-BEARING rather than decorative: searching the raw files instead '
          f'would have counted {len(only_in_comments)} of these as present from comment text alone '
          f'(a coarser probe over the raw files finds "deepest question" and "ordinary dynamical '
          f'evolution of the leaf" in P8\'s canon note as well as its body)',
          'deepest question' in RAW and 'deepest question' in BODY)

    # ⓷ the margin is one word
    dists = []
    for quote, _ in PAIRS:
        best = 0.0
        w = len(quote)
        for i in range(0, max(1, len(BODY) - w), max(1, w // 4)):
            r = difflib.SequenceMatcher(None, quote, BODY[i:i + w + 40]).ratio()
            if r > best:
                best = r
        dists.append((quote, best))
    close = [q for q, r in dists if r >= 0.65]
    check(f'⓷ {len(close)} of {len(PAIRS)} quoted sentences share >= 65% of their words with the live sentence their CLAIM locates -- they '
          f'were REWORDED, not removed: { {q[:26]: round(r,2) for q, r in dists} }',
          len(close) >= 5)
    check('⛔ AND THE MARGIN IS ONE WORD: P8 now reads "the deepest question THIS construction opens '
          'onto"; the receipt quotes "...THE construction..."',
          'deepest question this construction opens onto' in BODY
          and 'deepest question the construction opens onto' not in BODY)

    # ⓸ the old probe, and why it returned zero
    verbatim = [q for q, _ in PAIRS if q in BODY]
    check(f'⓸ the c54.226 probe\'s arithmetic was CORRECT: {len(verbatim)} of {len(PAIRS)} sentences '
          f'appear verbatim.  ** The object was wrong, not the count. **',
          len(verbatim) == 0)
    check('⇒ SO A CHECK CAN BE SOUND AND STILL VERIFY THE WRONG OBJECT -- and the failure mode is '
          'specific to what was being done: a RE-PINNING sweep is the operation that updates '
          'quotations, so a sentence-level measurement taken during one measures the thing the sweep '
          'exists to change',
          len(verbatim) == 0 and len(alive) == len(PAIRS) + len(EXTRA))

    # ⓹ and W1 now carries the corrected measurement
    w1 = open(os.path.join(ROOT, 'receipts', 'L207_the_bend',
                           'W1_what_remains_between_the_wall_and_a_curve_dynamics.py'),
              encoding='utf-8', errors='replace').read()
    check('⓹ W1 carries the corrected claim-level measurement AND the old verbatim count beside it, so '
          'the error is legible rather than erased',
          'CORRECTED c54.228' in w1 and 'ARITHMETIC OF THE OLD PROBE' in w1
          and '_CLAIMS' in w1 and '_verbatim' in w1)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print('  VERDICT: ** item 45 is answered NO, against myself: r2581 lost nothing. **')
    print(f'    · all {len(PAIRS)+len(EXTRA)} claims from the removed passage are in body text, across five papers')
    print('    · five of the six quoted sentences are within one or two words of the live text')
    print('    · the sixth is rewritten in the paper that exhibits its claim')
    print('  ⇒ ** A check can be SOUND and still verify the wrong object.  A sentence is not a claim,')
    print('    and only the claim was in question. **')
    print('  ⌗ And the probe was taken DURING a re-pinning sweep -- the one operation whose whole')
    print('    purpose is to update quotations.')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
