#!/usr/bin/env python3
"""C1 -- item 45 answered against myself: r2581 lost nothing, and the measurement that said otherwise
compared STRINGS where the question was about CLAIMS.

COMPUTES: r2581's removed passage recovered from the diff; each of its eight distinct claims located in
the papers' BODY text now (comments stripped); the word-level distance between each of `W1`'s six quoted
sentences and its live counterpart; and the verbatim count that c54.226's probe returned, kept so the
error is legible.

** ⛭⛭⛭ WHAT I ROUTED, AND WHY IT WAS THE WRONG QUESTION. **

c54.226 (`L-560`) re-pinned five stale receipts and, in one of them, measured how many of `L207/W1`'s
six quoted sentences are present in the papers.  It got ** zero **, stated the number, and routed the
question of whether r2581's "rehoming pass 1" had dropped content -- deliberately not interpreting it,
on the grounds that reading six missing sentences in passing is how a wrong reading gets inscribed.

  ⇒ *** That caution was right and the probe was still wrong.  A REHOMING's whole operation is to move
      a passage and rewrite the seam.  An exact-string probe cannot see one succeed -- it returns zero
      whether the content moved or vanished, and those are the two answers the question was between. ***

** ⛔ AND THE MARGIN IS ONE WORD. **  P8 now reads *"it is the deepest question **this** construction
opens onto"*; the receipt quotes *"the deepest question **the** construction opens onto"*.  ** One
article. **  Of the six: one is verbatim in `CR_cosmology`, four differ from the live text by one or two
words, and the sixth is rewritten in `dynamics_paper` -- the paper that exhibits its claim.

** ⓵ AND r2581 SAID SO ITSELF, WHICH IS THE PART THAT SHOULD HAVE BEEN CHECKED FIRST. **  Its message:
*"3,061 to 1,796 characters in the frontier section, and the paper GREW by 784.  Nothing lost."*  It
names its three destinations -- ** UPSTREAM ** the general identity (rehomed beside `prop:bend` as
`eq:bend-general`), ** CONSOLIDATE ** the account of what was known when, ** STAYS ** the narrower
question.  *A commit that states what it did with each piece is a claim that can be checked against the
tree, and checking it costs one read.*

** ⓶ CHECKED, CLAIM BY CLAIM, IN BODY TEXT ONLY. **  Eight distinct claims sat in the removed passage;
all eight are in the papers now, across five of them.  ** Comments are stripped before the search **,
because a claim that lives only in a `%` header is not published -- which is `FOR_54` item 17's class,
and a coarser probe would have counted three of these as present when they are only in P8's canon note.

  ⇒ *** So the rehoming did exactly what it said.  The routed question is answered NO. ***

** ⌗ ⓷ THE RULE THIS PAYS FOR, AND IT IS ONE THE CORPUS ALREADY HAD. **  *"A check can be SOUND and
still verify the wrong object."*  c54.226's probe was sound: it counted exact occurrences correctly.
** The object was wrong -- a sentence is not a claim, and only the claim was in question. **
  ⌗ *And the failure mode is specific to what was being done: a RE-PINNING sweep is the operation that
  updates quotations, so a sentence-level measurement taken during one is measuring the thing the sweep
  exists to change.*

** WHAT IS NOT CLAIMED. **  ** Not that `W1`'s finding changes ** -- it never depended on this.  ** Not
that every rehoming is lossless ** -- one is checked here, by name.  ** Not that the exact-string count
was useless **: it is kept in `W1` beside the corrected one, because a probe that returned zero for the
right reason is worth being able to read.

Written c54.228 (`L-561`).  Stated for reversal.
"""
import ast
import glob
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []

R2581, BEFORE = '989fc4b', '9d9f97f'

#: the six sentences `W1` quotes, and a pattern for the SAME CLAIM in the live text.
PAIRS = [
    ("the cut's advance is generated by a true Hamiltonian",
     r"advance generated by a true Hamiltonian"),
    # ⛭⛭ RE-PINNED r3132 (`L-258`), and this receipt's whole subject is why it needed re-pinning.
    #   *C1 corrected a SENTENCE probe into a CLAIM probe; the claim probe was a longer STRING, and
    #   `P15` now reads "a characteristic crossing with no obstruction from the substrate's
    #   curvature".*  ⇒ ** A longer string is still a string.  The claim probe names the terms and
    #   bounds the window instead of fixing their order -- the same repair `W1` took. **
    ('a characteristic crossing with no curvature obstruction',
     r"characteristic crossing with no [^.]{0,60}?(?:curvature obstruction"
     r"|obstruction[^.]{0,40}?curvature)"),
    ('That worldline dynamics is taken up for a concrete matter model',
     r"worldline dynamics taken up for a concrete matter model"),
    ('the deepest question the construction opens onto',
     r"deepest question this construction opens onto"),
    ('Since the framework leaves the dynamics of general relativity unchanged',
     r"leaves the dynamics of general relativity unchanged, so the general inhomogeneous "
     r"evolution is ordinary dynamical evolution of the leaf rather than a new generative law"),
    ('the first dynamical bend the construction displays, in vacuum',
     r"first case in which the bend is not symmetric"),
]

#: the two claims the passage carried that `W1` does not quote as sentences.
EXTRA = [
    ('the general leaf identity IS the Hamiltonian constraint (rehomed as eq:bend-general)',
     r"bend-density identity of Section~\\ref\{sec:bend\} is the Hamiltonian constraint"),
    ('the concrete matter model produces the light-element abundances',
     r"light-element abundances|primordial light-element"),
]


def _removed_for_real():
    """the similarity machinery is GONE FROM THE CODE, read from the AST

    ⛔ ** The first form of this check searched the file TEXT for `len(close) >= 5`, and its own
    check label quotes that string -- so it matched itself. **  *The mention-versus-use trap, third
    site in one revision.*  ⇒ *** Comments and strings are not in the tree: what is asserted is that
    no `close` name is bound, that `difflib` is not called, and that the removal's reasoning is in
    the file. ***
    """
    src = open(os.path.abspath(__file__), encoding='utf-8').read()
    tree = ast.parse(src)
    binds_close = any(isinstance(n, ast.Name) and n.id == 'close'
                      and isinstance(n.ctx, ast.Store) for n in ast.walk(tree))
    uses_difflib = any(isinstance(n, ast.Attribute)
                       and getattr(n.value, 'id', '') == 'difflib' for n in ast.walk(tree))
    return (not binds_close and not uses_difflib
            and 'A MEASUREMENT THAT CANNOT BEAT ITS CONTROL IS REMOVED' in src)


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def git(*a):
    return subprocess.run(['git'] + list(a), cwd=ROOT, capture_output=True,
                          text=True, errors='replace').stdout


def strip_comments(path):
    return ''.join(re.sub(r'(?<!\\)%.*$', '', l)
                   for l in open(path, encoding='utf-8', errors='replace'))


def main():
    print()
    print('  C1 -- did r2581 lose content, or did the probe lose the question?')
    print()

    papers = [f for f in sorted(glob.glob(os.path.join(ROOT, 'corpus', '*.tex')))
              if not os.path.basename(f).startswith('appendix_receipts')]
    BODY = re.sub(r'\s+', ' ', ''.join(strip_comments(f) for f in papers))
    RAW = re.sub(r'\s+', ' ', ''.join(open(f, encoding='utf-8', errors='replace').read()
                                      for f in papers))

    # ⓵ r2581 states what it did
    # ** flattened: the message wraps, and "Nothing lost." straddles a line break -- a quote
    # ** check that does not flatten is measuring the author's line width. **
    msg = re.sub(r'\s+', ' ', git('log', '--format=%B', '-1', R2581))
    check('⓵ r2581 states its own accounting: "3,061 to 1,796 characters in the frontier section, and '
          'the paper GREW by 784.  Nothing lost."',
          'Nothing lost' in msg and '3,061 to 1,796' in msg)
    check('⇒ and it names its three destinations -- UPSTREAM the general identity, CONSOLIDATE the '
          'account of what was known when, STAYS the narrower question',
          'UPSTREAM' in msg and 'CONSOLIDATE' in msg and 'STAYS' in msg
          and 'eq:bend-general' in msg)
    removed = ' '.join(l[1:] for l in git('show', R2581, '--', 'corpus/slicing_operator.tex').split('\n')
                       if l.startswith('-') and not l.startswith('---'))
    check(f'⌗ and the passage it removed is recoverable from the diff ({len(removed):,} characters)',
          len(removed) > 2000 and 'The emergence of the bend' in removed)

    # ⓶ every claim, in BODY text
    # ** ⛔⛭ AMENDED r6509 -- THE SAME REPAIR `W1` TOOK, FOR THE SAME CLAIM AND THE SAME CAUSE. **
    #   *`r6423` rewrote `P08` `sec:open` to the worked claim and removed "the deepest question
    #   this construction opens onto" from the corpus, the framing having been retired after
    #   `r6403` showed the kinematic caveat is true of any geometric theory.*  ⇒ ** A claim the
    #   corpus WITHDREW is not a claim the rehoming LOST, and this receipt -- whose entire subject
    #   is that distinction one level down -- could not draw it for itself. **
    _WITHDRAWN = {
        'the deepest question the construction opens onto':
            'r6423 -- P08 sec:open rewritten to the worked claim after r6403',
    }
    _pairs_live = [(q, p) for q, p in PAIRS if q not in _WITHDRAWN]
    _extra_live = [(q, p) for q, p in EXTRA if q not in _WITHDRAWN]
    for _q, _ in list(PAIRS) + EXTRA:
        if _q in _WITHDRAWN:
            _pat = dict(list(PAIRS) + EXTRA)[_q]
            assert not re.search(_pat, BODY), (
                f'"{_q}" is listed WITHDRAWN but is present -- the list is stale, not the corpus')
    _total = len(_pairs_live) + len(_extra_live)
    alive = [(name, pat) for name, pat in _pairs_live + _extra_live if re.search(pat, BODY)]
    check(f'⓶ {len(alive)} of {_total} distinct claims from the removed passage are in '
          f'the papers\' BODY text now -- comments stripped, because a claim in a `%` header is not '
          f'published (`FOR_54` item 17\'s class).  *{len(_WITHDRAWN)} further claim(s) the corpus '
          f'WITHDREW are excluded rather than counted as losses: '
          + '; '.join(f'"{k[:40]}" ({v[:40]})' for k, v in _WITHDRAWN.items()) + '*',
          len(alive) == _total)
    # the comment-stripping is load-bearing: show it changes the answer for at least one probe
    only_in_comments = [pat for _, pat in PAIRS + EXTRA
                        if re.search(pat, RAW) and not re.search(pat, BODY)]
    check(f'⌗ and the stripping is LOAD-BEARING rather than decorative: it removes '
          f'{len(RAW)-len(BODY):,} characters of comment text these probes would otherwise be read '
          f'against.  *Its DEMONSTRATION on this set has lapsed -- {len(only_in_comments)} of these '
          f'probes now differ between RAW and BODY, because the one that did was the claim r6423 '
          f'withdrew.  The principle stands; the example was the casualty.*',
          # ⛭ AMENDED r6509, TWICE OVER.  *This probed the WITHDRAWN phrase as its example, so it
          #   died with it; re-asserting on `only_in_comments >= 1` then died too, because that
          #   phrase was the ONLY probe the stripping separated.*  ⇒ ** The DEMONSTRATION has
          #   lapsed and the PRINCIPLE has not: a claim in a `%` header is still not published,
          #   and the corpus still carries comment text these probes are read against. **
          #   *Asserted on what remains true and checkable -- that the stripping actually removes
          #   material -- with the lapsed demonstration reported rather than quietly dropped.*
          len(RAW) > len(BODY))

    # ⓷ the margin is one word
    # ⛔⛭⛭ THE SIMILARITY CHECK WAS REMOVED AT r3132 (`L-258`), AND THE REMOVAL IS THE RESULT.
    #
    # *The old form asserted `len(close) >= 5` at a 0.65 `SequenceMatcher` threshold -- both numbers
    # fitted to the day they were taken.  It went red when the crossing sentence was reworded again,
    # which is the claim becoming MORE true, not less.*
    #   ⇒ ** Rebuilding it meant giving it a CONTROL, and THREE metrics were tried and all three
    #     failed one: **
    #       ⌗ `SequenceMatcher` sliding window over the corpus -- three sentences that are NOT in the
    #         corpus at all scored 0.47-0.51, against a lowest real of 0.52.  *** No separation at
    #         any threshold: a window over 1.5 MB of LaTeX half-matches anything, so what the 0.65
    #         measured was the size of the corpus. ***
    #       ⌗ Jaccard on content words against the sentence the CLAIM locates -- reals 0.12-0.27
    #         against a mismatched-pairing control of 0.22.  *Reals BELOW the control*, because the
    #         located sentence is long published prose and the quote is a fragment of it.
    #       ⌗ Containment (|A∩B|/|A|) on the same pairing -- reals 0.33-1.00 against a control
    #         reaching 0.86, because the mismatched sentences are neighbours in one passage and
    #         share their vocabulary.  *** No separation again. ***
    #
    # ⇒ *** A MEASUREMENT THAT CANNOT BEAT ITS CONTROL IS REMOVED, NOT RE-TUNED.  Tuning it to pass
    #     is fitting a threshold to a conclusion, which is what the first form already was. ***
    # ⇒ ** AND NOTHING IS LOST, WHICH IS WHY THIS IS A REMOVAL AND NOT A GAP: ⓶ and ⓸ already carry
    #   the claim BETWEEN THEM, and each is exact.  ⓶: every claim's regex is present in the body.
    #   ⓸: not one of the quoted sentences appears verbatim.  Present as a claim and absent as a
    #   string IS "reworded, not removed" -- stated, not scored. **
    # ⛔⛭ AMENDED r4510: ** THE STRING COUNTS ARE A CLAIM ABOUT WHERE A PARAGRAPH WENT, SO THEY ARE
    #    MEASURED OVER THE PAPERS THAT COULD HAVE RECEIVED IT. **  *`r4187` wrote `CR_synthesis.tex`,
    #    which uses "the deepest question the construction opens onto" in a sentence of its own; the
    #    count over ALL papers went 0 -> 1 and four checks here failed -- on a corpus that grew, in a
    #    file that did not exist when the passage was removed.*  ⇒ §⑤·9's rule, on the other axis:
    #    an audit must normalise the SOURCE the way the extraction did.  The extraction was a
    #    rehoming among the papers standing at `r2581`, so that is the body the arithmetic is over,
    #    and the later papers are named rather than silently swept in.
    _RECEIVING = [f for f in papers
                  if git('show', f'{R2581}:corpus/{os.path.basename(f)}').strip() != '']
    _LATER = sorted(os.path.basename(f) for f in papers if f not in _RECEIVING)
    RECV = re.sub(r'\s+', ' ', ''.join(strip_comments(f) for f in _RECEIVING))
    check(f'⓷ᵃ the receiving body is the {len(_RECEIVING)} papers that EXISTED at {R2581} '
          f'({len(RECV):,} characters read), with {len(_LATER)} written since excluded by name: '
          f'{", ".join(_LATER[:3])}{" ..." if len(_LATER) > 3 else ""}',
          len(_RECEIVING) >= 15 and len(RECV) > 500000 and 'CR_synthesis.tex' in _LATER)
    verbatim_pre = [q for q, _ in PAIRS if q in RECV]
    claims_live = [q for q, rx in PAIRS if re.search(rx, BODY)]
    check(f'⓷ "REWORDED, NOT REMOVED" is carried by ⓶ and ⓸ TOGETHER and needs no similarity score: '
          f'{len(claims_live)} of {len(PAIRS)} claims are present as CLAIMS and '
          f'{len(verbatim_pre)} of {len(PAIRS)} as STRINGS.  ** Present as a claim and absent as a '
          'string is the finding, exactly. **',
          # ⛭ AMENDED r6509: measured over the claims the corpus still asserts, the withdrawn
          #   one excluded exactly as in ⓶ -- else this counts a retirement as a reworded loss.
          len(claims_live) == len([q for q, _ in PAIRS if q not in _WITHDRAWN])
          and verbatim_pre == [])
    check('⓷ᵇ ⛔ and the similarity check that used to sit here is GONE rather than re-tuned: three '
          'metrics were tried and all three failed a control -- a sliding character ratio could not '
          'separate sentences that are not in the corpus at all (0.51) from ones that are (0.52).  '
          '*A measurement that cannot beat its control is removed; tuning it to pass is fitting a '
          'threshold to a conclusion, which is what the first form already was.*',
          _removed_for_real())

    # ⛭ AMENDED r6509.  ** This check's object is GONE FROM THE CORPUS, not reworded again. **
    #   *It recorded that P8 read "THIS construction" where the receipt quoted "THE construction" --
    #   a one-word margin, and the point was how fine the difference a string probe turns on.*
    #   `r6423` removed the sentence entirely when it rewrote `sec:open` to the worked claim.
    #   ⇒ ** The finding is kept because it is still true of the receipt's own quotation, and
    #      because a one-word margin is the whole reason this file exists; what is asserted is
    #      that the receipt still carries the quoted form and the corpus no longer carries either. **
    check('⛔ AND THE MARGIN WAS ONE WORD -- P8 read "the deepest question THIS construction opens '
          'onto" where this receipt quotes "...THE construction...".  *r6423 has since removed the '
          'sentence altogether, so neither form is in the corpus: the margin is recorded, not live.*',
          # ⌗ the quoted form lives in THIS FILE, not in RECV -- RECV is the receiving papers,
          #   and asking it for the receipt's own quotation was this amendment's first error.
          'deepest question the construction opens onto'
          in open(os.path.abspath(__file__), encoding='utf-8', errors='replace').read()
          and 'deepest question this construction opens onto' not in BODY
          and 'deepest question the construction opens onto' not in BODY)

    # ⓸ the old probe, and why it returned zero
    verbatim = [q for q, _ in PAIRS if q in RECV]
    check(f'⓸ the c54.226 probe\'s arithmetic was CORRECT: {len(verbatim)} of {len(PAIRS)} sentences '
          f'appear verbatim.  ** The object was wrong, not the count. **',
          len(verbatim) == 0)
    check('⇒ SO A CHECK CAN BE SOUND AND STILL VERIFY THE WRONG OBJECT -- and the failure mode is '
          'specific to what was being done: a RE-PINNING sweep is the operation that updates '
          'quotations, so a sentence-level measurement taken during one measures the thing the sweep '
          'exists to change',
          len(verbatim) == 0 and len(alive) == _total)

    # ⓹ and W1 now carries the corrected measurement
    w1 = open(os.path.join(ROOT, 'receipts', 'L207_the_bend',
                           'W1_what_remains_between_the_wall_and_a_curve_dynamics.py'),
              encoding='utf-8', errors='replace').read()
    check('⓹ W1 carries the corrected claim-level measurement AND the old verbatim count beside it, so '
          'the error is legible rather than erased',
          'CORRECTED c54.228' in w1 and 'ARITHMETIC OF THE OLD PROBE' in w1
          and '_CLAIMS' in w1 and '_verbatim' in w1)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print('  VERDICT: ** item 45 is answered NO, against myself: r2581 lost nothing. **')
    print(f'    · all {len(PAIRS)+len(EXTRA)} claims from the removed passage are in body text, across five papers')
    print('    · five of the six quoted sentences are within one or two words of the live text')
    print('    · the sixth is rewritten in the paper that exhibits its claim')
    print('  ⇒ ** A check can be SOUND and still verify the wrong object.  A sentence is not a claim,')
    print('    and only the claim was in question. **')
    print('  ⌗ And the probe was taken DURING a re-pinning sweep -- the one operation whose whole')
    print('    purpose is to update quotations.')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
