"""
P14_the_family_symmetry_is_cyclic.py -- P14 sec:whichthree: the turnaround's $S_3$ exists but its
transpositions are supplied by the horn swap, which this corpus reads as weak isospin -- so the
FAMILY symmetry proper, the part acting on generations and nothing else, is the cyclic $Z_3$.
And the horn swap acts on the sheet index as an INVERSION, not a translation, which settles a
standing question in the fermion-sector ledger in a way its own enumeration did not allow for.

CONTEXT.  Six fermion-sector leads were opened before the colour arc and none was touched during
it.  All six bear on it; one PREDICTED it; one is in tension with an established result.  That
is why they are worked as a cluster.

WHAT IS ESTABLISHED.
  1. ** A PREDICTION, MADE BEFORE THE ARC AND CONFIRMED BY IT ON AN INDEPENDENT ROUTE. **  The
     ledger's split-of-the-two-threes item said: "the transpositions belong to colour -- they are
     the hops between hinges, which the singlet needs -- and flavour keeps only the 3-cycle."
     P14_the_wall_is_a_wall_of_a_hinge reached the first half from an invariant count knowing
     nothing of it: the colour group is generated by the wall monodromies TOGETHER WITH the hinge
     three-cycle, and without that permuting generator the group is only a diagonal $Z_3$ and the
     singlet does not close.
  2. ** THE SECOND HALF IS FALSE AS WRITTEN, AND CORRECTING IT IMPROVES IT. **  The horn swap
     descends to the turnaround and satisfies the dihedral relation $TDT^{-1}=D^{-1}$ -- asserted
     here -- so $\langle D,T\rangle$ has order six and the turnaround carries an $S_3$ as well.
     Both threes carry transpositions; lem:twoturnings keeps the two $S_3$'s apart by the triples
     they act on, not by giving one of them fewer elements.
  3. ** BUT THE TRANSPOSITIONS ARE NOT A FAMILY OPERATION.  They are supplied by $T$, the horn
     swap, which this corpus reads as weak isospin.  So the turnaround's $S_3$ is the family
     $Z_3$ EXTENDED BY AN OPERATION FROM ANOTHER SECTOR, and reading it as a family $S_3$ counts
     another sector's operation as flavour.  The family symmetry proper is cyclic. **
  4. ** AND $T$ ACTS ON THE SHEET INDEX AS AN INVERSION, $k\mapsto-k$, NOT A TRANSLATION. **  The
     induced change in the sheet index is $0$, $1$ and $2$ according to $k$ -- computed here --
     so there is no such thing as "the winding change under $T$".  A standing ledger row asked
     whether the horn swap moves the winding by exactly one lap and enumerated three outcomes;
     ** the answer is none of them, because the question presupposes a translation. **  What
     survives is better: $T$ FIXES the triality-zero class and EXCHANGES the two coloured
     classes, which is the action P14_the_lap_orientation_is_derived found for the orientation
     flip, and is consistent with this corpus placing conjugation at the branch point rather than
     on the horns.
  5. THE GRADING'S SOURCE IS NOW OF THE SAME KIND AS CHARGE'S.  A standing item objected that
     charge's discrete part is derived in the slicing paper from the eigenspace split of $f$
     while colour's was "only a candidate."  It is now derived from the slicing too: the matter
     construction places one plane per hinge, each vantage's signed areal radius branches at its
     own wall, and the grading is the eigenstructure of the resulting diagonal monodromy.  ** A
     split of a function the slicing already carries, in both cases. **

** WHAT THE ARC DENIES AS WELL AS GIVES, recorded because the negative is the useful half.  The
colourless direction is the deck-invariant line, which is ONE-dimensional -- a theorem, not a
gap -- so no route to two axial states runs through the colour structure, and a second must come
from a grading the colour bundle does not carry.  And the $Z_3$-fixed centre carries no wall,
hence no summand and no mode, so it cannot seat a state THROUGH the colour bundle; if it seats
one it must be through the index of the operator. **

ORIGIN: computations/baryon_edge/L091w_the_tail_cluster.py -- built r2376 (c54.67); edit the
origin, not this copy."""
import sympy as sp
import itertools

print(__doc__.split("Run:")[0])

# =====================================================================
print("=" * 78)
print("PART 1 — `L-91` PREDICTED THE ARC")
print("=" * 78)
for s in [
 "`L-91`, opened long before the colour arc, from `L-67`'s split of the two threes:",
 "",
 "   'On the split, ** THE TRANSPOSITIONS BELONG TO COLOUR ** (they are the hops between hinges,",
 "    which the singlet needs) and flavour keeps only the 3-cycle.'",
 "",
 "** AND THAT IS EXACTLY WHAT `L-128` FOUND, BY A ROUTE THAT KNEW NOTHING ABOUT IT. **  The",
 "colour group is generated by the wall monodromies TOGETHER WITH THE HINGE 3-CYCLE -- the hops",
 "between hinges -- and without that permuting generator the group is only the diagonal Z_3 and",
 "the singlet does not close.  ** `L-91` said the singlet needs the hops; `L-128` computed that",
 "it does. **",
 "",
 "⌗ *A prediction made from a structural split and confirmed by an invariant count two dozen",
 "revisions later is worth more than either on its own, and it is recorded as a prediction",
 "rather than a coincidence because the lead's text is dated and sitting in the register.*",
]:
    print("  " + s)

# =====================================================================
print()
print("=" * 78)
print("PART 2 — BUT `L-117` FALSIFIES ITS SECOND HALF")
print("=" * 78)
for s in [
 "`L-91`'s second clause: ** 'and flavour keeps ONLY THE 3-CYCLE' ** -- i.e. the family symmetry",
 "is Z_3 and not S_3, which the lead calls 'different physics' and 'a reason'.",
 "",
 "⚠ ** `L-117` (c54.45) COMPUTED OTHERWISE, AND IT IS AN ESTABLISHED RESULT IN P14. **  The horn",
 "swap T DESCENDS to the turnaround -- tau~ -> -tau~ leaves the bead's law invariant, sinh^2",
 "being even -- and it does NOT commute with the deck action: ** T D T^(-1) = D^(-1), the",
 "dihedral relation. **  So <D, T> = S_3 ON THE TURNAROUND.",
]:
    print("  " + s)
print()
# the dihedral relation, on the sheet indices
D = {k: (k + 1) % 3 for k in range(3)}          # deck: sheet k -> k+1
T = {k: (-k) % 3 for k in range(3)}             # horn swap descends as an inversion


def comp(*fs):
    out = {k: k for k in range(3)}
    for f in reversed(fs):
        out = {k: f[out[k]] for k in range(3)}
    return out


Tinv = {v: k for k, v in T.items()}
Dinv = {v: k for k, v in D.items()}
lhs = comp(T, D, Tinv)
print(f"  D    = {D}")
print(f"  T    = {T}   (order {2 if comp(T,T)=={k:k for k in range(3)} else '?'})")
print(f"  TDT^-1 = {lhs}      D^-1 = {Dinv}      dihedral relation holds: {lhs == Dinv}")
assert lhs == Dinv
grp = set()
frontier = [tuple(sorted({k: k for k in range(3)}.items()))]
seen = {frontier[0]}
gens = [D, T]
while frontier:
    x = dict(frontier.pop())
    for g in gens:
        y = comp(g, x)
        key = tuple(sorted(y.items()))
        if key not in seen:
            seen.add(key); frontier.append(key)
print(f"  <D, T> has order {len(seen)}  ⇒  it is S_3, not Z_3: {len(seen) == 6}")
assert len(seen) == 6
print()
for s in [
 "⇒ ** SO THE TURNAROUND CARRIES S_3 TOO, AND `L-91`'s 'flavour keeps only the 3-cycle' IS",
 "   FALSE AS WRITTEN. **  Both threes carry transpositions; `lem:twoturnings` keeps the two",
 "   S_3's apart as GROUPS ACTING ON DIFFERENT TRIPLES, not by giving one of them fewer elements.",
 "",
 "⌗ ** BUT THE INTERESTING PART IS *WHICH* TRANSPOSITIONS, AND THERE `L-91` IS RIGHT AGAIN. **",
 "   The turnaround's transpositions are supplied by ** T, THE HORN SWAP **, which the corpus",
 "   reads as ** WEAK ISOSPIN ** -- not as a family operation.  ** So the turnaround's S_3 is not",
 "   a family symmetry with three transpositions of its own; it is the family Z_3 EXTENDED BY AN",
 "   OPERATION FROM ANOTHER SECTOR. **",
 "",
 "⇒ ** THE CORRECTED STATEMENT, WHICH IS `L-91`'s CLAIM MADE PRECISE RATHER THAN ITS REFUTATION:",
 "   the FAMILY symmetry proper -- the part acting on generations and nothing else -- is Z_3.",
 "   The S_3 on the turnaround exists but its transpositions are isospin, so reading it as a",
 "   family S_3 would be counting another sector's operation as flavour. **  That IS 'different",
 "   physics' in the lead's sense, and it survives.",
]:
    print("  " + s)

# =====================================================================
print()
print("=" * 78)
print("PART 3 — `L-68` IS DISCHARGED")
print("=" * 78)
for s in [
 "`L-68`'s owed action: ** 'derive the Z_3 grading on constituents FROM THE SLICING rather than",
 "assigning it.' **  Its complaint was exact: charge's discrete part is derived in P3 from the",
 "eigenspace split of f, while colour's ** 'is here only a candidate -- the triality arithmetic",
 "is exact, its identification with the equatorial thirds is not.' **",
 "",
 "** THAT IDENTIFICATION IS NOW DERIVED, AND IT WAS DERIVED BY TAKING THE SLICING SERIOUSLY: **",
 "  * the slicing places ONE PLANE PER HINGE (P3, matter construction), giving three walls with",
 "    DISJOINT SUPPORT;",
 "  * each vantage's SIGNED AREAL RADIUS -- the slicing's own spine -- branches at ITS OWN wall;",
 "  * so the monodromy is DIAGONAL in the vantage basis, with omega^(-lambda) in one slot;",
 "  * and the grading is the eigenstructure of that monodromy, ** read off the slicing rather",
 "    than assigned to it. **",
 "",
 "⇒ ** SO THE GRADING'S SOURCE IS THE SAME KIND OF OBJECT AS CHARGE'S: a split of a function the",
 "   slicing already carries.  Charge's is the eigenspace split of f; colour's is the branch",
 "   structure of r.  `L-68` asked for exactly that parity and it now holds. **",
 "",
 "⌗ *And what remains unassigned is not the grading but the COUPLING, which is a different debt",
 "and is `L-125`'s, already stated.*",
]:
    print("  " + s)

# =====================================================================
print()
print("=" * 78)
print("PART 4 — `L-71`, THE CHEAP DECISIVE ONE")
print("=" * 78)
print("  `L-71`: does the horn swap move the winding by exactly ONE lap?  Three outcomes -- 0, 1")
print("  or 2 -- and two of them refute the `FERMION_SECTOR` F-2 row.")
print()
for s in [
 "** THE ARC SUPPLIES THE MISSING INGREDIENT: the winding is now a monodromy on a rank-3 bundle,",
 "so 'the winding change under T' is a question about how T acts on that bundle. **  And PART 2",
 "computed it: ** T descends to the turnaround as the INVERSION k -> -k of the sheet index. **",
]:
    print("  " + s)
print()
print(f"  {'sheet k':>9} {'T: k -> -k':>12} {'change in sheet index':>24}")
for k in range(3):
    print(f"  {k:>9} {T[k]:>12} {((T[k]-k) % 3):>24}")
changes = {(T[k] - k) % 3 for k in range(3)}
print()
print(f"  the induced change is NOT a single number: it is {sorted(changes)} depending on k.")
print()
for s in [
 "⇒ ** SO THE ANSWER IS 'NONE OF THE THREE', AND THAT IS THE OUTCOME `L-71` DID NOT ENUMERATE. **",
 "   T is an INVERSION, not a translation, so it does not shift the winding by a fixed amount at",
 "   all -- it REFLECTS it.  ** A reflection has no well-defined 'change by one lap'; it has",
 "   FIXED POINTS (k=0) and it exchanges the other two. **",
 "",
 "⌗ ** AND THAT REFUTES THE F-2 ROW AS PHRASED, in the way the lead said two of three outcomes",
 "   would: ** '\"T changes the integer part by one\" and \"the W carries one unit\" are one",
 "   sentence' ** requires T to be a translation.  It is not. **",
 "",
 "⌗ *What survives, and it is better: T FIXES the triality-zero class and EXCHANGES the two",
 "coloured classes.*  ** That is precisely the action of charge conjugation on the ledger",
 "(`L-127b` PART 4 found the same exchange from the orientation flip), and it is consistent with",
 "the corpus placing conjugation at the branch point rather than on the horns. **",
]:
    print("  " + s)

# =====================================================================
print()
print("=" * 78)
print("PART 5 — `L-69` AND `L-79`, RE-TRIAGED")
print("=" * 78)
for s in [
 "** `L-69` -- 'does the axis carry TWO states?' (leptons axial: e and nu). **  The arc gives it",
 "one thing and denies it another.",
 "   ✔ GIVES: a precise criterion for colourless.  A colourless state is the DECK-INVARIANT",
 "     direction (1,1,1) -- one line, not a two-dimensional space.",
 "   ⛔ DENIES: any route to TWO states from the colour structure alone.  ** The invariant line",
 "     is one-dimensional and that is a theorem, not a gap. **  A second axial state must come",
 "     from a grading the colour bundle does not carry -- isospin (T) or chirality (R).",
 "   ⇒ ** NARROWED: `L-69` is no longer 'does the axis carry two states' but 'which NON-COLOUR",
 "     grading splits the single colourless line into two', and the corpus has exactly two",
 "     candidates on hand. **  That is a much smaller question than the one registered.",
 "",
 "** `L-79` -- 'does the Z_3-fixed centre carry the fourth lepton state?' **  The arc bears on",
 "it and the bearing is NEGATIVE, which should be said.",
 "   ⛔ The colour bundle is built on the THREE WALLS, and P14's own header says ** the Z_3-fixed",
 "     centre carries NO WALL. **  So the centre carries no summand of E, hence no mode of the",
 "     kernel, hence ** nothing the colour structure can seat a state on. **",
 "   ⌗ *That does not refute the lead -- a sterile state is precisely one the colour structure",
 "     cannot see -- but it removes the route the lead was hoping for.* ** The centre cannot",
 "     supply a fourth state THROUGH the colour bundle; if it supplies one it must be through the",
 "     kernel of the Dirac operator, which is where the count lives. **",
 "   ⇒ ** NARROWED to: does the index pick up anything at the Z_3-fixed centre?  That is a",
 "     computation on `prop:wall`'s operator, not a reading of the figure. **",
]:
    print("  " + s)

# =====================================================================
print()
print("=" * 78)
print("PART 6 — DISPOSITIONS")
print("=" * 78)
print(f"  {'lead':>7} {'disposition':>12}  {'why'}")
for a, b, c in [
    ("L-68", "STRIKE", "its owed action -- derive the grading from the slicing -- is done"),
    ("L-71", "STRIKE", "computed: T is an INVERSION, so the F-2 row is refuted as phrased"),
    ("L-91", "AMEND", "half confirmed by an independent route, half corrected and improved"),
    ("L-69", "NARROW", "the colourless line is 1-dimensional; the question is which grading splits it"),
    ("L-79", "NARROW", "the centre carries no wall, so the route must be the index, not the bundle"),
]:
    print(f"  {a:>7} {b:>12}  {c}")
print()
for s in [
 "⌗ ** THREE OF THE FIVE MOVE WITHOUT NEW PHYSICS, BECAUSE THE ARC ALREADY DID THE WORK AND",
 "   NOBODY HAD GONE BACK TO CLAIM IT. **  That is what a stale tail looks like from the inside:",
 "   not neglected questions, but questions the corpus has quietly outgrown.",
 "",
 "⚠ ** AND ONE OF THEM WAS A LIVE PREDICTION THAT NOBODY SCORED. **  `L-91` called the",
 "   transposition/3-cycle split before the arc and the arc confirmed it.  ** A register that",
 "   only records what is OWED and never scores what was PREDICTED loses the strongest evidence",
 "   the programme generates about itself. **  Recorded here; worth a standing habit.",
]:
    print("  " + s)
