"""
P14_the_gap_is_antisymmetry.py -- P14 sec:openquestions: the invariants of the flat holonomy
group are counted against SU(3)'s, and the result gives the corpus's standing "there is no
curvature" a SIZE and a NAME -- and turns up a failure sharper than the one it was looking for.

WHAT PROMPTED IT.  P14_leg_count_equals_arc_count established that triality zero is NECESSARY
for a colour singlet and not sufficient, and named the missing step: the SU(3) invariants,
askable for the first time now that P14_the_wall_is_a_wall_of_a_hinge supplies the group.

TWO GROUPS ARE IN PLAY AND THE CORPUS MUST SAY WHICH.
  Gamma_full = <gamma_0, gamma_1, gamma_2, P>, order 81.  This is the ACTUAL HOLONOMY GROUP --
    every generator is a loop in the base and encircling one wall is such a loop -- and a single
    gamma_c has determinant omega, so it is NOT inside SU(3).
  Gamma_SU = Gamma_full intersect SU(3), order 27, generated by the ratios and the hinge
    3-cycle.  This is what the su(3) entailment used, and that claim is untouched here.
The epsilon tensor transforms by the determinant, so which group is demanded decides whether the
baryon exists at all; the counting is meaningless until that is said.

WHAT IS ESTABLISHED.
  1. ** THE MESON CHANNEL IS EXACT, IN BOTH GROUPS: one invariant on V (x) V*, the same as
     SU(3), and it is delta^a_b.  The flat holonomy alone picks the meson out and nothing else
     -- no connection is needed for it, and the corpus has been under-claiming there. **
  2. ** THE BARYON CHANNEL FAILS, AND IN TWO DIFFERENT DIRECTIONS. **  Under Gamma_SU there are
     THREE invariants where SU(3) admits one.  epsilon is in the span -- computed, not asserted
     (the projector's basis is {all-on-one-vantage, even-permutation sum, odd-permutation sum},
     and epsilon = even - odd) -- so the flat structure does not FORBID the baryon.  ** But the
     symmetric sum even + odd is in the span too, and SU(3) forbids that; the structure cannot
     tell the baryon from it.  The excess is exactly two. **
  3. ** AND UNDER Gamma_full IT IS WORSE THAN A GAP.  There is exactly ONE invariant and IT IS
     NOT epsilon: 54 of the 81 elements move epsilon.  The unique invariant is the
     all-three-on-one-vantage state -- three constituents of the SAME colour, which is exactly
     what a baryon is not. **  So if single-valuedness is demanded around every loop, which is
     what single-valuedness means and a single wall is a loop, the geometry returns the wrong
     state rather than too many.
  4. ** THE NAME OF THE GAP, WHICH IS THE POINT OF DOING THIS RATHER THAN COUNTING. **  Both
     spurious states are ones a flat Z_3-graded structure cannot distinguish from the baryon,
     and the reason is structural: a grading records HOW MANY constituents sit in each slot and
     nothing about the ORDER or the SIGN.  epsilon is a statement about antisymmetry,
     antisymmetry is a statement about exchange, and exchange is what a discrete abelian grading
     has no access to.  ** So what is missing is not "force" in the abstract; it is the
     ANTISYMMETRY. **

** AND THAT MAY NOT BE A GAUGE QUESTION AT ALL, WHICH IS POSED HERE AND NOT ANSWERED: the
fermionic exchange sign is a SPIN datum rather than a gauge datum, and this sector's
constituents are Dirac zero-modes carrying an exact chirality operator (Proposition prop:wall).
Whether spin-statistics can do what the connection was being asked to do is registered, not
claimed. **

** WHAT THE CORPUS MUST NOW FIX AND HAS NEVER HAD TO: WHICH GROUP SINGLE-VALUEDNESS IS DEMANDED
UNDER.  P14_route_or_point's criterion was written when there was one radius and the question
could not arise.  It arises now, and (3) shows it is load-bearing rather than bookkeeping. **

** A FIRST VERSION OF THIS COMPUTATION WAS WRONG AND IS RECORDED AS SUCH: multiplying sympy
matrices with cube roots and re-simplifying does not canonicalise, and the group closure
reported |Gamma_SU| = 29 -- a prime, hence impossible -- while the basis extraction returned 27
"invariants" from a non-idempotent average.  The rewrite represents monomial matrices
combinatorially and does integer arithmetic mod 3; the orders now come out 81 and 27, and the
projector is asserted idempotent before its columns are read. **

ORIGIN: computations/baryon_edge/L129_the_invariants.py -- built r2376 (c54.54); edit the
origin, not this copy."""
import sympy as sp
import itertools

print(__doc__.split("Run:")[0])

w = sp.exp(2 * sp.pi * sp.I / 3)


def W(k):
    return sp.simplify(sp.expand_complex(w**(k % 3)))


# =====================================================================
print("=" * 78)
print("PART 1 — THE TWO GROUPS IN PLAY")
print("=" * 78)
for s in [
 "`L-128` gives, on the rank-3 vantage bundle, three wall monodromies gamma_c (diagonal,",
 "omega^(-lambda) in slot c) and the hinge 3-cycle P.  ** But those generate two different",
 "groups and the corpus must be clear which one it is claiming. **",
 "",
 "  Gamma_full = <gamma_0, gamma_1, gamma_2, P>.  ** This is the ACTUAL HOLONOMY GROUP: every",
 "    generator is a loop in the base, and encircling ONE wall is such a loop. **  A single",
 "    gamma_c has det = omega^(-lambda), so ** Gamma_full is NOT inside SU(3). **",
 "",
 "  Gamma_SU  = Gamma_full intersect SU(3), generated by the RATIOS gamma_a gamma_b^(-1) and P.",
 "    ** This is what `L-128` used, and `L-128`'s claim was about it: the smallest CONNECTED",
 "    group containing it is SU(3). **  That claim is untouched here.",
 "",
 "⚠ ** AND THE DISTINCTION IS NOT PEDANTRY, IT IS THE WHOLE QUESTION. **  The epsilon tensor is",
 "   SL(3)-invariant, so it transforms by det: under Gamma_full it picks up omega^(-lambda) and",
 "   is NOT invariant.  ** So which group a bound state must be invariant under decides whether",
 "   the baryon exists at all, and it has to be settled before the counting means anything. **",
 "",
 "⇒ ** THE SETTLEMENT, AND IT IS THE CORPUS'S OWN: `L-74` states single-valuedness as the",
 "   criterion, and single-valuedness is invariance under EVERY closed loop -- that is",
 "   Gamma_full. **  But `L-74` also establishes that a lone coloured constituent is NOT",
 "   single-valued and only COMBINATIONS are; and the combination's transport is the product of",
 "   its constituents' -- which for one-per-vantage is the FULL LAP, det 1.  ** Both counts are",
 "   therefore run below and reported separately, because the corpus does not yet fix which. **",
]:
    print("  " + s)

# =====================================================================
print()
print("=" * 78)
print("PART 2 — THE INVARIANTS, COUNTED")
print("=" * 78)

# ---------------------------------------------------------------------
# Group elements are MONOMIAL matrices, so represent them exactly and
# combinatorially -- (sigma, d) meaning  g e_i = omega^{d_i} e_{sigma(i)}.
# Multiplying sympy matrices with cube roots and re-simplifying does NOT
# canonicalise reliably (a first version of this file reported |Gamma_SU| = 29,
# which is prime and therefore impossible); integer arithmetic mod 3 does.
# ---------------------------------------------------------------------
def mul(g, h):
    (gs, gd), (hs, hd) = g, h
    s = tuple(gs[hs[i]] for i in range(3))
    d = tuple((hd[i] + gd[hs[i]]) % 3 for i in range(3))
    return (s, d)


def sgn(s):
    return 1 if list(s) in ([0, 1, 2], [1, 2, 0], [2, 0, 1]) else -1


def det(g):
    s, d = g
    return sgn(s) * W(sum(d))


def trace(g):
    s, d = g
    return sp.simplify(sp.expand_complex(sum((W(d[i]) for i in range(3) if s[i] == i),
                                             sp.Integer(0))))


def mat(g):
    s, d = g
    M = sp.zeros(3, 3)
    for i in range(3):
        M[s[i], i] = W(d[i])
    return M


def close(gens):
    ident = ((0, 1, 2), (0, 0, 0))
    G, frontier = {ident}, [ident]
    while frontier:
        x = frontier.pop()
        for g in gens:
            y = mul(x, g)
            if y not in G:
                G.add(y)
                frontier.append(y)
    return sorted(G)


ID = (0, 1, 2)
CYC = (1, 2, 0)                        # the hinge 3-cycle P
# lambda = 1, so gamma_c carries omega^(-1) = omega^2 in slot c
gam = [(ID, tuple(2 if i == c else 0 for i in range(3))) for c in range(3)]
Pgen = (CYC, (0, 0, 0))

G_full = close(gam + [Pgen])
ratios = [mul(gam[a], (ID, tuple((-gam[b][1][i]) % 3 for i in range(3))))
          for a, b in ((0, 1), (1, 2))]
G_su = close(ratios + [Pgen])

print(f"  |Gamma_full| = {len(G_full):>3}   (expected 81 = 3^3 semidirect 3)   "
      f"dets: {sorted({str(sp.nsimplify(det(g))) for g in G_full})}")
print(f"  |Gamma_SU|   = {len(G_su):>3}   (expected 27 = 3^2 semidirect 3)   "
      f"dets: {sorted({str(sp.nsimplify(sp.simplify(det(g)))) for g in G_su})}")
assert len(G_full) == 81 and len(G_su) == 27, "group orders must divide and be right"
assert all(sp.simplify(det(g) - 1) == 0 for g in G_su), "Gamma_SU must be unimodular"
assert set(G_su) <= set(G_full)


def inv_dim(G, chi):
    """dim of invariants = (1/|G|) sum chi(g), by the projector's trace"""
    tot = sum((chi(g) for g in G), sp.Integer(0))
    v = sp.simplify(sp.expand_complex(tot / len(G)))
    assert sp.im(v) == 0 and v == int(v), f"an invariant count must be a non-negative integer: {v}"
    return int(v)


def chi_VVV(g):
    return sp.expand_complex(trace(g)**3)


def chi_VVbar(g):
    t = trace(g)
    return sp.expand_complex(t * sp.conjugate(t))


def invariant_basis(G, dim, repmat):
    Pr = sp.zeros(dim, dim)
    for g in G:
        Pr += repmat(g)
    Pr = sp.simplify(sp.expand_complex(Pr / len(G)))
    assert sp.simplify(sp.expand_complex(Pr * Pr - Pr)) == sp.zeros(dim, dim), \
        "the average over a GROUP must be idempotent"
    return Pr.columnspace()


print()
print(f"  {'channel':>28} {'Gamma_full':>12} {'Gamma_SU':>10} {'SU(3)':>8} {'the SM object':>16}")
rows = []
for nm, chi, su3, obj in [("V (x) V (x) V   (baryon)", chi_VVV, 1, "epsilon_abc"),
                          ("V (x) V*        (meson)", chi_VVbar, 1, "delta^a_b")]:
    df, ds = inv_dim(G_full, chi), inv_dim(G_su, chi)
    rows.append((nm, df, ds, su3))
    print(f"  {nm:>28} {df:>12} {ds:>10} {su3:>8} {obj:>16}")

# ---- is epsilon actually invariant, under each group?  asked directly ----
eps = sp.zeros(27, 1)
for perm in itertools.permutations(range(3)):
    eps[perm[0] * 9 + perm[1] * 3 + perm[2]] = sgn(perm)


def rep3(g):
    M = mat(g)
    return sp.Matrix(sp.kronecker_product(M, M, M))


print()
for nm, G in (("Gamma_full", G_full), ("Gamma_SU", G_su)):
    bad = [g for g in G
           if sp.simplify(sp.expand_complex(rep3(g) * eps - eps)) != sp.zeros(27, 1)]
    print(f"  ** is epsilon_abc invariant under {nm}?  {not bad} **"
          + ("" if not bad else f"   ({len(bad)} of {len(G)} elements move it)"))

# =====================================================================
print()
print("=" * 78)
print("PART 3 — THE RESULT")
print("=" * 78)
bar_f, bar_s = rows[0][1], rows[0][2]
mes_f, mes_s = rows[1][1], rows[1][2]
for s in [
 f"** THE MESON CHANNEL IS EXACT, IN BOTH GROUPS.  {mes_s} invariant on V (x) V*, and SU(3) gives 1,",
 "   and it is delta^a_b.  ** The flat holonomy alone already picks the meson out and nothing",
 "   else -- no connection is needed for it, and the corpus has been under-claiming there. **",
 "",
 f"⚠ ** THE BARYON CHANNEL FAILS IN BOTH GROUPS, AND IT FAILS IN TWO DIFFERENT DIRECTIONS. **",
 "",
 f"   Under Gamma_SU: {bar_s} invariants where SU(3) admits one.  epsilon IS among them (asserted",
 "   above, element by element), so the flat structure does not FORBID the baryon -- ** but it",
 f"   fails to SELECT it, and the excess is exactly {bar_s - 1}. **",
 "",
 f"   Under Gamma_full: exactly {bar_f} invariant -- ** and it is NOT epsilon. **  54 of the 81",
 "   elements move epsilon, because epsilon transforms by the determinant and Gamma_full is not",
 "   unimodular.  ** So if single-valuedness is demanded around EVERY loop -- which is what",
 "   single-valuedness MEANS, and a single wall IS a loop -- the geometry admits exactly one",
 "   three-constituent invariant and it is the wrong one. **",
 "",
 "⌗ ** THAT SECOND FAILURE IS THE SHARPER ONE AND IT IS NOT WHAT I EXPECTED TO FIND. **  The",
 "   comfortable story was 'the flat structure gets the baryon but over-counts'.  ** Under the",
 "   stricter and more natural reading of single-valuedness it does not get the baryon at all. **",
]:
    print("  " + s)

# =====================================================================
print()
print("=" * 78)
print("PART 4 — WHAT THE INVARIANTS ACTUALLY ARE")
print("=" * 78)


def describe(v):
    terms = []
    for idx in range(27):
        c = sp.nsimplify(sp.simplify(v[idx]))
        if c != 0:
            terms.append((c, (idx // 9, (idx // 3) % 3, idx % 3)))
    return terms


def classify(terms):
    idxs = [ijk for _, ijk in terms]
    if all(len(set(x)) == 1 for x in idxs):
        return "sum_m e_m (x) e_m (x) e_m   -- ALL THREE CONSTITUENTS ON ONE VANTAGE"
    if all(len(set(x)) == 3 for x in idxs):
        par = {sgn(x) for x in idxs}
        if len(idxs) == 6 and par == {1, -1}:
            cs = {tuple(x): c for c, x in terms}
            anti = all(sp.simplify(cs[x] - sgn(x) * cs[(0, 1, 2)]) == 0 for x in cs)
            return ("epsilon_abc  ** THE BARYON **" if anti
                    else "one-per-vantage, both parities, NOT antisymmetric")
        return ("one-per-vantage, EVEN permutations only (cyclic)" if par == {1}
                else "one-per-vantage, ODD permutations only (cyclic)")
    return "mixed"


for nm, G in (("Gamma_SU", G_su), ("Gamma_full", G_full)):
    print(f"  {nm}:")
    for k, v in enumerate(invariant_basis(G, 27, rep3), 1):
        terms = describe(v)
        print(f"     invariant {k}:  {len(terms):>2} terms   {classify(terms)}")
    print()

# epsilon is not one of the basis vectors the projector happens to return; it is in their SPAN.
# Say so by computing, rather than by asserting it in prose over a listing that shows otherwise.
B = sp.Matrix.hstack(*invariant_basis(G_su, 27, rep3))
sym = sp.zeros(27, 1)
for perm in itertools.permutations(range(3)):
    sym[perm[0] * 9 + perm[1] * 3 + perm[2]] = 1
in_span = lambda v: B.rank() == sp.Matrix.hstack(B, v).rank()
print(f"     the projector's basis is {{all-on-one-vantage, EVEN-permutation sum, ODD-permutation sum}}")
print(f"     -- and epsilon = (even) - (odd) is in their span: {in_span(eps)}")
print(f"     while the SYMMETRIC one-per-vantage sum = (even) + (odd) is ALSO in the span: "
      f"{in_span(sym)}   ** and SU(3) forbids that one **")
assert in_span(eps) and in_span(sym)
print()
for s in [
 "** SO THE Gamma_SU INVARIANT SPACE CONTAINS epsilon -- THE BARYON IS THERE -- BUT ALSO",
 "   CONTAINS THE SYMMETRIC ONE-PER-VANTAGE SUM AND THE ALL-ON-ONE-VANTAGE STATE, WHICH SU(3)",
 "   FORBIDS.  The flat structure cannot tell the baryon from either. **  And the single",
 "   Gamma_full invariant is the 'all three on one vantage' state -- ** three constituents of the",
 "   SAME colour, which is exactly what a baryon is not. **",
 "",
 "⌗ ** AND THAT NAMES THE PHYSICS OF THE GAP, WHICH IS THE POINT OF DOING THIS RATHER THAN",
 "   COUNTING. **  Both spurious states are ones a flat Z_3-graded structure cannot distinguish",
 "   from the baryon, and the reason is structural: ** a grading records HOW MANY constituents",
 "   sit in each slot and nothing about the ORDER or the SIGN. **  epsilon is a statement about",
 "   antisymmetry, antisymmetry is a statement about exchange, and exchange is precisely what a",
 "   discrete abelian grading has no access to.",
 "",
 "⇒ ** SO WHAT IS MISSING IS NOT 'FORCE' IN THE ABSTRACT.  IT IS THE ANTISYMMETRY. **  That is a",
 "   sharper target, and it may not be a gauge question at all: ** the fermionic exchange sign is",
 "   a SPIN datum, not a gauge datum **, and P14's constituents are Dirac zero-modes carrying an",
 "   exact chirality operator.  ** Whether spin-statistics can do what the connection was being",
 "   asked to do is a question this file POSES AND DOES NOT ANSWER.  Registered, not claimed. **",
]:
    print("  " + s)

# =====================================================================
print()
print("=" * 78)
print("PART 5 — WHAT THIS DOES TO THE FRONTIER")
print("=" * 78)
for s in [
 "① ** THE MESON IS DONE AND NOBODY NOTICED. **  Flat holonomy alone gives exactly delta^a_b.",
 "   That is a positive result sitting inside what has been recorded as a pure gap.",
 "",
 "② ** THE BARYON GAP HAS A SIZE AND A NAME. **  Under Gamma_SU it is TWO DIMENSIONS, and the",
 "   name is ANTISYMMETRY -- not 'no dynamics', which is what the corpus has been writing.",
 "   ** And under Gamma_full it is worse than a gap: the unique invariant is the WRONG STATE. **",
 "",
 "③ ** AND ONE THING THE CORPUS MUST NOW FIX, WHICH IT HAS NEVER HAD TO: WHICH GROUP",
 "   SINGLE-VALUEDNESS IS DEMANDED UNDER. **  Gamma_full (every loop, including one wall) kills",
 "   epsilon outright; Gamma_SU (the unimodular part, which is what a bound one-per-vantage",
 "   combination actually traverses) keeps it.  ** `L-74`'s criterion was written when there was",
 "   only one radius and the question could not arise.  It arises now and it is load-bearing. **",
 "   Registered as the next thing, ahead of anything about curvature.",
]:
    print("  " + s)
