#!/usr/bin/env python3
"""
RECEIPT — P14 `sec:intro` / `sec:chirality`: ** THE FLATNESS IS NOT A STAGE THE CONSTRUCTION HAS NOT
REACHED.  IT IS A COMPLETE OBSTRUCTION, AND HERE IS ITS INVARIANT. **

P14 states *"the bundle above is flat, so the construction supplies colour's exact selection rules
and no force"*.  That is asserted, not shown, and a reader is entitled to hear it as "the coupling
is not built yet".  This computes the three facts that make it structural.

  PART 1  the wall monodromies, and the holonomy group they generate: ** FINITE **.
  PART 2  ** the moduli of flat connections with the wall classes fixed: ZERO-DIMENSIONAL. **
  PART 3  ** and every point of that space carries $F\\equiv0$ — which is why the dimension was
          never the question. **

rc=0 on success.  Run: python3 P14_the_flat_bundle_cannot_carry_a_force.py      (numpy)
"""
import sys

import numpy as np

print(__doc__.split("rc=0")[0])
W = np.exp(2j * np.pi / 3)

# ---------------------------------------------------------------- PART 1
print("=" * 78)
print("PART 1 — THE WALL MONODROMIES AND THEIR GROUP")
print("=" * 78)
gA, gB, gC = np.diag([W, 1, 1]), np.diag([1, W, 1]), np.diag([1, 1, W])
I3 = np.eye(3, dtype=complex)
print("  A wall branches only the vantage that owns it (disjoint supports, P3/P14), so on the")
print("  fibre C^3 = span(v_A,v_B,v_C) each wall monodromy moves ONE coordinate by omega.")
assert abs(np.linalg.det(gA) - W) < 1e-12, "P14: a single wall monodromy has determinant omega"
assert np.linalg.norm(gA @ gB @ gC - W * I3) < 1e-12, "P14: a full lap is central"
print("     det gamma_A = omega            ✔ (P14 sec:chirality)")
print("     gamma_A gamma_B gamma_C = omega I, central   ✔ (P14: 'the centre')")

# exact monomial arithmetic -- floats round cube roots apart and inflate the group order


def mul(x, y):
    s1, e1 = x
    s2, e2 = y
    return (tuple(s2[s1[i]] for i in range(3)),
            tuple((e1[i] + e2[s1[i]]) % 3 for i in range(3)))


GENS = [((0, 1, 2), (1, 0, 0)), ((0, 1, 2), (0, 1, 0)),
        ((0, 1, 2), (0, 0, 1)), ((2, 0, 1), (0, 0, 0))]
seen, frontier = {((0, 1, 2), (0, 0, 0))}, [((0, 1, 2), (0, 0, 0))]
while frontier:
    nxt = []
    for m in frontier:
        for g in GENS:
            p = mul(m, g)
            if p not in seen:
                seen.add(p)
                nxt.append(p)
    frontier = nxt
print(f"\n  ** the holonomy group generated by the three walls and the hinge cycle: "
      f"|Gamma| = {len(seen)} **")
assert len(seen) == 81, len(seen)
print("     FINITE -- and necessarily so: the holonomy is BRANCHING and a branch structure has")
print("     finitely many sheets.  For a finite group in characteristic zero H^1(Gamma, ad) = 0,")
print("     so the representation does not deform as a representation of its own holonomy group.")

# ---------------------------------------------------------------- PART 2
print()
print("=" * 78)
print("PART 2 — THE MODULI OF FLAT CONNECTIONS, WALL CLASSES FIXED")
print("=" * 78)
GM = [np.array(m, dtype=complex) for m in [
    [[0, 1, 0], [1, 0, 0], [0, 0, 0]], [[0, -1j, 0], [1j, 0, 0], [0, 0, 0]],
    [[1, 0, 0], [0, -1, 0], [0, 0, 0]], [[0, 0, 1], [0, 0, 0], [1, 0, 0]],
    [[0, 0, -1j], [0, 0, 0], [1j, 0, 0]], [[0, 0, 0], [0, 0, 1], [0, 1, 0]],
    [[0, 0, 0], [0, 0, -1j], [0, 1j, 0]], np.diag([1, 1, -2]) / np.sqrt(3)]]
BAS = [1j * g / 2 for g in GM]


def vec(X):
    return np.array([np.real(np.trace(X.conj().T @ b)) / np.real(np.trace(b.conj().T @ b))
                     for b in BAS])


def Ad(g):
    return np.column_stack([vec(g @ b @ np.linalg.inv(g)) for b in BAS])


E = np.eye(8)
AdA, AdB, AdC, AdAB = Ad(gA), Ad(gB), Ad(gC), Ad(gA @ gB)
K = np.hstack([(E - AdA), AdA @ (E - AdB), AdAB @ (E - AdC)])
dim_sol = 24 - np.linalg.matrix_rank(K, tol=1e-8)
kers = [8 - np.linalg.matrix_rank(E - M, tol=1e-8) for M in (AdA, AdB, AdC)]
dim_triv = np.linalg.matrix_rank(np.vstack([(E - AdA), (E - AdB), (E - AdC)]), tol=1e-8)
dim_M = dim_sol - sum(kers) - dim_triv
print("  Deform each wall monodromy inside its conjugacy class and keep the product fixed:")
print("     a = (1-Ad_A)X,  b = (1-Ad_B)Y,  c = (1-Ad_C)Z,  a + Ad_A b + Ad_AB c = 0")
print(f"  {'solutions (X,Y,Z)':>44} {dim_sol:>4}")
print(f"  {'mapping to zero deformation':>44} {sum(kers):>4}")
print(f"  {'trivial (simultaneous conjugation)':>44} {dim_triv:>4}")
print(f"\n  ** dim of the moduli space = {dim_M} : the flat connection is ISOLATED **")
assert dim_M == 0, dim_M
print(f"     Each wall class is SUBREGULAR -- diag(omega,1,1) has a repeated eigenvalue, so its")
print(f"     class has dimension {8 - kers[0]} and not the regular 6.  Three regular classes on a")
print(f"     three-punctured base would have given 3*6 - 2*8 = 2, a two-parameter family;")
print(f"     ** the DISJOINTNESS of the vantages' supports is exactly what removes it. **")
assert 8 - kers[0] == 4

# ---------------------------------------------------------------- PART 3
print()
print("=" * 78)
print("PART 3 — AND THE DIMENSION WAS NEVER THE QUESTION")
print("=" * 78)
print("  The moduli space of FLAT connections consists of FLAT connections: F = 0 at every point.")
print("  A deformation inside it changes WHICH flat bundle one has, not whether there is a field")
print("  strength.  So the argument does not rest on PART 2's answer being zero -- it would go")
print("  through at any dimension.  ** To obtain curvature one must leave the flat locus, and no")
print("  holonomy datum can take you off it, because holonomy is precisely the complete invariant")
print("  a flat connection has. **")
print()
print("  ⇒ the same shape as `P14_quantisation_not_strength` one level up: there the WINDING was")
print("    shown to quantise and not measure; here the BUNDLE is.  A topological datum supplies")
print("    selection rules and cannot supply a strength.")
print()
print("ALL PASS")
sys.exit(0)
