#!/usr/bin/env python3
"""
RECEIPT -- P14 (+P7): ** THE CORPUS'S TWO THREE-FOLD STRUCTURES ARE NOT RELATED AS COVERS.  THE
TURNAROUND DECK FIXES THE ROOT COVER'S BASE AND DOES NOT PERMUTE ITS FIBRE -- omega*r IS A ROOT OF
THE SAME CUBIC ONLY AT r = 0. **

Built r2376+c54.179.  ** THE RESULT IS THE OBSERVER LINE'S, ROUTED AS `FOR_54` ITEM 10.  THE CHECK
IS THIS LINE'S, AND IT EXISTS BECAUSE THE ROUTED RECEIPTS CANNOT FAIL. **

*`C2_the_two_threes_are_not_one_tower` and `C1_the_two_covers_branch_where_the_corpus_pries` carry
ten and twelve printed OK lines between them and ZERO assertions -- `scripts/lint_assertions.py`
puts both in the thirteen that "carry no check of any kind".*  ** `\\rcpt{X}` means X would FAIL if
the claim were false, so neither could be cited from a paper. **  The mathematics was verified
independently here before any of it was landed, and this file is what the paper cites.

** THE TWO THREES. **
  the ROOT cover        base the 2M-plane, fibre the roots of r^3 - alpha^2 r + 2M alpha^2, deck
                        S_3, branched where two roots collide at |r| = alpha/sqrt3 (Nariai).
  the TURNAROUND cover  base the r^(D-1)-plane, fibre the cube roots, deck Z_3 generated by
                        tau -> tau + 2 pi i alpha/(D-1), which FIXES 2M, branched at r = 0.

  PART 1  ** THE COMPUTATION, AND IT IS ONE LINE. **  In the gauge alpha = 1 let r be a root of
          r^3 - r + 2M.  Then, using omega^3 = 1 and r^3 = r - 2M,

              (omega r)^3 - omega r + 2M  =  r^3 + 2M - omega r  =  r - omega r  =  r (1 - omega),

          ** which vanishes only at r = 0. **  So the turnaround deck carries a root of the cubic to
          a root of the same cubic ONLY at the branch point.
  PART 2  ** SO THE DECK DOES NOT ACT ON THE OTHER COVER'S FIBRE AT ALL. **  Checked numerically on
          a spread of 2M across the whole range, in both directions and for both non-trivial cube
          roots: the image is never a root, and the residual is exactly |r||1 - omega| = sqrt(3)|r|.
  PART 3  ** AND THE TWO BRANCH SETS ARE DISJOINT: {+-alpha/sqrt3} against {0}. **  *Which is the
          companion result, and it is the weaker of the two -- disjoint branch loci alone would not
          forbid a covering relation.  PART 1 is what forbids it.*
  PART 4  ** THIS IS STRICTLY STRONGER THAN `lem:twoturnings`, WHICH IS A STATEMENT ABOUT ROOTS. **
          That lemma says no AFFINE change of variable identifies the horizon roots with the
          turnaround's.  ** This says neither three's deck acts on the other's fibre, so they cannot
          be related by ANY covering-space construction over the 2M-plane -- affine or not. **
          The affine statement is exhibited here as the special case it is.

** WHAT THIS DOES NOT SHOW, AND THE ROUTED NOTE SAYS SO TOO. **  It does not show the covers share no
structure.  They share r and 2M, and ** both count three because f = 0 has degree D - 1 ** -- which
is `sec:whichthree`'s own statement and is untouched by any of this.

rc=0 on success.  Run: python3 P14_the_two_threes_are_not_related_as_covers.py   (numpy, ~1 s)
"""
import sys

import numpy as np

print(__doc__.split("rc=0")[0])
fail = []

W = np.exp(2j * np.pi / 3)                       # a primitive cube root of unity
ALPHA = 1.0                                      # the gauge the computation is done in


def cubic(r, M):
    """r^3 - alpha^2 r + 2 M alpha^2, at alpha = 1"""
    return r ** 3 - ALPHA ** 2 * r + 2 * M * ALPHA ** 2


# =====================================================================
print("=" * 78)
print("PART 1/2 — omega.r IS A ROOT OF THE SAME CUBIC ONLY AT r = 0")
print("=" * 78)
print(f"  {'2M':>10} {'root r':>26} {'|cubic(w r)|':>16} {'|r(1-w)| predicted':>20}")
MS = [-0.9, -0.5, -0.2, 0.0, 0.05, 0.2, 0.3849, 0.5, 0.9]
worst = 0.0
n_checked = 0
for M2 in MS:
    for r in np.roots([1.0, 0.0, -ALPHA ** 2, 2 * (M2 / 2) * ALPHA ** 2]):
        for w in (W, W ** 2):
            val = abs(cubic(w * r, M2 / 2))
            pred = abs(r * (1 - w))
            worst = max(worst, abs(val - pred))
            n_checked += 1
            # ** the identity is EXACT, so the check is that the residual EQUALS |r(1-w)| and not
            # merely that it is non-zero.  A test that only asked "is it non-zero" would pass on a
            # wrong formula. **
            if abs(val - pred) > 1e-9 * max(1.0, pred):
                fail.append(f"at 2M={M2}, r={r:.4f}: |cubic(wr)| = {val:.3e} against {pred:.3e}")
        if abs(M2) < 1e-12:
            print(f"  {M2:>10.4f} {str(np.round(r, 6)):>26} {abs(cubic(W*r, M2/2)):>16.3e} "
                  f"{abs(r*(1-W)):>20.3e}")
print(f"  ...{n_checked} (2M, root, omega) triples checked; worst departure from the exact "
      f"identity {worst:.2e}")
print(f"\n  ** THE RESIDUAL IS |r||1-omega| = sqrt(3)|r| EXACTLY, so it vanishes IFF r = 0. **")
print(f"     |1 - omega| = {abs(1-W):.10f}, sqrt(3) = {np.sqrt(3):.10f}")
if abs(abs(1 - W) - np.sqrt(3)) > 1e-12:
    fail.append("|1 - omega| is not sqrt(3)")
# ** and the ONLY place it vanishes: at 2M = 0 the cubic has a root at r = 0 and two at +-alpha,
#    and the deck fixes exactly the first. **
r0 = np.roots([1.0, 0.0, -ALPHA ** 2, 0.0])
fixed = [r for r in r0 if abs(cubic(W * r, 0.0)) < 1e-12]
print(f"\n  at 2M = 0 the roots are {np.round(np.sort_complex(r0), 6)} and the deck maps into the")
print(f"  root set at exactly {len(fixed)} of them: {np.round(np.array(fixed), 6)}")
if len(fixed) != 1 or abs(fixed[0]) > 1e-12:
    fail.append(f"the deck should fix exactly r=0 and fixes {fixed}")

# =====================================================================
print()
print("=" * 78)
print("PART 3 — AND THE BRANCH SETS ARE DISJOINT")
print("=" * 78)
# the root cover branches where the discriminant of r^3 - a^2 r + 2 M a^2 vanishes: two roots
# collide.  For this depleted cubic that is 2M = +- 2 alpha / (3 sqrt3), at r = -+ alpha/sqrt3.
M_nar = ALPHA / (3.0 * np.sqrt(3.0))
rr = np.roots([1.0, 0.0, -ALPHA ** 2, 2 * M_nar * ALPHA ** 2])
rr = np.sort_complex(rr)
_pairs = [(abs(rr[i] - rr[j]), i, j) for i in range(3) for j in range(i + 1, 3)]
gap, _i, _j = min(_pairs)
_where = abs(0.5 * (rr[_i] + rr[_j]))            # the locus of the collided pair, not of any other root
print(f"  at 2M = 2*alpha/(3 sqrt3) = {2*M_nar:.6f} the roots are {np.round(rr, 6)}")
print(f"  the closest pair is {gap:.2e} apart — they have COLLIDED, at |r| = {_where:.6f}")
print(f"  alpha/sqrt3 = {ALPHA/np.sqrt(3):.6f}")
print(f"\n  ** the root cover branches at |r| = alpha/sqrt3 = {ALPHA/np.sqrt(3):.4f}; the turnaround")
print(f"     cover branches at r = 0.  DISJOINT. **")
print("     *These are exactly the two loci P7 insists on prying apart — 'quantities never to be")
print("     conflated'.  So that naming guard has an analytic cause: conflating the loci identifies")
print("     a point where one cover is branched with a point where the other is not.*")
if gap > 1e-6:
    fail.append(f"the roots do not collide at the Nariai mass: closest pair {gap:.2e}")
if abs(ALPHA / np.sqrt(3)) < 1e-9:
    fail.append("the two branch loci are not disjoint")

# =====================================================================
print()
print("=" * 78)
print("PART 4 — STRICTLY STRONGER THAN THE AFFINE STATEMENT, AND THE SPECIAL CASE IS EXHIBITED")
print("=" * 78)
# lem:twoturnings: no AFFINE map r -> a r + b carries the horizon roots onto the turnaround's.
# The deck is the affine map with a = omega, b = 0 -- so it is one point of that lemma's domain,
# and PART 1 rules out the whole deck rather than one map.
print("  `lem:twoturnings` quantifies over AFFINE maps r -> a r + b; the turnaround deck is the")
print("  single case (a, b) = (omega, 0).  ** PART 1 is not an instance of that lemma but a")
print("  statement about the DECK ACTION, which no affine statement reaches: it says the deck's")
print("  orbit leaves the root variety, for every root and every non-trivial omega. **")
nonaffine = 0
for M2 in MS:
    for r in np.roots([1.0, 0.0, -ALPHA ** 2, 2 * (M2 / 2) * ALPHA ** 2]):
        if abs(r) > 1e-12 and abs(cubic(W * r, M2 / 2)) > 1e-12:
            nonaffine += 1
print(f"\n  ** {nonaffine} of the {n_checked//2} (2M, root) pairs with r != 0 have omega.r OFF the")
print("     root variety, and none has it on.  So the deck does not permute the fibre anywhere")
print("     except at the branch point, where the fibre is not three points. **")
if nonaffine == 0:
    fail.append("no pair left the root variety -- PART 4's claim is empty")

# =====================================================================
print()
print("=" * 78)
if fail:
    print("FAILED: " + "; ".join(fail))
    sys.exit(1)
print("ALL CHECKS PASS — omega.r is a root of the same cubic only at r = 0, the residual is exactly")
print("sqrt(3)|r|, the two branch sets are disjoint, and the statement about DECKS is strictly")
print("stronger than lem:twoturnings' statement about affine maps on ROOTS.")
print("=" * 78)

# ============================================================================================
# GATE — r2376+c54.179.  P7 (beside lem:twoturnings) and P14 (sec:whichthree) now carry this, and
# the three things they carry are pinned.
#   (1) the identity is EXACT and equals |r(1-omega)| = sqrt(3)|r| -- not merely non-zero, since a
#       non-zero test passes on a wrong formula;
#   (2) the deck fixes exactly ONE root, r = 0;
#   (3) the branch sets are alpha/sqrt3 and 0 and are disjoint -- the two loci P7 pries apart.
# ============================================================================================
assert abs(abs(1 - W) - np.sqrt(3)) < 1e-12, "the residual factor |1-omega| must be sqrt(3)"
assert worst < 1e-9, f"the identity is not exact: worst departure {worst:.2e}"
assert len(fixed) == 1 and abs(fixed[0]) < 1e-12, "the deck must fix exactly r = 0"
assert abs(ALPHA / np.sqrt(3) - 0.5773502691896258) < 1e-12, "the root cover's branch radius moved"
assert nonaffine >= 20, f"only {nonaffine} pairs left the root variety -- too few to be a sweep"
assert abs(_where - ALPHA / np.sqrt(3)) < 1e-6, \
    f"the collided pair sits at |r| = {_where:.6f}, not at alpha/sqrt3 -- the branch locus moved"
print(f"GATE c54.179 (r2376): omega.r leaves the root variety at every one of {nonaffine} roots with "
      f"r != 0, with residual exactly sqrt(3)|r|; the deck fixes only r = 0; branch sets "
      f"{{+-{ALPHA/np.sqrt(3):.4f}}} and {{0}} disjoint -- pinned against P7 lem:twoturnings and P14 "
      f"sec:whichthree.")
