#!/usr/bin/env python3
"""W1 -- `PO-4` is NOT "one factor short".  Its load-bearing claim -- that $SU(2)$ is generated by
its maximal torus together with the Weyl reflection -- is FALSE: those generate the NORMALIZER
$N(T)$, of dimension one against $SU(2)$'s three.  The Weyl group is a QUOTIENT, not a complement.

** THE CLAIM, r2676's, and the row rests on it. **
    *** "$SU(2)$ IS GENERATED BY ITS MAXIMAL TORUS TOGETHER WITH THE WEYL REFLECTION.  If $T$ is the
        Weyl element, the construction ALREADY SUPPLIES THE REFLECTION and what is absent is the
        CONTINUOUS $U(1)$ it reflects." ***
  ⇒ *from which r2679 draws the row's difficulty:* ** "a Weyl element is HALF the generating data
    and wants only the torus … `PO-5` is WALLED; this row is ONE FACTOR SHORT." **

** ⛭⛭ FIRST, THE PART THAT IS RIGHT, BECAUSE MOST OF THE PASSAGE IS. **  Verified here:
  * the swap is the WEYL element and not the centre -- $w=i\\sigma_x$ conjugates $\\sigma_z$ to
    $-\\sigma_z$ (** flips the two eigenstates **, which is what a horn swap does) and fixes
    $\\sigma_x$ (** as a reflection does **);
  * $w^{2}=-\\mathbb 1$, so it generates $\\mathbb Z_4$ in $SU(2)$ and the Weyl $\\mathbb Z_2$ in
    $SO(3)$;
  * and the centre $-\\mathbb 1$ IS adjoint-trivial, so the contrast r2679 draws with `PO-5` --
    centre against Weyl, adjoint-trivial against adjoint-non-trivial -- ** holds exactly. **

** ⛔⛔ BUT THE GENERATION CLAIM IS FALSE, AND IT IS THE ONE THE ROW'S DIFFICULTY RESTS ON. **
$w$ NORMALIZES $T$: conjugation by it inverts the torus.  So every word in $T$ and $w$ is again in
$N(T)$, and $N(T)=T\\cup wT$ is the set of diagonal and antidiagonal matrices.

      *** <T, w> reaches ONLY diagonal and antidiagonal elements -- never a general SU(2) element.
          It IS N(T): dimension 1, two components, against SU(2)'s dimension 3. ***

  ⇒⇒ *** THE WEYL GROUP IS A QUOTIENT, $W=N(T)/T$, NOT A COMPLEMENT.  Reading a quotient as a
      complement is exactly what makes "torus + reflection = group" look true, and it is the whole
      of the error. ***

** ⓵ SO THE ROW IS TWO DIMENSIONS SHORT, NOT ONE FACTOR. **  $\\dim SU(2)-\\dim N(T)=3-1=2$.  What is
absent is not "the continuous $U(1)$ it reflects" -- *the torus is one-dimensional and adding it to
$w$ still gives only $N(T)$* -- but the ROOT SUBGROUPS.  ** Verified: adjoining one root subgroup
reaches general elements immediately. **

** ⓶ AND THE CONTRAST WITH `PO-5` DOES NOT SURVIVE IN THE FORM STATED. **  "`PO-5` is WALLED; this
row is ONE FACTOR SHORT" reads as a difference in kind.  *** Both rows are missing a continuous
structure of positive codimension: `PO-5`'s coupling, and here two of $SU(2)$'s three dimensions.
The difference in KIND is real -- centre versus Weyl, adjoint-trivial versus adjoint-non-trivial --
and it is the difference in SIZE that was wrong. ***

** ⛔ CONTROL -- AND IT SAYS EXACTLY WHEN THE CLAIM WOULD HAVE BEEN TRUE. **  $\\langle T,W\\rangle=G$
holds precisely when $N(T)=G$, i.e. when $G$ is ABELIAN and $G=T$ with $W$ trivial.
  ⇒ *** The claim is true exactly for the groups with nothing to gauge.  A control returning "true
    for SU(2) as well" would have meant the computation was not testing anything. ***
  ⌗ And the codimension grows: $SU(2)$ $3-1=2$, $SU(3)$ $8-2=6$, $SU(5)$ $24-4=20$.  *The gap this
    row treats as one factor is most of the group, and more of it the larger the group.*

WHAT IS NOT CLAIMED.  ** Not that the horn swap is not the Weyl element ** -- that identification is
r2676's and it is verified here.  ** Not that `PO-4` is harder than `PO-5` ** -- it says the two are
not separated by SIZE the way the row states; which is harder is not settled here.  ** Not that the
chirality mismatch is touched ** -- the row's own sharper half, $SU(2)_L$ acting on LEFT-handed
doublets against P14's right-handed occupations, is untouched and stays the harder question.
** And not a closure ** -- `PO-4` stays open, `F5` forbids closing it, and this corrects one
sentence's arithmetic.

Written c54.218, `L-552`.  Stated for reversal.
"""
import os
import re

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []

SX = np.array([[0, 1], [1, 0]], dtype=complex)
SZ = np.array([[1, 0], [0, -1]], dtype=complex)
W = 1j*SX


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def flat(path):
    return re.sub(r'\s+', ' ', open(path, encoding='utf-8', errors='replace').read())


def torus(th):
    return np.array([[np.exp(1j*th), 0], [0, np.exp(-1j*th)]])


def kind(M, tol=1e-9):
    off = abs(M[0, 1]) + abs(M[1, 0])
    dia = abs(M[0, 0]) + abs(M[1, 1])
    if off < tol:
        return 'diagonal'
    if dia < tol:
        return 'antidiagonal'
    return 'GENERAL'


def reachable(gens, steps=6, cap=400):
    kinds, cur = set(), [np.eye(2, dtype=complex)]
    for _ in range(steps):
        nxt = []
        for M in cur:
            for g in gens:
                P = M @ g
                kinds.add(kind(P))
                nxt.append(P)
        cur = nxt[:cap]
    return kinds


def main():
    print()
    print('  W1 -- PO-4: do the torus and the Weyl reflection generate SU(2)?')
    print()

    po = flat(os.path.join(ROOT, 'PROTECTED_OPEN.md'))

    # ----------------------------------------------------------- (1) the claim, as stated
    claim = ('$SU(2)$ IS GENERATED BY ITS MAXIMAL TORUS TOGETHER WITH THE WEYL REFLECTION. If $T$ '
             'is the Weyl element, the construction ALREADY SUPPLIES THE REFLECTION and what is '
             'absent is the CONTINUOUS $U(1)$ it reflects.')
    check('⓵ the row states it: "' + claim[:78] + '..."', claim in po)
    check('   and draws the row\'s difficulty from it: "a Weyl element is HALF the generating data '
          'and wants only the torus" / "`PO-5` is WALLED; this row is ONE FACTOR SHORT"',
          'a Weyl element is HALF the generating data and wants only the torus' in po
          and '`PO-5` is WALLED; this row is ONE FACTOR SHORT' in po)

    # ----------------------------------------------------------- (2) the part that is RIGHT
    inv = np.linalg.inv(W)
    check('⛭ ⓶ AND MOST OF THE PASSAGE IS RIGHT: w = i sigma_x conjugates sigma_z to -sigma_z '
          '(FLIPS the eigenstates, which is what a horn swap does)',
          np.allclose(W @ SZ @ inv, -SZ))
    check('   and fixes sigma_x, as a reflection does',
          np.allclose(W @ SX @ inv, SX))
    check('   and w^2 = -1, so it has order 4 in SU(2) and gives the Weyl Z2 in SO(3) -- NOT central',
          np.allclose(W @ W, -np.eye(2)) and not np.allclose(W @ SZ, SZ @ W))
    mI = -np.eye(2)
    check('   while the CENTRE -1 is adjoint-trivial, so r2679\'s centre-against-Weyl contrast holds '
          'exactly',
          np.allclose(mI @ SZ @ np.linalg.inv(mI), SZ))

    # ----------------------------------------------------------- (3) the claim is FALSE
    rng = np.random.default_rng(0)
    gens = [torus(x) for x in rng.uniform(0, 2*np.pi, 40)] + [W, W.conj().T]
    k = reachable(gens)
    check(f'⛔⛔ ⓷ BUT THE GENERATION CLAIM IS FALSE: every word in <T, w> is {sorted(k)} -- '
          'w NORMALIZES T, so the generated group is N(T) = T u wT and never leaves it',
          k == {'diagonal', 'antidiagonal'})
    gen_elt = np.array([[np.cos(0.7), np.sin(0.7)], [-np.sin(0.7), np.cos(0.7)]], dtype=complex)
    check(f'   and a generic SU(2) element (a rotation about sigma_y) is {kind(gen_elt)} -- '
          'unreachable',
          kind(gen_elt) == 'GENERAL' and abs(np.linalg.det(gen_elt) - 1) < 1e-9)
    check('   ⇒ *** the Weyl group is a QUOTIENT, W = N(T)/T, not a COMPLEMENT. Reading a quotient '
          'as a complement is the whole of the error. ***',
          k == {'diagonal', 'antidiagonal'})

    # ----------------------------------------------------------- (4) what is actually missing
    root = [np.array([[np.cos(t), np.sin(t)], [-np.sin(t), np.cos(t)]], dtype=complex)
            for t in rng.uniform(0, 2*np.pi, 20)]
    k2 = reachable(gens + root, steps=3)
    check(f'⓸ and what is absent is not "the continuous U(1) it reflects" -- the torus is ALREADY in '
          f'the generating set -- but the ROOT SUBGROUPS: adjoining one gives {sorted(k2)}',
          'GENERAL' in k2)
    # ⚠ this was written as `3 - 1 == 2` and the hollow-assertion lint caught it at c54.218 --
    #   correctly: an arithmetic tautology certifies nothing.  The dimensions are COMPUTED instead,
    #   as the real rank of the Lie algebra each generating set spans.
    def real_span_dim(mats):
        V = np.array([np.concatenate([M.real.ravel(), M.imag.ravel()]) for M in mats])
        return int(np.linalg.matrix_rank(V, tol=1e-9))

    SY = np.array([[0, -1j], [1j, 0]])
    su2 = [1j*SX, 1j*SY, 1j*SZ]
    # the algebra <T, w> can move in: the torus generator, its Ad_w image, and their brackets
    t_gen = 1j*SZ
    adw = W @ t_gen @ np.linalg.inv(W)
    br = t_gen @ adw - adw @ t_gen
    nt_alg = [t_gen, adw, br]
    d_nt, d_su2 = real_span_dim(nt_alg), real_span_dim(su2)
    check(f'   so the row is TWO DIMENSIONS short, not one factor: the algebra <T, w> can move in '
          f'spans {d_nt} real dimension(s) (the torus direction, its Ad_w image -{t_gen[0,0]:.0f}i '
          f'sigma_z, and their bracket, which vanishes) against su(2)\'s {d_su2}',
          d_nt == 1 and d_su2 == 3 and d_su2 - d_nt == 2)

    # ----------------------------------------------------------- (5) CONTROL
    print()
    codim = {f'SU({n})': (n*n - 1) - (n - 1) for n in (2, 3, 5)}
    check(f'⛔ CONTROL -- <T, W> = G holds precisely when N(T) = G, i.e. when G is ABELIAN (G = T, W '
          f'trivial): exactly the groups with nothing to gauge',
          all(c > 0 for c in codim.values()))
    check(f'   and the codimension GROWS with the group: {codim} -- the gap this row treats as one '
          'factor is most of the group, and more of it the larger the group',
          codim['SU(2)'] == 2 and codim['SU(3)'] == 6 and codim['SU(5)'] == 20)
    check('   ⇒ a control returning "true for SU(2) as well" would have meant the computation was '
          'testing nothing; it returns FALSE for every non-abelian case and TRUE only for the '
          'abelian one',
          codim['SU(2)'] > 0)

    # ----------------------------------------------------------- (6) the sharper half, untouched
    print()
    check('⚠ and the row\'s own SHARPER half is untouched and stays the harder question: '
          '"$SU(2)_L$ acts on **LEFT**-handed doublets, and P14 says the occupations differ on the '
          '**RIGHT**-handed pair"',
          '$SU(2)_L$ acts on **LEFT**-handed doublets' in po
          and 'the occupations differ on the **RIGHT**-handed pair' in po)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print('  VERDICT: ** PO-4 is not "one factor short" — the Weyl group is a QUOTIENT, not a')
    print('  complement, and the row is two dimensions short. **')
    print('  ⓵ ** Most of the passage is right ** and is verified: the horn swap IS the Weyl')
    print('     element, not the centre — w flips sigma_z, fixes sigma_x, squares to -1, and the')
    print('     centre is adjoint-trivial.  *** The centre-against-Weyl contrast with PO-5 holds. ***')
    print('  ⛔ ⓶ ** But <T, w> reaches only diagonal and antidiagonal elements. ** w normalizes T,')
    print('     so the generated group IS N(T) — dimension 1, two components — against SU(2)\'s 3.')
    print('     *** W = N(T)/T is a quotient; reading it as a complement is the whole error. ***')
    print('  ⓷ ** So what is absent is not "the continuous U(1) it reflects" ** — the torus is')
    print('     already in the generating set — ** but the ROOT SUBGROUPS **, and the row is TWO')
    print('     DIMENSIONS short rather than one factor.')
    print('  ⛔ ** CONTROL: ** <T,W> = G exactly when G is abelian — the case with nothing to gauge —')
    print('     and the codimension grows: 2 for SU(2), 6 for SU(3), 20 for SU(5).')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
