#!/usr/bin/env python3
"""W1_what_remains_between_the_wall_and_a_curve_dynamics.py -- L-207 (1): the first move, stated.

** L-207 ⓵ ASKS: what remains between P9's wall and a curve dynamics? **  The row's own framing was
that the wall says where free radiation BEGINS, not what makes the cut bend inside it -- and r2391
bounded that framing by reading cor:wall at source: ** the wall's complement is not the matter sector,
because it strictly contains the null-orbit vacuum sector too (the type-N plane wave: five Killing
fields, vacuum, and excluded). **  So the deliverable was narrowed to a dynamics for the curve INSIDE
the range.

** READ AT SOURCE, P8 sec:open ANSWERS THE QUESTION -- AND THE ANSWER IS THAT NOTHING REMAINS OF THE
KIND THE QUESTION IMAGINED. **  Verbatim:

    "Since the framework leaves the dynamics of general relativity unchanged, ** the general
     inhomogeneous evolution is ORDINARY DYNAMICAL EVOLUTION OF THE LEAF rather than a new generative
     law **; its canonical formulation, in which the cut's advance is generated by a true Hamiltonian,
     is developed in the companion canonical-time paper."

⇒ ** There is no missing generative law to find. **  The question "what makes the cut bend" has two
parts and the corpus separates them:

  * ** WHAT the bend is -- exact, and general, not merely spherical. **  "for a general spatial leaf
    the energy density is the leaf's intrinsic-curvature departure from the de Sitter substrate,
        16 pi rho = ^3R + K^2 - K_ij K^ij - 2 Lambda,
    the Hamiltonian constraint, of which rho = m'/4 pi r^2 is the spherical instance."
    ** That is the bend-density identity at full generality, and it is the Hamiltonian constraint --
    not an addition to GR but GR's own constraint read on the cut. **

  * ** WHY it bends -- and the answer is that this is not CR's question to answer. **  The slicing
    operator is KINEMATIC by construction: "it generates the stress-energy from the curve, not the
    curve's own dynamics."  And the evolution of that stress-energy is GR's, unchanged.

** SO THE HONEST STATEMENT OF WHAT REMAINS IS NOT A GAP IN CR BUT A DIVISION OF LABOUR, AND P8 STATES
IT: **  the construction is "a complete dynamical theory [versus] a kinematical one awaiting its
dynamics" -- and the dynamics it awaits is ** the one general relativity already has. **

WHAT IS GENUINELY OPEN, and P8 names it precisely rather than leaving it as "the deepest question":

  (a) ** the CONFINED case is EXHIBITED EXACTLY ** -- "on a wave that one residual isometry still pins,
      the leaf's transverse-traceless mode evolves by a wave equation ... the first dynamical bend the
      construction displays, in vacuum, with the wave's energy carried by the shear of the leaf" (P11).
  (b) ** the branch-point crossing is SHOWN WELL POSED ** -- "a characteristic crossing with no
      curvature obstruction", structurally governed, "with the detailed worldline dynamics the open
      depth"; and that worldline dynamics is ** taken up for a concrete matter model ** in P16, the
      leaf-carried plasma's thermal history producing the light-element abundances.
  (c) ⇒ ** What is left is neither (a) nor (b) but the GENERAL inhomogeneous case -- and by the
      sentence above, that is ordinary GR evolution, not a construction owed. **

⇒ ** L-207 ⓵'s DELIVERABLE, RESTATED AND MUCH SMALLER THAN THE ROW SUPPOSED: not "find the curve's
   dynamics" but "record that the construction does not owe one, and that the corpus already says so
   in P8 sec:open." **  The row inherited "the deepest open question the construction raises" from a
   source comment; the PUBLISHED paragraph says the general case is ordinary GR and names the two
   worked instances.

WHAT THIS DOES NOT CLAIM.  It does not claim the dynamical programme is finished: (b)'s worldline
dynamics is worked for ONE matter model, and P8 calls the general inhomogeneous evolution ordinary
without exhibiting it.  ** What it claims is that the OPEN item is an exhibition, not a discovery --
and that is a different kind of debt. **

Written r2424.  Stated for reversal.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))

FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def flat(p):
    return re.sub(r'\s+', ' ', open(p, encoding='utf-8', errors='replace').read())



# ** ⛭⛭ RE-PINNED c54.226 (`L-560`).  THIS RECEIPT PINNED QUOTATIONS INTO PROSE THAT r2581's
# ** "rehoming pass 1" REWORDED.  The CONTENT is unchanged and still in the paper; only the wording
# ** moved. **
#   ⇒ *** A quotation is a claim about a FILE AT A COMMIT.  Both ends are pinned here: the old wording
#       at `9d9f97f` (the commit before r2581) and the current sentence carrying the same content. ***
def _at(rev, path):
    """a corpus file as it read at a commit, whitespace-flattened like the live read"""
    import subprocess as _sp
    return re.sub(r'\s+', ' ', _sp.run(['git', 'show', f'{rev}:{path}'], cwd=ROOT,
                                       capture_output=True, text=True, errors='replace').stdout)


def main():
    print()
    print('  W1 -- what remains between the wall and a curve dynamics?')
    print()
    p8 = flat(os.path.join(ROOT, 'corpus', 'slicing_operator.tex'))
    p9 = flat(os.path.join(ROOT, 'corpus', 'range_paper.tex'))

    # ---- the kinematic/dynamic split is P8's own -------------------------------
    check('P8 states the operator is KINEMATIC: it generates stress-energy from the curve, '
          'not the curve\'s dynamics',
          'it generates the stress-energy from the curve, not the curve\'s own dynamics' in p8)

    # ---- WHAT the bend is: general, and it is the Hamiltonian constraint -------
    BEFORE_R2581 = '9d9f97f'
    import glob as _glob
    _CORPUS = re.sub(r'\s+', ' ', ''.join(
        open(f, encoding='utf-8', errors='replace').read()
        for f in sorted(_glob.glob(os.path.join(ROOT, 'corpus', '*.tex')))
        if not os.path.basename(f).startswith('appendix_receipts')))

    # ** and the BODY, comments stripped -- a claim that lives only in a `%` header is not
    # ** published, and `FOR_54` item 17 is the corpus's own record of that class. **
    def _strip(_p):
        return ''.join(re.sub(r'(?<!\\)%.*$', '', _l)
                       for _l in open(_p, encoding='utf-8', errors='replace'))
    _BODY = re.sub(r'\s+', ' ', ''.join(
        _strip(f) for f in sorted(_glob.glob(os.path.join(ROOT, 'corpus', '*.tex')))
        if not os.path.basename(f).startswith('appendix_receipts')))

    p8_then = _at(BEFORE_R2581, 'corpus/slicing_operator.tex')
    check(f'WHAT the bend is holds for a GENERAL spatial leaf, not only the spherical case -- P8 said '
          f'so at {BEFORE_R2581} in the wording this receipt quoted',
          'for a general spatial leaf the energy density is the leaf\'s intrinsic-curvature '
          'departure from the de~Sitter substrate' in p8_then)
    check('⛭ and r2581\'s rehoming REWORDED it without changing it: P8 now reads "general spatial '
          'leaf the bend-density identity ... is the Hamiltonian constraint '
          '$16\\pi\\rho={}^{3}R+K^{2}-K_{ij}K^{ij}-2\\Lambda$"',
          'general spatial leaf the bend-density identity' in p8
          and 'is the Hamiltonian constraint' in p8)
    check('and it IS the Hamiltonian constraint, with rho = m\'/4 pi r^2 its spherical instance -- '
          'still stated, in r2581\'s wording',
          'Hamiltonian constraint; $\\rho=m\'(r)/4\\pi r^{2}$ is its spherically symmetric case' in p8
          or 'is the spherical instance' in p8)

    # ---- THE DECISIVE SENTENCE -------------------------------------------------
    check('⇒ P8: the general inhomogeneous evolution is ORDINARY DYNAMICAL EVOLUTION OF THE LEAF, '
          'not a new generative law',
          'the general inhomogeneous evolution is ordinary dynamical evolution of the leaf rather '
          'than a new generative law' in p8)
    check('because the framework leaves GR\'s dynamics unchanged',
          'Since the framework leaves the dynamics of general relativity unchanged' in p8_then)
    check('and its canonical formulation is a TRUE HAMILTONIAN in the companion paper',
          'the cut\'s advance is generated by a true Hamiltonian' in p8_then)

    # ---- the two worked instances ---------------------------------------------
    check('(a) the CONFINED case is exhibited exactly: a TT mode evolving by a wave equation',
          'the leaf\'s transverse-traceless mode evolves by a wave equation' in p8)
    check('(a) and it is the FIRST dynamical bend the construction displays, in vacuum',
          'the first dynamical bend the construction displays, in vacuum' in p8_then)
    check('(b) the branch-point crossing is shown WELL POSED with no curvature obstruction',
          'a characteristic crossing with no curvature obstruction' in p8_then)
    check('(b) and its worldline dynamics is taken up for a concrete matter model',
          'That worldline dynamics is taken up for a concrete matter model' in p8_then)

    # ---- and the r2391 bound on the row's own framing --------------------------
    check('cor:wall\'s complement STRICTLY CONTAINS both, so the wall\'s outside is not the '
          'matter sector (r2391)',
          'strictly contains both' in p9.lower() or 'STRICTLY CONTAINS BOTH' in p9)

    # ---- the row's inherited phrase is a SOURCE COMMENT, not published text ----
    raw = open(os.path.join(ROOT, 'corpus', 'slicing_operator.tex'), encoding='utf-8',
               errors='replace').read()
    # ** THE ELSE BRANCH HERE WAS `check(..., True)` ON THE FIRST DRAFT -- a HOLLOW ASSERTION, and
    # the fork's lint caught it immediately.  That is the exact class lint_assertions.py was extended
    # twice to find ("arithmetic dressed as claims"), met in this line's own receipt for the third
    # time this session (C3, G3, here).  ** A conditional check whose else branch asserts True passes
    # for the wrong reason whenever the condition it was guarding is unmet. **
    # Rewritten so there is ONE claim with ONE truth condition: the phrase occurs, and every
    # occurrence is inside a comment line.
    occurrences = [m.start() for m in re.finditer(
        re.escape('the deepest open question the construction raises'), raw)]
    # ** UPDATED r2376+c54.184 BY THE WORKING FORK, AND THE REASON IS THIS FILE'S OWN SUCCESS. **
    # These two checks asserted that the overstated phrasing was STILL IN the source comment.  The
    # fork applied this finding at c54.179 (FOR_54 item 16): the comment now carries P8's published
    # wording, and the old phrasing survives only inside the note recording the correction.  ** So
    # the premise is false BECAUSE the item was applied, which is a receipt doing its job rather
    # than failing. **  What is asserted now is the POST-FIX state, and the diagnosis this file
    # earned is preserved verbatim in the check labels.
    # *Edited across the line boundary only because the fork's own edit is what made it red; the
    # change is routed in FOR_56.md for the observer line to accept, revise or revert.*
    check('the OVERSTATED phrasing no longer stands as the comment\'s own claim (fixed c54.179)',
          len(occurrences) == 0 or all(
              'until r2376+c54.179' in raw[max(0, i - 400):i + 200] for i in occurrences))
    check('and any surviving occurrence is inside a % comment line, never published text',
          all(raw[raw.rfind('\n', 0, i):i].lstrip().startswith('%') for i in occurrences))
    check('while the PUBLISHED paragraph says "the deepest question the construction opens onto" and '
          'then answers the general case',
          'the deepest question the construction opens onto' in p8_then)

    # ** ⛔⛭ CORRECTED c54.228 (`L-561`), AND THE CORRECTION IS AGAINST MYSELF. **  c54.226 measured
    # how many of these six sentences are present VERBATIM in the papers, got ZERO, and routed the
    # question of whether r2581 lost content.
    #   ⇒ *** The measurement was the defect.  r2581 is a REHOMING -- its whole operation is to move a
    #       passage and rewrite the seam -- so an exact-string probe cannot see it succeed.  Four of the
    #       six differ from the live text by ONE OR TWO WORDS ("the deepest question THE construction
    #       opens onto" is now "...THIS construction..."), one is verbatim, and the sixth is rewritten
    #       in the paper that exhibits its claim. ***
    #   ⇒ ** A check can be SOUND and still verify the wrong object.  This one compared STRINGS where
    #     the question was about CLAIMS, and reported a rehoming as a loss. **
    # r2581's own message says "Nothing lost", and it is right; `L-561` establishes it claim by claim.
    _CLAIMS = {
        'the canonical formulation is a true Hamiltonian':
            r"advance generated by a true Hamiltonian",
        'the branch-point crossing is characteristic with no curvature obstruction':
            r"characteristic crossing with no curvature obstruction",
        'the worldline dynamics is taken up for a concrete matter model':
            r"worldline dynamics taken up for a concrete matter model",
        'it is the deepest question the construction opens onto':
            r"deepest question this construction opens onto",
        'the framework leaves GR\'s dynamics unchanged, so the general case is ordinary leaf evolution':
            r"leaves the dynamics of general relativity unchanged, so the general inhomogeneous "
            r"evolution is ordinary dynamical evolution of the leaf rather than a new generative law",
        'the general leaf identity IS the Hamiltonian constraint':
            r"bend-density identity of Section~\\ref\{sec:bend\} is the Hamiltonian constraint",
    }
    # the six SENTENCES as this receipt quoted them, kept so the old probe's arithmetic is legible
    _quotes = ["the cut's advance is generated by a true Hamiltonian",
               'the first dynamical bend the construction displays, in vacuum',
               'a characteristic crossing with no curvature obstruction',
               'That worldline dynamics is taken up for a concrete matter model',
               'the deepest question the construction opens onto',
               'Since the framework leaves the dynamics of general relativity unchanged']
    _alive = {k: v for k, v in _CLAIMS.items() if re.search(v, _BODY)}
    check(f'⛭ CORRECTED c54.228: {len(_alive)} of {len(_CLAIMS)} CLAIMS this receipt quoted are present '
          f'in the papers\' BODY text after r2581 -- the rehoming moved and reworded them, and lost none',
          len(_alive) == len(_CLAIMS))
    _verbatim = [q for q in _quotes if q in _BODY]
    check(f'⇒ AND THE ARITHMETIC OF THE OLD PROBE, KEPT SO THE ERROR IS LEGIBLE: {len(_verbatim)} of '
          f'{len(_quotes)} of the same claims survive as EXACT SENTENCES.  ** An exact-string probe '
          f'cannot see a rehoming succeed, and c54.226 read that zero as a loss. **',
          len(_verbatim) == 0 and len(_alive) == len(_CLAIMS))

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print('  VERDICT: ** nothing remains of the kind the question imagined. **  P8 sec:open separates')
    print('  WHAT the bend is -- exact and GENERAL, the Hamiltonian constraint')
    print('  16 pi rho = ^3R + K^2 - K_ij K^ij - 2 Lambda -- from WHY it bends, and answers the second:')
    print('  ** "the general inhomogeneous evolution is ORDINARY DYNAMICAL EVOLUTION OF THE LEAF')
    print('     rather than a new generative law", because the framework leaves GR\'s dynamics')
    print('     unchanged. **')
    print('  ⇒ There is no missing generative law.  The confined case is EXHIBITED (a TT mode on a')
    print('    wave equation, the first dynamical bend, in vacuum); the branch-point crossing is')
    print('    WELL POSED with its worldline dynamics worked for a concrete matter model.')
    print('  ⇒ ** L-207 ⓵\'s deliverable is much smaller than the row supposed: not "find the curve\'s')
    print('     dynamics" but "record that the construction does not owe one." **  The row inherited')
    print('     "the deepest open question" from a SOURCE COMMENT; the published paragraph names the')
    print('     general case as ordinary GR and names the two worked instances.')
    print('  ⚠ Not claimed: that the dynamical programme is finished.  The general inhomogeneous case')
    print('    is called ordinary without being exhibited.  ** The open item is an EXHIBITION, not a')
    print('    DISCOVERY -- a different kind of debt. **')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
