"""
=== RETIRED r2350 --- CARRIES THE CONFORMAL-TIME SEEDING DEFECT (r2349) ===

This file builds its background as
    ag = np.logspace(-5, 0, ...)
    eg = np.concatenate([[0.], cumulative_trapezoid(c/(ag**2*Hub(ag)), ag)])
which SEEDS THE CONFORMAL TIME AT ZERO where a = 1e-5, omitting the 4.596 Mpc already
elapsed from a = 0.  (In radiation domination H ~ a^-2 makes c/(a^2 H) constant, so the
missing piece is a/(H0 sqrt(Omega_r)) = 4.635 Mpc; the exact integral is 4.59615.)

CONSEQUENCE: eta is short by 4.596 Mpc at every epoch.  That is 0.03% of eta_0 but 12% at
z = 1e4, so LATE-TIME results here (l_A, peak positions, P1/P2) are unaffected while any
EARLY-TIME quantity or any comparison against another code is distorted.  This is what
produced the "4.4% T(k) deficit" that was chased as physics from r2197 to r2348.

NOT RETROACTIVELY CORRECTED, deliberately: this file is stored as it was built and used, so
the record of what was run stays honest.  The defect is recorded here instead.  The two
CITED files carrying it (C11TEST_radiation_zeroed, ROBUST_p1p2_scan) and the live instrument
(HIER_photon_hierarchy) WERE fixed at r2349-r2350.
=========================================================================================
"""
"""TC8 — Psi EVOLVED FROM ITS OWN EQUATION, NOT IMPOSED.  Control first.
r1966 named the fault: my Psi(k,eta) was C1's radiation-era law with an IMPOSED freeze, and the
driving phase shift is generated by Psi's time-dependence THROUGH the transition.  So evolve it:
    Psi'' + 3H(1+c_s^2) Psi' + [2H' + (1+3c_s^2)H^2] Psi + c_s^2 k^2 Psi = 0
with c_s^2 the TOTAL mixture sound speed, c_s^2 = (4 rho_r/3)/(4 rho_r + 3 rho_m).
  radiation limit: c_s^2=1/3, H=1/eta  ->  Psi''+(4/eta)Psi'+(k^2/3)Psi=0   [C1's equation]
  matter limit:    c_s^2=0,   H=2/eta  ->  Psi''+(6/eta)Psi'=0  ->  Psi=const [C11's result]
*** SO THE SAME EQUATION REPRODUCES BOTH C1 AND C11 AS LIMITS, AND INTERPOLATES DYNAMICALLY. ***"""
import numpy as np
from scipy.integrate import solve_ivp, quad, cumulative_trapezoid
from scipy.interpolate import CubicSpline
from scipy.signal import argrelextrema
c=299792.458
H0=67.4; Om=0.307; z_eq=3403.6; Or=Om/(1+z_eq); OL=1-Om
ombh2=0.0224; z_rec=1089.9; a_rec=1/(1+z_rec); a_eq=1/(1+z_eq)
Rb_rec=31500*ombh2/(2.7255/2.7)**4/(1+z_rec)
Hub=lambda a: H0*np.sqrt(Or/a**4+Om/a**3+OL)
ag=np.logspace(-8, np.log10(a_rec), 12000)
eg=np.concatenate([[0.],cumulative_trapezoid(c/(ag**2*Hub(ag)),ag)])
eta_rec=eg[-1]
a_s=CubicSpline(eg,ag)
Rbs=CubicSpline(eg, Rb_rec*(ag/a_rec))
# conformal Hubble H = a'/a = a H /c  (in 1/Mpc)
Hc_g=ag*Hub(ag)/c
Hcs=CubicSpline(eg,Hc_g)
cs2_g=(4*Or/ag**4/3)/(4*Or/ag**4+3*Om/ag**3)
cs2s=CubicSpline(eg,cs2_g)
DM=quad(lambda a: c/(a**2*Hub(a)), a_rec, 1.0, limit=250)[0]
rs=quad(lambda a: c/(a**2*Hub(a)*np.sqrt(3*(1+Rb_rec*a/a_rec))), 1e-9, a_rec, limit=250)[0]
lstar=np.pi*DM/rs
print("="*80); print("TC8 — Psi EVOLVED, CONTROL"); print("="*80)
print(f"\n  eta_rec={eta_rec:.2f}  r_s={rs:.2f}  D_M={DM:.0f}  l_*={lstar:.1f}")
print(f"  c_s^2 check: deep radiation {cs2s(eg[5]):.5f} (want 1/3)   at recombination {cs2s(eta_rec):.5f} (want ~0)")
def solve_psi(k, eta_i):
    def rhs(e,y):
        Hc=Hcs(e); Hcp=Hcs(e,1); cs2=cs2s(e)
        return [y[1], -3*Hc*(1+cs2)*y[1] - (2*Hcp+(1+3*cs2)*Hc**2)*y[0] - cs2*k**2*y[0]]
    s=solve_ivp(rhs,[eta_i,eta_rec],[1.0,0.0],method='RK45',rtol=1e-7,atol=1e-12,dense_output=True)
    return s
def mode(k, eps=0.01):
    eta_i=eps/k
    sp=solve_psi(k,eta_i)
    egr=np.linspace(eta_i,eta_rec,3000)
    Ps=CubicSpline(egr, sp.sol(egr)[0])
    def rhs(e,y):
        Rb=Rbs(e); Rbp=Rbs(e,1); cs2p=1/(3*(1+Rb))
        return [y[1], -(Rbp/(1+Rb))*y[1] - k**2*cs2p*y[0] - (k**2/3)*Ps(e) - Ps(e,2) - (Rbp/(1+Rb))*Ps(e,1)]
    s=solve_ivp(rhs,[eta_i,eta_rec],[-Ps(eta_i)/2,0.0],method='RK45',rtol=1e-7,atol=1e-12,dense_output=True)
    return s.sol(eta_rec)[0]+Ps(eta_rec), Ps(eta_rec)
print(f"\n  Psi evolved: check the radiation->matter decay for a super-horizon mode")
v,P=mode(1e-4); print(f"    k=1e-4 (super-horizon throughout): Psi(rec)/Psi_i = {P:.4f}  (want ~0.90)")
ls=np.arange(120,1300,10.0)
out=np.array([mode(l/DM)[0] for l in ls])
rD=DM/1362.
Dl=(out*np.exp(-((ls/DM)*rD)**2))**2*ls**(0.965-1)
idx=[i for i in argrelextrema(Dl,np.greater,order=2)[0]]
print(f"\n  {'peak':>5s} {'l found':>9s} {'l measured':>11s}")
meas=[220,536,813,1126]
for n,i in enumerate(idx[:4]): print(f"  {n+1:>5d} {ls[i]:>9.0f} {meas[n] if n<4 else '-':>11}")
if len(idx)>=3:
    h=[Dl[i] for i in idx[:3]]
    print(f"\n  P1/P2 = {h[0]/h[1]:7.3f}   measured 2.212")
    print(f"  P1/P3 = {h[0]/h[2]:7.3f}   measured 2.257")
