import numpy as np, itertools
np.set_printoptions(suppress=True, linewidth=140, precision=6)

print("="*80)
print("c20fork TURN 2 — classify the discrete symmetry of the SdS solution space")
print("(P3 sec:groupoid-symmetry Prop:morphism-generation DEFERS this classification).")
print("Gauge alpha=1.  Horizon cubic r^3 - r + 2M = 0, 2M = r0 - r0^3, roots sum to 0.")
print("="*80)

def roots_of(twoM):
    # r^3 + 0*r^2 - 1*r + 2M = 0
    return np.sort_complex(np.roots([1.0, 0.0, -1.0, twoM]))
def twoM_of(r0):
    return r0 - r0**3

# ---------------------------------------------------------------------------
# (1) WITHIN ONE GEOMETRY: the three roots all carry the SAME 2M (P3 readingswap),
#     so designating any of the three as the slicing parameter r0 gives the SAME
#     geometry.  The symmetry is the PERMUTATION group of the three roots = S_3.
print("\n[1] WITHIN-GEOMETRY symmetry = permutations of the 3 horizon roots (fix 2M).")
ok_sum0 = True; ok_sameM = True
for twoM in [0.0, 0.1, 0.2, 0.3, 0.35]:
    rts = roots_of(twoM).real
    s = rts.sum()
    Ms = [twoM_of(r) for r in rts]            # 2M recovered from each root as parameter
    ok_sum0 &= abs(s) < 1e-9
    ok_sameM &= all(abs(M - twoM) < 1e-9 for M in Ms)
    print(f"   2M={twoM:+.3f}: roots={rts}  sum={s:+.2e}  2M(each root)={np.round(Ms,4)}")
print(f"   roots sum to 0 (A2 traceless/Cartan) ? {ok_sum0}")
print(f"   every root gives the same 2M (=> S_3 relabeling FIXES the geometry) ? {ok_sameM}")
print("   => within-one-geometry discrete group = Sym(3 roots) = S_3 = Weyl(A_2), order 6.")
print("      (sky angles w, pi/3-w, -pi/3-w: sigma=w<->pi/3-w swaps two; +2pi/3 shift cycles)")

# verify the three sky-angle preimages carry one 2M, and sigma fixes it
print("\n   sky-angle check: 2M = (2/(3*sqrt3)) sin(3w); the 3 preimages of 3w:")
w = 0.21
preimg = [w, np.pi/3 - w, -np.pi/3 - w]
vals = [(2/(3*np.sqrt(3)))*np.sin(3*x) for x in preimg]
print(f"   w={w}: preimages={np.round(preimg,4)}  2M(each)={np.round(vals,6)}  equal={np.allclose(vals,vals[0])}")

# ---------------------------------------------------------------------------
# (2) THE MASS-REFLECTION mu : 2M -> -2M  (P3 sec:ellipse anti-diagonal (r0,r)->(-r0,-r)).
#     roots -> -roots; it maps to the NEGATIVE-MASS geometry (a DISTINCT geometry),
#     so mu is NOT within-geometry; it acts on the SOLUTION SPACE.
print("\n[2] MASS-REFLECTION mu: 2M -> -2M  (negative mass; the backward-radial / anti-diagonal).")
twoM = 0.2
rts = np.sort(roots_of(twoM).real); rts_neg = np.sort(roots_of(-twoM).real)
print(f"   roots(+2M)={rts}   -roots(+2M)={np.sort(-rts)}   roots(-2M)={rts_neg}")
print(f"   mu sends roots -> -roots and 2M -> -2M (distinct geometry) ? {np.allclose(np.sort(-rts), rts_neg)}")

# ---------------------------------------------------------------------------
# (3) GROUP GENERATED by S_3 (root perms) and mu (global negation), acting on the
#     6-element set {+/-r1,+/-r2,+/-r3} = the 6 roots of the A_2 root system.
print("\n[3] <S_3, mu> acting on the 6-element set {+-r1,+-r2,+-r3} (the A_2 roots):")
labels = [0,1,2,3,4,5]   # 0,1,2 = r1,r2,r3 ; 3,4,5 = -r1,-r2,-r3
def neg(i): return (i+3)%6
# S_3 = permutations of {0,1,2} acting compatibly on {3,4,5}; mu = i -> neg(i)
gens = []
for p in itertools.permutations([0,1,2]):
    perm = list(p) + [neg(p[0])%6 if False else None]*0
    g = [0]*6
    for k in range(3):
        g[k] = p[k]; g[k+3] = (p[k]+3)
    gens.append(tuple(g))
mu = tuple(neg(i) for i in range(6))
def compose(a,b): return tuple(a[b[i]] for i in range(6))
# close the set generated by all S3 perms + mu
group = set(gens); group.add(mu); group.add(tuple(range(6)))
changed = True
while changed:
    changed = False
    for a in list(group):
        for b in list(group):
            c = compose(a,b)
            if c not in group:
                group.add(c); changed = True
S3only = set(gens); 
# close S3only (already a group of 6)
print(f"   |S_3| (within-geometry, root perms)          = {len(S3only)}   (expect 6 = Weyl(A_2))")
print(f"   |<S_3, mu>| (with mass-reflection)            = {len(group)}   (expect 12)")
print("   => the discrete SOLUTION-SPACE symmetry is order 12 = S_3 x Z_2 = D_6")
print("      = Aut(A_2 root system): Weyl(A_2)=S_3 (within-geometry horizon-designations)")
print("        extended by the diagram automorphism Z_2 = the mass-reflection 2M->-2M.")

# A_2 quadratic form (P3 Prop:locus): r^2 + r r0 + r0^2, matrix [[1,1/2],[1/2,1]]
A2 = np.array([[1,0.5],[0.5,1]]); ev = np.linalg.eigvalsh(A2)
print(f"\n   A_2 form eigenvalues (P3 locus) = {ev}  (1/2, 3/2 — the A_2 Cartan ratios)")

print("\n"+"="*80)
print("VERDICT (c20fork turn 2): the deferred classification CLOSES, cleanly.")
print(" - Within one geometry: the discrete description group is exactly Weyl(A_2)=S_3")
print("   (the 3 horizon-roots' permutations, all carrying one 2M).  [closes P3 Prop:")
print("    morphism-generation: sigma + sky-angle periodicity generate it IN FULL = S_3]")
print(" - On the solution space: adding the mass-reflection mu (2M->-2M, the anti-diagonal /")
print("   negative-mass / backward-radial direction) gives Aut(A_2)=S_3 x Z_2 (order 12),")
print("   the Weyl group extended by the A_2 DIAGRAM AUTOMORPHISM.  mu is exactly that Z_2.")
print(" - The regime connections are NOT in this finite group: BH<->cosmology (under<->over-")
print("   critical) and Riemannian<->Lorentzian (the seam) are the CONTINUOUS analytic")
print("   continuation sin->cosh (3w=pi/2+i*beta), i.e. Aut(A_2) acting on the COMPLEXIFIED")
print("   sky-angle, with the regimes as its real/imaginary sections (P3 already complexifies).")
print(" => SHARPENS c19's 'one S_3-orbit unifying BH/cosmology/negative-mass': the unification")
print("    is LAYERED — discrete Aut(A_2)=S_3xZ_2 (horizon-designations + mass-sign) carried")
print("    across regimes by the continuous continuation, not a single orbit.")
print(" OPEN (P3-deferred, next grind / candidate fork): the action between distinct de Sitter")
print("    representations (different alpha) — whether it extends the symmetry or is mere scaling.")
print("="*80)
