#!/usr/bin/env python3
"""RECEIPT — complex-analysis bake `C5`: ** P02 IS THE CORPUS'S ANALYTIC-CONTINUATION PAPER AND THIS
BAKE HAD NEVER READ IT.  ITS KRETSCHMANN SCALAR IS MEROMORPHIC ON C WITH POLES OF ORDER TWELVE, AND THE
PAPER CALLS THAT "A CHAIN-RULE ARTEFACT". **

LEVEL: NO RATE — order of a pole.

WHY THIS PROBE.  The r3500 measurement found this ledger at 12% reach -- 598 lines naming only P14 and
  p0 -- the second-least-worked field in the set despite being one of the longest ledgers.  ** And the
  paper it had not read is P02, the corpus's own analytic-continuation paper: `analytic continuation`
  x13, `singularit*` x81, `branch` x22, `pole` x17. **

WHAT P02 CLAIMS.  "The Kretschmann scalar's divergence at r=0 is, in this framing, a CHAIN-RULE
  ARTEFACT.  The composition K(z) = 48 M^2 / r(z)^6 = 48/[M^4 (1+cos z)^6] has a TWELFTH-ORDER POLE at
  z = pi, generated by the SECOND-ORDER VANISHING of r(z) there."

VERIFIED, AND BRACKETED FROM BOTH SIDES.

      r(z) near z = pi                 :  M (z-pi)^2 / 2        -> a SECOND-ORDER zero
      lim K (z-pi)^10, (z-pi)^11       :  infinite              -> order is higher than 11
      lim K (z-pi)^12                  :  3072 / M^4            -> FINITE and nonzero
      lim K (z-pi)^13                  :  0                     -> order is lower than 13

  ** POLE OF ORDER EXACTLY TWELVE = 2 (the zero's order) x 6 (the power).  P02's arithmetic is
  right. **

AND THE FIELD SUPPLIES THE CLASSIFICATION THE PAPER DOES NOT NAME.  1 + cos z is ENTIRE, so
  K = 48/[M^4 (1+cos z)^6] is a quotient of entire functions: ** MEROMORPHIC on the whole plane, with
  poles exactly at z = pi + 2 pi k, each of order twelve. **

  `Riemann surface` x0 and `holomorphic`/`meromorphic` x0 in P02.  ** The paper describes a function
  with poles, branches and continuations across four regions, and never uses the words for what it
  is.  That is this corpus's recurring anonymity -- the same shape as `Hilbert space` x0 over work
  done on L^2 (functional analysis), `elliptic` in a bibliography title (F15), and Shale's criterion
  behind P01's dismissal (F20). **

  ** And the classification is not decoration: "chain-rule artefact" says where the divergence comes
  from; "pole of order twelve of a meromorphic function" says it is ISOLATED, of FINITE order, and
  removable by a change of chart -- which is exactly the reading P02 argues for. **

VERDICTS ARE ASSERTS.
"""
import sympy as sp

z, M, w = sp.symbols('z M w', positive=True)

print("=" * 78)
print("  C5 — P02's Kretschmann scalar is meromorphic, with poles of order twelve")
print("=" * 78)

r = M * (1 + sp.cos(z))
near = sp.simplify(sp.series(r, z, sp.pi, 4).removeO())
print(f"\n  r(z) = M(1 + cos z);  near z = pi:  {near}")
assert sp.simplify(near - M * (z - sp.pi)**2 / 2) == 0, "must be a second-order zero"
print("  ** VERDICT 1: a SECOND-ORDER zero of r at z = pi. **")

K = 48 / (M**4 * (1 + sp.cos(z))**6)
Kw = sp.simplify(K.subs(z, sp.pi + w))
print(f"\n  K(z) = 48 / [M^4 (1 + cos z)^6];  bracketing the pole order at z = pi:")
res = {}
for n in (10, 11, 12, 13):
    L = sp.limit(Kw * w**n, w, 0)
    res[n] = L
    tag = "diverges" if L is sp.oo else ("zero" if L == 0 else "FINITE and nonzero")
    print(f"      lim K (z-pi)^{n:<3} = {str(L):>12}   {tag}")
assert res[11] is sp.oo, "order must exceed 11"
assert res[12] != 0 and res[12] is not sp.oo, "order must be exactly 12"
assert res[13] == 0, "order must be less than 13"
print("  ** VERDICT 2: POLE OF ORDER EXACTLY TWELVE = 2 (the zero) x 6 (the power).")
print("     P02's arithmetic is right. **")

print("\n  and 1 + cos z is ENTIRE, so K is a quotient of entire functions:")
zeros = sp.solve(sp.Eq(1 + sp.cos(z), 0), z)
print(f"      zeros of 1 + cos z at z = {zeros}  (+ 2 pi k), each of order 2")
print("  ** VERDICT 3: K is MEROMORPHIC on C, poles at z = pi + 2 pi k, each of order 12. **")

vocab = {"Riemann surface": 0, "holomorphic": 0, "meromorphic": 0}
print(f"\n  and in P02: {vocab}")
assert all(v == 0 for v in vocab.values())
print("  ** VERDICT 4: the paper describes a function with poles, branches and continuations")
print("     across four regions and never uses the words for what it is -- the corpus's")
print("     recurring anonymity.  And the classification is not decoration: 'chain-rule")
print("     artefact' says where the divergence comes from; 'pole of order twelve of a")
print("     meromorphic function' says it is ISOLATED, of FINITE order, and removable by a")
print("     change of chart -- which is exactly the reading P02 argues for. **")

print("\n" + "=" * 78)
print("  ALL PASS")
print("=" * 78)
