"""
ATTACKING prop:closure (i) -- the closure's OTHER load-bearing leg, and the one I
never verified. I took it from the glossary, exactly as I took (iii); (iii) turned
out to cite a receipt (`r_swap.py`) that does not exist.

THE CLAIM (i): R "carries the fundamental to the antifundamental, 3bar = R(3) --
the matter/antimatter skeleton", because R "is the A2 diagram automorphism".

The chain the corpus actually asserts, in three links:
   (a) R negates the horizon roots  (r -> -r on the roots)
   (b) therefore R is the A2 DIAGRAM AUTOMORPHISM (the outer Z2 of Aut(A2))
   (c) therefore R carries 3 -> 3bar

Each link can fail independently. (b) is the one nobody has shown: negation and the
diagram automorphism are different descriptions, and for a general root system they
are NOT the same map. Ask the algebra, not the prose.
"""
import numpy as np
import itertools

def pol(v): return np.hypot(*v), np.degrees(np.arctan2(v[1], v[0])) % 360

# --- A2, standard realisation ---
a1 = np.array([np.sqrt(2.0), 0.0])
a2 = np.array([-np.sqrt(2.0)/2, np.sqrt(6.0)/2])
simple = [a1, a2]
roots  = [a1, a2, a1+a2, -a1, -a2, -(a1+a2)]

print("="*80)
print("(a)  Does NEGATION preserve the A2 root system?")
print("="*80)
def in_set(v, S, tol=1e-9): return any(np.allclose(v, s, atol=tol) for s in S)
neg_ok = all(in_set(-r, roots) for r in roots)
print(f"  -root in the root system for every root?   {neg_ok}")
print("  (Trivially yes: A2's roots come in +/- pairs. So negation IS an automorphism")
print("   of the root SYSTEM. That much is free -- and it is NOT yet the claim.)")

print()
print("="*80)
print("(b)  THE LINK NOBODY SHOWED: is negation the DIAGRAM AUTOMORPHISM?")
print("="*80)
print("  The Weyl group W(A2) = S3, generated by the two simple reflections.")
# [N4] MY OWN BUG, logged not deleted (THE_CODA s"The negatives are the map"):
# the first pass enumerated only words of LENGTH EXACTLY 4 (itertools.product(...,
# repeat=4)), which misses the identity and every odd-length word, and returned |W|=3.
# A buggy receipt returning a TRUE conclusion is the worst kind: (c) verified, so the
# verdict read as sound while its demonstration was broken. Words of length 0..3 are
# what generate S3.
S = lambda a: np.eye(2) - 2*np.outer(a, a)/(a @ a)      # simple reflection matrix
W = []
for L in range(4):
    for word in itertools.product([0, 1], repeat=L):
        M = np.eye(2)
        for i in word: M = S(simple[i]) @ M
        if not any(np.allclose(M, X) for X in W): W.append(M)
print(f"  |W| generated = {len(W)}   (S3 has order 6)   {'OK' if len(W)==6 else 'CHECK'}")

minus_I = -np.eye(2)
in_W = any(np.allclose(minus_I, X) for X in W)
print(f"  Is -1 (negation) IN the Weyl group?   {in_W}")
print("  -> For A2, -1 is NOT in W. (It is for A1, B2, G2 ... but NOT A2.)")
print("     So negation is an OUTER automorphism -- it lies in Aut(A2) \\ W.")
print()
print(f"  |Aut(A2)| = |W| x |outer| = 6 x 2 = 12 = D6.  The outer factor has ORDER 2,")
print("  so Aut(A2)/W has exactly ONE non-trivial coset -- and BOTH negation and the")
print("  diagram automorphism lie in it (neither is in W).")
print("  ** THEREFORE negation and the diagram automorphism differ by an element of W,")
print("     and generate the SAME outer Z2. The corpus's identification is SOUND. **")
print()
print("  Explicitly: the diagram automorphism swaps a1 <-> a2. Compose it with the")
print("  longest Weyl element w0 and you get -1:")
# [N5] second bug, same run: D was built as A^-1 (A P) = P -- the PERMUTATION in the
# root BASIS, not the linear map on the plane. The map wanted is D A = A P, i.e.
# D = A P A^-1 with A the matrix whose COLUMNS are a1, a2.
A = np.column_stack([a1, a2]); P = np.array([[0.0, 1.0], [1.0, 0.0]])
D = A @ P @ np.linalg.inv(A)                                       # a1->a2, a2->a1
print(f"     diagram automorphism D:   a1 -> {np.round(D@a1,4)}  (= a2? {np.allclose(D@a1, a2)})")
print(f"                               a2 -> {np.round(D@a2,4)}  (= a1? {np.allclose(D@a2, a1)})")
w0 = next((X for X in W if np.allclose(X @ D, minus_I)), None)
print(f"     is there a Weyl element w with w.D = -1 ?   {w0 is not None}")
if w0 is not None:
    print(f"     -> NEGATION = w o D  with w in W. Negation and the diagram automorphism")
    print(f"        differ by a WEYL element, so they generate the SAME outer Z2. CONFIRMED.")
    print(f"        (w is the longest element w0; det w = {np.linalg.det(w0):+.1f}, det D = {np.linalg.det(D):+.1f})")

print()
print("="*80)
print("(c)  Does the outer Z2 carry 3 -> 3bar? Compute on the WEIGHTS.")
print("="*80)
w1 = np.linalg.solve(np.array([a1,a2]) @ np.array([a1,a2]).T, np.array([1.0,0.0]))
w1 = np.array([a1,a2]).T @ w1
three    = [w1, w1 - a1, w1 - a1 - a2]
threebar = [-w for w in three]
print("  weights of 3   :", [f"{pol(w)[1]:6.1f} deg" for w in three])
print("  weights of 3bar:", [f"{pol(w)[1]:6.1f} deg" for w in threebar])
img = [-w for w in three]                      # apply negation
match = all(any(np.allclose(i, b) for b in threebar) for i in img)
print(f"  negation applied to the 3's weights lands on the 3bar's weight set?  {match}")
print("  -> the outer Z2 exchanges the 3 and the 3bar.   ** (c) CONFIRMED **")

# r2376+c54.158 -- pins the three links this receipt tests, at the figures it prints.
#   (a) A2 has 6 roots and negation carries every one of them to a root.
#   (b) THE LOAD-BEARING LINK, and the one the [N4] bug got wrong: the two simple reflections
#       generate a group of order 6 -- W(A2) = S3.  The bug returned |W| = 3, i.e. a receipt that
#       printed a TRUE verdict on a broken demonstration, so 6 is pinned here and not just shown.
#       And -1 is NOT among those 6.  THAT is the A2-specific warrant the corpus is owed a clause
#       for (NOTES_owed_clause.md): were -1 Weyl, negation would be INNER and would NOT conjugate
#       the representation.  The witness is explicit: the diagram automorphism D swaps a1 <-> a2
#       with det D = -1, and a Weyl element w0 (det -1) exists with w0 . D = -1, so negation and D
#       differ by a Weyl element and generate the same outer Z2.
#   (c) negation carries the 3's weights, at 30/150/270 degrees, onto the 3bar's weight set at
#       210/330/90 -- each rotated by exactly 180 degrees, which is the 3 -> 3bar exchange.
assert len(roots) == 6 and neg_ok
assert len(W) == 6, len(W)
assert not in_W, "-1 IS in W(A2) -- the A2-specific warrant would be gone"
assert w0 is not None and np.allclose(w0 @ D, minus_I)
assert np.allclose(D @ a1, a2) and np.allclose(D @ a2, a1)
assert abs(np.linalg.det(D) + 1) < 1e-9 and abs(np.linalg.det(w0) + 1) < 1e-9
assert sorted(round(pol(w)[1]) for w in three) == [30, 150, 270]
assert sorted(round(pol(w)[1]) for w in threebar) == [90, 210, 330]
assert match

print()
print("="*80)
print("VERDICT on prop:closure (i)")
print("="*80)
print("  ** (i) STANDS, and it did NOT have to. **")
print("  The link that could have failed -- and that no receipt in the bundle checks --")
print("  is (b): 'R negates the roots, THEREFORE R is the diagram automorphism.'")
print("  Negation and the diagram automorphism are DIFFERENT MAPS. They coincide as an")
print("  outer class here only because of a fact special to A2: **-1 is not in W(A2)**,")
print("  and Aut(A2)/W has order 2, so the two non-Weyl candidates cannot help but")
print("  generate the same Z2. Explicitly, negation = w0 o D.")
print()
print("  >> HAD -1 BEEN IN THE WEYL GROUP, THE INFERENCE WOULD BE FALSE: negation would")
print("     be INNER, would NOT be the diagram automorphism, and would NOT conjugate the")
print("     representation. That is the case for A1, B2, G2, and every rank-2 system")
print("     EXCEPT A2. The corpus's step is sound for a reason that is specific to A2 and")
print("     is nowhere stated -- it reads as though 'negates the roots' means 'conjugates")
print("     the rep' generally, and it does not.")
print()
print("  >> SO: the leg holds, the closure is unmoved, and the corpus is owed one clause:")
print("     the identification is A2-specific, and its warrant is that -1 is not Weyl.")
