#!/usr/bin/env python3
"""
negation_outer_A2.py -- the A2-specific warrant for "R negates the roots => R conjugates
the representation 3 <-> 3bar".

The step is NOT general.  R acts on the horizon-cubic roots as r -> -r (negation, -1 on the
root plane).  That negation induces the diagram automorphism (hence conjugates the rep) ONLY
because -1 is not in the Weyl group of A2.  For the other rank-two systems -1 IS Weyl, so
negation there is inner and fixes each representation.  This receipt verifies both facts.

Backs: groupoid_paper.tex rem:orientation (P5); the first leg of the matter/antimatter
closure (P13, P7) that R carries 3 <-> 3bar.
"""
import numpy as np, itertools

def weyl_group(simple):
    """All distinct 2x2 matrices in the Weyl group generated by the simple reflections."""
    def refl(v, a):
        return v - 2 * np.dot(v, a) / np.dot(a, a) * a
    gens = [(lambda v, a=a: refl(v, a)) for a in simple]
    mats = set()
    for L in range(0, 9):                      # words up to length 8 saturate rank-2 groups
        for w in itertools.product(gens, repeat=L):
            cols = []
            for e in np.eye(2):
                v = e.copy()
                for g in w:
                    v = g(v)
                cols.append(v)
            mats.add(tuple(np.round(np.array(cols).T.flatten(), 4)))
    return mats

systems = {
    "A2":       [np.array([1.0, 0.0]), np.array([-0.5, np.sqrt(3) / 2])],
    "A1xA1":    [np.array([1.0, 0.0]), np.array([0.0, 1.0])],
    "B2":       [np.array([1.0, 0.0]), np.array([-1.0, 1.0])],
    "G2":       [np.array([1.0, 0.0]), np.array([-1.5, np.sqrt(3) / 2])],
}
negI = tuple(np.round((-np.eye(2)).flatten(), 4))

allok = True
print("system   |W|   -1 in W?   negation is")
print("-" * 48)
for name, simple in systems.items():
    W = weyl_group(simple)
    has = negI in W
    kind = "INNER (fixes each rep)" if has else "OUTER (conjugates rep)"
    print(f"{name:8s} {len(W):3d}    {str(has):5s}      {kind}")
    # r2376+c54.158 -- pins the table this receipt PRINTS, which is its whole claim: the Weyl
    # orders of the four rank-two systems are |W(A2)|=6, |W(A1xA1)|=4, |W(B2)|=8, |W(G2)|=12,
    # and -1 lies in W for the three CONTROLS but NOT for A2.  Were -1 Weyl for A2 the negation
    # r -> -r would be INNER and would not conjugate 3 <-> 3bar (P5 rem:orientation).
    assert len(W) == {"A2": 6, "A1xA1": 4, "B2": 8, "G2": 12}[name], (name, len(W))
    assert has == (name != "A2"), (name, has)
    if name == "A2":
        allok &= (not has)                     # A2: -1 must be OUTER
    else:
        allok &= has                           # others: -1 must be INNER

print("-" * 48)
print("A2-specific warrant:", "HOLDS" if allok else "FAILS",
      "-- only for A2 is -1 outside W, so only there does mass-negation conjugate 3<->3bar.")
print("ALL CHECKS PASS" if allok else "SOME CHECKS FAILED")
# r2376+c54.158 -- rule 7: the receipt already computes the warrant's PASS/FAIL and only PRINTS it.
assert allok
