"""
WALKING III.3 -- "one 1:2, wearing three costumes". The second branch I filed instead
of walking, in the same document as the 30, an hour apart. Daryl names this one
repeatedly -- "the asymmetry -- Nariai, 1/3 vs 2/3 -- the asymmetry IS the
symmetry-breaking, not a footnote to it" -- so it is the last thing that should sit
under "checkable, unchecked".

THE THREE 1:2s (my harvest, III.3):
  (1) the lift bound |Im tau~| = pi a/3  vs  the full imaginary period 2 pi a/3
  (2) the lap's arc split, 120 : 240
  (3) turnaround / seam = cbrt(2)   ("the ratio of their cubes is exactly 2", r1064)

I wrote: "Three 1:2's ... whether they are one fact is checkable and unchecked."
Walk it. It can return one, two, or three.
"""
import numpy as np, sympy as sp

r, a, M, rho = sp.symbols('r alpha M rho', positive=True)
print("="*78)
print("(1)  The lift's 1:2  --  where does it come from?")
print("="*78)
print("  Turnaround: 1-f = 0 => r^3 = -2M a^2 => r = -A,  A = (2M a^2)^(1/3).")
print("  In the law r^3 = 2M a^2 sinh^2(3 tau~/2a), that is sinh^2 = -1.")
print("  On the imaginary axis sinh(i th) = i sin th, so sinh^2(i th) = -sin^2(th):")
for th in (0, np.pi/4, np.pi/2, 3*np.pi/4, np.pi):
    print(f"     th = {th:.4f} = {th/np.pi:.2f} pi   sinh^2(i th) = {np.sinh(1j*th)**2:.4f}")
print("  -> sinh^2 runs 0 -> -1 -> 0 over th: 0 -> pi/2 -> pi. PERIOD pi; MINIMUM at pi/2.")
print("  So the turnaround sits at HALF the period, and the 1:2 IS:")
print("       ** sin^2 attains its extremum at HALF of its own period. **")
print("  (Equivalently: sin peaks a QUARTER of the way through ITS period 2pi; squaring")
print("   halves the period and relabels the quarter as a half. Same trigonometric fact.)")
print("  Converting: 3 tau~/2a = i pi/2 -> tau~ = i pi a/3 = the bound. Period: iπ -> 2 pi a/3.")
print("  >> (1)'s 2 is a fact about SINH. No cubic in sight.")

print()
print("="*78)
print("(2) and (3)  --  the depressed cubic with a double root does BOTH")
print("="*78)
print("  Any monic depressed cubic with a double root rho factors ONE way:")
expr = sp.expand((r - rho)**2 * (r + 2*rho))
print(f"     (r - rho)^2 (r + 2 rho)  =  {expr}")
print("  so  p = -3 rho^2  and  q = +2 rho^3, and the third root is -2 rho.")
print("  ** The -2 of the third root and the 2 of the constant term are THE SAME 2. **")
print("     Both are read off the single factorisation. Not two facts.")
print()
print("  Our horizon cubic is r^3 - a^2 r + 2 M a^2 = 0, so p = -a^2, q = 2 M a^2:")
print("     p:  -a^2 = -3 rho^2   =>   a^2 = 3 rho^2   =>   rho = a/sqrt3     [the seam]")
print("     q:  2 M a^2 = 2 rho^3 =>   M a^2 = rho^3                          [= NARIAI]")
sol_rho = sp.sqrt(a**2/3)
print(f"     check rho = {sp.simplify(sol_rho)}  -> a/sqrt(3) : {sp.simplify(sol_rho - a/sp.sqrt(3))==0}")
print()
print("  NOW (3):  A^3 = 2 M a^2  =  q  =  2 rho^3.   So   A = cbrt(2) . rho.")
print("     ** The turnaround's amplitude A is the CUBE ROOT OF THE CUBIC'S CONSTANT TERM,")
print("        and that constant term is 2 rho^3 BY THE DOUBLE ROOT'S OWN ALGEBRA. **")
print("  AND (2):  the third (backward) root is -2 rho = -2a/sqrt3.")
print("     The lap's flattened reading is X1 = -a cos(2 pi r / sqrt3 a) -- LINEAR in r --")
th_seam = 2*np.pi*(1/np.sqrt(3))/(np.sqrt(3))
th_back = 2*np.pi*(-2/np.sqrt(3))/(np.sqrt(3))
print(f"        r = +a/sqrt3  -> angle {np.degrees(th_seam):7.2f} deg")
print(f"        r = -2a/sqrt3 -> angle {np.degrees(th_back):7.2f} deg")
print(f"        ratio {abs(th_back/th_seam):.4f}  = 2  -- the arc ratio IS the root ratio,")
print("        because the map r -> angle is linear.")
print()
print("  >> (2) AND (3) ARE ONE 2: the algebra of (r-rho)^2 (r+2rho).")
print("     The backward root at -2rho, the constant term at 2rho^3, hence the amplitude")
print("     at cbrt(2) rho, hence the 120:240 arc. ONE factorisation, four faces.")

print()
print("="*78)
print("(4)  Numbers, at Nariai, to make sure this is not a story")
print("="*78)
al = 1.0
rho_n = al/np.sqrt(3); M_n = rho_n**3/al**2; t_n = -2*rho_n; A_n = (2*M_n*al**2)**(1/3)
print(f"  rho (double root / seam) = {rho_n:.6f}   = a/sqrt3      {np.isclose(rho_n, al/np.sqrt(3))}")
print(f"  M                        = {M_n:.6f}   = a/(3sqrt3)   {np.isclose(M_n, al/(3*np.sqrt(3)))}")
print(f"  third root               = {t_n:.6f}   = -2a/sqrt3    {np.isclose(t_n, -2*al/np.sqrt(3))}")
print(f"  A (turnaround amplitude) = {A_n:.6f}   = cbrt2 . a/sqrt3  {np.isclose(A_n, 2**(1/3)*al/np.sqrt(3))}")
print(f"  A / rho                  = {A_n/rho_n:.6f}   = cbrt(2)   {np.isclose(A_n/rho_n, 2**(1/3))}")
print(f"  (A/rho)^3                = {(A_n/rho_n)**3:.6f}   = 2")
print(f"  |third| / rho            = {abs(t_n)/rho_n:.6f}   = 2")
print("  roots of r^3 - a^2 r + 2M a^2:", np.sort_complex(np.roots([1,0,-al**2, 2*M_n*al**2])).round(6))
print("  -> double root at +0.5774 (twice) and -1.1547 = -2 x 0.5774. Sum = 0. Confirmed.")

print()
print("="*78)
print("VERDICT -- and it is not what I filed")
print("="*78)
print("  I filed: 'One 1:2, wearing three costumes ... worth checking whether they are")
print("  one fact; the thread names all three and never asks.' WALKED:")
print()
print("  ** IT IS TWO 2s, NOT ONE AND NOT THREE. **")
print()
print("   * (2) and (3) MERGE, and the merge is exact and forced: a monic depressed")
print("     cubic with a double root factors as (r-rho)^2(r+2rho), which hands you the")
print("     third root -2rho AND the constant term 2rho^3 in one stroke. The bead's")
print("     amplitude A is the cube root of that constant term, so A = cbrt(2) rho; the")
print("     lap's arc map is linear in r, so 120:240 is the root ratio. FOUR of the")
print("     corpus's numbers -- the seam a/sqrt3, the backward root -2a/sqrt3, the")
print("     turnaround cbrt2 a/sqrt3, and the 120/240 split -- are ONE factorisation.")
print("     And 'M a^2 = rho^3' falling out of q = 2rho^3 IS the Nariai condition:")
print("     Nariai is not an extra input here, it is what the double root MEANS.")
print()
print("   * (1) DOES NOT MERGE. Its 2 is 'sin^2 attains its extremum at half its own")
print("     period' -- a fact about the transcendental function the cosmic-time reading")
print("     uses, with no cubic in it. And the corpus ALREADY separates these: the")
print("     turnaround is 1-f=0 and the horizons are f=0, two affinely inequivalent")
print("     cubics; no AFFINE change of variable identifies their root sets (P7, lem:twoturnings),")
print("     the two being the E=1 and E=0 ends of one turning-point family (rem:tworealisations).")
print()
print("  >> SO: Daryl's 'Nariai, 1/3 vs 2/3' -- the 120:240 arc -- is the DOUBLE ROOT'S")
print("     2, and it is forced, and it is the same 2 as the cbrt(2). That asymmetry is")
print("     real structure and it is exactly where he keeps pointing.")
print("     The lift's 1:2 is a look-alike from sinh, and lem:twoturnings already says")
print("     why it need not be the same.")
print()
print("  >> AND THE ONE THING (3) DOES THAT lem:twoturnings DOES NOT COVER: A = cbrt(2) rho")
print("     is a METRIC relation BETWEEN the two turnings -- it ties the comoving")
print("     turnaround's scale to a horizon root. lem:twoturnings denies a canonical")
print("     identification of the two Z3 SYMMETRIES; it says nothing against a ratio")
print("     between two specific radii. Whether that bridge means anything is NAMED and")
print("     UNRUN -- not 'no mechanism on the table'.")
