"""
THE ISOMETRY (r1108) — Daryl's conjecture, computed. He is explicit that it is a
conjecture and not proven:

  "That 4 has to map isometrically to the other 4: FOUR HINGE TRANSPOSES AROUND THE
   CIRCLE relates in some way to TURNING THE DIAL AROUND IN PI/2 SEGMENTS and all the
   symmetries that collapse equivalent descriptions."

TWO FOURS:
  (A) the KALEIDOSCOPE's four -- stamp the whole figure at azimuth 0/90/180/270.
      3 hinges x 4 stamps = 12 hinges at 30-degree spacing.
  (B) the DIAL's four -- the ray from the hinge, all 360, in four pi/2 segments.

FIRST, THE OBSTRUCTION THAT COULD KILL IT OUTRIGHT, tested before anything else:
  a group of order 4 is either Z4 (cyclic) or Z2xZ2 (Klein). THEY ARE NOT ISOMORPHIC.
  If (A) is cyclic and (B) is Klein, ** no isometry can identify them ** and the
  conjecture is dead on group theory, with no geometry needed.
"""
import numpy as np
import itertools

a = 1.0

print("="*80)
print("(0)  THE OBSTRUCTION FIRST — could the two fours even be the same group?")
print("="*80)
print("  (A) the stamp: rotation by 90 in azimuth. R^4 = identity, R^2 != identity.")
print("      -> generated by ONE element of order 4  ->  ** Z4, CYCLIC **")
print()
print("  (B) the dial: I called it {toward,away} x {mirror} in dial_360.py -- which is")
print("      KLEIN, and if that is the right reading of (B), THE CONJECTURE IS DEAD HERE.")
print("      But that was a description of how the four quadrants RELATE, not of a group")
print("      ACTING on the dial. Ask instead: what acts on the dial in pi/2 segments?")
print("      -> psi -> psi + 90. Four turns return. ** Z4, CYCLIC. **")
print()
print("  >> ** THE OBSTRUCTION DOES NOT BITE, AND I NEARLY MANUFACTURED IT. ** {toward,away}")
print("     x {mirror} is Klein and is a true statement about the quadrants' EQUIVALENCES.")
print("     The GROUP TURNING the dial is Z4. Two different objects; I had conflated them,")
print("     and the conflation would have killed a live conjecture on a false obstruction.")

print()
print("="*80)
print("(1)  THE SETUP — what a slicing actually depends on")
print("="*80)
print("  A hinge at azimuth chi sits at  H(chi) = 2a (cos chi, sin chi).")
print("  A vertical slicing plane's overhead trace is a LINE. Parametrise it by its normal:")
print("       line(d, theta) = { x : x . (cos theta, sin theta) = d }")
print("  The line passes through H(chi) iff  d = 2a cos(theta - chi).")
print()
def d_of(chi_deg, theta_deg):
    return 2*a*np.cos(np.radians(theta_deg - chi_deg))
for chi, th in [(0,0),(0,60),(0,90),(90,90),(90,150),(30,30)]:
    print(f"    chi={chi:>3}  theta={th:>3}  ->  d = {d_of(chi,th):+.6f} = 2a cos(theta-chi)")
print()
print("  ** AND THE PHYSICS DEPENDS ON d ALONE: ** d > a overcritical (misses the throat),")
print("     d = a NARIAI (tangent -> the cut degenerates to the two null rulings), d < a")
print("     undercritical (cuts). Nothing else about the plane enters.")
print("  ** SO THE PHYSICS DEPENDS ONLY ON (theta - chi). THE HINGE'S AZIMUTH AND THE DIAL")
print("     ARE NOT TWO COORDINATES. THEY ARE ONE. **")

print()
print("="*80)
print("(2)  THE ISOMETRY — is transposing the hinge the same as turning the dial?")
print("="*80)
print("  If d = 2a cos(theta - chi), then MOVING THE HINGE by +delta with the plane held")
print("  fixed gives the same d as TURNING THE PLANE by -delta with the hinge held fixed.")
print("  Test it on the physics, not the formula:")
print()
print(f"  {'delta':>6} {'d(chi+delta, theta)':>21} {'d(chi, theta-delta)':>21}  identical?")
ok = True
rng = np.random.default_rng(1)
for delta in (90, 180, 270, 37.5):
    chi, th = 12.0, 71.0
    d1, d2 = d_of(chi+delta, th), d_of(chi, th-delta)
    ok &= np.isclose(d1, d2)
    print(f"  {delta:>6} {d1:>21.9f} {d2:>21.9f}  {np.isclose(d1,d2)}")
for _ in range(300):
    chi, th, delta = rng.uniform(0,360,3)
    ok &= np.isclose(d_of(chi+delta, th), d_of(chi, th-delta))
print(f"\n  + 300 random (chi, theta, delta): all identical?  {ok}")
print()
print("  >> ** YES. A HINGE TRANSPOSE **IS** A DIAL TURN, in the opposite sense. **")
print("     And the map realising it is the AZIMUTHAL ROTATION of the (X1,X2) plane, which")
print("     IS an isometry of the substrate -X0^2 + X1^2 + X2^2 = a^2 -- it preserves the")
print("     form exactly (it is SO(2) acting on the spatial block, inside SO(5,1)).")
print("  ** DARYL'S ISOMETRY EXISTS. It is not exotic: it is the rotation, read from the")
print("     two ends of one relative angle. **")

print()
print("="*80)
print("(3)  BUT WHY FOUR? The isometry works for ANY delta. What picks pi/2?")
print("="*80)
print("  This is the real question, and (2) does not answer it. A rotation by 37.5 works")
print("  just as well. So what makes the dial's quadrants QUADRANTS?")
print()
print("  The dial has exactly two distinguished directions, and neither is a choice:")
print("     * THE AXIS (psi = 0 / 180): the hinge-to-hole line. toward vs away.")
print("     * ITS PERPENDICULAR (psi = 90 / 270): the VERTICAL slicing -- the one whose")
print("       closest approach is maximal (d = 2a), whose vertex IS THE HINGE, and which")
print("       the script calls 'THE END OF THE DIAL'.")
for psi in (0, 90, 180, 270):
    th = psi          # normal angle for a line through the hinge at azimuth 0
    print(f"     psi={psi:>3}: d = {abs(d_of(0, psi)):.6f} a" +
          ("   <- AXIS: through the hole's centre (d=0)... " if psi in (90,270) else
           "   <- PERPENDICULAR: d = 2a, the VERTICAL, vertex = the hinge"))
print()
print("  ** THE TWO DISTINGUISHED DIRECTIONS ARE AT RIGHT ANGLES, BECAUSE ONE IS THE")
print("     PERPENDICULAR OF THE OTHER. PERPENDICULARITY IS NOT A CHOICE. **")
print("  So the dial is divided by {axis, perpendicular} into FOUR quadrants of 90 -- and")
print("  the four is not imposed on the dial, it is what having an axis MEANS.")

print()
print("="*80)
print("(4)  THE CONSEQUENCE — does 12 = 3 x 4 now have both factors forced?")
print("="*80)
print("  the 3: the hinge triangle -- FORCED (the triple angle; three roots of one cubic).")
print("  the 4: the dial's quadrants -- FORCED (axis + perpendicular).")
print("  the bridge: a hinge transpose IS a dial turn -- VERIFIED in (2), and the map is")
print("              an isometry of the substrate.")
print()
n = 0
orbit = sorted({(120*i + 90*k) % 360 for i in range(3) for k in range(4)})
gaps = {round((orbit[(i+1) % len(orbit)] - orbit[i]) % 360, 6) for i in range(len(orbit))}
print(f"  3 hinges x 4 quarter-turns -> {len(orbit)} hinges at {sorted(gaps)} degree spacing")
print(f"  and it closes evenly because gcd(3,4) = {np.gcd(3,4)}")
print()
print("  >> ** IF (2) AND (3) BOTH HOLD, THEN THE KALEIDOSCOPE'S FOUR IS NOT CHOSEN. **")
print("     It is the dial's own quadrant structure, transported to the azimuth by an")
print("     isometry. And then 12 = 3 x 4 has BOTH factors forced, and:")
print("        the kaleidoscope's 30 = 360/12 = 360/(3x4)")
print("        the Nariai dial's  30 = arcsin(a/2a), the hole's half-angle at the hinge")
print("     ** ARE THE SAME 30 -- both are 'the 3 of the triple angle against the 4 of the")
print("        axis-and-perpendicular', read once in the azimuth and once in the dial. **")

print()
print("="*80)
print("WHAT IS PROVED HERE, AND WHAT IS NOT — kept apart, because the gap is the point")
print("="*80)
print("  PROVED:")
print("   1. the physics depends only on (theta - chi)  -- so the hinge azimuth and the")
print("      dial are ONE coordinate, not two. [verified, 300 random triples]")
print("   2. a hinge transpose by delta IS a dial turn by -delta, and the map realising it")
print("      is the azimuthal rotation, an isometry of the substrate. ** DARYL'S ISOMETRY")
print("      EXISTS. **")
print("   3. the dial carries exactly two distinguished directions, the axis and its")
print("      perpendicular, and they are at 90 BY DEFINITION of perpendicular.")
print()
print("  NOT PROVED, AND THIS IS THE HOLE:")
print("   ** that the KALEIDOSCOPE'S stamp is the DIAL'S quadrant structure and not merely")
print("      isomorphic to it. ** (2) says any delta transports; (3) says the dial's own")
print("      divisions sit at 90. Together they say: IF you stamp at 90, you are stamping")
print("      the dial's quadrants. They do NOT say the construction MUST stamp at 90.")
print("      thirty_degrees.py's finding survives intact at that level: every n coprime to")
print("      3 still closes evenly, and nothing yet FORCES the stamp to be 4 rather than 5.")
print()
print("  ** WHAT WOULD CLOSE IT: a reason the stamp must reproduce the dial's quadrants --")
print("     i.e. a statement that the figure must be closed under the same group that acts")
print("     on its own slicing. That is not a computation; it is a claim about what the")
print("     construction IS. Daryl may have it. I do not, and I will not manufacture it. **")
print()
print("  >> HONEST VERDICT: ** the isometry is REAL and it is his. ** The conjecture's")
print("     bridge exists and is verified. What is still open is narrower than it was and")
print("     is now stateable in one line: WHY MUST THE FIGURE BE CLOSED UNDER ITS DIAL'S")
print("     OWN SYMMETRY? Answer that and the two 30s are one, and 12 = 3x4 is forced end")
print("     to end.")
