"""turnaround_temporal_threeness.py (r1621) -- A2.9's bullet 2, worked: the turnaround
cubic's Z/3 IS the deck action of cosmic time's imaginary period, and there is a TWO-fold
sitting inside it at half-period which the horizon cubic's three-ness has no analogue of.

WHY. P3 carries the turnaround as the other cubic's root, its Nariai co-distinction
(A = cbrt(2) rho), and (r1608) its identity with the matter-Lambda equality radius. What P3
does NOT carry, and what the A2.9 note lists as grounded-but-unplaced, is the POSITIVE
statement of what the turnaround's three-ness IS: the temporal three-ness, against the
horizon triple's spatial one (hinges, S_3).

THE BEAD LAW (P7 fig C / P8 prop:cosmo):  r^3 = 2 M alpha^2 sinh^2(3 tau~ / 2 alpha).

WHAT THIS RECEIPT ESTABLISHES
  (1) FULL PERIOD  tau~ -> tau~ + 2 pi i alpha/3  leaves r^3 INVARIANT and cycles the three
      cube-root sheets: r -> e^{2 pi i/3} r. So the turnaround cubic's Z/3 is exactly the
      deck action of the cube-root cover generated by cosmic time's imaginary period.
  (2) HALF PERIOD  tau~ -> tau~ + i pi alpha/3  carries sinh^2 -> -cosh^2, i.e. the real
      EXPANSION leg to the conjugate COLLAPSE wings. This is why the wings sit at
      Im tau~ = +/- pi alpha/3 -- exactly half-period off the real axis.
  (3) THE TURNAROUND SITS AT THE HALF-PERIOD POINT ITSELF: at tau~ = -i pi alpha/3,
      sinh^2 = -1 exactly, so r^3 = -2 M alpha^2 and r = -(2 M alpha^2)^{1/3}. The
      kinematic turning is not somewhere on the wing; it is the half-period.
  (4) ASYMMETRY WITH THE SPATIAL LEG: the horizon cubic's three-ness is a real S_3 on
      colinear roots with NO internal two-fold of this kind. The temporal three-ness
      factors through a half-period that exchanges the branches; the spatial one does not.

HELD, do-not-assert: nothing here identifies the two cubics' ROOT SETS, which
order3_bridge.py holds open, and nothing here bears on the su(3) weight-triangle reading
struck as over-reach at r1430. This is the deck action of one cubic, not a bridge.
"""
import sympy as sp

M, al = sp.symbols('M alpha', positive=True)
t = sp.symbols('tau')            # cosmic time (complex)
x = 3*t/(2*al)                   # the phase

r3 = 2*M*al**2*sp.sinh(x)**2
P  = 2*sp.pi*sp.I*al/3           # the imaginary period
H  = sp.pi*sp.I*al/3             # half of it

print("="*76); print("(1) THE FULL PERIOD: invariance of r^3, and the sheet cycle"); print("="*76)
r3_shift = sp.simplify(r3.subs(t, t + P))
print("  r^3(tau + 2.pi.i.alpha/3) - r^3(tau) =", sp.simplify(r3_shift - r3))
assert sp.simplify(r3_shift - r3) == 0
print("  -> r^3 INVARIANT under the full imaginary period.")
# the three sheets: cube roots of a fixed r^3 differ by e^{2 pi i/3}
w = sp.exp(2*sp.pi*sp.I/3)
assert sp.simplify(w**3 - 1) == 0 and sp.simplify(w - 1) != 0
print(f"  -> the cube-root sheets differ by omega = e^(2.pi.i/3), omega^3 = 1: the Z/3 deck.")
print("  => the turnaround cubic's Z/3 IS this deck action. Its roots ARE the three sheets")
print("     of the one bead law, cycled by cosmic time's imaginary period.")

print(); print("="*76); print("(2) THE HALF PERIOD: expansion leg -> collapse wings"); print("="*76)
r3_half = sp.simplify(sp.expand_trig(r3.subs(t, t + H)))
print("  r^3(tau + i.pi.alpha/3) =", r3_half)
target = -2*M*al**2*sp.cosh(x)**2
print("  compared with -2.M.alpha^2.cosh^2 :", sp.simplify(r3_half - target))
assert sp.simplify(r3_half - target) == 0
print("  -> sinh^2 -> -cosh^2 exactly: the REAL EXPANSION leg becomes the COLLAPSE law")
print("     r = -(2.M.alpha^2)^{1/3} cosh^{2/3}(3.Re tau/2.alpha), negative-r, on the wing.")
print("  => the two collapse wings at Im tau = +/- pi.alpha/3 are the half-period images")
print("     of the real leg. Their location is not a choice; it is half the period.")

print(); print("="*76); print("(3) THE TURNAROUND IS THE HALF-PERIOD POINT"); print("="*76)
t_TA = -sp.I*sp.pi*al/3
s2 = sp.simplify(sp.sinh(x.subs(t, t_TA))**2)
print(f"  at tau = -i.pi.alpha/3 :  sinh^2(3 tau/2 alpha) = {s2}")
assert s2 == -1
r3_TA = sp.simplify(r3.subs(t, t_TA))
print(f"                            r^3 = {r3_TA}   =>  r = -(2.M.alpha^2)^{{1/3}}")
assert sp.simplify(r3_TA - (-2*M*al**2)) == 0
print(f"  and tau_TA / period = {sp.simplify(t_TA/P)}  -> exactly -1/2")
assert sp.simplify(t_TA/P) == sp.Rational(-1, 2)
print("  => the kinematic turning is not a point ON the wing: it IS the half-period.")
# consistency: it is a genuine velocity zero of the E=1 law
drdt = sp.diff(sp.root(r3, 3), t)
print("  velocity (d/dtau) of r at the turnaround :",
      sp.simplify(sp.limit(drdt.subs(t, t_TA + sp.Symbol('e', positive=True)), sp.Symbol('e', positive=True), 0)))

print(); print("="*76); print("(4) THE SPATIAL LEG HAS NO SUCH INTERNAL TWO-FOLD"); print("="*76)
# horizon cubic at a generic sub-Nariai mass: three colinear REAL roots, S_3 on them
twoM = sp.Rational(1, 4)                      # sub-Nariai in alpha=1 gauge (crit = 2/(3 sqrt 3) ~ .385)
hroots = sp.nroots(sp.Poly([1, 0, -1, twoM], sp.Symbol('r')))
print("  horizon roots at 2M=1/4 (alpha=1):", [sp.nsimplify(sp.re(z), rational=False) for z in hroots])
assert all(abs(sp.im(z)) < 1e-12 for z in hroots), "expected three real roots"
print("  -> all three REAL and distinct: the three-ness is a real S_3 on colinear roots.")
# COMPUTED r1625, not asserted (per THE_RECEIPT_AUDIT's standard): the horizon condition
# carries no cosmic-time dependence at all, so there is no shift of tau inside its Z/3.
f = 1 - 2*sp.Symbol('M')/sp.Symbol('r') - sp.Symbol('r')**2/sp.Symbol('alpha')**2
tau_sym = sp.Symbol('tau')
assert tau_sym not in f.free_symbols, "f unexpectedly depends on cosmic time"
print(f"  -> COMPUTED: f = {f} ; free symbols {sorted(str(x) for x in f.free_symbols)} -- tau ABSENT.")
print("     The horizon condition f=0 is a condition on r alone, so NO SHIFT OF COSMIC TIME")
print("     lives inside its Z/3 -- which is what this computation establishes, and all of it.")
print("     *** SCOPE (r1674): the verdict must not widen past the quantifier. This shows f has")
print("     no tau dependence; it does NOT show that no branch exchange is associated with the")
print("     spatial three-ness. R exchanges branches -- it carries (rho,rho,-2rho) to its")
print("     P-conjugate twin -- acting BETWEEN the two Nariai members rather than inside one")
print("     member's S_3. The asymmetry is of WHERE the exchange sits, not whether one exists.")
print("  => TEMPORAL three-ness factors through a branch-exchanging half-period;")
print("     SPATIAL three-ness does not. The two order-threes differ in their INTERIOR,")
print("     which is a sharper separation than the affine inequivalence of lem:twoturnings.")

print(); print("="*76)
print("VERIFIED (1)-(4). HELD do-not-assert: no identification of the two cubics' root sets")
print("(order3_bridge.py holds that open), and no su(3) weight-triangle reading (struck r1430).")
print("This is the deck action of ONE cubic and the interior structure of ONE three-ness.")
