"""
WHAT THE CLOSED LIGHT-PATH IS. (r1110)  Successor to U1b_what_the_cycles_are.py.

WHERE THIS STANDS. U1 found the 24 hinges form four 6-cycles under the rulings. U1b found
those four classes ARE the stamp's four copies, and that each 6-cycle is one hinge-TRIPLE
traversed twice -- once per horn -- the walk alternating level at every step because a null
line cannot stand still in time. Both receipts stopped there and said so: they quantify over
incidence and azimuth arithmetic, and say nothing about what a cycle MEANS.

THE QUESTION, and it is forced by two things the corpus already says:
  * P3 prop:triple -- a triple is ONE GEOMETRY UNDER THREE DESIGNATIONS. The three hinges of
    a cycle are not three geometries; they are three names for one.
  * P5 -- the within-single-geometry morphisms are exactly D_3 = <sigma, tau>: sigma the
    root-exchange (order 2), tau the sky-angle periodicity w -> w + 2pi/3 (order 3). These
    are the operations that RELABEL which root is designated, at fixed geometry.
  * the_isometry.py (tab23) -- the physics depends only on (theta - chi), so a HINGE
    TRANSPOSE by delta IS a DIAL TURN by -delta, realised by an azimuthal rotation of the
    substrate. The hinge's azimuth and the dial are ONE coordinate.

  ** So the walk moves the hinge azimuth. By tab23 that IS a dial turn. And a dial turn is
     a groupoid morphism. THEREFORE: DOES THE LIGHT-PATH REALISE D_3? **

THREE QUESTIONS, named before computing:
  Q1  two ruling-steps advance the azimuth by how much -- and is that tau's step?
  Q2  what is ONE ruling-step? It is half of tau, and tau has order 3, so a "half-tau"
      cannot be a power of tau. What is it?
  Q3  the cycle has SIX vertices and D_3 has SIX elements. Are they the same six?

** THE PREDICTION ON Q3, NAMED BEFORE RUNNING, AND IT IS A NEGATIVE. ** A 6-cycle traversed
by one repeated step is a Z_6 -- cyclic, abelian, with an element of order 6. D_3 = S_3 is
NON-abelian and has NO element of order 6 (its elements have orders 1, 2, 3). So if the walk
generated D_3 the group theory would be wrong. ** I predict the six hinges are NOT the six
D_3 labels, and that the coincidence of 6s is exactly that. ** If it comes back otherwise,
this receipt is wrong and the corpus's group theory is wrong, which is worth knowing.

COULD THIS RETURN OTHERWISE? Yes at every step: the azimuth arithmetic is arithmetic; the
group generated by the walk is computed from the walk, not assumed; and Q3's prediction is
falsifiable by an explicit isomorphism check.
"""
import numpy as np
from itertools import permutations

a = 1.0
S3 = np.sqrt(3)
X0H = S3*a
AZ = [30*k for k in range(12)]

# the coupling, as established (U1): above at A <-> below at A -/+ 120
def ruling_step(state, fam):
    """(level, az) -> (other level, az -/+ 120). fam = +1 or -1."""
    lv, az = state
    if lv == 'A':
        return ('B', (az - fam*120) % 360)
    return ('A', (az + fam*120) % 360)

print("="*80)
print("Q1 -- TWO RULING-STEPS: how far does the azimuth move, and is that tau?")
print("="*80)
st = ('A', 0)
print(f"  start          {st}")
s1 = ruling_step(st, +1); print(f"  one step  (+)  {s1}")
s2 = ruling_step(s1, -1); print(f"  two steps (-)  {s2}")
print(f"\n  two steps: level {st[0]} -> {s2[0]} (SAME horn), azimuth {st[1]} -> {s2[1]}")
dz = (s2[1] - st[1]) % 360
print(f"  azimuth advance = {dz} degrees")
assert s2[0] == 'A' and dz == 120
print(f"""
  ** TWO RULING-STEPS = SAME HORN, AZIMUTH +{dz}. **
  tau is w -> w + 2pi/3 = w + 120 on the SKY ANGLE. By tab23 (the_isometry.py) a hinge
  transpose by delta IS a dial turn by -delta. So a hinge advance of +120 IS a dial turn of
  -120 = ** tau^(-1) = tau^2 **, which generates <tau> exactly as tau does.
  (I first asserted the advance was 240 and the receipt refused: A0 -> B240 -> A120 is +120,
  not +240. Inferred, not computed -- face 35, caught by putting the verdict in the assert.)""")

print("\n  AND THE FAMILIES MUST ALTERNATE, which is what makes it a cycle at all:")
back = ruling_step(s1, +1)
print(f"    ('A',0) --(+)--> {s1} --(+)--> {back}    <- same family twice = BACK ALONG THE SAME RULING")
assert back == ('A', 0)
print(f"    ('A',0) --(+)--> {s1} --(-)--> {s2}    <- alternating = the walk advances")
print("""  ** So the 6-cycle is not 'follow the rulings' -- it is 'alternate the two ruling
  families'. Repeating one family is an out-and-back along a single null line. The cycle
  exists because the hyperboloid is DOUBLY ruled. **""")

print("\n" + "="*80)
print("** Q1 ANSWERED: TWO RULING-STEPS ARE tau. **")
print("="*80)
print("""  The groupoid's order-3 generator -- the sky-angle periodicity, the relabelling of which
  root of the triple is designated -- IS TWO STEPS ALONG A NULL RULING.

      >>> tau IS NOT AN ALGEBRAIC RELABELLING. IT IS A LIGHT-PATH. <<<

  And it takes TWO steps because one step changes horn. tau lives on one horn; a ruling does
  not. So the walk realises tau only by leaving the horn and coming back.""")
# verify tau^3 = id along the walk
st = ('A', 0); seq = [st]
for i in range(6):
    st = ruling_step(st, +1 if i % 2 == 0 else -1); seq.append(st)
print(f"\n  six steps from {seq[0]}: {' -> '.join(f'{l}{z}' for l, z in seq)}")
assert seq[-1] == seq[0]
print(f"  ** returns. six ruling-steps = tau^3 = id. The 6-cycle IS tau's order, doubled by the horn. **")

print("\n" + "="*80)
print("Q2 -- WHAT IS ONE RULING-STEP? (a 'half-tau', which cannot be a power of tau)")
print("="*80)
print(f"  one step: ('A', 0) -> {ruling_step(('A',0), +1)}")
print("""  It does two things at once: azimuth -120 AND horn flip. Name each against the corpus's
  own operations (ONTOLOGY_FOUNDATION_INDEX §0, R/P/T):
      tau      : the dial's +120. Azimuthal. HORN-PRESERVING (it is a rotation).
      R        : the mass reflection r0 -> -r0. Spacelike, ** HORN-PRESERVING ** (P3/§1e).
      T        : the time reflection X0 -> -X0. Timelike, ** HORN-FLIPPING **.
  A ruling-step flips the horn. So it is not tau and it is not R. It has a T in it.""")
print(f"""
  ** ONE RULING-STEP = tau^(-1/2) composed with the horn flip -- and 'tau^(-1/2)' is not an
  element of D_3 at all, because tau has order 3 and 3 is odd: THERE IS NO SQUARE ROOT OF
  tau IN <tau>. **

  So a single ruling-step is NOT a groupoid morphism. It is not in D_3. Only its SQUARE is.

      >>> THE RULING IS FINER THAN THE GROUPOID. <<<
  The groupoid's morphisms act within one horn, at fixed geometry. A ruling does not stay in
  one horn, so it is not one of them -- but two of them compose to one. The light cone sees
  a structure the vantage-groupoid cannot express: a HALF of its own order-3 generator.""")

print("\n" + "="*80)
print("Q3 -- ARE THE CYCLE'S SIX HINGES THE SIX D_3 LABELS?  (predicted: NO)")
print("="*80)
print("""  D_3 = S_3 has six elements: id, tau, tau^2, sigma, sigma.tau, sigma.tau^2. P5 §247: they
  "permute six labelled positions, corresponding to the six distinct sky-angle labels a
  single intrinsic curve can carry."
  The cycle has six hinges. Test whether the walk's group IS D_3.""")
# the group generated by the walk (one repeated 2-step) acting on the 6 cycle-vertices
verts = []
st = ('A', 0)
for i in range(6):
    verts.append(st); st = ruling_step(st, +1 if i % 2 == 0 else -1)
idx = {v: i for i, v in enumerate(verts)}
# the walk's generator as a permutation of the six
g = tuple(idx[ruling_step(v, +1 if idx[v] % 2 == 0 else -1)] for v in verts)
print(f"\n  the six cycle-vertices, in walk order: {[f'{l}{z}' for l, z in verts]}")
print(f"  the walk's single step, as a permutation: {g}")
# order of g
def compose(p, q): return tuple(p[q[i]] for i in range(len(q)))
e = tuple(range(6)); h = g; order = 1
while h != e:
    h = compose(h, g); order += 1
print(f"  its order: {order}")
assert order == 6
print(f"""
  ** THE WALK'S STEP HAS ORDER {order}. The group it generates is Z_6 -- CYCLIC. **
  ** D_3 = S_3 is NON-ABELIAN and its elements have orders 1, 2, 3. IT HAS NO ELEMENT OF
     ORDER 6. So Z_6 is NOT D_3, and the six hinges are NOT the six D_3 labels. **
  ** PREDICTION CONFIRMED, and it is a negative worth having: the coincidence of 6s is a
     coincidence. Two different groups of order six. **""")
# make it explicit
print(f"""
  Z_6 vs S_3, both order 6, and the difference is exactly what the walk shows:
      Z_6 : cyclic, abelian, HAS an element of order 6  <- the walk
      S_3 : non-abelian, no element of order 6          <- the groupoid
  and Z_6 = Z_3 x Z_2 -- ** which is the walk's own structure: tau's 3, times the horn's 2. **
  The 6 of the cycle is 3 x 2 = (the triple) x (the horn).
  The 6 of D_3 is 3! = the permutations of the triple.
  Same number. Different objects. The cycle counts the triple AND the horn; D_3 counts the
  triple's rearrangements.""")

print("\n" + "="*80)
print("SO WHERE IS sigma?  (the honest gap this opens)")
print("="*80)
print("""  The walk realises tau (Q1) and nothing else -- Z_6 = <tau> x <horn>. It never produces
  sigma, the root-exchange, and it cannot: sigma is a REFLECTION (order 2, w -> pi/3 - w,
  fixed at w = 30 = Nariai), and no power of a 6-cycle's generator is a reflection of the
  azimuth.

  ** SO THE LIGHT-PATH GIVES tau AND NOT sigma. ** That is a real asymmetry between the
  groupoid's two generators, and it is new: P5 gives them equal standing (both generators of
  D_3, related by (sigma.tau)^2 = id). The rulings do not. tau is a light-path; sigma is not
  reached by any walk on this graph.

  ** NAMED, UNRUN: is sigma a light-path at all? ** It has a fixed point (Nariai, w=30), and
  a walk on a graph with a fixed vertex is a different object from a free 6-cycle. The
  natural next question is whether sigma is realised by the rulings of the NARIAI member --
  where the cut degenerates to the two null rulings themselves (thales_is_the_dial.py tab18).
  That is where sigma's fixed point and the rulings meet, and nobody has looked.""")

print("\n" + "="*80)
print("WHAT THIS RETURNED")
print("="*80)
print("""  ** tau IS A LIGHT-PATH. ** The groupoid's order-3 generator -- the sky-angle periodicity,
  the relabelling of which root of the triple is designated -- is TWO STEPS ALONG A NULL
  RULING. Verified: two steps return to the same horn with the azimuth advanced +120,
  which by tab23 (hinge transpose = dial turn) IS a dial turn of -120 = tau^2. Six steps = tau^3 =
  id, which is the 6-cycle.
  ** tau is not an algebraic relabelling. It is a closed path of light through both horns. **

  ** AND ONE RULING-STEP IS NOT A GROUPOID MORPHISM AT ALL. ** It flips the horn, so it is
  neither tau nor R (both horn-preserving); it has a T in it. And it is a 'half-tau' -- which
  cannot exist in <tau>, since tau has order 3 and 3 is odd. ** THE RULING IS FINER THAN THE
  GROUPOID: the light cone sees a half of the groupoid's own generator, and the groupoid
  cannot express it. Only the square is a morphism. **

  ** THE PREDICTED NEGATIVE HELD: the cycle's six is NOT D_3's six. ** The walk generates
  Z_6 (cyclic, an element of order 6); D_3 = S_3 is non-abelian with no element of order 6.
  Z_6 = Z_3 x Z_2 = (the triple) x (the horn); S_3 = 3! = the triple's rearrangements. Same
  number, different objects. The coincidence of 6s is a coincidence -- checked, not assumed.

  ** AND THE ASYMMETRY IT EXPOSES, which is the finding to carry: THE RULINGS GIVE tau AND
  NOT sigma. ** P5 gives the two generators equal standing. The light cone does not: tau is
  a walk; sigma is a reflection with a fixed point and no walk produces it.

  NAMED, UNRUN: is sigma a light-path at the NARIAI member, where the cut degenerates into
  the two null rulings themselves (tab18) and sigma has its fixed point? That is the one
  place sigma and the rulings are forced to meet. Nobody has looked.

  ⚠ BOUNDED (face 35): quantifies over the AZIMUTH ARITHMETIC and the WALK'S GROUP. The
  identification of a hinge advance with a dial turn is tab23's, cited not re-derived. No f,
  no 2M, no cut appears here.""")
