import math
print("   substrate isometry algebra:      so(5,1),  rank 3,  dim 15")
print("   its complexification:            so(6,C) = D_3")
print("   exceptional isomorphism:         D_3 = A_3   (so(6,C) = sl(4,C))")
print()
print("   |W(A_2)|   = 3!      = %2d    <- the corpus's Weyl S_3 (the horizon cubic's roots)"%math.factorial(3))
print("   |Aut(A_2)| = S_3xZ_2 = %2d    <- the corpus's D_6 (family x chirality)"%12)
print("   |W(A_3)|   = 4!      = %2d    <- family + holonomy V_4, closed at 24"%math.factorial(4))
print("   |W(B_3)|   = 2^3*3!  = %2d    <- family + chirality + holonomy, closed at 48"%(8*6))
print()
print("   TWO ROOT SYSTEMS, and they are different objects:")
print("      A_2   -- the HORIZON CUBIC's three roots: the corpus's discrete skeleton")
print("      A_3=D_3 -- the SUBSTRATE's complexified isometry algebra so(6,C)")
print()
print("   and W(A_3) = S_4 is EXACTLY what family + holonomy closes to.")
print("   A_2 sits inside A_3 as a sub-root-system (delete one node of the A_3 diagram).")
