"""X4-REDONE — what is actually left once P2 is read.
P2 prop:Kretschmann ALREADY: K(z) has a TWELFTH-ORDER POLE at z=pi, 'generated by the chain rule applied
to the composition at a non-degenerate critical point of r(z)'; bounded at z=0.
So the POLE classification and its MECHANISM are the corpus's.  What is NOT stated anywhere is the
exclusion of an ESSENTIAL singularity -- which is what makes 'a branch point, not a barrier' an ANALYTIC
statement and not only a geometric one.  That exclusion is the whole of what survives here.
"""
import numpy as np, sympy as sp
z,M,t,al = sp.symbols('z M tau alpha', positive=True)

print("="*78); print("X4-REDONE — THE ONLY THING P2 DOES NOT ALREADY SAY"); print("="*78)

print("\nSTEP 1 — confirm P2's own statement in P2's own variable, so the audit is honest.")
r = M*(1+sp.cos(z)); K = 48*M**2/r**6
eps=sp.symbols('epsilon', positive=True)
lead = sp.limit(K.subs(z, sp.pi-eps)*eps**12, eps, 0)
print("   lim_{eps->0} K(pi-eps) . eps^12 =", sp.simplify(lead), " (finite and nonzero => order exactly 12)")
print("   and eps^11 test:", sp.limit(K.subs(z, sp.pi-eps)*eps**11, eps, 0), "(diverges => not order 11)")
print("   => leading term ~ eps^(-12): a TWELFTH-ORDER pole.  P2 prop:Kretschmann, verified.")
print(f"   and at z=0:  K = {sp.simplify(K.subs(z,0))}  -- finite.  P2, verified.")

print("\nSTEP 2 — THE EXCLUSION, which is the new content.  Are there essential singularities?")
print("   In P2's variable: r(z) = M(1+cos z) is ENTIRE; K(z) = 48/(M^4 (1+cos z)^6) is therefore")
print("   MEROMORPHIC on the whole finite z-plane -- its only singularities are the poles where")
print("   cos z = -1, i.e. z = pi + 2k.pi.  No essential singularity anywhere in the finite plane.")
sols=sp.solve(sp.cos(z)+1, z)
print(f"     poles at cos z = -1:  z = {sols} + 2k.pi")
print("   In P3's bead variable: r^3 = 2M a^2 sinh^2(3 tau/2a) with sinh ENTIRE, so r(tau)'s only")
print("   finite-plane singularities are the algebraic branch points where sinh vanishes.")
for k in range(3):
    print(f"     sinh(3 tau/2a) = 0 at tau = {k}.(2 i pi a/3)  -> r ~ (tau-tau_k)^(2/3), order-3 branch")
print("   No poles of r, no essential points.")

print("\nSTEP 3 — WHY THE EXCLUSION IS THE LOAD-BEARING PART.")
print("   A POLE continues as a map to the Riemann sphere.  A FINITE-ORDER BRANCH POINT continues")
print("   onto a cover.  AN ESSENTIAL SINGULARITY CONTINUES AS NEITHER -- by Picard's theorem the")
print("   function takes every value infinitely often in any neighbourhood, and nothing whatever")
print("   can be said of the values beyond it.")
print("   So P2's 'chain-rule artefact' and P3/P7's 'a branch point, not a barrier' are ANALYTIC")
print("   statements and not merely geometric ones PRECISELY BECAUSE the singularity is of finite")
print("   order in both senses -- and that is the fact the corpus had not recorded.")
print("\n" + "="*78)
print("RESULT X4-REDONE:  P2 prop:Kretschmann already classifies the divergence as a finite-order")
print("  POLE and already gives its mechanism (the chain rule at a non-degenerate critical point).")
print("  The r1870 claim that 'the corpus asserts both and never says they are compatible' was")
print("  WRONG -- P2's chain-rule reading IS the compatibility statement, in the corpus's own terms.")
print("  WHAT SURVIVES, and it is one sentence: NO ESSENTIAL SINGULARITY IS PRESENT in the finite")
print("  plane, in either parametrisation -- which is what makes 'not a barrier' analytic.")
print("="*78)
