"""X5 — the monodromy GROUP of the corpus's cover, not just the map.
Cubic r^3 - r + m = 0 over the m-plane.  Corpus (P5): 'the deck group is S_3, generated by the
monodromies about the branch points'.  Two transpositions generate S_3 only if they DIFFER."""
import numpy as np
mN = 2/(3*np.sqrt(3))
def roots_at(m): return np.roots([1,0,-1,m])
def track(path):
    r = roots_at(path[0])
    for m in path[1:]:
        new = roots_at(m); used=set(); out=np.empty(3,dtype=complex)
        for i,ri in enumerate(r):
            j = min((k for k in range(3) if k not in used), key=lambda k: abs(new[k]-ri))
            out[i]=new[j]; used.add(j)
        r = out
    return r
def perm_from(base, path):
    r0=roots_at(base); rf=track(np.concatenate([[base],path,[base]]))
    return tuple(int(np.argmin([abs(rf[i]-r0[k]) for k in range(3)])) for i in range(3))
def compose(p,q): return tuple(p[q[i]] for i in range(3))
def cyc(p):
    fx=[i for i in range(3) if p[i]==i]
    if len(fx)==3: return "identity"
    if len(fx)==1:
        mv=[i for i in range(3) if p[i]!=i]; return f"transposition ({mv[0]},{mv[1]})"
    return f"3-cycle {p}"

base = 0.0+0.35j
def loop(c, eps=0.02, N=4000):
    return np.concatenate([np.linspace(base,c+eps,N//4),
                           c+eps*np.exp(2j*np.pi*np.linspace(0,1,N//2)),
                           np.linspace(c+eps,base,N//4)])
def loop_inf(R=60.0, N=8000):
    u=base/abs(base)
    return np.concatenate([np.linspace(base,R*u,N//4),
                           R*u*np.exp(2j*np.pi*np.linspace(0,1,N//2)),
                           np.linspace(R*u,base,N//4)])

print("="*78); print("X5 — THE MONODROMY GROUP"); print("="*78)
print(f"\n  ALL loops based at the SAME point m = {base}.  (Permutations compose only when they are.)")
tp=perm_from(base,loop(+mN)); tm=perm_from(base,loop(-mN)); ci=perm_from(base,loop_inf())
print(f"   tau_+  (about +2/3sqrt3) = {tp}  -> {cyc(tp)}")
print(f"   tau_-  (about -2/3sqrt3) = {tm}  -> {cyc(tm)}")
print(f"   c_inf  (about infinity)  = {ci}  -> {cyc(ci)}")
print(f"\n  *** THE TWO NARIAI TRANSPOSITIONS DIFFER: {tp != tm}  -- so they generate S_3. ***")
print("      Had they been the SAME transposition the group would be Z_2 and P5's claim false.")

G={(0,1,2)}; frontier=[tp,tm]
while frontier:
    g=frontier.pop()
    if g in G: continue
    G.add(g)
    for h in list(G):
        for x in (compose(g,h),compose(h,g)):
            if x not in G: frontier.append(x)
print(f"\n  group generated: order {len(G)}  =>  {'S_3, CONFIRMED' if len(G)==6 else 'NOT S_3'}")
print(f"   elements: {sorted(G)}")

print("\n  THE pi_1 RELATION on a thrice-punctured sphere (product of the loops is trivial):")
for lab,val in [("tau_- . tau_+ . c_inf", compose(compose(tm,tp),ci)),
                ("c_inf . tau_- . tau_+", compose(compose(ci,tm),tp))]:
    print(f"   {lab:24s} = {val}   trivial? {val==(0,1,2)}")
# r2376+c54.158 -- pins X5's result exactly as receipts/INDEX.md quotes it: tau_+ = (0 2) and
# tau_- = (1 2) -- DIFFERENT transpositions, which is the whole content (the SAME transposition
# twice would give Z_2 and make P5's deck-group claim false) -- the loop about infinity is a
# 3-CYCLE, the group they generate is the full S_3 (order 6, all six permutations, as printed),
# and the pi_1 relation tau_- tau_+ c_inf = id closes EXACTLY, so the base is thrice-punctured.
assert cyc(tp) == "transposition (0,2)", (tp, cyc(tp))
assert cyc(tm) == "transposition (1,2)", (tm, cyc(tm))
assert tp != tm
assert cyc(ci).startswith("3-cycle"), (ci, cyc(ci))
assert len(G) == 6
assert sorted(G) == [(0,1,2),(0,2,1),(1,0,2),(1,2,0),(2,0,1),(2,1,0)], sorted(G)
assert compose(compose(tm,tp),ci) == (0,1,2)
assert compose(compose(ci,tm),tp) == (0,1,2)
print("\n" + "="*78)
print("RESULT X5:")
print("  (a) The two Nariai monodromies are DIFFERENT transpositions, so they generate S_3.")
print("      P5's deck-group claim is VERIFIED, not assumed -- and the alternative was real:")
print("      the same transposition twice would have given Z_2 and made the claim false.")
print("  (b) The monodromy about INFINITY is a 3-CYCLE, confirming X1's total branching there")
print("      by an independent route -- monodromy rather than asymptotics.")
print("  (c) The relation closes EXACTLY, so the base is a THRICE-punctured sphere.  The corpus")
print("      names two branch points; the representation needs three, and the third is what")
print("      makes the relation close.")
print("  INSTRUMENT NOTE: permutations compose only when all loops are based at the SAME point")
print("  with consistent paths.  A first pass computed c_inf on a circle based at m=60 instead,")
print("  and the relation appeared to fail.  It does not.")
print("="*78)
