#!/usr/bin/env python3
r"""C1 -- R-M station Ⓒ, closed on the question its own receipt left open.  `M1` established that the
equianharmonic Z_6 and the monodromy S_3 are "same order, not isomorphic" and stated plainly that
"nothing here exhibits an action".  The Z_6 does act: it is a subgroup of the corpus's own Aut(A_2).
And there is a THIRD order-six reading nobody named, which a sentence already in P13 excludes.

COMPUTES: every subgroup of order six of S_3 x Z_2, by exhaustive generation from all subsets of size
<= 3 of the twelve elements; their isomorphism types by element-order profile and commutativity; the
identification of the unique cyclic one with <deck Z_3> x <central Z_2>; the twisted S_3 and that it
is a distinct subgroup of the same order and type; and a re-verification that stations Ⓖ and Ⓗ survive
the instrument hardening this receipt forced.  Nothing is pinned or fitted.

** ⛭ ⓵ THE QUESTION `M1` LEFT OPEN, IN ITS OWN WORDS. **  *"NOT that Z_6 acts on anything in the
construction.  Nothing here exhibits an action; what is exhibited is that the group complex analysis
attaches to an equianharmonic cross-ratio is not the [monodromy group]."*

** ⛭⛭ ⓶ IT ACTS, AND IT ACTS INSIDE THE CORPUS'S OWN GROUP. **  P13:
*"The substrate's full discrete automorphism is `Aut(A_2) = S_3 x Z_2 = D_6`.  Its `Z_2` is the
orientation parity `R = gamma^5` shown above to grade fermion chirality; its `S_3` permutes the three
mass-tied roots of the offset-mass cubic."*
  ⇒ *** `D_6` has EXACTLY THREE subgroups of order six -- computed below by exhaustion -- and one of
      them is cyclic: `Z_6 = <the deck Z_3> x <the central Z_2>`.  So the Z_6 is not a group attached
      from outside; it is the subgroup generated by the two data the corpus already carries. ***

** ⛔⛭⛭ ⓷ AND THERE IS A THIRD READING, WHICH NEITHER `M1` NOR THE PAPERS NAME. **  The other two
order-six subgroups are both isomorphic to `S_3`, and they are *different subgroups*:

      *** `S_3 x 1`         -- root permutations, chirality untouched
          `{(sigma, sgn sigma)}` -- root permutations WITH a chirality flip on every transposition ***

  ⇒ ** So "the degree-six dial" has three candidate readings inside the corpus's own `Aut(A_2)`, not
    two, and the corpus supplies generators for all three. **

** ⌗ ⓸ AND ONE SENTENCE ALREADY IN P13 EXCLUDES THE TWISTED ONE. **  *"`sigma` exchanges a pair
**within** a sign-half, while the backward-radial reflection `r_0 -> -r_0` -- the outer `Z_2` --
carries between the two-positive and two-negative halves."*
  ⇒ *** A transposition that stays within a sign-half carries trivial `Z_2` component.  That is
      exactly the statement that the `S_3` is `S_3 x 1` and not the graph of the sign map. ***
  ⇒ ** The sentence was written to defuse an apparent asymmetry in the `2+1` labelling, and it
    settles a group-identification question it was not addressing. **

** ⛔⛭⛭ ⓹ AND THIS STATION FORCED A HARDENING OF THE INSTRUMENT, BY PRODUCING A FALSE HOLE ON
ITSELF. **  *A baseline survey for `Aut(A_2)` returned **zero** while the object appears **thirty-four
times** across seven papers -- because the corpus writes `\mathrm{Aut}(A_2)` and the macro's closing
brace splits the term.*
  ⇒ *** A COUNT CAN FAIL TO BE ABOUT ITS TERM AT ALL.  `reach_baseline`'s head already said a count is
      not a verdict; this is the sharper case, where the count is not even a count of the thing
      asked for -- and it is `L-263`'s own instrument doing it to `L-263`'s own author. ***
  ⇒ ** Every survey now runs twice, raw and de-macroed, and FLAGS any term whose de-macroed count is
    higher. **  ⌗ *And stations Ⓖ and Ⓗ are re-verified against the hardened instrument below: their
    zeros are still zeros.*

WHAT IS NOT CLAIMED.  ** Not that the equianharmonic curve's `Z_6` IS the corpus's `Z_6` ** -- both are
`Z_3 x Z_2` and `M1`'s handoff identifies the `Z_3` factors (complex multiplication by `omega` is the
deck's `omega`), but the `Z_2` factors are different structures -- the elliptic involution `y -> -y`
against the ruling exchange `gamma^5` -- and that identification is NOT made here and is what remains
of this station.  ** Not that P13 is wrong ** -- its sentence is correct and is used here for a
purpose it was not written for.  ** Not that the twisted `S_3` was ever asserted ** -- it was never
named at all, which is the point: an unnamed candidate cannot be excluded, and it now is.  ** And not
that item 23 is closed ** -- what is closed is which order-six subgroups exist and which one the
corpus's own sentence selects; the deck/monodromy/Galois relations `rem:galois` states are untouched.

    python3 receipts/L266_station_C_three_readings_of_the_dial/C1_the_degree_six_dial_has_three_readings_and_the_paper_excludes_one.py

Written r3154, `L-266`.  Stated for reversal.
"""
import importlib.util
import itertools
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []

spec = importlib.util.spec_from_file_location('_rb', os.path.join(ROOT, 'corpus',
                                                                  'reach_baseline.py'))
RB = importlib.util.module_from_spec(spec)
spec.loader.exec_module(RB)

#: ** ⛭ THE BASELINE AT THIS STATION'S OWN CLOSE (r3972), in BOTH views -- raw and de-macroed --
#: ** because the artefact question is precisely a comparison between the two.  Mirrors
#: ** `reach_baseline.bodies()` and `demacro()` rather than re-deriving them, so the historical
#: ** counts are produced by the same preprocessing as the live ones.
_AT_BUILD = '65de83f1'          # r3154 -- this station's own close
_AT_BUILD_CACHE = {}


def _at_build_counts(term, tex=False):
    """`RB.counts(term, tex=tex)` as it read at this station's own close."""
    import re as _re
    import subprocess as _sp
    if not _AT_BUILD_CACHE:
        for _tex, _key in RB.TEX2P.items():
            _raw = _sp.run(['git', 'show', f'{_AT_BUILD}:corpus/{_tex}'], cwd=ROOT,
                           capture_output=True, text=True, errors='replace').stdout
            _b = '\n'.join(l for l in _raw.split('\n') if not l.lstrip().startswith('%'))
            _j = _b.find('\\begin{thebibliography}')
            _body = _re.sub(r'\s+', ' ', _b[:_j] if _j > 0 else _b)
            _AT_BUILD_CACHE[_key] = (_body, RB.demacro(_body))
        assert len(_AT_BUILD_CACHE) == len(RB.TEX2P), (
            'every paper must be readable at the throw commit, or the baseline is partial',
            sorted(set(RB.TEX2P.values()) - set(_AT_BUILD_CACHE)))
    return {k: len(_re.findall(_re.escape(term), v[1 if tex else 0], _re.I))
            for k, v in _AT_BUILD_CACHE.items()}

B, BT = RB.BODIES, RB.BODIES_TEX

E = (tuple(range(3)), 0)
S3 = list(itertools.permutations(range(3)))
G = [(p, e) for p in S3 for e in (0, 1)]


def mul(a, b):
    (p, e), (q, f) = a, b
    return (tuple(p[q[i]] for i in range(3)), (e + f) % 2)


def order(g):
    x, n = g, 1
    while x != E:
        x = mul(x, g)
        n += 1
    return n


def gen(S):
    H = {E}
    while True:
        new = H | set(S) | {mul(a, b) for a in H | set(S) for b in H | set(S)}
        if new == H:
            return frozenset(H)
        H = new


def sgn(p):
    return sum(1 for i in range(3) for j in range(i + 1, 3) if p[i] > p[j]) % 2


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def main():
    print()
    print('  C1 -- station Ⓒ: does the Z_6 act, and how many readings does the dial have?')
    print()

    # ============================================================ (1) the corpus's group
    print('  ' + '=' * 74)
    print('  PART 1 -- ⛭ THE GROUP IS THE CORPUS\'S OWN, AND SO ARE THE GENERATORS')
    print('  ' + '=' * 74)
    check('⓵ P13 states it: Aut(A_2) = S_3 × Z_2 ≅ D_6, its Z_2 the orientation parity R = γ⁵ '
          'grading fermion chirality, its S_3 permuting the three mass-tied roots',
          'S_3\\times\\mathbb{Z}_2\\cong D_6' in B['P13']
          and 'orientation parity $R=\\gamma^5$' in B['P13']
          and 'permutes the three mass-tied roots' in B['P13'])
    check('⓵ᵇ and P14 carries the deck Z_3 as the family symmetry and the hinge S_3 as a '
          'WITHIN-STATE index, having withdrawn the generation-is-a-wall identification',
          'the hinge $S_3$ is a \\emph{within-state} index and not a family symmetry' in B['P14']
          and 'the turnaround\'s deck $\\mathbb{Z}_3$' in B['P14'])
    check('⓵ᶜ and M1 states the open question in terms: "nothing here exhibits an action"',
          'Nothing here exhibits an action' in
          open(os.path.join(ROOT, 'receipts', 'L203_reach_stations',
                            'M1_the_equianharmonic_group_is_not_the_monodromy_group.py'),
               encoding='utf-8').read())

    # ============================================================ (2) the three subgroups
    print()
    print('  ' + '=' * 74)
    print('  PART 2 -- ⛭⛭ D_6 HAS EXACTLY THREE SUBGROUPS OF ORDER SIX')
    print('  ' + '=' * 74)
    check(f'⓶ |D_6| = {len(G)} and its element orders are {sorted(set(order(g) for g in G))}',
          len(G) == 12 and sorted(set(order(g) for g in G)) == [1, 2, 3, 6])
    subs = set()
    for k in (1, 2, 3):
        for S in itertools.combinations(G, k):
            H = gen(S)
            if len(H) == 6:
                subs.add(H)
    types = sorted(('Z_6' if any(order(g) == 6 for g in H) else 'S_3') for H in subs)
    print(f'    order-six subgroups found by exhaustion over all subsets of size ≤3: {len(subs)} '
          f'-- types {types}')
    check('⓶ᵇ exactly three, two of type S_3 (non-abelian) and one cyclic Z_6',
          len(subs) == 3 and types == ['S_3', 'S_3', 'Z_6'])

    # the cyclic one, identified
    cyc = [H for H in subs if any(order(g) == 6 for g in H)][0]
    deck = ((1, 2, 0), 0)                       # the 3-cycle: the deck's ω
    chir = ((0, 1, 2), 1)                       # the central Z_2: γ⁵, the ruling exchange
    check('⛭ ⓶ᶜ *** and the cyclic one is generated by the corpus\'s two data: ⟨deck Z_3⟩ × '
          '⟨central Z_2 = γ⁵⟩ -- so the Z_6 DOES act, as the subgroup of Aut(A_2) generated by the '
          'family deck and the chirality parity ***',
          gen([deck, chir]) == cyc)
    check('⓶ᵈ and it is cyclic because gcd(3,2)=1, which is why an order-six group can be abelian '
          'here at all', all(mul(a, b) == mul(b, a) for a in cyc for b in cyc))

    # ============================================================ (3) the third reading
    print()
    print('  ' + '=' * 74)
    print('  PART 3 -- ⛔⛭ A THIRD READING NOBODY NAMED')
    print('  ' + '=' * 74)
    plain = frozenset((p, 0) for p in S3)
    twist = frozenset((p, sgn(p)) for p in S3)
    check('⓷ the two S_3-type subgroups are DISTINCT: S_3 × 1 (roots permuted, chirality untouched) '
          'and the graph {(σ, sgn σ)} (every transposition carries a chirality flip)',
          plain in subs and twist in subs and plain != twist)
    check('⓷ᵇ both are order six and non-abelian, so no count and no isomorphism type can tell them '
          'apart -- only the ACTION can',
          len(plain) == len(twist) == 6
          and not all(mul(a, b) == mul(b, a) for a in twist for b in twist)
          and sorted(order(g) for g in plain) == sorted(order(g) for g in twist))
    check(f'⓷ᶜ so the dial has THREE readings inside Aut(A_2), not two: {len(subs)}',
          len(subs) == 3)

    # ============================================================ (4) P13 excludes it
    print()
    print('  ' + '=' * 74)
    print('  PART 4 -- ⌗ AND A SENTENCE ALREADY IN P13 EXCLUDES THE TWISTED ONE')
    print('  ' + '=' * 74)
    SENT = ('$\\sigma$ exchanges a pair \\emph{within} a sign-half')
    check(f'⓸ P13 says it: "{SENT}", while "the backward-radial reflection $r_0\\mapsto-r_0$---the '
          'outer $\\mathbb{Z}_2$---carries between the two-positive and two-negative halves"',
          SENT in B['P13']
          and 'carries between the two-positive and two-negative halves' in B['P13'])
    check('⛭ ⓸ᵇ *** a transposition that stays WITHIN a sign-half carries trivial Z_2 component, '
          'which is exactly the statement that the S_3 is S_3 × 1 and not the graph of the sign '
          'map -- so the twisted reading is excluded by a sentence written to defuse an apparent '
          'asymmetry in the 2+1 labelling ***',
          all(e == 0 for _, e in plain) and any(e == 1 for _, e in twist))
    check('⓸ᶜ and the exclusion is not circular: the sentence is about where σ moves a pair, and '
          'the group question is which Z_2-component σ carries -- the same fact, asked twice',
          SENT in B['P13'] and plain in subs)

    # ============================================================ (5) the instrument's false hole
    print()
    print('  ' + '=' * 74)
    print('  PART 5 -- ⛔⛭⛭ AND THE INSTRUMENT PRODUCED A FALSE HOLE ON ITSELF')
    print('  ' + '=' * 74)
    raw = sum(RB.counts('Aut(A_2)').values())
    dem = sum(RB.counts('Aut(A_2)', tex=True).values())
    check(f'⓹ a raw survey for `Aut(A_2)` returns {raw}; the de-macroed text has {dem}, across '
          f'{len([p for p, n in RB.counts("Aut(A_2)", tex=True).items() if n])} papers -- the corpus '
          'writes `\\mathrm{Aut}(A_2)` and the macro\'s closing brace splits the term',
          raw == 0 and dem > 30)
    check('⓹ᵇ ⇒ *** a count can fail to be about its term AT ALL -- the sharper case of "a count is '
          'not a verdict", produced by L-263\'s own instrument on L-263\'s own author ***',
          raw == 0 and dem > 0)
    check('⓹ᶜ and the instrument now runs every survey twice and FLAGS a term whose de-macroed '
          'count is higher',
          'DE-MACROED' in open(os.path.join(ROOT, 'corpus', 'reach_baseline.py'),
                               encoding='utf-8').read()
          and 'def demacro' in open(os.path.join(ROOT, 'corpus', 'reach_baseline.py'),
                                    encoding='utf-8').read())
    # ** the re-verification that matters: do the earlier stations survive the hardening? **
    survived = {t: (sum(RB.counts(t).values()), sum(RB.counts(t, tex=True).values()))
                for t in ('Fredholm', 'Jacobi', 'Atiyah sequence', 'adjoint bundle',
                          'exact sequence', 'Chevalley', 'principal bundle')}
    print(f'    stations Ⓖ/Ⓗ baselines, (raw, de-macroed): {survived}')
    # ** ⛭⛭⛭ RE-PINNED r3972.  THE QUESTION THIS ASKS IS *"WAS THE ZERO AN ARTEFACT?"*, AND THAT IS
    # ** NOT THE SAME QUESTION AS *"IS IT STILL ZERO?"* **  The hardening exists because a survey
    # ** for `Aut(A_2)` returned ZERO while the object appears ten times -- the corpus writes it
    # ** `\mathrm{Aut}(A_2)` and the macro's closing brace splits the term.  *** So the artefact
    # ** SIGNATURE is `raw == 0 while de-macroed > 0`, and that is what re-verifies a station. ***
    # ** Asserting the zeros persist instead makes the check fail the moment a station is ANSWERED,
    # ** which is what happened: Ⓖ's vocabulary landed at r3251 and Ⓗ's `Fredholm` at r3722.
    # **   ⇒ ** Both are asserted now: the signature is absent today for every term, at any count;
    # **     and the zeros themselves are pinned where they were measured, at this station's own
    # **     throw, which is where a baseline belongs. **
    _sig = {t: (r, d) for t, (r, d) in survived.items() if r == 0 and d > 0}
    check(f'⛭ ⓹ᵈ AND STATIONS Ⓖ AND Ⓗ SURVIVE IT: no term they rested on shows the artefact '
          f'signature -- a raw zero over a de-macroed non-zero -- in the live text, so neither '
          f'finding was a macro splitting a term: {len(_sig)} such term(s), {survived}',
          not _sig)
    _then = {t: (sum(_at_build_counts(t).values()), sum(_at_build_counts(t, tex=True).values()))
             for t in survived}
    check(f'⛭ ⓹ᵈ¹ and their baselines were REAL zeros when measured, raw AND de-macroed, at '
          f'{_AT_BUILD} -- this station\'s own close: {_then}',
          all(r == 0 and d == 0 for r, d in _then.values()))

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        for f in FAILED:
            print(f'    - {f[:150]}')
        return 1
    print('  VERDICT: ** the Z_6 acts.  It is the unique cyclic order-six subgroup of the corpus\'s')
    print('  own Aut(A_2), generated by the deck Z_3 and the chirality Z_2 -- the two data P14 says')
    print('  descend, as against the within-state Weyl S_3. **  *That closes the question M1 left:')
    print('  "nothing here exhibits an action".*')
    print('  ⛔ ** And the dial has THREE readings, not two: ** D_6 has exactly three order-six')
    print('     subgroups -- two isomorphic to S_3 and one cyclic -- and the two S_3\'s differ by')
    print('     whether a root transposition carries a chirality flip.  *No count and no isomorphism')
    print('     type can tell them apart; only the action can.*')
    print('  ⌗ ** A sentence already in P13 excludes the twisted one: ** σ exchanges a pair WITHIN a')
    print('     sign-half, which is exactly "σ carries trivial Z_2 component".  *Written to defuse')
    print('     an asymmetry in the 2+1 labelling; it settles a group question it was not asking.*')
    print('  ⛔ ** And this station forced a hardening: ** a survey for `Aut(A_2)` returned ZERO')
    print('     against thirty-four occurrences, because `\\mathrm{...}` splits the term.  *A count')
    print('     can fail to be about its term at all.*  Ⓖ and Ⓗ are re-verified and survive.')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
