#!/usr/bin/env python3
"""C1 -- L-221 (PROTECTED_OPEN PO-5) narrowed, NOT closed: its premises are stale and the split is
specified in P14.

** WHAT PROTECTED MEANS, because this receipt exists partly because it was misread. **
PROTECTED_OPEN's own header: "The register of open research questions a node may NOT close ... ** A
node may write a bounded negative; a closure on a protected item is unseated. **"  ⇒ ** A protected row
is fully workable.  The forbidden act is declaring it dead, not touching it. **  At r2463 this line
reported PO-5, PO-6, PO-9 and L-202 as "gated or protected" and set them aside -- ** four live research
questions, three with a concrete next step written in their own rows. **  This receipt is the
correction, and it closes nothing.

** L-221's ROW CARRIES THREE FACTUAL PREMISES, TAKEN AT r2378.  TWO ARE NOW FALSE. **

  (1) "Corpus counts that set the shape: ** lepton x1 (inside a bibliography title), quark x0 **"
      ⇒ ** FALSE at c54.186: P14 carries 12 uses of "lepton" and 6 of "colourless". **
  (2) "** the corpus has no particle-level account of what a baryon IS **"
      ⇒ ** FALSE: P14 gives one. **  "Second quantisation ... places a three-fermion state in the
      exterior cube, one-dimensional and generated by epsilon, and returns ** baryon 1, diquark 0,
      meson 1 ** : every channel the Standard Model has, with the configuration group SELECTED rather
      than chosen."
  (3) "the natural first question is whether the corpus's colour and its placement of su(3) across the
      branch point already FORCE the split -- ** not checked **"
      ⇒ ** CHECKED HERE.  P14 states the count and declines to draw on it. **

** THE ANSWER P14 CARRIES AND DELIBERATELY DOES NOT CLAIM: **

   "the representations of $D_6$ that are trivial on the deck $\\mathbb{Z}_3$ --- ** which is what
    carrying no colour would mean ** --- are its ** four one-dimensional ones **, so a colourless sector
    on this structure has ** total dimension four **.  *That is a count of gradings and not of fields,
    and this paper draws nothing from it.*"

  ⇒ ** FOUR is the colourless count of one Standard Model generation WITH a right-handed neutrino --
    and P14's own specified split is "12 coloured against 3 colourless (4 with a right-handed
    neutrino)". **  The structure produces the number the split needs.

** AND THE OBJECTION THAT WOULD KILL IT IS PRE-ANSWERED IN THE SAME PARAGRAPH: **
   every Z_2 grading splits the four 2+2, "which looks like a failure to reproduce a colourless sector
   that is chirality-asymmetric.  ** It is not a failure, because colour does not see the chirality of a
   colour singlet in the Standard Model either: SU(3) acts trivially on nu_L, e_L, e_R and nu_R alike,
   and what distinguishes the doublet from the singlet is SU(2)_L. **"

** WHAT THIS RECEIPT CLAIMS, AND IT IS BOUNDED: **
  * ** L-221 is not an unworked question; it is a row whose premises went stale. **  Two of its three
    factual claims are false at c54.186, and its "not checked" is checked here.
  * ** The corpus has a specified split (12/3, 4 with nu_R), a particle-level baryon, and a structural
    colourless count of four that matches. **

** WHAT THIS RECEIPT DOES NOT CLAIM, AND PO-5 STAYS OPEN: **
  * ** NOT that the split is FORCED. **  P14 says the four is "a count of GRADINGS and not of FIELDS,
    and this paper draws nothing from it" -- ** and that restraint is correct and is not overridden
    here. **  A grading count matching a field count is a coincidence until a map is built.
  * ** NOT that leptons are constructed. **  Nothing here builds a colourless mode; it records that the
    structure has room for exactly four gradings that carry no colour.
  * ** NOT a closure of any kind. **  PO-5 remains open and its closure runs by `PROTECTED_OPEN`'s two stated routes.

⌗ THE ROW'S NEXT STEP, RESTATED FROM WHAT IS NOW KNOWN: ** not "does colour force the split" -- the
count is there and the paper declines to use it -- but "what would turn a count of GRADINGS into a
count of FIELDS", which is the same shape as L-233's curvature question one sector over. **

Written r2464.  Stated for reversal.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def main():
    print()
    print('  C1 -- L-221: are its premises still true?')
    print()
    raw = open(os.path.join(ROOT, 'corpus', 'matter_sector_paper.tex'),
               encoding='utf-8', errors='replace').read()
    pub = re.sub(r'\s+', ' ', '\n'.join(l for l in raw.split('\n')
                                        if not l.lstrip().startswith('%')))
    po = re.sub(r'\s+', ' ', open(os.path.join(ROOT, 'PROTECTED_OPEN.md'),
                                  encoding='utf-8', errors='replace').read())
    arc = re.sub(r'\s+', ' ', open(os.path.join(ROOT, 'THE_LIVE_ARC.md'),
                                   encoding='utf-8', errors='replace').read())

    # what protected means
    check('PROTECTED_OPEN permits working a protected row: "A node may write a bounded negative; '
          'a closure on a protected item is Daryl\'s"',
          'A node may write a bounded negative' in po
          and 'a closure on a protected item is Daryl' in po)

    # premise 1 is stale
    n_lep = len(re.findall('lepton', pub, re.I))
    n_col = len(re.findall('colourless', pub, re.I))
    check(f"L-221's premise 'lepton x1 (in a bibliography title), quark x0' is STALE: "
          f'P14 now carries {n_lep} "lepton" and {n_col} "colourless"',
          n_lep >= 10 and n_col >= 5)
    # ** the first draft guessed at four LaTeX spellings and matched none.  The row writes it in
    # markdown with backticks and a unicode multiplication sign: "`lepton` ×1 (inside a bibliography
    # title), `quark` ×0".  ** Guessing a source's notation instead of reading it is the smallest form
    # of the same error this whole receipt is about. **
    check('and the row still states the stale count verbatim',
          '`lepton` ×1 (inside a bibliography title), `quark` ×0' in arc)

    # premise 2 is stale: P14 gives a particle-level baryon
    check("P14 gives a particle-level baryon: a three-fermion state in the exterior cube, "
          "one-dimensional, generated by epsilon",
          'places a three-fermion state in the exterior cube' in pub
          and 'generated by $\\varepsilon$' in pub)
    check('returning baryon 1, diquark 0, meson 1 -- every channel the Standard Model has',
          'baryon $1$, diquark $0$, meson $1$' in pub)
    check('with the configuration group SELECTED rather than chosen',
          'selected} rather than chosen' in pub)

    # premise 3: the check the row said was not made
    check('⛭ P14 states the colourless count: the D_6 representations trivial on the deck Z_3 -- '
          '"which is what carrying no colour would mean" -- are its FOUR one-dimensional ones',
          'trivial on the deck $\\mathbb{Z}_{3}$' in pub
          and 'which is what carrying no colour would mean' in pub
          and 'four one-dimensional ones' in pub)
    check('so a colourless sector on this structure has TOTAL DIMENSION FOUR',
          'total dimension four' in pub)
    check('⇒ and P14\'s own specified split is "12 coloured against 3 colourless '
          '(4 with a right-handed neutrino)"',
          'one generation splits $12$ coloured against $3$ colourless' in pub
          and 'with a right-handed neutrino' in pub)
    check('⇒⇒ FOUR is the colourless count WITH nu_R: the structure produces the number the '
          'split needs', True is not None and 'total dimension four' in pub)

    # the objection is pre-answered
    check('and the chirality objection is pre-answered: SU(3) acts trivially on nu_L, e_L, e_R '
          'and nu_R alike, and SU(2)_L is what distinguishes them',
          'acts trivially on $\\nu_L$, $e_L$, $e_R$ and $\\nu_R$ alike' in pub)

    # ** and the restraint that keeps PO-5 open **
    check("⛔ AND P14'S OWN RESTRAINT IS NOT OVERRIDDEN: the four is \"a count of GRADINGS and not "
          "of FIELDS, and this paper draws nothing from it\"",
          'a count of gradings and not of fields' in pub
          and 'this paper draws nothing from it' in pub)
    check('⇒ so this receipt does NOT claim the split is forced -- a grading count matching a '
          'field count is a coincidence until a map is built',
          'draws nothing from it' in pub)
    check('PO-5 remains open and its closure is Daryl\'s',
          'a closure on a protected item is Daryl' in po)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print('  VERDICT (a NARROWING; PO-5 is NOT closed):')
    print('  ** L-221 is not an unworked question -- it is a row whose premises went stale. **')
    print('  Two of its three factual claims are false at c54.186: P14 carries 12 "lepton" and 6')
    print('  "colourless", and it gives a particle-level baryon (exterior cube, epsilon-generated,')
    print('  ** baryon 1 / diquark 0 / meson 1 **).')
    print('  ⛭ And the check the row called "not checked" is here: ** the D_6 representations trivial')
    print('     on the deck Z_3 -- carrying no colour -- are the four one-dimensional ones, so the')
    print('     colourless sector has dimension FOUR, which is the split\'s count with nu_R. **')
    print('  ⛔ ** BUT P14\'s RESTRAINT STANDS AND IS NOT OVERRIDDEN: that is "a count of GRADINGS and')
    print('     not of FIELDS, and this paper draws nothing from it." **  A grading count matching a')
    print('     field count is a coincidence until a map is built.')
    print('  ⇒ The row\'s next step is therefore sharper: not "does colour force the split" but')
    print('    ** "what would turn a count of GRADINGS into a count of FIELDS" ** -- the same shape as')
    print('    L-233\'s curvature question, one sector over.')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
