#!/usr/bin/env python3
"""C2 -- PO-5's live question answered in form: a count of GRADINGS becomes a count of FIELDS by
being the KERNEL of an operator, and the unbuilt thing is an operator rather than a sector.

** PROTECTED_OPEN PO-5 (= L-221).  Worked and narrowed, NOT closed. **

** THE QUESTION, as r2464 restated it: ** not "does colour force the quark/lepton split" -- the
colourless count is there and P14 declines to use it -- but ** "what would turn a count of GRADINGS into
a count of FIELDS". **

** THE ANSWER IS IN THE CORPUS'S OWN PRACTICE, because the coloured side already made the crossing. **

  P14: "Second quantisation---the ordinary step, ** available because the three wall modes are one
  operator's KERNEL and therefore identical particles ** ---places a three-fermion state in the exterior
  cube, one-dimensional and generated by $\\varepsilon$, and returns baryon 1, diquark 0, meson 1."

  And what makes it a COUNT rather than a description: "that count is ** a well-defined INDEX ** in the
  precise sense the ontology makes available: in the leaf's proper measure the closed slicing has finite
  total length, so the leaf is compact and ** its Dirac operator carries a well-defined analytical
  index **."

  ⇒⇒ *** A COUNT OF GRADINGS BECOMES A COUNT OF FIELDS WHEN THE GRADINGS ARE THE KERNEL OF AN OPERATOR.
      Kernel ⇒ identical particles ⇒ second quantisation ⇒ fields.  That is the whole bridge, and the
      corpus crossed it once. ***

** ⛭ AND THE TWO SIDES ARE NOW EXACTLY DISTINGUISHED, which is what the row needed: **

      the coloured THREE   the INDEX of a Dirac operator on a compact leaf   -> has an operator -> FIELDS
      the colourless FOUR  the one-dimensional representations of $D_6$      -> no operator      -> GRADINGS
                           that are trivial on the deck $\\mathbb{Z}_3$

  ⇒ ** So P14's "that is a count of gradings and not of fields, and this paper draws nothing from it" is
    EXACTLY RIGHT, and now for a stated reason: the four are a representation-theoretic fact about a
    GROUP; the three are the kernel of SOMETHING. **

** ⛭⛭ AND IT NAMES WHAT P13 MEANS BY "REMAINS UNBUILT". **
P13: "The compact-face fermion sector the obstruction would act on ** remains unbuilt **, and its
construction is the major undertaking any geometric gauge-matter route would first have to complete."

  ⇒ *** THE UNBUILT THING IS AN OPERATOR, NOT A SECTOR. ***

  (r6931+70.1: DISCHARGED on the P13 side.  Since r6683 (73eb61ef) P13 no longer calls that sector
  unbuilt: sec:open specifies it -- a fermion on the compact face is an SU(4) spinor on the round S^5 --
  and finds it obstructed twice, the second obstruction being that the round face's Dirac operator has
  NO zero modes.  That is this reading carried out: the thing owed was an operator's kernel, and the
  operator was exhibited and its kernel is empty -- "the emptiness of a definite object".  The PO-5
  question below, about the COLOURLESS four, is a different operator and stays as stated.)

  ⇒ ** So PO-5's live question resolves into something buildable and sharply stated: IS THERE AN
    OPERATOR ON THIS STRUCTURE WHOSE KERNEL IS THE FOUR COLOURLESS GRADINGS? **  Not "can a colourless
    sector be built" -- ** can the operator whose index counts four be exhibited. **

WHAT IS NOT CLAIMED.  ** Nothing here builds such an operator, or argues that one exists. **  Not that
the four gradings are fields; ** they are not, and that is the point. **  Not that the coloured route
transfers: its operator is the leaf's Dirac operator and the colourless four are not obviously anything's
kernel.  ** Not a closure of PO-5 in any direction. **

⌗ THE ROUTE: this is the same move that answered L-233 -- ** ask what the corpus DID in the case that
worked, and read the licence it used ** -- rather than asking what might work in the case that has not.

Written r2476.  Stated for reversal.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def main():
    print()
    print('  C2 -- what turns a count of gradings into a count of fields?')
    print()
    p13 = re.sub(r'\s+', ' ', open(os.path.join(ROOT, 'corpus', 'boundary_paper.tex'),
                                   encoding='utf-8', errors='replace').read())
    p14 = re.sub(r'\s+', ' ', open(os.path.join(ROOT, 'corpus', 'matter_sector_paper.tex'),
                                   encoding='utf-8', errors='replace').read())
    po = re.sub(r'\s+', ' ', open(os.path.join(ROOT, 'PROTECTED_OPEN.md'),
                                  encoding='utf-8', errors='replace').read())

    check('a protected row may be worked and narrowed; only closure is reserved',
          'A node may write a bounded negative' in po)

    # ** the licence the coloured side used **
    check('⛭ P14 names the licence for second quantisation: the three wall modes are ONE OPERATOR\'S '
          'KERNEL and therefore identical particles',
          "the three wall modes are one operator's kernel and therefore identical particles" in p14)
    check('and that is what makes the count an INDEX: the leaf is compact and its Dirac operator '
          'carries a well-defined analytical index',
          's \\emph{finite} total length\\rcpt{P14_leaf_compactness}, so the leaf is compact and its Dirac operator carries a well-defined analytical index' in p14)
    check('⇒ so the coloured three cross to fields BECAUSE they are a kernel: '
          'kernel -> identical particles -> second quantisation -> fields',
          "e one operator's kernel" in p14 and 'Second quantisation' in p14)
    check('and the crossing delivers baryon 1, diquark 0, meson 1',
          'baryon $1$, diquark $0$, meson $1$' in p14)

    # ** and what the colourless four ARE **
    check('the colourless four are the one-dimensional representations of $D_6$ trivial on the '
          'deck $\\mathbb{Z}_3$',
          'trivial on the deck $\\mathbb{Z}_{3}$' in p14 and 'e its four one-dimensional ones' in p14)
    check('⛔ and P14 declines to draw on them, for a reason now stated: "that is a count of '
          'gradings and not of fields, and this paper draws nothing from it"',
          'a count of gradings and not of fields' in p14
          and 't of fields}, and this paper draws nothing from it' in p14)
    check('⇒⇒ THE DISTINCTION: the three are the KERNEL of something; the four are a '
          'representation-theoretic fact about a GROUP',
          "e one operator's kernel" in p14 and 'e its four one-dimensional ones' in p14)

    # ** and what P13's "unbuilt" means **
    # ** r6931+70.1: class (b), DISCHARGED.  These three checks pinned P13's "The compact-face fermion
    #   sector the obstruction would act on remains unbuilt, and its construction is the major
    #   undertaking any geometric gauge-matter route would first have to complete", which r6683
    #   (73eb61ef) replaced with "sec:open specifies that sector and finds it obstructed twice".  And
    #   the way P13 discharged it is THIS RECEIPT'S READING carried out: sec:open specifies the sector
    #   as a definite object -- a fermion on the compact face is an SU(4) spinor on the round S^5 -- and
    #   its second obstruction is a statement about that object's Dirac OPERATOR: "the round face
    #   carries no Dirac zero modes, so there is no massless content for it to act on", closing the
    #   squash and torsion evasions, so "what is definite is the emptiness of a definite object".  The
    #   unbuilt thing was an operator's kernel; P13 exhibited the operator and its kernel is empty.
    #   Re-pinning to the new wording alone would keep "unbuilt" alive past its answer, so the checks
    #   are re-pointed at what discharged it.  The PO-5 narrowing above is untouched by this. **
    check('P13 has since specified "the compact-face fermion sector the obstruction would act on": '
          '"that sector can be specified, and is obstructed twice" (was "remains unbuilt"; r6683)',
          'that sector can be specified, and is obstructed twice' in p13
          and 'remains unbuilt' not in p13)
    check('and the specified object is a definite spinor with a definite Dirac operator: "a fermion on '
          'the compact face is an SU(4) object", and "the round face carries no Dirac zero modes"',
          'a fermion on the compact face is an $\\SU(4)$ object' in p13
          and 'the round face carries no Dirac zero modes, so there is no massless content for it to act on' in p13)
    check('⇒ SO THE UNBUILT THING WAS AN OPERATOR\'S KERNEL, NOT A SECTOR -- and P13 discharged it by '
          'exhibiting the operator and finding the kernel empty: "the emptiness of a definite object"',
          "e one operator's kernel" in p14
          and 't evade the positive-curvature obstruction, so what is definite is the emptiness of a definite object' in p13)

    # ** and nothing is built here **
    check('⛔ and nothing here exhibits such an operator or argues one exists -- PO-5 stays open',
          'A node may write a bounded negative' in po)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print('  VERDICT (a NARROWING; PO-5 is NOT closed):')
    print('  ** A count of GRADINGS becomes a count of FIELDS when the gradings are the KERNEL of an')
    print('     operator. **  Kernel -> identical particles -> second quantisation -> fields, and the')
    print('  corpus crossed that bridge once: the coloured three are the INDEX of a Dirac operator on')
    print('  a compact leaf.')
    print('  ⇒ ** The colourless four are the one-dimensional representations of D_6 trivial on the')
    print('     deck Z_3 -- a fact about a GROUP, not the kernel of anything. **  So P14\'s "a count of')
    print('  gradings and not of fields" is exactly right, and now for a stated reason.')
    print('  ⛭⛭ AND IT NAMED WHAT P13\'s "REMAINS UNBUILT" MEANT: ** the unbuilt thing was an OPERATOR,')
    print('     not a sector ** -- and P13 has since discharged it that way: the face\'s Dirac operator is')
    print('     specified and has no zero modes, the emptiness of a definite object.')
    print('  ⇒ PO-5\'s live question is therefore buildable and sharply stated: ** is there an operator')
    print('    on this structure whose kernel is the four colourless gradings? **  Not "can a')
    print('    colourless sector be built" -- ** can the operator whose index counts four be')
    print('    exhibited. **')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
