#!/usr/bin/env python3
"""I8 -- L-174 (1)'s question answered structurally: NO sweep-subgroup reaches the unworked stratum,
the theorem is already stated for all of them, and the gap was never the operator's to fill.

** WHERE r2512 LEFT IT. **  The unworked stratum's free data is TWO functions -- the graviton's
transverse polarizations, sigma^TT -- and cor:radiation says a sweep cannot carry them: "** a swept
geometry depends only on its orbit-space coordinates while a free wave depends on the transverse
coordinates through which it propagates **", and "** a sweep generates a deformation of FIXED
ORIENTATION **".

** ⓵ THE QUESTION THAT PROMPTED THIS, AND THE READING BEHIND IT WAS WRONG. **  "A sweep, singular" and
"a deformation of fixed orientation" read as a statement about ONE sweep -- and the construction carries
THREE hinges (P3: "the substrate in fact carries three such hinges, 120 degrees apart at transverse
distance 2 alpha").  ** So: does composing sweeps about several orientations produce the transverse
dependence a free wave needs? **

** ⛭⛭ ⓶ THE THEOREM IS ALREADY STATED FOR ALL OF THEM. **  thm:bound:

  "Let a geometry be generated by the operator: a lower-dimensional slicing object on the de Sitter
   substrate, swept or reassigned by ** a subgroup H of so(4,1) ** of the substrate's isometries.  Then
   the generated geometry is ** invariant under H **.  Consequently every geometry in the range of the
   operator carries an isometry group containing a sweep-subgroup of so, and the range is contained in
   the symmetry-reducible sector."

  and the proof is one line: "** the induced metric is constant along those orbits BY CONSTRUCTION **, so
  H acts by isometries of the generated geometry."

  ⇒ ** H is ANY subgroup, of any dimension, including one generated by several sweeps.  The reading of
    "a sweep, singular" was wrong. **

** ⇒⇒ ⓷ AND COMPOSING SWEEPS MAKES IT WORSE, NOT BETTER. **

  ** A larger H means MORE isometry, so the generated geometry sits FURTHER INSIDE the symmetry-reducible
  sector, not closer to the wall. **  The wall is "the loss of ALL confining symmetry"; more sweeps
  supply more confining symmetry.
  ⇒ *** The three hinges cannot help.  They would give a bigger H. ***
  ⇒ *** SO NOTHING INSIDE THE OPERATOR REACHES THE STRATUM -- not one sweep, not three, not any subgroup.
      The wall is not a limitation of a particular construction: IT IS A THEOREM ABOUT THE OPERATOR. ***

** ⌗ ⓸ AND THAT IS WHAT P9 ALREADY SAYS THE CORPUS DOES. **  cor:wall: the radiative degrees of freedom
beyond the wall "** are carried past it by the ordinary general-relativistic evolution **… the wall a
** regular boundary of the operator's reach and not a frontier of the theory **."

  ⇒ *** THE CONSTRUCTION GENERATES THE INITIAL DATA; ORDINARY GR EVOLVES IT PAST THE WALL.  THE
      TWO-FUNCTION GAP WAS NEVER THE OPERATOR'S TO FILL. ***
  ⇒ ** So L-174 (1) is not "make the operator reach further".  It is: EXHIBIT the ordinary evolution of
    data with sigma^TT != 0, which is a GR calculation and not a construction question. **  That is a
    smaller and different task than the row has ever stated.

WHAT IS NOT CLAIMED.  ** Not that the exhibition is done ** -- nothing here evolves anything.  ** Not
that thm:bound is a theorem in the strongest sense **: P9 itself marks the surrounding readings as "what
is computed and what is the reading the computations support", and this receipt asserts only what
thm:bound and its proof state.  Not that a sweep-subgroup could not be found for some geometry nobody
has tried: ** the point is that IF one exists the geometry is not beyond the wall, by the theorem. **

Written r2513.  Stated for reversal.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def pub(f):
    raw = open(os.path.join(ROOT, 'corpus', f), encoding='utf-8', errors='replace').read()
    return re.sub(r'\s+', ' ', '\n'.join(l for l in raw.split('\n')
                                         if not l.lstrip().startswith('%')))


def main():
    print()
    print('  I8 -- can any sweep-subgroup reach the unworked stratum?')
    print()
    p9 = pub('range_paper.tex')
    p3 = pub('SdS-slicing-curve_v2.tex')

    # ⓵ the reading that prompted it
    check('cor:radiation says a swept geometry depends only on its orbit-space coordinates while a '
          'free wave depends on the transverse coordinates',
          'a swept geometry depends only on its orbit-space coordinates while a free wave depends on '
          'the transverse coordinates' in p9)
    check('and that a sweep generates a deformation of FIXED orientation',
          'a sweep generates a deformation of \\emph{fixed} orientation' in p9)
    check('while P3 records that the substrate carries THREE hinges, 120 degrees apart',
          'three such hinges' in p3)

    # ⓶ the theorem covers all H
    check('⛭ thm:bound is stated for A SUBGROUP $H\\subseteq\\so$ -- any subgroup, any dimension',
          'swept or reassigned by a subgroup $H\\subseteq\\so$' in p9)
    check('and concludes the generated geometry is INVARIANT UNDER $H$',
          'Then the generated geometry is invariant under $H$' in p9)
    check('with a one-line proof: the induced metric is constant along those orbits BY CONSTRUCTION',
          'the induced metric is constant along those orbits by construction' in p9)
    check('⇒ so the reading of "a sweep, singular" was wrong -- the theorem already quantifies over '
          'every sweep-subgroup',
          'swept or reassigned by a subgroup $H\\subseteq\\so$' in p9)

    # ⓷ composing makes it worse
    check('the wall is the loss of ALL confining symmetry',
          'only the loss of all confining symmetry frees' in p9)
    check('⇒⇒ SO A LARGER $H$ MEANS MORE ISOMETRY, hence FURTHER INSIDE the symmetry-reducible sector '
          '-- composing sweeps moves AWAY from the wall',
          'the range is contained in the symmetry-reducible sector' in p9
          and 'only the loss of all confining symmetry frees' in p9)
    check('⇒ and a geometry with no continuous isometry "is not of this form"',
          'A geometry with no continuous isometry, or whose isometry group contains no '
          '$\\so$-subgroup acting as a sweep, is not of this form' in p9)

    # ⓸ and what the corpus already says
    check('⌗ cor:wall: the beyond-wall modes are carried past it by the ordinary '
          'general-relativistic evolution',
          'are carried past it by the ordinary general-relativistic evolution' in p9)
    check('with the wall "a regular boundary of the operator\'s reach and not a frontier of the theory"',
          "a regular boundary of the operator's reach and not a frontier of the theory" in p9)
    check('⇒⇒ SO THE TWO-FUNCTION GAP WAS NEVER THE OPERATOR\'S TO FILL: the construction generates '
          'the data, ordinary GR evolves it past the wall',
          'are carried past it by the ordinary general-relativistic evolution' in p9
          and 'swept or reassigned by a subgroup $H\\subseteq\\so$' in p9)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print('  VERDICT: ** no sweep-subgroup reaches the stratum, and the theorem already says so. **')
    print('  thm:bound quantifies over ** A SUBGROUP H of so(4,1) -- any subgroup, any dimension **, and')
    print('  concludes the geometry is invariant under H, by a one-line proof: the induced metric is')
    print('  constant along the orbits BY CONSTRUCTION.')
    print('  ⇒ ** So "a sweep, singular" was a misreading.  And composing sweeps makes it WORSE: a')
    print('     larger H is MORE isometry, hence further inside the symmetry-reducible sector, while')
    print('     the wall is the loss of ALL confining symmetry.  The three hinges cannot help. **')
    print('  ⇒⇒ ** The wall is not a limitation of a particular construction.  It is a theorem about')
    print('     the operator. **')
    print('  ⌗ And cor:wall already says what fills the gap: ** the beyond-wall modes are carried past')
    print('    it by ORDINARY GR EVOLUTION, the wall "a regular boundary of the operator\'s reach and')
    print('    not a frontier of the theory". **')
    print('  ⇒ So L-174 (1) is not "make the operator reach further".  It is ** exhibit the ordinary')
    print('    evolution of data with sigma^TT != 0 -- a GR calculation, not a construction question. **')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
