"""X4-REDONE — what is actually left once P2 is read.
P2 prop:Kretschmann ALREADY: K(z) has a TWELFTH-ORDER POLE at z=pi, 'generated by the chain rule applied
to the composition at a non-degenerate critical point of r(z)'; bounded at z=0.
So the POLE classification and its MECHANISM are the corpus's.  What is NOT stated anywhere is the
exclusion of an ESSENTIAL singularity -- which is what makes 'a branch point, not a barrier' an ANALYTIC
statement and not only a geometric one.  That exclusion is the whole of what survives here.

ORIGIN: storyboard_receipts/X4r_no_essential_singularity.py -- registered r2376 (c54); edit the origin, not this copy."""
import numpy as np, sympy as sp
z,M,t,al = sp.symbols('z M tau alpha', positive=True)

print("="*78); print("X4-REDONE — THE ONLY THING P2 DOES NOT ALREADY SAY"); print("="*78)

print("\nSTEP 1 — confirm P2's own statement in P2's own variable, so the audit is honest.")
r = M*(1+sp.cos(z)); K = 48*M**2/r**6
eps=sp.symbols('epsilon', positive=True)
lead = sp.limit(K.subs(z, sp.pi-eps)*eps**12, eps, 0)
print("   lim_{eps->0} K(pi-eps) . eps^12 =", sp.simplify(lead), " (finite and nonzero => order exactly 12)")
print("   and eps^11 test:", sp.limit(K.subs(z, sp.pi-eps)*eps**11, eps, 0), "(diverges => not order 11)")
print("   => leading term ~ eps^(-12): a TWELFTH-ORDER pole.  P2 prop:Kretschmann, verified.")
print(f"   and at z=0:  K = {sp.simplify(K.subs(z,0))}  -- finite.  P2, verified.")

print("\nSTEP 2 — THE EXCLUSION, which is the new content.  Are there essential singularities?")
print("   In P2's variable: r(z) = M(1+cos z) is ENTIRE; K(z) = 48/(M^4 (1+cos z)^6) is therefore")
print("   MEROMORPHIC on the whole finite z-plane -- its only singularities are the poles where")
print("   cos z = -1, i.e. z = pi + 2k.pi.  No essential singularity anywhere in the finite plane.")
sols=sp.solve(sp.cos(z)+1, z)
print(f"     poles at cos z = -1:  z = {sols} + 2k.pi")
print("   In P3's bead variable: r^3 = 2M a^2 sinh^2(3 tau/2a) with sinh ENTIRE, so r(tau)'s only")
print("   finite-plane singularities are the algebraic branch points where sinh vanishes.")
for k in range(3):
    print(f"     sinh(3 tau/2a) = 0 at tau = {k}.(2 i pi a/3)  -> r ~ (tau-tau_k)^(2/3), order-3 branch")
print("   No poles of r, no essential points.")

print("\nSTEP 3 — WHY THE EXCLUSION IS THE LOAD-BEARING PART.")
print("   A POLE continues as a map to the Riemann sphere.  A FINITE-ORDER BRANCH POINT continues")
print("   onto a cover.  AN ESSENTIAL SINGULARITY CONTINUES AS NEITHER -- by Picard's theorem the")
print("   function takes every value infinitely often in any neighbourhood, and nothing whatever")
print("   can be said of the values beyond it.")
print("   So P2's 'chain-rule artefact' and P3/P7's 'a branch point, not a barrier' are ANALYTIC")
print("   statements and not merely geometric ones PRECISELY BECAUSE the singularity is of finite")
print("   order in both senses -- and that is the fact the corpus had not recorded.")
print("\n" + "="*78)
print("RESULT X4-REDONE:  P2 prop:Kretschmann already classifies the divergence as a finite-order")
print("  POLE and already gives its mechanism (the chain rule at a non-degenerate critical point).")
print("  The r1870 claim that 'the corpus asserts both and never says they are compatible' was")
print("  WRONG -- P2's chain-rule reading IS the compatibility statement, in the corpus's own terms.")
print("  WHAT SURVIVES, and it is one sentence: NO ESSENTIAL SINGULARITY IS PRESENT in the finite")
print("  plane, in either parametrisation -- which is what makes 'not a barrier' analytic.")
print("="*78)

# =====================================================================
# ** THE BEAD PARAMETRISATION, COMPUTED (r2376+c54.157). **
#
# ** WHY. **  The receipt-vs-sentence pass found P7 citing this file for "the exclusion holds in
# BOTH parametrisations: r(z) = M(1+cos z) AND sinh are entire, so the invariant is meromorphic
# and the bead's radius carries only ALGEBRAIC branch points -- no essential singularity anywhere
# in the finite plane."  Of that sentence this file computed the pole ORDER of the Schwarzschild
# invariant in the cycloid variable -- which the same sentence credits to the companion paper --
# and nothing else.  The sinh half had no computation at all: the symbols tau and alpha were
# declared and never used, numpy was imported and never used, and the branch-point statement was
# a loop over range(3) inside an f-string.  ** It is computed here. **
import sympy as _sp

_tau, _eps = _sp.symbols('tau epsilon', positive=True)
_al = _sp.Symbol('alpha', positive=True)
_M = _sp.Symbol('M', positive=True)
print()
print("=" * 78)
print("THE BEAD RADIUS: ALGEBRAIC BRANCH POINTS, AND NOTHING ELSE")
print("=" * 78)
_fail4 = []

# r^3 = 2 M alpha^2 sinh^2(3 tau / 2 alpha) -- the bead law, cubed to keep it polynomial in r
_S = _sp.sinh(3 * _tau / (2 * _al))
_r3 = 2 * _M * _al**2 * _S**2
print("  r(tau)^3 = 2 M alpha^2 sinh^2(3 tau / 2 alpha)")

# (i) the CUBE is entire: sinh is entire, so r^3 is entire, so r^3 has NO singularity at all --
#     finite or essential.  Every singular point of r is therefore a BRANCH point of the cube
#     root, and a cube root has only algebraic branch points.
_z = _sp.Symbol('zeta')
_ser = _sp.series(_r3.subs(_tau, _z), _z, 0, 8).removeO()
print(f"  its Taylor series about tau = 0 begins {_sp.simplify(_ser)}")
if _ser.has(1 / _z) or _ser.has(_sp.log(_z)):
    _fail4.append("r^3 is not entire at tau = 0")

# (ii) the zeros of sinh(3 tau / 2 alpha) are tau_k = 2 pi i alpha k / 3, all SIMPLE, so sinh^2
#      -- and with it r^3 -- has a DOUBLE zero there, and r ~ (tau - tau_k)^(2/3): an algebraic
#      branch point of order three.  ** The first draft of this check asserted a SIMPLE zero of
#      r^3 and fired; sinh is squared in the bead law, which is exactly why the exponent is 2/3
#      and not 1/3.  Recorded because the assertion is what caught it. **
_w = _sp.Symbol('w')
# sinh(3(tau_k + w)/2alpha) = sinh(i pi k + 3w/2alpha) = (-1)^k sinh(3w/2alpha), so the SQUARE is
# the same function of w at every k.  Verified as an identity rather than assumed, then expanded.
print(f"\n  {'k':>3} {'tau_k':>22} {'shift identity holds':>22}")
for _k in (1, 2, 3):
    _tk = 2 * _sp.pi * _sp.I * _al * _k / 3
    _id = _sp.simplify(_sp.expand(_sp.expand_trig(
        _sp.sinh(3 * (_tk + _w) / (2 * _al))**2 - _sp.sinh(3 * _w / (2 * _al))**2)))
    print(f"  {_k:>3} {str(_tk):>22} {str(_id == 0):>22}")
    if _id != 0:
        _fail4.append(f"the shift identity fails at k={_k}: {_id}")
_shift = 2 * _M * _al**2 * _sp.sinh(3 * _w / (2 * _al))**2
_ser_k = _sp.expand(_sp.series(_shift, _w, 0, 6).removeO())
_pol = _sp.Poly(_ser_k, _w)
_ord = min(m[0] for m in _pol.monoms())
_lead_k = _sp.simplify(_pol.coeff_monomial(_w**_ord))
print(f"\n  r^3(tau_k + w) = {_sp.simplify(_ser_k)} + O(w^6)")
print(f"  order of the zero: {_ord}      leading coefficient: {_lead_k}")
if _ord != 2:
    _fail4.append(f"r^3 has a zero of order {_ord} at every tau_k, expected 2")
if _sp.simplify(_lead_k - 9 * _M / 2) != 0:
    _fail4.append(f"leading coefficient is {_lead_k}, expected 9M/2")

# (iii) so r = (r^3)^(1/3) ~ (9M/2)^(1/3) (tau - tau_k)^(2/3): the exponent is 2/3 exactly, an
#       ALGEBRAIC branch point, and 2/3 is not an integer so it is a genuine branch rather than
#       a removable point.
print("\n  r^3 ~ (9M/2)(tau - tau_k)^2  =>  r ~ (9M/2)^(1/3) (tau - tau_k)^(2/3)")
print("  ** 2/3 is not an integer, so the point is a genuine ALGEBRAIC branch point of order 3. **")

# (iv) THE EXCLUSION ITSELF.  An essential singularity is a point at which no finite power makes
#      the function bounded.  Here r^3 is entire, so for EVERY finite tau_0 some finite power of
#      (tau - tau_0) bounds r^3 -- namely the zeroth.  Exhibited at a generic point and at a zero:
_t1 = 2 * _sp.pi * _sp.I * _al / 3
for _lbl, _t0 in [("a generic point", _al), ("a branch point", _t1)]:
    _lim = _sp.simplify(_r3.subs(_tau, _t0))
    print(f"  r^3 at {_lbl:>16}: value = {_lim}  -- FINITE")
    if _lim.has(_sp.oo) or _lim.has(_sp.zoo) or _lim.has(_sp.nan):
        _fail4.append(f"r^3 unbounded at {_lbl}")
print()
print("  ⇒ ** r^3 IS ENTIRE, SO IT HAS NO ESSENTIAL SINGULARITY IN THE FINITE PLANE, AND EVERY")
print("     SINGULAR POINT OF r IS A CUBE-ROOT BRANCH POINT -- ALGEBRAIC BY CONSTRUCTION. **")
print("     *That is the sinh half of the paper's 'both parametrisations', and it had no")
print("     computation behind it until c54.157.*")

# (v) and the cycloid half, asserted rather than printed: r(z) = M(1+cos z) is entire, so the
#     invariant 48 M^2/r^6 is MEROMORPHIC -- poles only, at the zeros of r.
_zz = _sp.Symbol('zz')
_rc = _M * (1 + _sp.cos(_zz))
_Kc = 48 * _M**2 / _rc**6
_lead12 = _sp.simplify(_sp.limit(_Kc.subs(_zz, _sp.pi + _eps) * _eps**12, _eps, 0))
print(f"\n  cycloid: lim K(pi+eps) eps^12 = {_lead12}   -- a POLE of order 12, not an essential point")
if _sp.simplify(_lead12 - 3072 / _M**4) != 0:
    _fail4.append(f"the order-12 coefficient is {_lead12}, not 3072/M^4")
assert not _fail4, "; ".join(_fail4)
print("\n  CHECKS PASS — both parametrisations, and the exclusion is now computed rather than typed.")
