#!/usr/bin/env python3
"""build_fork_span.py -- ARC 14 step 5.  Give CORPUS_MAP an honest record of the c54 fork span
by COPYING the commit subjects out of FORK_HISTORY_c54.txt, verbatim.

The problem it solves: CORPUS_MAP carries ONE `### Revision` entry for the c54 fork (c54.10)
against 108 advances.  The four-step state advance requires a log entry per advance and nothing
FAILED when it was skipped.

What this does NOT do, deliberately: reconstruct narrative changelog entries.  A changelog is the
one grain where a claim and its later correction sit in the same record; synthesising 76 entries
out of the register would be inventing that record, and an invented record is worse than a gap
because it reads as evidence.  What exists and was written at the time is FORK_HISTORY_c54.txt --
one line per revision, by the node that did the work, on the day.  Those lines are copied over
verbatim and MARKED AS COMMIT SUBJECTS, at the weight they actually carry.

    python3 scripts/build_fork_span.py            # insert/refresh the fork-span section
    python3 scripts/build_fork_span.py --check    # exit 1 if the section is missing or behind

Written r2377.  Stated for reversal.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
MAP = os.path.join(ROOT, 'CORPUS_MAP.md')
HIST = os.path.join(ROOT, 'FORK_HISTORY_c54.txt')

BEGIN = '<!-- FORK-SPAN c54 BEGIN -- generated by scripts/build_fork_span.py; do not hand-edit -->'
END = '<!-- FORK-SPAN c54 END -->'
ROW = re.compile(r'^([0-9a-f]{7,40})\s+(\d{4}-\d\d-\d\d)\s+r2376\+c54\.([0-9]+[a-z]?)\s+—\s*(.*)$')


def read_history():
    rows = []
    if not os.path.exists(HIST):
        return rows
    for line in open(HIST, encoding='utf-8', errors='replace').read().split('\n'):
        m = ROW.match(line.strip())
        if m:
            rows.append((m.group(1)[:8], m.group(2), m.group(3), m.group(4).strip()))
    # oldest first, so it reads as a log
    def key(r):
        n = re.match(r'(\d+)', r[2])
        return (int(n.group(1)) if n else 0, r[2])
    return sorted(rows, key=key)


def logged_revisions():
    """Which c54 revisions already have a real `### Revision` entry in CORPUS_MAP."""
    t = open(MAP, encoding='utf-8', errors='replace').read()
    body = t.split(BEGIN)[0]
    return set(re.findall(r'^### Revision r2376\+c54\.([0-9]+[a-z]?)', body, re.M))


def render(rows, already):
    covered = sorted({r[2] for r in rows})
    nums = [int(re.match(r'(\d+)', c).group(1)) for c in covered]
    out = [BEGIN, '']
    out.append('---')
    out.append('')
    out.append('## ⌗⌗ THE c54 FORK SPAN — the commit record, copied over, NOT a changelog')
    out.append('')
    out.append(f'*Generated r2377 by `scripts/build_fork_span.py` from `FORK_HISTORY_c54.txt`. '
               f'**{len(rows)} revisions, c54.{min(nums)}–c54.{max(nums)}.***')
    out.append('')
    out.append('> **⚠ READ THIS AT ITS OWN WEIGHT, WHICH IS NOT A CHANGELOG\'S.** *This changelog '
               'carried **one** `### Revision` entry for the c54 fork — `c54.10` — against **108 '
               'advances**. The four-step state advance requires a log entry per advance and '
               '**nothing failed when it was skipped**, so 76 revisions of work went unlogged and '
               '`check_currency` could not say so (its baseline was `FORK_c54.md`, which had itself '
               'stopped at c54.35).*\n>\n> ***The gap is NOT filled by reconstruction, and that is '
               'deliberate.*** *A changelog is the one grain where a claim and its later correction '
               'sit in the same record; synthesising narrative entries out of the register would be '
               '**inventing** that record, and an invented record is worse than a gap because it '
               'reads as evidence. **What exists, written at the time by the node that did the work, '
               'is the commit subject line.** Those are copied here verbatim, marked as what they '
               'are.*\n>\n> **What a commit subject IS:** *one sentence, contemporaneous, naming the '
               'result and usually the lead it struck.* **What it is NOT:** *the reasoning, the '
               'alternatives considered, the corrections applied later. **For any of those, the '
               'source is the paper, the receipt, or the lead register row** — this table is an '
               'index into them, not a substitute.*')
    out.append('')
    if already:
        out.append(f'*⌗ **{len(already)} of these already carry a full `### Revision` entry above** '
                   f'({", ".join("c54." + a for a in sorted(already))}) — those rows are marked '
                   f'`◆` and the full entry is the source.*')
        out.append('')
    out.append('| rev | date | commit | subject (verbatim) |')
    out.append('|---|---|---|---|')
    for sha, date, rev, subj in rows:
        mark = '◆ ' if rev in already else ''
        subj = subj.replace('|', '\\|')
        out.append(f'| {mark}**c54.{rev}** | {date} | `{sha}` | {subj} |')
    out.append('')
    missing = sorted(set(range(min(nums), max(nums) + 1)) - set(nums))
    if missing:
        out.append(f'> **⌗ NOT IN THE COMMIT RECORD EITHER: {len(missing)} revision number(s) in '
                   f'this span have no commit row** — `{", ".join("c54." + str(m) for m in missing)}`. '
                   f'*Stated rather than smoothed over: they were either folded into a neighbouring '
                   f'commit or not committed separately. **The register (`THE_LIVE_ARC`) is the place '
                   f'to look for what happened at those numbers**, and its rows carry their own '
                   f'revision markers.*')
        out.append('')
    tail = max(nums)
    out.append(f'> **⚠ AND THE COMMIT RECORD ITSELF STOPS AT c54.{tail}** *while the fork front is '
               f'further on — see `check_currency`. The revisions past c54.{tail} are in the register '
               f'and in the papers and are **not** in any log. **Re-run this script after the fork '
               f'history is brought forward.***')
    out.append('')
    out.append(END)
    return '\n'.join(out)


def main():
    rows = read_history()
    if not rows:
        print('  [FAIL] no commit rows parsed from FORK_HISTORY_c54.txt')
        return 1
    already = logged_revisions()
    section = render(rows, already)
    t = open(MAP, encoding='utf-8', errors='replace').read()
    if '--check' in sys.argv:
        if BEGIN not in t:
            print('  [FAIL] CORPUS_MAP carries no fork-span section'); return 1
        cur = t.split(BEGIN)[1].split(END)[0]
        newest = rows[-1][2]
        if f'**c54.{newest}**' not in cur:
            print(f'  [FAIL] fork-span section is behind the commit record (newest c54.{newest})')
            return 1
        print(f'  fork-span current: {len(rows)} revisions to c54.{newest}')
        return 0
    if BEGIN in t:
        pre, rest = t.split(BEGIN, 1)
        post = rest.split(END, 1)[1] if END in rest else ''
        t = pre + section + post
    else:
        t = t.rstrip() + '\n\n' + section + '\n'
    open(MAP, 'w', encoding='utf-8').write(t)
    print(f'  wrote fork-span into CORPUS_MAP: {len(rows)} commit rows, '
          f'c54.{rows[0][2]}–c54.{rows[-1][2]}; {len(already)} already have full entries')
    return 0


if __name__ == '__main__':
    sys.exit(main())
