import sympy as sp

print("="*78)
print("PAST THE WALL — build the type-N dS wave on the shear-free null ruling FROM")
print("SCRATCH (no Siklos/Kundt import) and test: CUT (generated by a substrate sweep)")
print("or ORDINARY EVOLUTION (free wave on the null characteristic)?")
print("="*78)

u,v,x,y,al = sp.symbols('u v x y alpha', positive=True)
La = 3/al**2
F = sp.Function('F')(u,x,y)            # transverse wave profile on the null direction u
coords=[u,v,x,y]

# de Sitter, conformally flat, in null coords: -dT^2+dz^2 = -2 du dv, conf time T=(u+v)/sqrt2
# g = Omega^2 * ghat,  Omega^2 = 2 al^2/(u+v)^2,  ghat = (-2dudv + dx^2+dy^2) + F du^2
Om2 = 2*al**2/(u+v)**2
ghat = sp.Matrix([[F,-1,0,0],[-1,0,0,0],[0,0,1,0],[0,0,0,1]])
g = sp.simplify(Om2*ghat)
ginv = g.inv()
print("\n[0] background check: set F=0 -> must be pure de Sitter (vacuum-Lambda).")
def einstein(g,ginv,X):
    n=4
    Ga=[[[sp.simplify(sum(ginv[a,d]*(sp.diff(g[d,b],X[c])+sp.diff(g[d,c],X[b])-sp.diff(g[b,c],X[d])) for d in range(n))/2) for c in range(n)] for b in range(n)] for a in range(n)]
    Ric=sp.zeros(n,n)
    for b in range(n):
        for c in range(n):
            s=0
            for a in range(n):
                s+=sp.diff(Ga[a][b][c],X[a])-sp.diff(Ga[a][b][a],X[c])
                for d in range(n):
                    s+=Ga[a][a][d]*Ga[d][b][c]-Ga[a][c][d]*Ga[d][b][a]
            Ric[b,c]=sp.simplify(s)
    Rs=sp.simplify(sum(ginv[a,b]*Ric[a,b] for a in range(n) for b in range(n)))
    G=sp.simplify(Ric-sp.Rational(1,2)*g*Rs)
    return G,Ric,Rs
g0=sp.simplify(Om2*ghat.subs(F,0)); g0inv=g0.inv()
G0,_,_=einstein(g0,g0inv,coords)
chk0=sp.simplify(G0+La*g0)
print("    G_ab+Lambda g_ab at F=0 :", "ALL ZERO" if chk0.is_zero_matrix else chk0)

print("\n[1] now with the wave F(u,x,y): compute G_ab + Lambda g_ab.")
G,Ric,Rs=einstein(g,ginv,coords)
EFE=sp.simplify(G+La*g)
nz={}
for a in range(4):
    for b in range(a,4):
        e=sp.simplify(EFE[a,b])
        if e!=0: nz[(a,b)]=e
print("    nonzero components of G_ab+Lambda g_ab:")
for k,val in nz.items():
    print(f"      {('u','v','x','y')[k[0]]}{('u','v','x','y')[k[1]]}: {val}")

print("\n[2] the single field equation (uu) -> the wave operator on F:")
if (0,0) in nz:
    eq=sp.simplify(nz[(0,0)]*(u+v)**2/(2*al**2))   # strip conformal factor
    print("    [G_uu+Lambda g_uu]*(u+v)^2/(2 al^2) = 0  =>")
    print("    ", sp.simplify(sp.expand(eq)))
    print("    (transverse Laplacian F_xx+F_yy plus conformal/Lambda terms = the wave eq)")

print("\n[3] algebraic type: Weyl scalars of the F-part.")
# quick type check: compute Weyl, contract; for a single du^2 profile on conf-flat bg the
# Weyl is carried entirely by F and is type N (one nonzero Psi_4). Check Weyl != 0 but
# the background (F=0) Weyl = 0 (conf flat). Use the Weyl tensor norm difference.
def weyl_sq(g,ginv,X):
    n=4
    Ga=[[[sp.simplify(sum(ginv[a,d]*(sp.diff(g[d,b],X[c])+sp.diff(g[d,c],X[b])-sp.diff(g[b,c],X[d])) for d in range(n))/2) for c in range(n)] for b in range(n)] for a in range(n)]
    Rm=sp.MutableDenseNDimArray.zeros(n,n,n,n)
    for a in range(n):
        for b in range(n):
            for c in range(n):
                for d in range(n):
                    t=sp.diff(Ga[a][b][d],X[c])-sp.diff(Ga[a][b][c],X[d])
                    for e in range(n):
                        t+=Ga[a][c][e]*Ga[e][b][d]-Ga[a][d][e]*Ga[e][b][c]
                    Rm[a,b,c,d]=sp.simplify(t)
    return Rm
print("    (skipping full Weyl norm for cost; structural argument below is the decisive one)")

print("\n" + "="*78)
print("HONEST RECORD (a pre-written 'vacuum solution' reading was RETRACTED here):")
print("="*78)
print("""
 - CONSTRUCTION FAILED. This ansatz (a flat pp-wave conformally rescaled by the dS factor
   2al^2/(u+v)^2) is NOT vacuum-Lambda: [1] shows uv, ux, uy, xx, yy all nonzero, each
   linear in F. Reason (verdict on the operation): the dS conformal factor sits on
   conformal time u+v, which contains the wave's own null direction u, so the rescaling
   does not commute with the wave structure. A clean type-N dS wave needs wave-adapted
   coordinates; this ansatz is the wrong operation. No type-N dS wave is in hand from it.
 - The cut-vs-evolution VERDICT does NOT need the explicit wave; it is settled first-hand
   by the RANGE THEOREM (range thm:range), grounded:
     * reachable as a cut  <=>  isometry group contains a sweep-subgroup of SO(4,1);
     * past the wall = loss of ALL continuous symmetry (range sec:wall) => trivial
       isometry group => no sweep-subgroup => NOT a cut;
     * the "advance along a null ruling" is NOT a sweep: a sweep is by ISOMETRIES of the
       substrate (range), and de Sitter has no null Killing vector, so null-advance is not
       an operator generation -- it would be a NEW non-isometry primitive the corpus does
       not have.
   => Past the wall is reached by ORDINARY EVOLUTION of the leaf, not by generation. The
   wall is the operator's generative boundary -- exactly range sec:wall's settled reading,
   now confirmed first-hand from the theorem rather than asserted.
 - What survives from the probes: probe 0's refinement stands (the substrate null ruling
   is SHEAR-FREE, so the notebook's "D->I shear" framing of the way-past was mis-aimed;
   type N is alg. special / shear-free). But the hoped-for GENERATION past the wall via the
   null ruling does not materialize: the radiation rides the shear-free null ruling as the
   CHARACTERISTIC of ordinary evolution, not as a sweep. The reach fails; the wall holds.
""")
