#!/usr/bin/env python3
"""regen_map_status.py -- give OPEN_PROBLEMS_MAP a GENERATED status front, read from the register.

** THE TASK WAS NOT WHAT ITS DESCRIPTION SAID, and that is worth recording here rather than
quietly working around. **  It was queued as "OPEN_PROBLEMS_MAP's status column as a generated
view."  Read at source: THE MAP HAS NO STATUS COLUMN.  It is 152 KB of narrative -- ten clusters
whose item states are embedded in prose annotations accreted from r544 to c54.108
("[ADVANCED, NOT resolved -- r565: ...]", "**Open.**", "TWO RESIDUES NOW CONVERGE HERE"), plus
three sort sections (the priority axis, the readiness/dependency sort, the runway) that nothing
else carries.  The "status column" was my paraphrase of the file's description field.  Fifth time
in this audit that a description has misdescribed its document.

** SO THE BUILD IS DIFFERENT FROM THE ONE QUEUED, and it is the one the file can actually take. **
The map became a VIEW of the lead register at c54.90 -- "a new item enters the register first and
appears here as a view of it, never the other way round."  What it lacked was any mechanism making
that true.  This generates a status front: for every map code the register carries, the register's
own verdict.  The clusters, the priority axis and the runway stay hand-written, because they are
the only place that content exists and they are not state -- they are judgement about ordering.

** WHY A FRONT RATHER THAN A REWRITE. **  Rewriting the cluster prose would destroy the accreted
reasoning -- the "two residues converge here" notes are findings, not status.  A generated front
cannot drift, and it sits where a reader arrives, so the narrative below can never silently
contradict what is open.  The map keeps what only it has; the register keeps what it is the source
of.

    python3 scripts/regen_map_status.py            # write/refresh the block
    python3 scripts/regen_map_status.py --check     # exit 1 if the block is missing or behind

Written r2383.  Stated for reversal.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..'))
MAP = os.path.join(ROOT, 'OPEN_PROBLEMS_MAP.md')
ARC = os.path.join(ROOT, 'THE_LIVE_ARC.md')

BEGIN = '<!-- MAP-STATUS BEGIN -- generated by scripts/regen_map_status.py; do not hand-edit -->'
END = '<!-- MAP-STATUS END -->'

CLUSTER_NAME = {
    'A': 'the matter sector', 'B': 'the quantum completion',
    'C': 'structural-completion computations', 'D': 'perspectival reframing',
    'E': "the cosmology's empirical edges", 'F': 'the inherited boundary data',
    'G': 'empirical-coherence motivation', 'H': 'corpus-wide refinement',
    'I': 'the P7/P13 split', 'J': 'the conjugacy / quantum-germ frontier',
}


def read(p):
    return open(p, encoding='utf-8', errors='replace').read()


def register():
    """map code -> (lead id, struck?, state cell, first 200 chars of the verdict)."""
    t = read(ARC)
    out = {}
    for ln in t.split('\n'):
        m = re.match(r'^\|\s*(~~)?\*{0,2}(L-\d+)\*{0,2}(~~)?\s*\|(.*)$', ln)
        if not m:
            continue
        struck, lid, rest = bool(m.group(1)), m.group(2), m.group(4)
        cells = [c.strip().rstrip('|').strip() for c in rest.split(' | ')]
        origin = cells[1] if len(cells) > 1 else ''
        state = cells[3] if len(cells) > 3 else ''
        body = cells[0] if cells else ''
        for code in re.findall(r'\b([A-J])·(\d+)\b', origin):
            out[f'{code[0]}·{code[1]}'] = (lid, struck, state, body)
    return out


def front(t):
    rs = [int(x) for x in re.findall(r'c54\.(\d+)', t)]
    return max(rs) if rs else 0


def render(reg, fr):
    by_cluster = {}
    for code, v in reg.items():
        by_cluster.setdefault(code[0], []).append((code, v))
    o = [BEGIN, '']
    o.append('## ⌗⌗ THE REGISTER\'S VERDICT ON EVERY FOLDED CODE — generated')
    o.append('')
    o.append(f'*Generated by `scripts/regen_map_status.py` from `THE_LIVE_ARC.md` at fork front '
             f'**c54.{fr}**. **Do not hand-edit.***')
    o.append('')
    o.append('> **⌗ WHY THIS BLOCK EXISTS, AND WHY IT IS A FRONT RATHER THAN A REWRITE (r2383).**')
    o.append('> *This map became a **view** of the lead register at c54.90 — "a new item enters the '
             'register first and appears here as a view of it, never the other way round" — and '
             '**nothing made that true**. Its item states live in prose annotations accreted from '
             'r544 to c54.108, so the map and the register could disagree silently across 152 KB.*')
    o.append('> ⌗ ***The cluster prose below is NOT regenerated, deliberately.*** *Notes like "two '
             'residues now converge here" are **findings**, not status, and the priority axis, the '
             'readiness sort and the runway exist nowhere else. **The map keeps what only it has; '
             'the register keeps what it is the source of.***')
    o.append('> ⚠ *And the queued task was "the status column as a generated view."* ***There is no '
             'status column.*** *That was the file\'s `description:` field paraphrased — the fifth '
             'time in this audit a description has misdescribed its document. The build had to '
             'change to the one the file can actually take.*')
    o.append('')
    live = [c for c, v in reg.items() if not v[1]]
    struck = [c for c, v in reg.items() if v[1]]
    o.append(f'**{len(reg)} folded codes — {len(struck)} struck, {len(live)} live.**')
    o.append('')
    for cl in sorted(by_cluster):
        rows = sorted(by_cluster[cl], key=lambda r: int(r[0].split('·')[1]))
        nlive = sum(1 for _, v in rows if not v[1])
        head = (f'### Cluster {cl} — {CLUSTER_NAME.get(cl, "")} — '
                f'{len(rows)} folded, **{nlive} live**')
        o.append(head)
        o.append('')
        o.append('| map code | register | state | the register\'s verdict, first line |')
        o.append('|---|---|---|---|')
        for code, (lid, st, state, body) in rows:
            verdict = re.sub(r'\s+', ' ', re.sub(r'[*`~⌗⇒⚑⚠✔⌫★⛭⛔⟐⌖]', '', body)).strip()[:170]
            o.append(f'| **{code}** | {"~~" + lid + "~~" if st else "**" + lid + "**"} | '
                     f'{"✔ struck" if st else (state or "open")} | {verdict}… |')
        o.append('')
    # r2383: run the footer's own check rather than only stating it.  The first run reported nine
    # codes present in the clusters and absent from this block; eight are closed at source (C·1, C·2
    # closed before the fold; C·6 computed r964 and does not cap; D·1 absorbed; I·1-I·4 struck) and
    # ONE -- A·1 -- was a genuine fold miss, now L-207.  ** A footer that says "look for this" and
    # does not look is a footer. **
    body = read(MAP).split(END)[-1] if END in read(MAP) else ''
    incluster = {f'{a}·{b}' for a, b in re.findall(r'\b([A-J])·(\d+)\b', body)}
    absent = sorted(incluster - set(reg))
    KNOWN_CLOSED = {'C·1', 'C·2', 'C·6', 'D·1', 'I·1', 'I·2', 'I·3', 'I·4'}
    unaccounted = [c for c in absent if c not in KNOWN_CLOSED]
    o.append(f'> **⌗ THE FOLD-MISS CHECK, RUN: {len(absent)} code(s) appear in the clusters and not '
             f'above.** *{len(absent) - len(unaccounted)} are accounted closed at source — `C·1`/`C·2` '
             f'closed before the fold, `C·6` computed r964 ("it does NOT cap"), `D·1` absorbed into '
             f'`D·2`, `I·1`–`I·4` struck.* '
             + (f'⛔ ***{len(unaccounted)} UNACCOUNTED: '
                + ', '.join(f'`{c}`' for c in unaccounted)
                + ' — read each at source; an unaccounted live code is a fold miss.***'
                if unaccounted else
                '✔ ***None unaccounted.*** *`A·1` was the one genuine miss and is now `L-207`.*'))
    o.append('>')
    o.append('> **⌗ A CODE ABSENT FROM THIS BLOCK IS A CODE THE REGISTER DOES NOT CARRY.** *At c54.90 '
             'twenty-seven live items were folded; codes closed before the fold were "correctly left '
             'in place" and are not here. **If a live item appears in the clusters below and not in '
             'this block, that is a fold miss and a finding** — it is how `A·5`, `B·1`, `B·2` and '
             '`G·1` were caught at c54.115–116, having never been folded despite the map\'s header '
             'saying every live item was.*')
    o.append('')
    o.append(END)
    return '\n'.join(o)


def main():
    reg = register()
    if not reg:
        print('  [FAIL] no map codes found in the register')
        return 1
    t = read(MAP)
    fr = max(front(t), front(read(ARC)))
    block = render(reg, fr)
    if '--check' in sys.argv:
        if BEGIN not in t:
            print('  [FAIL] OPEN_PROBLEMS_MAP carries no generated status block')
            return 1
        cur = t.split(BEGIN)[1].split(END)[0]
        live = sum(1 for v in reg.values() if not v[1])
        want = f'**{len(reg)} folded codes — {len(reg) - live} struck, {live} live.**'
        if want not in cur:
            print(f'  [FAIL] status block is behind the register ({len(reg)} codes, {live} live)')
            return 1
        print(f'  map status current: {len(reg)} folded codes, {live} live')
        return 0
    if BEGIN in t:
        pre, rest = t.split(BEGIN, 1)
        post = rest.split(END, 1)[1] if END in rest else ''
        t = pre + block + post
    else:
        anchor = '\n## The items, by work-cluster'
        i = t.find(anchor)
        t = (t[:i] + '\n\n' + block + '\n' + t[i:]) if i > 0 else (t.rstrip() + '\n\n' + block + '\n')
    open(MAP, 'w', encoding='utf-8').write(t)
    live = sum(1 for v in reg.values() if not v[1])
    print(f'  wrote OPEN_PROBLEMS_MAP status block: {len(reg)} folded codes, {live} live, '
          f'front c54.{fr}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
