#!/usr/bin/env python3
"""regen_frontier.py -- writes THE_FRONTIER.md: the one board Daryl reads every turn.

** WHAT IT IS FOR. **  *** Ten open problems, in dependency order, each with: what it is, how many steps
to close, where it stood LAST revision, whether its runway is clear, and what must be cleared first.
** The overall and the breakdown, on one screen. ** ***

** THE ESTIMATES ARE STORED HERE AND EDITED BY HAND ** -- *** they are judgements, not measurements, and
the file records them so the CHANGE is visible turn to turn.  A step is one worked result, not one turn;
turns-per-step is the separate estimate. ***

    python3 scripts/regen_frontier.py
"""
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
OUT = os.path.join(ROOT, 'THE_FRONTIER.md')

# ** id: (short name, steps-left, steps-last-revision, turns-per-step, gate, runway note) **
EST = {
 'PO-11': ('the propagating spinor sector', 3, 3, 3, None,
           'cc54 building the omega!=0 continuum; the +/-lambda reproduction is the hard step'),
 'PO-5':  ('quark/lepton split; the five multiplets', 2, 2, 4, 'PO-11',
           'four of five coupling routes closed; the fifth needs a propagating sector to compose from'),
 'PO-2':  ('Nariai / three quarks', 1, 1, 2, 'PO-5',
           'levels 1 and 2 done; level 3 is the identification and follows PO-5'),
 'PO-1c': ('does uud have a geometric counterpart', 1, 2, 1, None,
           'CLEAR -- the horn is established; one count to run'),
 'PO-1b': ('the SIGN 2+1', 1, 2, 2, None,
           'CLEAR -- sign(r) IS species and the parity link is established; one type-check to finish'),
 'PO-1a': ('the DESIGNATION 2+1', 2, 2, 3, None,
           'CLEAR but unsourced -- nothing derives the flavour indexical from the geometry'),
 'PO-1d': ('the causal 2+1 on three hinges', 0, 1, 0, 'PO-1c',
           'classification COMPLETE; open only as PO-1c\'s candidate'),
 'PO-6':  ('the interacting tower', 2, 3, 3, None,
           'CLEAR -- reduced r2838 to ONE commutator at higher order'),
 'PO-7':  ('the first acoustic peak', 3, 2, 3, None,
           'CLEAR and SHARPEST -- a structural departure from P15 own claim, mechanism eliminated r2840'),
 'PO-10': ('the scalar remainder', 1, 2, 1, None,
           'CLEAR -- read M2\'s own bound to settle whether half 1 is answered'),
}
# ** turns since the last discovery that the problem space was misunderstood, and what it was **
SINCE = 0
LASTFIND = ("r2841: `PO-7`'s deficit was ALREADY ESTABLISHED and phase-robust — B3's scan gives "
            "'0.79 ± 0.04 of ℓ_A across every phase, AND NEVER 1.0', a ~21% deficit. But L-830's "
            "pin test gives 0.856, which sits OUTSIDE that band. Two runs, one name, different "
            "numbers.")

ORDER = ['PO-11', 'PO-5', 'PO-2', 'PO-1c', 'PO-1d', 'PO-1b', 'PO-1a', 'PO-6', 'PO-7', 'PO-10']
GROUP = {'PO-11': 'A', 'PO-5': 'A', 'PO-2': 'A',
         'PO-1c': 'B', 'PO-1d': 'B', 'PO-1b': 'B', 'PO-1a': 'B',
         'PO-6': 'C', 'PO-7': 'D', 'PO-10': 'D'}
GNAME = {'A': 'THE CHAIN — one unbuilt sector, two consequences. Strictly ordered.',
         'B': 'THE 2+1 CLUSTER — four readings of two splits. Independent of A.',
         'C': 'THE QUANTUM SECTOR — independent.',
         'D': 'COSMOLOGY — independent, and the only group confronted with data.'}


def main():
    raw = open(os.path.join(ROOT, 'PROTECTED_OPEN.md'), encoding='utf-8', errors='replace').read()
    live = set()
    for line in raw.split('\n'):
        m = re.match(r'\|\s*(~~)?\s*\*\*(PO-\d+[a-z]?)\*\*', line)
        if m and not (m.group(1) or line.lstrip('|').lstrip().startswith('~~')):
            live.add(m.group(2))

    steps = sum(EST[p][1] for p in ORDER if p in live)
    was = sum(EST[p][2] for p in ORDER if p in live)
    turns = sum(EST[p][1] * EST[p][3] for p in ORDER if p in live)

    L = []
    L.append('# ▣ THE FRONTIER\n')
    L.append('*Generated by `scripts/regen_frontier.py`. **Ten open problems, in dependency order.** '
             'A STEP is one worked result; turns-per-step is a separate estimate.*\n')
    L.append(f'## ⇒ **{len(live)} OPEN · {steps} STEPS LEFT** *(was {was} last revision)* '
             f'**· ~{turns} turns at current estimates**\n')
    blocked = [p for p in ORDER if p in live and EST[p][4]]
    # ** r2839, Daryl: the number to hold is TURNS SINCE WE LAST DISCOVERED WE DID NOT KNOW
    # THE PROBLEM SPACE.  *** 0 means the last turn found a misunderstanding -- which is what
    # fixing the problem FUNDAMENTALLY looks like, as against advancing a step incrementally.
    # It is guidance for CHOOSING a turn: pick the row held least well, not the row nearest
    # closing. ***
    L.append(f'## ⇒ **TURNS SINCE WE LAST FOUND WE DID NOT KNOW THE PROBLEM SPACE: '
             f'{SINCE}**\n')
    if SINCE == 0:
        L.append(f'*⌗ **{LASTFIND}***\n')
    else:
        L.append('*⚠ **Above 0 means the last turn advanced a step without learning the space. '
                 'Pick the row held LEAST well next, not the one nearest closing.***\n')
    L.append(f'**RUNWAY: {len(live)-len(blocked)} of {len(live)} clear now**; '
             f'{len(blocked)} gated ({", ".join(f"{p}→{EST[p][4]}" for p in blocked)}).\n')

    for g in ('A', 'B', 'C', 'D'):
        L.append(f'\n### {g} · {GNAME[g]}\n')
        L.append('| id | what it is | steps | was | turns/step | gate | runway |')
        L.append('|---|---|---|---|---|---|---|')
        for p in ORDER:
            if GROUP[p] != g or p not in live:
                continue
            name, s, w, t, gate, note = EST[p]
            arrow = '' if s == w else (f' ↓{w-s}' if s < w else f' ↑{s-w}')
            L.append(f'| **{p}** | {name} | **{s}**{arrow} | {w} | {t} | '
                     f'{gate or "—"} | {note} |')

    L.append('\n---\n')
    L.append('*⌗ Steps and turn-estimates are judgements recorded so their CHANGE is visible. '
             'They are edited in `scripts/regen_frontier.py`, never here.*')
    open(OUT, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    print(f'  THE_FRONTIER.md written: {len(live)} open, {steps} steps (was {was}), ~{turns} turns')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
