#!/usr/bin/env python3
"""regen_teed_up.py -- regenerate WHATS_TEED_UP.md from THE_LIVE_ARC.md's lead register.

WHATS_TEED_UP's own frontmatter says it is "regenerated by parsing THE_LIVE_ARC each turn",
and nothing did the parsing: it was regenerated by hand at c54.65 and not again.  By c54.108
it listed 44 leads, ALL FORTY-FOUR OF THEM STRUCK, and none of the 14 actually open -- a
working queue exactly inverted.  A stale card misinforms a node; a stale queue DISPATCHES one.

The arc's register rows are the source of truth:
    | **L-NNN** | ... |     a live lead
    | ~~L-NNN~~ | ... |     a struck lead
This reads them and writes the queue.  Run it whenever the register moves.

    python3 scripts/regen_teed_up.py            # rewrite WHATS_TEED_UP.md
    python3 scripts/regen_teed_up.py --check    # exit 1 if the queue is out of date

Written r2377.  Stated for reversal.
"""
import os, re, sys, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
ARC = os.path.join(ROOT, 'THE_LIVE_ARC.md')
QUEUE = os.path.join(ROOT, 'WHATS_TEED_UP.md')

LIVE = re.compile(r'^\| \*\*(L-\d+)\*\* \|(.*)$')


def clean(s):
    """Strip markdown emphasis and the register's marker glyphs; leave LaTeX alone."""
    s = re.sub(r'[⌗⇒⚑⚠✔⌫★⛭⛔⟐⌖]', '', s)
    s = re.sub(r'\*+', '', s)
    s = re.sub(r'~~', '', s)
    return re.sub(r'\s+', ' ', s).strip()
STRUCK = re.compile(r'^\| ~~(L-\d+)~~ \|')
# r2381: HELD is a first-class state and is listed FIRST.  A row Daryl has deliberately held is not
# "open work nobody has got to" -- treating it as OPEN invites a node to re-raise a question that is
# already answered, which is the manufactured-decision-point failure arriving from the register side.
# r2385: OBSERVED is a row this line MEASURED and the working fork is WORKING.  It is not our work
# and must not be picked up: duplicating the fork's live edge is the prime directive's first refusal.
STATE_WORDS = ('HELD', 'OBSERVED', 'QUEUED', 'DARYL', 'HOT', 'GATED', 'PART', 'OPEN')


def read_arc():
    """Return (live, struck) where live is [(id, opening_text, state)]."""
    live, struck = [], []
    for line in open(ARC, encoding='utf-8', errors='replace').read().split('\n'):
        m = STRUCK.match(line)
        if m:
            struck.append(m.group(1))
            continue
        m = LIVE.match(line)
        if not m:
            continue
        lead, rest = m.group(1), m.group(2)
        cells = [c.strip().rstrip('|').strip() for c in rest.split(' | ')]
        # register columns are: lead-text | origin | first move | state
        body = cells[0] if cells else ''
        origin = cells[1] if len(cells) > 1 else ''
        move = cells[2] if len(cells) > 2 else ''
        state_cell = cells[3] if len(cells) > 3 else ''
        # r2381: `kind` was assigned INSIDE the state loop, so it took whatever the last iteration
        # left and carried over from the previous row when the loop broke early.  ** A variable
        # assigned inside a loop that breaks is a variable whose value depends on the data, not on
        # the logic. **  Caught by the printed counts: 28 WORK where the register has 27, and the
        # HELD section never rendering.  Both computed outside the loop now.
        kind = 'WORK' if 'KIND:WORK' in state_cell.upper() else 'QUESTION'
        state = ''
        for w in STATE_WORDS:
            if re.search(r'\b' + w + r'\b', state_cell.upper()):
                state = w
                break
        live.append((lead, clean(body), state, clean(origin), clean(move), kind))
    return live, struck


def render(live, struck, fork_rev):
    """r2378: THE QUEUE MUST PARTITION BY KIND, and this is a defect I shipped before fixing.

    The r2378 fold put 24 `kind:WORK` rows (CONSOLIDATE's arcs and §13's phases) into the register.
    They are genuinely open work, so this generator counted them -- and the queue went from 11 items
    to 35 UNDIFFERENTIATED ones.  ** That is the r2377 queue inversion in a new costume: **  a view
    that misinforms the node reading it about what is owed.  check_burndown was scoped by kind the
    same revision and the scoping was not carried here.

    So: two tables, questions first, and the counts stated separately.  A QUESTION is a thing to
    answer; a WORK row is a programme with steps whose content lives in CONSOLIDATE.  A node opening
    this file to pick up work needs to know which it is looking at before it reads a word of the row.
    """
    # r2382: QUEUED sorts after the open work and before HELD.  A queued row is not "not started" --
    # its whole apparatus is assembled and named in THE_STAGED_REVISIONS, and the row says where.
    order = {'HOT': 0, 'DARYL': 1, 'PART': 2, 'OPEN': 3, 'GATED': 4, 'QUEUED': 6, 'OBSERVED': 7, 'HELD': 9, '': 5}
    ques = sorted([r for r in live if r[5] == 'QUESTION'],
                  key=lambda r: (order.get(r[2], 5), int(r[0][2:])))
    work = sorted([r for r in live if r[5] == 'WORK'], key=lambda r: int(r[0][2:]))
    out = []
    out.append('---')
    out.append('name: whats-teed-up')
    out.append('kind: VIEW')
    out.append(f'current: {fork_rev.split("+")[-1]}')
    out.append('description: The working queue — every open lead, partitioned into QUESTIONS and '
               'WORK, regenerated by parsing THE_LIVE_ARC. Run scripts/regen_teed_up.py; do not '
               'hand-edit.')
    out.append('sources: [cowork]')
    out.append('---')
    out.append('')
    out.append("# WHAT'S TEED UP")
    out.append(f'*Regenerated {fork_rev} by `scripts/regen_teed_up.py`. **Do not hand-edit** — the '
               f'register in `THE_LIVE_ARC.md` is the source of truth and this file is a view of it.*')
    out.append('')
    held = [r for r in ques if r[2] == 'HELD']
    obs = [r for r in ques if r[2] == 'OBSERVED']
    ques = [r for r in ques if r[2] not in ('HELD', 'OBSERVED')]
    out.append(f'**{len(ques)} open QUESTIONS · {len(work)} open WORK rows'
               + (f' · {len(obs)} OBSERVED' if obs else '')
               + (f' · {len(held)} HELD' if held else '') + '** '
               f'*({len(struck)} struck of {len(live) + len(struck)} registered).*')
    out.append('')
    out.append('> **⌗ THE TWO KINDS, AND WHY THEY ARE NOT ONE LIST.** *A **QUESTION** is a thing to '
               'answer, and the register\'s gates are built for it — `check_supersession` scores it '
               'against 268 receipts, `check_kills` bars closing it. A **WORK** row is a programme '
               'with steps (`CONSOLIDATE`\'s arcs and §13\'s phases, folded r2378 so nothing owed is '
               'strewn about); its content lives in `CONSOLIDATE` and its freshness is gated by '
               '`corpus/check_arcs.py`. **Pick up a question by reading the row; pick up work by '
               'reading its section.***')
    out.append('')
    out.append('> **⚠ THIS PARTITION WAS ADDED AFTER THE FOLD SHIPPED WITHOUT IT (r2379).** *For one '
               'revision this file read **35 undifferentiated items** where it had read 11 — the '
               'fold counted correctly and the view did not distinguish. **That is the r2377 queue '
               'inversion in a new costume**: a view that misinforms the node reading it about what '
               'is owed. `check_burndown` was scoped by kind the same revision and the scoping was '
               'not carried here.*')
    out.append('')
    out.append('## ⌗ QUESTIONS — things to answer')
    out.append('')
    if ques:
        out.append('| lead | state | what it is | origin | first move |')
        out.append('|---|---|---|---|---|')
        for lead, text, state, origin, move, _ in ques:
            snippet = text[:260] + ('…' if len(text) > 260 else '')
            mv = move[:150] + ('…' if len(move) > 150 else '')
            out.append(f'| **`{lead}`** | {state or "—"} | {snippet} | {origin} | {mv} |')
    else:
        out.append('*(none open)*')
    out.append('')
    if obs:
        out.append('## 👁 OBSERVED — measured here, being worked by the FORK')
        out.append('')
        out.append('*Not this line\'s work. **Do not pick these up** — duplicating the working '
                   'fork\'s live edge is the prime directive\'s first refusal (`ARC 15`). What comes '
                   'back is the fork\'s correction, by absorption.*')
        out.append('')
        out.append('| lead | what was measured | what this line does |')
        out.append('|---|---|---|')
        for lead, text, state, origin, move, _ in sorted(obs, key=lambda r: int(r[0][2:])):
            out.append(f'| **`{lead}`** | {text[:220]}… | {move[:160]} |')
        out.append('')
    if held:
        out.append('## ⏸ HELD BY DARYL — answered, not waiting')
        out.append('')
        out.append('*A held row is **not** open work nobody has got to. The call was made, and it was made '
                   '**held**. **Do not re-raise it as a question** — that is a manufactured decision point '
                   'arriving from the register side.*')
        out.append('')
        out.append('| lead | what it is | why it is held |')
        out.append('|---|---|---|')
        for lead, text, state, origin, move, _ in sorted(held, key=lambda r: int(r[0][2:])):
            out.append(f'| **`{lead}`** | {text[:200]}… | {move[:200]} |')
        out.append('')
    out.append('## ⌗ WORK — programmes with steps; the content lives in `CONSOLIDATE`')
    out.append('')
    out.append('*Not picked up by reading a row. **Read the section**, and note that '
               '`check_arcs.py` reports which of these carry a dated position and which are '
               '`DECLARED-UNDATED` — an honest gap, not a closed one.*')
    out.append('')
    if work:
        out.append('| lead | source section | what it is |')
        out.append('|---|---|---|')
        for lead, text, state, origin, move, _ in work:
            snippet = text[:200] + ('…' if len(text) > 200 else '')
            out.append(f'| **`{lead}`** | {origin} | {snippet} |')
    else:
        out.append('*(none open)*')
    out.append('')
    return '\n'.join(out) + '\n'


def main():
    live, struck = read_arc()
    revs = [int(x) for x in re.findall(r'c54\.(\d+)',
            open(ARC, encoding='utf-8', errors='replace').read())]
    fork_rev = f'r2376+c54.{max(revs)}' if revs else 'unknown'
    text = render(live, struck, fork_rev)
    if '--check' in sys.argv:
        cur = open(QUEUE, encoding='utf-8', errors='replace').read() if os.path.exists(QUEUE) else ''
        listed = set(re.findall(r'\*\*`(L-\d+)`\*\*', cur))
        want = {r[0] for r in live}
        # r2379: the id-set check alone PASSED while the file mixed the two kinds into one list,
        # because every id was present and none extra.  ** A set check cannot see a structure
        # defect. **  So the partition is checked too: the two headings must exist and the counts
        # in the file must match the register's counts per kind.
        # r2381: HELD rows are QUESTIONS by kind but are reported separately, so the header states
        # the OPEN question count and not the kind count.  The first version of this check compared
        # against the kind count and failed on a file it had just written -- ** a check that fails on
        # its own generator's output is checking the wrong invariant. **
        nheld = len([r for r in live if r[5] == 'QUESTION' and r[2] == 'HELD'])
        nobs = len([r for r in live if r[5] == 'QUESTION' and r[2] == 'OBSERVED'])
        nq = len([r for r in live if r[5] == 'QUESTION']) - nheld - nobs
        nw = len([r for r in live if r[5] == 'WORK'])
        structural = []
        if '## ⌗ QUESTIONS' not in cur or '## ⌗ WORK' not in cur:
            structural.append('the QUESTIONS/WORK partition is missing')
        want_hdr = (f'**{nq} open QUESTIONS · {nw} open WORK rows'
                    + (f' · {nobs} OBSERVED' if nobs else '')
                    + (f' · {nheld} HELD' if nheld else '') + '**')
        if want_hdr not in cur:
            structural.append(f'the header does not state {nq} QUESTIONS, {nw} WORK'
                              + (f' and {nheld} HELD' if nheld else ''))
        if nheld and '## ⏸ HELD BY DARYL' not in cur:
            structural.append('HELD rows exist but the file has no HELD section')
        if listed == want and not structural:
            print(f'  queue current: {nq} QUESTIONS + {nw} WORK'
                  + (f' + {nobs} OBSERVED' if nobs else '')
                  + (f' + {nheld} HELD' if nheld else ''))
            return 0
        for x in structural:
            print(f'  [FAIL] {x}')
        print(f'  [FAIL] queue out of date — lists {len(listed)}, register has {len(want)} open')
        if listed - want:
            print(f'    listed but STRUCK: {", ".join(sorted(listed - want, key=lambda s: int(s[2:])))}')
        if want - listed:
            print(f'    open but MISSING:  {", ".join(sorted(want - listed, key=lambda s: int(s[2:])))}')
        return 1
    open(QUEUE, 'w', encoding='utf-8').write(text)
    print(f'  wrote {QUEUE}: {len(live)} open, {len(struck)} struck, at {fork_rev}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
