"""
P05_deck_group_S3.py -- verifies: the between-member morphisms of the horizon cubic form a three-sheeted
  branched cover whose DECK GROUP is S3 -- the monodromy about each Nariai branch point is the transposition
  of the two colliding roots (prop:monodromy), the two independent transpositions GENERATE S3 (prop:deck),
  equivalently the Galois group of the cubic over C(2M) (rem:galois); and with the orientation Z2 (R) it
  assembles to the full solution-space symmetry S3xZ2=D6 (sec:classification). [P5 groupoid_paper sec:deck, sec:classification]
STATUS: ✔✔   RUN: python3 P05_deck_group_S3.py   RUNTIME: ~3s
COMPUTES: analytic continuation of the roots of r^3 - r + 2M = 0 around each Nariai value 2M*=±2/(3 sqrt3),
  tracked by nearest-neighbour matching over phi:0->2pi, giving the permutation (a transposition of the pair
  that collides there, third fixed); the group generated by the two transpositions (= S3, order 6); and the
  discriminant 4 - 27(2M)^2, not a square in C(2M), fixing the Galois group as S3 not A3.
  CONTROL: continuing around a NON-branch (generic) 2M returns the identity permutation (no monodromy).
ORIGIN: built new r1350 (uncited P5 claim).
"""
import numpy as np, itertools
def check(t,c): print(f"  [{'PASS' if c else 'FAIL'}] {t}"); return bool(c)
ok=True
S3 = np.sqrt(3); twoMstar = 2/(3*S3)
def track_monodromy(branch, base=0.0j, R=0.12, n=9000):
    """Monodromy about a branch point, read in the COMMON labelling at `base`: loop base->near branch->
    circle it (radius R)->back, tracking the 3 roots by continuity; return the permutation of base roots."""
    ang0 = np.angle((base - branch)) if abs(base-branch)>0 else 0.0
    appr = branch + R*np.exp(1j*ang0)                       # point on the circle nearest base
    leg1 = base + (appr-base)*np.linspace(0,1,n//3)
    leg2 = branch + R*np.exp(1j*np.linspace(ang0, ang0+2*np.pi, n//3))
    leg3 = appr + (base-appr)*np.linspace(0,1,n//3)
    path = np.concatenate([leg1, leg2, leg3])
    labels = np.roots([1,0,-1, path[0]])                   # labels[i] = current location of base-root i
    for z in path[1:]:
        nr=np.roots([1,0,-1, z]); used=[False]*3; new=[None]*3
        for i in range(3):
            j=min((k for k in range(3) if not used[k]), key=lambda k: abs(nr[k]-labels[i]))
            used[j]=True; new[i]=nr[j]
        labels=np.array(new)
    start=np.roots([1,0,-1, path[0]])
    return tuple(min(range(3), key=lambda k: abs(start[k]-labels[i])) for i in range(3))
print("="*70); print("P05 deck group S3: monodromy of the horizon cubic's three-sheeted cover"); print("="*70)
# prop:monodromy -- around +Nariai: a transposition (2-cycle), one root fixed
p_plus = track_monodromy(twoMstar)
n_moved = sum(1 for i in range(3) if p_plus[i]!=i)
ok&=check(f"prop:monodromy: around +Nariai 2M*=+2/(3sqrt3), monodromy perm={p_plus} is a TRANSPOSITION (2 moved, 1 fixed)",
          n_moved==2)
p_minus = track_monodromy(-twoMstar)
ok&=check(f"around -Nariai 2M*=-2/(3sqrt3): also a transposition perm={p_minus}", sum(1 for i in range(3) if p_minus[i]!=i)==2)
# prop:deck -- the two transpositions generate S3 (order 6)
def perm_mul(a,b): return tuple(a[b[i]] for i in range(3))
gens=[p_plus, p_minus]; grp={(0,1,2)}
frontier=list(gens)
while frontier:
    g=frontier.pop()
    if g not in grp:
        grp.add(g)
        for h in gens+list(grp): 
            for x in (perm_mul(g,h), perm_mul(h,g)):
                if x not in grp: frontier.append(x)
ok&=check(f"prop:deck: the two Nariai transpositions GENERATE S3 (|group|={len(grp)}=6)", len(grp)==6)
ok&=check("  (S3 = all 6 permutations of 3 roots)", grp==set(itertools.permutations(range(3))))
# rem:galois -- discriminant 4 - 27(2M)^2 not a square in C(2M) => Galois group S3 (not A3)
import sympy as sp
tM=sp.symbols('twoM'); disc=sp.simplify(-4*(-1)**3 - 27*tM**2)
ok&=check("rem:galois: cubic discriminant = 4 - 27(2M)^2", sp.simplify(disc-(4-27*tM**2))==0)
ok&=check("  discriminant is not a perfect square in C(2M) (a degree-2 poly, sqrt irrational) => Galois S3 not A3",
          not sp.sqrt(disc).is_polynomial(tM))
# CONTROL: generic (non-branch) 2M -> identity monodromy
p_gen = track_monodromy(0.10, base=0.0j, R=0.02)   # tiny loop near 0.10, encircling no branch point
ok&=check(f"CONTROL: around a generic 2M=0.10 (non-branch), monodromy = identity {p_gen}", p_gen==(0,1,2))
# sec:classification -- the full solution-space symmetry: deck S3 x orientation Z2 = S3xZ2 = D6 (order 12)
S3_perms=set(itertools.permutations(range(3)))
D6 = {(p,e) for p in S3_perms for e in (0,1)}         # S3 x Z2, the orientation Z2 (R) central
ok&=check("sec:classification: <deck S3, orientation R> = S3 x Z2 (order 12)", len(D6)==12)
# S3xZ2 has an element of order 6 ((3-cycle, 1)) -> = D6 (dihedral of the hexad), not another order-12 group here
has_ord6 = any((lcm:=np.lcm(3 if p in {(1,2,0),(2,0,1)} else (1 if p==(0,1,2) else 2), 2 if e else 1))==6 for (p,e) in D6)
ok&=check("  S3 x Z2 has an element of order 6 (3-cycle x flip) => = D6, the dial's hexad symmetry Aut(A2)", has_ord6)
# r2376+c54.158 -- rule 7: the receipt computes every PASS/FAIL above and only PRINTS them.  Pin
# `ok`, and with it the group-theoretic content P5 sec:deck/sec:classification claims: each Nariai
# monodromy moves exactly 2 of the 3 roots and fixes 1 (a transposition); the two are DIFFERENT --
# the alternative was real, the same transposition twice gives Z_2 and P5's claim is false -- so
# they generate the FULL S_3, order 6 = all 3! permutations of the roots; a generic non-branch loop
# is the identity; and adjoining the orientation Z_2 gives the order-12 symmetry S3xZ2 = D_6.
assert sum(1 for i in range(3) if p_plus[i] != i) == 2, p_plus
assert sum(1 for i in range(3) if p_minus[i] != i) == 2, p_minus
assert p_plus != p_minus, (p_plus, p_minus)
assert len(grp) == 6 and grp == set(itertools.permutations(range(3))), grp
assert p_gen == (0, 1, 2), p_gen
assert len(D6) == 12 and has_ord6
assert sp.simplify(disc - (4 - 27*tM**2)) == 0
assert ok
print("="*70)
print("RESULT:", "ALL PASS -- each Nariai monodromy is a transposition, the two generate S3 (the deck/Galois\n         group of the three-sheeted cover); a generic loop is trivial. The family symmetry is the cover's\n         monodromy, not a substrate isometry." if ok else "SOME FAILED")
print("="*70)
