#!/usr/bin/env python3
"""B10 -- `PO-2`'s resemblance is no longer a resemblance: the same $\\varepsilon$ the row used to REMOVE a
leg is the one P14 uses to BUILD the baryon, and the row never turned it around.

** THE ITEM, never worked (0 dated moves). **  `PO-2`, "The Nariai / three-quark lead", targeting "** the
three horizon roots, their zero-sum, and the distinguished merged member --- against a baryon's three
quarks in a colour singlet **".  Held at do-not-assert on three separated levels, imploded and restored
twice.

** ⓵ THE ROW ALREADY CARRIES THE $\\varepsilon$ FACT, AND USED IT DESTRUCTIVELY. **  Its own status text:
"on the colour side a distinguished one is structurally impossible: ** $\\Lambda^3$ of the wall kernel is
one-dimensional and generated by $\\varepsilon$ **, so exchanging two colours reverses a sign and changes
no physics."
  ⇒ ** That removed one leg of the analogy -- the "distinguished merged member" has no colour-side
    counterpart. **  *** And the row stopped there. ***

** ⛭⛭ ⓶ AND THE SAME FACT IS P14's BARYON CONSTRUCTION, READ FORWARD. **  "Second quantisation---the
ordinary step, ** available because the three wall modes are one operator's kernel and therefore
identical particles **---** places a three-fermion state in the exterior cube, one-dimensional and
generated by $\\varepsilon$ **, and returns ** baryon $1$, diquark $0$, meson $1$: every channel the
Standard Model has, with the configuration group SELECTED rather than chosen **."

  ⇒⇒ *** The row's own destructive fact and P14's constructive one are the SAME fact.  $\\Lambda^3$
      one-dimensional and generated by $\\varepsilon$ is simultaneously why no root can be distinguished
      on the colour side AND why the three-fermion state is a singlet. ***

** ⓷ SO THE ANALOGY IS NO LONGER AN ANALOGY. **  `PO-2` was held at do-not-assert because "the zero-sum
triple and its resemblance to baryon combinatorics" was a ** resemblance **.
  ⇒ ** But the corpus now builds the baryon side rather than noticing it: ** the three modes are ** one
    operator's kernel **, so they are identical particles by construction; the configuration group is
    ** selected rather than chosen **; and the channel count is ** computed **, not matched.
  ⌗ *** What was a resemblance between two three-fold structures is now a construction on one of them
      that returns the other's channel counts.  That is a different epistemic object, and the row's
      do-not-assert was calibrated to the older one. ***

** ⓸ AND THE ROOT SIDE IS THE HALF THAT REMAINS. **  P13 ties the roots to the same skeleton: the
offset-to-mass cubic's "three zero-sum roots are the $A_2$ weights that $S_3$ permutes".
  ⇒ ** So both sides are now built objects: the roots as $A_2$ weights, the modes as one kernel. **
  *** What is NOT established is that they are the same $A_2$ -- and that, rather than "is the
  resemblance real", is what `PO-2` should now ask. ***

WHAT IS NOT CLAIMED.  ** Not that the roots and the wall modes are the same structure ** -- that is the
narrowed question and this receipt does not answer it.  ** Not that `PO-2` closes ** -- `F5` reserves it
and the do-not-assert holds on the identification.  ** Not that the baryon delivery is a force ** -- "the
bundle is flat.  Flat holonomy supplies exact selection rules and no curvature".

Written r2629.  Stated for reversal.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def body(f):
    b = '\n'.join(l for l in open(f, encoding='utf-8', errors='replace').read().split('\n')
                  if not l.lstrip().startswith('%'))
    j = b.find('\\begin{thebibliography}')
    return b[:j] if j > 0 else b


def main():
    print()
    print("  B10 -- is PO-2's resemblance still a resemblance?")
    print()
    p13 = re.sub(r'\s+', ' ', body(os.path.join(ROOT, 'corpus', 'boundary_paper.tex')))
    p14 = re.sub(r'\s+', ' ', body(os.path.join(ROOT, 'corpus', 'matter_sector_paper.tex')))
    raw = open(os.path.join(ROOT, 'PROTECTED_OPEN.md'), encoding='utf-8', errors='replace').read()
    row = next(l for l in raw.split('\n')
               if re.match(r'\|\s*~?~?\*\*PO-2\*\*', l))

    # ⓵ the row's own epsilon fact, used destructively
    check('⓵ the row carries the $\\varepsilon$ fact: "$\\Lambda^{3}$ of the wall kernel is '
          'one-dimensional and generated by $\\varepsilon$"',
          'one-dimensional and generated by $\\varepsilon$' in row)
    check('and uses it to REMOVE a leg: "on the colour side a distinguished one is structurally '
          'impossible"',
          'a distinguished one is structurally impossible' in row)
    check('and calls the rest a RESEMBLANCE: "The zero-sum triple and its resemblance to baryon '
          'combinatoric[s]"',
          'resemblance to baryon combinatoric' in row)

    # ⓶ the same fact, constructive, in P14
    check('⛭⛭ ⓶ and P14 uses the SAME fact constructively: "places a three-fermion state in the exterior '
          'cube, one-dimensional and generated by $\\varepsilon$"',
          'places a three-fermion state in the exterior cube, one-dimensional and generated by '
          '$\\varepsilon$' in p14)
    check('with the licence stated: "available because the three wall modes are one operator\'s kernel '
          'and therefore identical particles"',
          "available because the three wall modes are one operator's kernel and therefore identical "
          'particles' in p14)
    check('and the result computed: "returns baryon $1$, diquark $0$, meson $1$: every channel the '
          'Standard Model has, with the configuration group selected rather than chosen"',
          'baryon $1$, diquark $0$, meson $1$' in p14
          and 'the configuration group selected rather than chosen' in p14)

    # ⓸ the root side
    check('⓷ and P13 ties the ROOT side to the same skeleton: the cubic\'s "three zero-sum roots are the '
          '$A_{2}$ weights that $S_{3}$ permutes"',
          'three zero-sum roots are the $A_{2}$ weights that $S_{3}$ permutes' in p13
          or 'three zero-sum roots are the $A_2$ weights that $S_3$ permutes' in p13)

    # the limit
    check('⚠ and the delivery is selection rules, not force: "Flat holonomy supplies exact selection '
          'rules and no curvature"',
          'Flat holonomy supplies exact selection rules and no curvature' in p14)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print("  VERDICT: ** PO-2's resemblance is no longer a resemblance, and the row's own fact is why. **")
    print('  ⓵ ** The row used $\\varepsilon$ DESTRUCTIVELY: ** "Λ³ of the wall kernel is one-dimensional')
    print('     and generated by ε, so exchanging two colours reverses a sign and changes no physics" --')
    print('     removing the "distinguished merged member" leg.  ** And it stopped there. **')
    print('  ⛭⛭ ⓶ ** P14 uses the SAME fact CONSTRUCTIVELY: ** it "places a three-fermion state in the')
    print('     exterior cube, one-dimensional and generated by ε, and returns ** baryon 1, diquark 0,')
    print('     meson 1: every channel the Standard Model has, with the configuration group SELECTED')
    print('     rather than chosen **".')
    print('     ⇒⇒ ** The row\'s destructive fact and P14\'s constructive one are THE SAME FACT. **')
    print('  ⓷ ** So the analogy is now a construction: ** the three modes are one operator\'s kernel and')
    print('     therefore identical particles ** by construction **; the channel count is ** computed **,')
    print('     not matched.  ** The row\'s do-not-assert was calibrated to the older object. **')
    print('  ⓸ ** And both sides are now built: ** the roots as A₂ weights (P13), the modes as one kernel')
    print('     (P14).  ** What is NOT established is that they are the same A₂ -- and that, rather than')
    print('     "is the resemblance real", is what PO-2 should now ask. **')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
