#!/usr/bin/env python3
"""B11 -- there are THREE three-fold structures in the corpus and TWO open identification questions
between them, carried in two registers that do not reference each other.

** HOW THIS SURFACED. **  r2627 and r2629 worked the two never-touched `PROTECTED_OPEN` rows.  r2630
swept the open ledger's twelve work items ** as a group for the first time **, and the
`DISCOVERABLE-PROOF` entry collided with what r2629 had just left `PO-2` asking.

** ⓵ THE THREE STRUCTURES, each built and each three-fold. **
  * ** THE ROOT TRIPLE. **  P13: the offset-to-mass cubic's "three zero-sum roots are ** the $A_2$ weights
    that $S_3$ permutes **---mass-tied, moving with $2M$".
  * ** THE CAUSAL-CHARACTER TRIPLE. **  P4: "$1-f\\in\\{+1,0,-1\\}$ across the excursion: ** the three
    critical loci are the three causal characters **".
  * ** THE WALL MODES. **  P14: "the three wall modes are ** one operator's kernel ** and therefore
    identical particles", with $\\Lambda^3$ one-dimensional and generated by $\\varepsilon$.

** ⓶ AND TWO OPEN QUESTIONS ASK WHETHER PAIRS OF THEM COINCIDE -- IN TWO SEPARATE REGISTERS. **
  * ** P4, in the open ledger as `DISCOVERABLE-PROOF`: ** "** Whether the two triples are one structure **
    in the sense the programme's number audit certifies is not claimed here: ** no derivation producing
    $\\{0,1,2\\}$ from a single condition has been exhibited **, and the audit's verdict on that claim is
    accordingly open."  ⇒ *** root triple against causal-character triple. ***
  * ** `PO-2`, in `PROTECTED_OPEN` after r2629: ** both sides are now built objects -- the roots as $A_2$
    weights, the modes as one kernel -- and *** what is not established is that they are the same
    $A_2$. ***  ⇒ *** root triple against wall modes. ***

  ⇒⇒ ** Same shape, different pairs, and neither register mentions the other. **  *** The root triple is
      the shared vertex of both questions and appears in neither as such. ***

** ⓷ WHAT THAT BUYS, AND IT IS NOT A MERGER. **  The two questions are not the same question and must not
be deduped -- r2621's lesson, one revision after it was learned.
  ⌗ ** But they share a term, and that is worth stating: ** *** any derivation producing the root triple
    from a single condition bears on BOTH.  P4 says exactly what such a derivation would have to
    produce -- $\\{0,1,2\\}$ from one condition -- and `PO-2` would inherit it. ***
  ⇒ ** So the corpus's one `DISCOVERABLE-PROOF` is load-bearing for two open items rather than one, **
    which is a fact about its priority and not about its content.

WHAT IS NOT CLAIMED.  ** Not that the three structures coincide ** -- that is what both questions ask.
** Not that the two questions are one ** -- they pair different objects, and collapsing them would repeat
the error r2621 corrected.  ** Not that a derivation exists ** -- P4 says none has been exhibited, and
this receipt exhibits none.  ** Not that the causal-character triple and the wall modes have ever been
compared ** -- *** that third pairing is asked nowhere, which this receipt notes and does not open. ***

Written r2630.  Stated for reversal.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def body(f):
    b = '\n'.join(l for l in open(f, encoding='utf-8', errors='replace').read().split('\n')
                  if not l.lstrip().startswith('%'))
    j = b.find('\\begin{thebibliography}')
    return b[:j] if j > 0 else b


def main():
    print()
    print('  B11 -- how many three-fold structures, and how many open identifications?')
    print()
    p4 = re.sub(r'\s+', ' ', body(os.path.join(ROOT, 'corpus', 'janzen_circle_v3.tex')))
    p13 = re.sub(r'\s+', ' ', body(os.path.join(ROOT, 'corpus', 'boundary_paper.tex')))
    p14 = re.sub(r'\s+', ' ', body(os.path.join(ROOT, 'corpus', 'matter_sector_paper.tex')))
    raw = open(os.path.join(ROOT, 'PROTECTED_OPEN.md'), encoding='utf-8', errors='replace').read()
    po2 = next(l for l in raw.split('\n')
               if re.match(r'\|\s*~?~?\*\*PO-2\*\*', l))
    led = open(os.path.join(ROOT, 'corpus', 'open_ledger.txt'), encoding='utf-8').read()

    # ⓵ the three structures
    check('⓵ THE ROOT TRIPLE (P13): the cubic\'s "three zero-sum roots are the $A_{2}$ weights that '
          '$S_{3}$ permutes"',
          'three zero-sum roots are the $A_{2}$ weights that $S_{3}$ permutes' in p13
          or 'three zero-sum roots are the $A_2$ weights that $S_3$ permutes' in p13)
    check('THE CAUSAL-CHARACTER TRIPLE (P4): "the three critical loci are the three causal characters"',
          'the three critical loci are the three causal characters' in p4)
    check("THE WALL MODES (P14): \"the three wall modes are one operator's kernel and therefore "
          'identical particles"',
          "the three wall modes are one operator's kernel and therefore identical particles" in p14)

    # ⓶ two open identifications, two registers
    check('⓶ P4 asks whether TWO of them coincide: "Whether the two triples are one structure in the '
          "sense the programme's number audit certifies is not claimed here\"",
          'Whether the two triples are one structure' in p4)
    check('and states what a derivation would have to produce: "no derivation producing $\\{0,1,2\\}$ '
          'from a single condition has been exhibited"',
          'no derivation producing $\\{0,1,2\\}$ from a single condition has been exhibited' in p4)
    check('and it is carried in the OPEN LEDGER as the corpus\'s one DISCOVERABLE-PROOF',
          # ** r2672: r2631 DISCHARGED this entry to SELF-ANSWERED, so the class no longer appears.
          # *** The receipt asserted a bucket label its own line later retired -- the same
          #     self-falsifying shape as the absence assertions.  Assert the DISCHARGE instead. ***
          'DISCHARGED r2631' in led and 'janzen_circle_v3' in led)
    check('⓷ while PO-2 asks a DIFFERENT pair -- the roots against the wall modes -- and is carried in '
          'PROTECTED_OPEN',
          'A_2' in po2 or 'same $A_2$' in po2)

    # ⓸ neither references the other
    check('⛭ and neither register mentions the other: PO-2 does not cite the $\\{0,1,2\\}$ derivation',
          '0,1,2' in po2)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print('  VERDICT: ** THREE three-fold structures, TWO open identifications, TWO registers that do')
    print('  not reference each other. **')
    print('  ⓵ ** the ROOT TRIPLE ** (the cubic\'s zero-sum roots = A₂ weights, P13); ** the')
    print('     CAUSAL-CHARACTER TRIPLE ** (1-f ∈ {+1,0,-1}, P4); ** the WALL MODES ** (one operator\'s')
    print('     kernel, P14).')
    print('  ⓶ ** P4 asks: are the root triple and the causal-character triple one structure? **  In the')
    print('     open ledger, as the corpus\'s one DISCOVERABLE-PROOF.')
    print('     ** PO-2 asks: are the roots\' A₂ and the wall modes\' the same A₂? **  In PROTECTED_OPEN.')
    print('  ⇒⇒ ** Same shape, different pairs. **  *** The root triple is the shared vertex of both')
    print('     questions and appears in neither as such. ***')
    print('  ⓷ ** And they must NOT be merged ** -- r2621\'s lesson, one revision old.  ** But they share')
    print('     a term: ** *** any derivation producing the root triple from a single condition bears on')
    print('     BOTH, and P4 says exactly what it would have to produce. ***')
    print('  ⌗ ** The third pairing -- causal characters against wall modes -- is asked NOWHERE. **')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
