#!/usr/bin/env python3
"""B13 -- `PO-2`'s identification IS stated in P14, and r2631 said one turn earlier that it stays open.

** WHAT r2631 LEFT. **  It computed that the ROOT TRIPLE is the $f=0$ locus -- the horizon cubic's roots
$\\{1/\\sqrt3,1/\\sqrt3,-2/\\sqrt3\\}$ -- and discharged P4's pairing (roots against causal characters)
negatively on a type argument.  *** And it closed: "Says nothing about `PO-2`'s own pairing -- the roots
against the WALL MODES -- which stays open." ***

** ⛔ ⓵ IT DOES NOT STAY OPEN.  P14 STATES THE IDENTIFICATION IN ONE SENTENCE. **

  "the three zero-modes are permuted by the full $S_3$ generated by the three hinges, and that $S_3$ is
   not a second group resembling the substrate's own: ** each hinge designates one of the three roots of
   the horizon cubic as its own black-hole horizon **, so ** a transposition of roots is a hop to a
   neighbouring hinge ** and ** the Weyl $S_3$ is the relation among the three hinges **."

  ⇒⇒ *** The chain is complete and every link is in the corpus: ***
  * ** roots ↔ hinges: ** "each hinge designates one of the three roots of the horizon cubic";
  * ** hinges ↔ walls: ** "places a slicing plane on each: ** three throat walls **";
  * ** walls ↔ modes: ** "hence three chiral zero-modes", one per wall (`prop:wall`);
  * ** and the $S_3$ is the SAME $S_3$: ** "not a second group resembling the substrate's own ... a
    transposition of roots is a hop to a neighbouring hinge".

** ⓶ AND THE SENTENCE IS WRITTEN TO FORESTALL EXACTLY THE ERROR `PO-2` WAS HOLDING AGAINST. **  `PO-2` was
held at do-not-assert because the three-fold structures might be a ** resemblance **.  *** P14's clause
"that $S_3$ is not a second group resembling the substrate's own" is a denial of that resemblance reading
-- and it denies it by exhibiting the map, not by asserting the identity. ***

** ⛭ ⓷ SO WHY DID r2631 GET IT WRONG ONE TURN EARLIER? **  Because it was computing P4's pairing, and
*** the sentence that settles `PO-2`'s pairing sits in a DIFFERENT paper section, reached by a different
question. ***  r2630 had noted the root triple was "the shared vertex of both questions and appears in
neither as such" -- and the vertex was already tied to the wall modes in the paper that builds them.
  ⌗ ** The `PO-2` row's own status text names the two distinguished roots ($1/\\sqrt3$ and $-2/\\sqrt3$)
    and never says they are the hinges'. **

** ⇒⇒ WHAT REMAINS ON `PO-2`, honestly. **  *** The identification of the root triple with the wall modes
is stated and its map is exhibited.  What the row also asks -- the baryon comparison -- was turned into a
construction at r2629.  So both halves of the row's target are now delivered, and what is left is the
do-not-assert on whether the DELIVERED structure is the physical one. ***  ** That is a different
question from the one the row was opened for, and `F5` reserves the closure. **

WHAT IS NOT CLAIMED.  ** Not that `PO-2` closes ** -- `F5` reserves it, and the physical identification
stays do-not-assert.  ** Not that the causal-character triple joins this chain ** -- r2631 showed it is
typed differently and that stands.  ** Not that the mass VALUES follow ** -- P13 marks that separately.

Written r2632.  Stated for reversal.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def body(f):
    b = '\n'.join(l for l in open(f, encoding='utf-8', errors='replace').read().split('\n')
                  if not l.lstrip().startswith('%'))
    j = b.find('\\begin{thebibliography}')
    return b[:j] if j > 0 else b


def main():
    print()
    print("  B13 -- is PO-2's identification stated anywhere?")
    print()
    p14 = re.sub(r'\s+', ' ', body(os.path.join(ROOT, 'corpus', 'matter_sector_paper.tex')))
    raw = open(os.path.join(ROOT, 'PROTECTED_OPEN.md'), encoding='utf-8', errors='replace').read()
    po2 = next(l for l in raw.split('\n') if l.startswith('| **PO-2**'))

    # ⓵ the chain, link by link
    check('⓵ ROOTS ↔ HINGES: "each hinge designates one of the three roots of the horizon cubic as its '
          'own black-hole horizon"',
          'each hinge designates one of the three roots of the horizon cubic as its own black-hole '
          'horizon' in p14)
    check('HINGES ↔ WALLS: "places a slicing plane on each: three throat walls"',
          'places a slicing plane on each: three throat walls' in p14)
    check('WALLS ↔ MODES: "hence three chiral zero-modes"', 'hence three chiral zero-modes' in p14)
    check('and the $S_3$ is the SAME one: "that $S_{3}$ is not a second group resembling the '
          "substrate's own\"",
          "is not a second group resembling the substrate's own" in p14)
    check('with the map exhibited: "a transposition of roots is a hop to a neighbouring hinge"',
          'a transposition of roots is a hop to a neighbouring hinge' in p14)
    check('and named: "the Weyl $S_{3}$ is the relation among the three hinges"',
          'the Weyl $S_3$ \\emph{is} the relation among the three hinges' in p14)

    # ⓶ the row does not carry it
    check('⛔ ⓶ and the PO-2 row names the two distinguished roots but never says they are the hinges\'',
          '1/\\sqrt3' in po2 and 'each hinge designates' in po2)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print("  VERDICT: ** PO-2's identification is stated in P14, and r2631 said one turn earlier that it")
    print('  stays open. **')
    print('  ⓵ ** The chain is complete and every link is in the corpus: **')
    print('     ** roots ↔ hinges ** -- "each hinge designates one of the three roots of the horizon')
    print('       cubic as its own black-hole horizon";')
    print('     ** hinges ↔ walls ** -- "places a slicing plane on each: three throat walls";')
    print('     ** walls ↔ modes ** -- "hence three chiral zero-modes";')
    print('     ** and the S₃ is the SAME S₃ ** -- "not a second group resembling the substrate\'s own …')
    print('       a transposition of roots is a hop to a neighbouring hinge".')
    print('  ⓶ ** And the sentence forestalls exactly the error PO-2 was holding against: ** the row was')
    print('     at do-not-assert because the structures might be a ** resemblance **, and P14 denies that')
    print('     reading ** by exhibiting the map, not by asserting the identity. **')
    print('  ⛭ ⓷ ** Why r2631 missed it: ** it was computing P4\'s pairing, and the sentence settling')
    print("     PO-2's sits in a different section reached by a different question.  ** r2630 had said")
    print('     the root triple "appears in neither register as such" -- and it was already tied to the')
    print('     wall modes in the paper that builds them. **')
    print('  ⇒⇒ ** So both halves of PO-2\'s target are now delivered ** (the baryon comparison became a')
    print('     construction at r2629), ** and what is left is the do-not-assert on whether the delivered')
    print('     structure is the PHYSICAL one ** -- a different question from the one the row was opened')
    print('     for.')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
