#!/usr/bin/env python3
"""B15 -- `PO-3`'s two clauses are answered in two different rows, and neither cites the other: the WHY at
r2627 on `PO-3`, the BRIDGE at r2626 on `PO-4`.

** THE OBJECT, in two clauses. **  "The $a_2$-meaning drill-site --- ** why does the SdS geometry produce a
zero-sum triple with a $\\mathbf3/\\bar{\\mathbf3}$ parity doubling **, ** and does that reason bridge to
$\\su(3)$? **"

** ⓵ CLAUSE ONE -- THE WHY -- ANSWERED AT r2627, ON THIS ROW. **  P14: "** The mass function is odd in the
signed offset exactly when $D$ is even **, so at $D=5$ the orientation parity $r_0\\mapsto-r_0$
*fixes* each geometry rather than exchanging it with its conjugate: there is no mass-reflection
$\\mathbb{Z}_2$, hence ** no $\\mathbf3\\oplus\\bar{\\mathbf3}$ Nariai hexad **".
  ⇒ ** Read forward: at $D=4$ the parity EXCHANGES conjugates, and that exchange IS the doubling. **

** ⛭⛭ ⓶ CLAUSE TWO -- THE BRIDGE -- ANSWERED AT r2626, ON `PO-4`. **  P14, as corrected at r6707/r6719:
"** the three wall monodromies and the hinge $3$-cycle generate a finite group of order $81$ in $U(3)$ **,
each monodromy carrying determinant $\\omega$, ** whose determinant-one part is $\\Delta(27)$ and lies in
$SU(3)$ **, with the lap as its centre", the module being "** the branching ** rather than any bundle of
the substrate"; and in the body, "the smallest connected group containing the ratios together with the
hinge three-cycle is $SU(3)$ itself".
  ⇒ *** So the reason DOES bridge to $\\su(3)$ -- the unimodular part of what the skeleton generates is
      Delta(27) inside SU(3), whose connected closure is SU(3) -- and by generation rather than by
      reduction, which is the finding r2626 recorded against `PO-4`'s stale "what reduces
      $\\so(6)\\to\\su(3)$?" ***

** r6931+70.1: CLAUSE TWO WAS WRITTEN ON AN ERROR THE CORPUS HAS SINCE CORRECTED. **  At r2645 P14 said
"the smallest connected group containing the three wall monodromies and the hinge 3-cycle is SU(3)", and
this receipt quoted it.  A single wall monodromy has determinant omega, so the monodromies generate a
FINITE group of order 81 in U(3), not SU(3); r6707 (3b921b95) corrected the body and r6719 (440623b6)
the abstract.  The bridge survives in the corrected form -- the determinant-one part, generated by the
monodromy RATIOS and the hinge 3-cycle, is Delta(27) in SU(3), and SU(3) is the smallest connected group
containing it -- so clause two is still answered, and still by generation.

** ⛔ ⇒⇒ ⓷ AND THIS RECEIPT'S FIRST DRAFT GOT THIS WRONG. **  It asserted the two halves were split across
`PO-3` and `PO-4`.  *** They are not.  `PO-3` carries BOTH, and has since c54.42--c54.62, in its own status
text: "The bridge was BUILT ... the three wall monodromies and the hinge $3$-cycle ...". ***  (r6931+70.1:
the row's status text still carries P14's pre-r6707 group statement, "smallest connected group ... is
SU(3)"; that is reported to node 66 and is no longer what this receipt pins.)
  ⇒ ** So the row has held its own complete answer for hundreds of revisions and still reads OPEN. **
  *** That is worse than a split: nothing had to be assembled, only read. ***

** ⓸ SO `PO-3` IS ANSWERED, IN BOTH CLAUSES. **
  * ** why the doubling: ** the mass function's parity in the signed offset, odd exactly when $D$ is even;
  * ** does it bridge: ** yes -- the same three-fold, read through the wall monodromies with the hinge
    $3$-cycle, generates a finite order-81 group in U(3) ** whose determinant-one part Delta(27) lies in
    SU(3) **, SU(3) being the smallest connected group containing that part.
  ⚠ ** And the answer is not that the bridge is a REDUCTION. **  *** The row's target says "the $A_2$
      skeleton and the parity doubling", and what the corpus delivers is a GENERATION from the skeleton --
      which is a stronger answer than the question's own framing anticipated. ***

WHAT IS NOT CLAIMED.  ** Not that `PO-3` closes ** -- `PROTECTED_OPEN` reserves the strike, and this
receipt marks the question answered rather than striking the row.  ** Not that the group so generated is
a FORCE ** -- "the bundle is flat.  Flat holonomy supplies exact selection rules and no curvature", which
is `PO-5`'s remaining half.  ** Not that the mass VALUES follow ** -- P13 marks that separately.

Written r2645.  Stated for reversal.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def body(f):
    b = '\n'.join(l for l in open(f, encoding='utf-8', errors='replace').read().split('\n')
                  if not l.lstrip().startswith('%'))
    j = b.find('\\begin{thebibliography}')
    return b[:j] if j > 0 else b


def main():
    print()
    print("  B15 -- are both of PO-3's clauses answered?")
    print()
    p14 = re.sub(r'\s+', ' ', body(os.path.join(ROOT, 'corpus', 'matter_sector_paper.tex')))
    raw = open(os.path.join(ROOT, 'PROTECTED_OPEN.md'), encoding='utf-8', errors='replace').read()
    # ** ⛭ AMENDED c54.224 (`L-558`): the row matcher required the OPEN form `| **PO-n**` and
    # ** `PO-4` was STRUCK at r2778, so this file died on `StopIteration`. **  It had gone on
    # ** passing only because `19139ed` duplicated the row and one copy came back UNSTRUCK --
    # *** so this receipt was reading a resurrected copy of an item the observer line closed. ***
    # ** A matcher that admits only the open form silently follows whichever copy is open. **
    _ROWPAT = (lambda t: re.compile(r'\|\s*(?:~~)?\s*\*\*' + re.escape(t) + r'\*\*'))
    po3 = next(l for l in raw.split('\n') if _ROWPAT('PO-3').match(l))
    po4 = next(l for l in raw.split('\n') if _ROWPAT('PO-4').match(l))

    # the object's two clauses
    check('⓵ the object has TWO clauses: "why does the SdS geometry produce a zero-sum triple with a '
          '$\\mathbf3/\\bar{\\mathbf3}$ parity doubling, and does that reason bridge to $\\su(3)$?"',
          'parity doubling, and does that reason bridge to $\\su(3)$' in po3)

    # ⓵ the why
    check('⓶ CLAUSE ONE answered: "The mass function is odd in the signed offset exactly when $D$ is '
          'even"',
          'The mass function is odd in the signed offset exactly when $D$ is even' in p14)
    check('and PO-3 carries it', 'odd in the signed offset' in po3)

    # ⓶ the bridge
    # ** r6931+70.1: class (a), FROZE AN ERROR.  This pinned P14's "the smallest connected group
    #   containing the three wall monodromies and the hinge $3$-cycle is $SU(3)$".  Each wall monodromy
    #   has determinant omega, so the group is finite, of order 81, in U(3); corrected at r6707
    #   (3b921b95, body) and r6719 (440623b6, abstract).  What this check is about is that clause two
    #   -- does the reason bridge to su(3)? -- is answered BY GENERATION.  It still is, in corrected
    #   form: the determinant-one part is Delta(27) inside SU(3), and the body states that the smallest
    #   connected group containing the ratios with the three-cycle is SU(3).  The pin follows the
    #   correction, and requires the old sentence's absence so the error cannot return unnoticed. **
    check('⛭⛭ ⓷ CLAUSE TWO answered: "the three wall monodromies and the hinge $3$-cycle generate a finite '
          'group of order $81$ in $U(3)$ ... whose determinant-one part is $\\Delta(27)$ and lies in '
          '$SU(3)$", SU(3) being the smallest connected group containing the ratios and the three-cycle',
          'the three wall monodromies and the hinge $3$-cycle generate a finite group of order $81$ in $U(3)$' in p14
          and 'whose determinant-one part is $\\Delta(27)$ and lies in $SU(3)$' in p14
          and ('the smallest connected group containing the ratios together with the hinge three-cycle '
               'is $SU(3)$ itself') in p14
          and ('the smallest connected group containing the three wall monodromies and the hinge '
               '$3$-cycle is $SU(3)$') not in p14)
    check('and PO-4 carries THAT', 'wall monodromies with the hinge' in po4
          or 'three wall monodromies and the hinge' in po4)

    # ⓷ neither row holds both
    # ** ⛔ AND THE FIRST DRAFT OF THIS RECEIPT WAS WRONG.  It asserted that PO-3 does not carry the
    # generation clause.  *** It does -- and has since c54.42-c54.62, in its own status text: "The
    # bridge was BUILT ... the three wall monodromies and the hinge 3-cycle ..." (the group it then
    # named, SU(3), is the pre-r6707 error; see below). ***  So the halves were never split across rows; ** BOTH have been in
    # PO-3 the whole time, and the row still reads OPEN. **
    # ** r6931+70.1: these two pinned 'smallest connected group' in the PO-3 row -- i.e. the row's copy
    #   of P14's pre-r6707 group statement, which the register has NOT been corrected to (reported to
    #   node 66).  The checks are about the row carrying the BRIDGE clause, not about the group's name,
    #   so the pin moves to the bridge clause itself: "The bridge was BUILT" with the wall-monodromy /
    #   hinge-3-cycle generation.  True of the row now, and still true once its group is corrected. **
    _gen3 = ('three wall monodromies and the hinge' in po3 or 'three wall monodromies with the hinge' in po3)
    check('⛭⛭ ⓸ and PO-3 ALREADY CARRIES the generation clause -- "The bridge was BUILT at '
          'c54.42--c54.62 ... the three wall monodromies and the hinge $3$-cycle ..."',
          'The bridge was BUILT' in po3 and _gen3)
    check('so BOTH clauses are in this one row, and it still reads OPEN',
          'odd in the signed offset' in po3 and _gen3
          and 'OPEN' in po3)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print("  VERDICT: ** PO-3 is answered in BOTH clauses, and BOTH are already in its own row. **")
    print('  ⓵ ** WHY the doubling ** (r2627, on PO-3): the mass function is "odd in the signed offset')
    print('     ** exactly when D is even **" -- so at D=4 the parity EXCHANGES conjugates, and that')
    print('     exchange IS the doubling.')
    print('  ⛭⛭ ⓶ ** DOES IT BRIDGE ** (r2626, on PO-4): yes -- the three wall monodromies and the hinge')
    print('     3-cycle generate a finite order-81 group in U(3) whose determinant-one part ** Delta(27)')
    print('     lies in SU(3) **, with the lap as its centre; SU(3) is its connected closure.')
    print('')
    print("  ⛔ ⓷ ** And this receipt's first draft asserted the halves were split across PO-3 and")
    print('     PO-4.  They are not: PO-3 carries BOTH, and has since c54.42-c54.62 -- "The bridge was')
    print('     BUILT ... the three wall monodromies and the hinge 3-cycle ...". **')
    print('     ⇒ *** So the row has held its own complete answer for hundreds of revisions and still')
    print('       reads OPEN.  That is worse than a split: nothing had to be assembled, only read. ***')
    print('  ⚠ ** And the answer is STRONGER than the question anticipated: ** the bridge is not a')
    print('    REDUCTION but a ** GENERATION ** from the skeleton -- which is why PO-4\'s stale "what')
    print('    reduces so(6) to su(3)?" never matched it.')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
