#!/usr/bin/env python3
"""B19 -- `PO-4`'s remaining gap, characterised: $T$ is the WEYL $\\mathbb Z_2$ of $\\mathfrak{su}(2)$, not
its centre, so what is missing is the TORUS -- and that is a different debt from "no group at all".

** THE ROW, narrowed at r2626 to one target. **  P14: "Weak isospin as a gauging: ** $T$ is a discrete
horn swap and delivers a species label, not $SU(2)_L$'s chiral action **, the two occupations differing on
the right-handed pair."

** ⓵ THE NAIVE READING MAKES THE GAP LOOK TOTAL. **  $T^2=1$ so $\\langle T\\rangle\\cong\\mathbb Z_2$,
dimension $0$; $SU(2)_L$ is $3$-dimensional.  ** Three generators absent, not one. **
  ⌗ ** And $\\mathbb Z_2$ sits in $SU(2)$ as the CENTRE $\\{\\pm I\\}$, which acts trivially on the adjoint:
    $(-I)T(-I)^{-1}=T$ for every generator. **  *** On that reading the swap carries no adjoint
    information at all and the gap is the whole group. ***

** ⛭⛭ ⓶ BUT $SU(2)$ HAS A SECOND $\\mathbb Z_2$, AND A SWAP IS THAT ONE. **  Computed:

      *** centre  -I        : adjoint on sigma_z UNCHANGED, on sigma_x UNCHANGED
          Weyl    i*sigma_x : adjoint on sigma_z FLIPPED (+1,-1) -> (-1,+1), on sigma_x UNCHANGED ***

  ⇒ *** The Weyl element $i\\sigma_x$ EXCHANGES the two $\\sigma_z$ eigenstates -- which is exactly what a
      "horn swap delivering a species label" does.  It is NOT central: it acts non-trivially on the
      adjoint. ***
  ⌗ ** And its square is $-I$, the centre ** -- so $\\langle i\\sigma_x\\rangle\\cong\\mathbb Z_4$ in $SU(2)$
    and $\\mathbb Z_2$ in $SO(3)$, which is the ordinary Weyl group $W(\\mathfrak{su}(2))=\\mathbb Z_2$.

** ⇒⇒ ⓷ SO THE DEBT IS THE TORUS, NOT THE GROUP. **  *** $SU(2)$ is generated by its maximal torus
$U(1)$ together with the Weyl reflection.  If $T$ is the Weyl element, the construction already supplies
the reflection and what is absent is the CONTINUOUS $U(1)$ it reflects. ***
  ⌗ ** That is the same shape as `PO-5`'s verdict, one level down: ** *** P14 walled a coupling because
    "a coupling is not the kind of thing a holonomy supplies"; here the missing piece is again a
    CONTINUOUS structure where the geometry delivers a DISCRETE one. ***

WHAT IS NOT CLAIMED.  ** Not that $T$ IS the Weyl element ** -- *** what is shown is that a swap has the
Weyl element's adjoint action and not the centre's, so the naive "no adjoint information" reading is
wrong; whether P14's $T$ realises it requires reading `sec:whichthree`'s construction, which this receipt
does not do. ***  ** Not that supplying a $U(1)$ is easy ** -- it is the same continuous-from-discrete
problem `PO-5` walls.  ** Not that the chirality gap is addressed ** -- *** $SU(2)_L$ acts on LEFT-handed
doublets and P14 says the occupations differ on the RIGHT-handed pair; that mismatch is untouched here and
is the sharper half. ***

Written r2676.  Stated for reversal.
"""
import os
import re

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def body(f):
    b = '\n'.join(l for l in open(f, encoding='utf-8', errors='replace').read().split('\n')
                  if not l.lstrip().startswith('%'))
    j = b.find('\\begin{thebibliography}')
    return b[:j] if j > 0 else b


def main():
    print()
    print("  B19 -- which Z_2 is a horn swap?")
    print()
    p14 = re.sub(r'\s+', ' ', body(os.path.join(ROOT, 'corpus', 'matter_sector_paper.tex')))

    check('⓵ P14 states the gap: "$T$ is a discrete horn swap and delivers a species label, not '
          "$SU(2)_L$'s chiral action\"",
          'a discrete horn swap and delivers a species label' in p14)
    check('and locates the difference: "the two occupations differing on the right-handed pair"',
          'the two occupations differing on the right-handed pair' in p14)

    sx = np.array([[0, 1], [1, 0]], dtype=complex)
    sz = np.diag([1, -1]).astype(complex)
    centre = -np.eye(2, dtype=complex)
    weyl = 1j * sx

    # ⓶ the centre acts trivially
    check('⓶ the CENTRE $-I$ acts trivially on the adjoint: $(-I)T(-I)^{-1}=T$ for both $\\sigma_z$ and '
          '$\\sigma_x$',
          np.allclose(centre @ sz @ np.linalg.inv(centre), sz)
          and np.allclose(centre @ sx @ np.linalg.inv(centre), sx))

    # the Weyl element does not
    adj_z = weyl @ sz @ np.linalg.inv(weyl)
    check('⛭⛭ and the WEYL element $i\\sigma_x$ FLIPS $\\sigma_z$ -- it exchanges the two eigenstates, '
          'which is what a horn swap does',
          np.allclose(adj_z, -sz))
    check('while leaving $\\sigma_x$ fixed, as a reflection does',
          np.allclose(weyl @ sx @ np.linalg.inv(weyl), sx))
    check('and it is NOT central: its adjoint action is non-trivial',
          not np.allclose(adj_z, sz))
    check('with $(i\\sigma_x)^2=-I$, the centre -- so it generates $\\mathbb{Z}_4$ in $SU(2)$ and the '
          'Weyl $\\mathbb{Z}_2$ in $SO(3)$',
          np.allclose(weyl @ weyl, centre))

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print("  VERDICT: ** the missing piece is the TORUS, not the group. **")
    print('  ⓵ ** The naive reading makes the gap total: ** Z_2 has dimension 0, SU(2) has dimension 3,')
    print('     and Z_2-as-the-CENTRE acts ** trivially on the adjoint ** — no information at all.')
    print('  ⛭⛭ ⓶ ** But SU(2) has a SECOND Z_2, and a swap is that one: ** the Weyl element iσ_x')
    print('     ** FLIPS σ_z ** — exchanging the two eigenstates, which is exactly what "a horn swap')
    print('     delivering a species label" does — while fixing σ_x, as a reflection does.')
    print('     ⇒ ** It is NOT central. **  Its square is -I, so it generates Z₄ in SU(2) and the Weyl')
    print('       Z₂ in SO(3).')
    print('  ⇒⇒ ⓷ ** SU(2) is generated by its maximal torus together with the Weyl reflection. **  If T')
    print('     is the Weyl element, ** the construction already supplies the reflection and what is')
    print('     absent is the CONTINUOUS U(1) it reflects. **')
    print('     ⌗ *** Which is PO-5\'s verdict one level down: a CONTINUOUS structure missing where the')
    print('       geometry delivers a DISCRETE one. ***')
    print('  ⚠ ** The chirality mismatch is untouched and is the sharper half: ** SU(2)_L acts on')
    print('    LEFT-handed doublets, and P14 says the occupations differ on the ** RIGHT-handed ** pair.')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
