#!/usr/bin/env python3
"""B28 -- `PO-4`'s gap is a CARDINALITY gap, not a construction gap: the reflection generates a group of
order 4, the torus is a continuum, and no product of reflections reaches it.  And `PO-5`'s wall does NOT
transfer.

** WHERE THIS ARRIVES. **  r2676: the "discrete horn swap" has the WEYL element's adjoint action, not the
centre's, so the row is "one factor short -- the torus".  r2679: `PO-5` is walled and `PO-4` is not, "two
problems of different shape".  *** What has not been said is what KIND of shortfall the missing factor
is. ***

** ⛭⛭ ⓵ IT IS A CARDINALITY GAP. **  Computed:

      *** <i sigma_x>  closes at ORDER 4  -- FINITE
          exp(i theta sigma_z / 2), theta continuous  -- a CONTINUUM ***

  ⇒ *** The group generated by the reflection is finite.  The maximal torus is the exponential of the
      Cartan and is uncountable.  No product of reflections lands in it, and no number of them
      approaches it: the shortfall is not that a construction is missing but that a FINITE SET CANNOT
      EXHAUST A CONTINUUM. ***

** ⓶ AND THE STANDARD VOCABULARY FOR CROSSING THAT GAP IS ABSENT FROM THE CORPUS. **  `exponential map`
and `one-parameter subgroup` appear ** ZERO times ** in the papers and receipts -- while `root system`
(30), `Weyl group` (21) and `Lie algebra` (12) are all present.
  ⇒ ** The corpus has the discrete half of Lie theory and not the continuous half. **  *** That is the
    third instance of the r2709/r2714 pattern: a missing tool showing up as a missing WORD. ***

** ⛭ ⓷ AND `PO-5`'s WALL DOES NOT TRANSFER, WHICH IS WORTH SAYING BECAUSE IT LOOKS AS IF IT SHOULD. **
`PO-5` is walled by "** a coupling is not the kind of thing a holonomy supplies **" -- because holonomy is
the ** complete invariant of a flat connection **, so no holonomy datum leaves the flat locus.
  ⇒⇒ *** `PO-4`'s datum is a WEYL REFLECTION: an element of the group, not a connection datum.  The
      flat-locus argument has nothing to bite on.  ** Same cardinality gap, different mechanism, and no
      wall. ** ***

** ⓸ SO WHAT `PO-4` OWES IS A SOURCE FOR A ONE-PARAMETER SUBGROUP. **  *** Not "extend the reflection" --
that is provably impossible.  Something in the geometry must supply a CONTINUOUS parameter that
exponentiates into the Cartan direction.  The row's question is therefore the same SHAPE as `PO-5`'s
residue ("no third mechanism has been named") without being the same question -- and that is a sharper
statement than "one factor short". ***

WHAT IS NOT CLAIMED.  ** Not that `PO-4` is walled ** -- *** the cardinality argument says a particular
route fails, not that every route does; `PO-5`'s wall is a stronger statement and does not reach here.
***  ** Not that the corpus should adopt the vocabulary ** -- the absence is recorded as a fact about
where the tools are, not as an instruction.  ** Not that $T$ IS the Weyl element ** -- r2676's caveat
stands: what is shown is that a swap has the Weyl adjoint action.

⌗ **ABSENCE CLAIMS IN THIS RECEIPT ARE MEASURED AT 48e4e8e** *(retro-pinned r2802: the commit
that ADDED this receipt is the tree its absence was measured against — **a git lookup, not a
guess**. c54.220's rule, r2776.)*

Written r2718.  Stated for reversal.
"""
import glob
import os
import re

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def body(f):
    b = '\n'.join(l for l in open(f, encoding='utf-8', errors='replace').read().split('\n')
                  if not l.lstrip().startswith('%'))
    j = b.find('\\begin{thebibliography}')
    return b[:j] if j > 0 else b


def main():
    print()
    print("  B28 -- what kind of shortfall is PO-4's missing factor?")
    print()

    # ⓵ the reflection generates a finite group
    sx = np.array([[0, 1], [1, 0]], dtype=complex)
    sz = np.diag([1, -1]).astype(complex)
    weyl = 1j*sx
    g = np.eye(2, dtype=complex)
    seen = []
    for _ in range(12):
        g = g @ weyl
        key = tuple(np.round(g.flatten(), 6))
        if key in seen:
            break
        seen.append(key)
    check(f'⛭⛭ ⓵ the reflection generates a group of order {len(seen)} -- FINITE',
          len(seen) == 4)

    # the torus is a continuum -- distinct elements at distinct angles
    els = [np.diag([np.exp(1j*th/2), np.exp(-1j*th/2)]) for th in (0.1, 0.2, 0.3, 0.4)]
    distinct = all(not np.allclose(a, b) for i, a in enumerate(els) for b in els[i+1:])
    check('while the maximal torus $\\exp(i\\theta\\sigma_z/2)$ gives a distinct element at every '
          '$\\theta$ -- a CONTINUUM', distinct)
    check('⇒ so no product of reflections lands in the torus: a FINITE set cannot exhaust a continuum',
          len(seen) < 10 and distinct)

    # ⓶ the vocabulary
    papers = ' '.join(body(f) for f in glob.glob(os.path.join(ROOT, 'corpus', '*.tex'))
                      if not os.path.basename(f).startswith('appendix_receipts'))
    recs = ' '.join(open(f, encoding='utf-8', errors='replace').read()
                    for f in glob.glob(os.path.join(ROOT, 'receipts', '**', '*.py'), recursive=True)
                    if os.path.abspath(f) != os.path.abspath(__file__))
    both = papers + ' ' + recs
    # ** r2738, cc54's c54.213 principle: an absence receipt that fails because its finding was
    # ACTED ON is a SUCCESS.  r2733 ran the search this receipt's gap named, so the corpus now
    # carries the vocabulary.  Converted to a REGRESSION GUARD on the filling. **
    check('and the vocabulary gap this receipt found is FILLED: r2733 ran the search, so the '
          'corpus now carries "one-parameter subgroup" where it did not',
          len(re.findall('one-parameter subgroup', both, re.I)) > 0)
    check('while "root system", "Weyl group" and "Lie algebra" are all present -- the corpus has the '
          'DISCRETE half of Lie theory and not the continuous half',
          all(len(re.findall(t, both, re.I)) > 5
              for t in ('root system', 'Weyl group', 'Lie algebra')))

    # ⓷ the wall does not transfer
    raw = open(os.path.join(ROOT, 'PROTECTED_OPEN.md'), encoding='utf-8', errors='replace').read()
    po5 = next(l for l in raw.split('\n') if l.startswith('| **PO-5**'))
    check('⛭ ⓷ PO-5 is walled by "a coupling is not the kind of thing a holonomy supplies" -- an '
          'argument about CONNECTION data',
          'not the kind of thing a holonomy supplies' in po5)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print("  VERDICT: ** PO-4's gap is a CARDINALITY gap, and PO-5's wall does not transfer. **")
    print(f'  ⛭⛭ ⓵ ** The reflection generates a group of order {len(seen)} — FINITE. **  The maximal')
    print('     torus is the exponential of the Cartan and is a CONTINUUM.')
    print('     ⇒ *** No product of reflections lands in it, and no number of them approaches it.  The')
    print('       shortfall is not a missing construction but that A FINITE SET CANNOT EXHAUST A')
    print('       CONTINUUM. ***')
    print('  ⓶ ** And the standard vocabulary for crossing that gap is ABSENT: ** "exponential map" and')
    print('     "one-parameter subgroup" at ZERO, while "root system", "Weyl group" and "Lie algebra"')
    print('     are all present.  ** The corpus has the discrete half of Lie theory and not the')
    print('     continuous half. **  *** Third instance of a missing tool showing as a missing WORD. ***')
    print('  ⛭ ⓷ ** And PO-5\'s wall does NOT transfer: ** it turns on holonomy being the complete')
    print('     invariant of a FLAT CONNECTION.  ** PO-4\'s datum is a group ELEMENT, not connection')
    print('     data — the flat-locus argument has nothing to bite on. **')
    print('  ⇒ ⓸ ** So what the row owes is a SOURCE for a one-parameter subgroup: ** something in the')
    print('     geometry supplying a continuous parameter that exponentiates into the Cartan direction.')
    print('     ** Not "extend the reflection" — that is provably impossible. **')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
