#!/usr/bin/env python3
"""B58 -- the question r2811 filed as owed is ANSWERED IN P14, and more completely than it was asked:
a deformation within flat connections changes WHICH flat bundle, not WHETHER there is a field strength.

** THE OWED QUESTION.  r2811: ** *** "Does anything in the corpus produce a continuous direction in the
branching?" ***  ** P14 answers it, and answers a stronger version. **

** ⛭⛭⛭ ⓵ THE ANSWER, AND IT DOES NOT DEPEND ON THE DIMENSION COUNT. **  *** "But the dimension is a bonus
and not the argument.  ** The moduli space of flat connections consists of flat connections, so a
deformation within it changes which flat bundle one has and not whether there is a field strength. ** " ***

  ⇒⇒ *** SO EVEN IF A CONTINUOUS DIRECTION EXISTED, IT WOULD NOT HELP.  ** Moving within the moduli of
      flat connections moves between flat bundles; $F$ is zero at every point of that space. **  The
      question as r2811 posed it was the wrong question, and P14 says so in advance. ***

** ⓶ AND THE DIMENSION COUNT IS THERE TOO, WITH ITS REASON. **  *** "Deformations of the fundamental
group's representation that keep each wall's conjugacy class fixed are counted directly and the moduli
space is ** zero-dimensional **: a wall branches one vantage and leaves the other two alone, so its
monodromy carries a repeated eigenvalue and its class is ** subregular, of dimension four rather than
the regular six **; three regular classes on a three-punctured base would have left a two-parameter
family, and the ** disjointness of the vantages' supports ** is exactly what removes it." ***

** ⛭⛭ ⓷ AND THE FINITENESS HAS A REASON THIS LINE RE-DERIVED WITHOUT NOTICING. **  *** "The holonomy
group generated by the three wall monodromies together with the hinge three-cycle is finite, of order
81 --- ** necessarily so, since the holonomy is branching and a branch structure has finitely many
sheets ** --- and a finite group in characteristic zero has vanishing first cohomology with any
coefficients, so the representation does not deform as a representation of its own holonomy." ***

  ⌗ ** That is r2806's argument, in the paper, with the cohomological reason r2806 lacked. **

** ⓸ AND THE ORDER CHECKS OUT, WHICH IS THE ONE THING THIS RECEIPT ADDS. **  *** r2811's numerical
closure returned $18$ mod phase from a two-generator set.  Recomputed: $\\langle Z,C\\rangle$ is $27$ as
matrices, and $81=27\\times3$ with the full $\\mathbb Z_3$ centre of phases.  ** $18$ was an artefact of
quotienting by phase on a smaller generating set than P14's three walls plus the hinge -- P14's $81$
stands. ** ***

WHAT IS NOT CLAIMED.  ** Not that P14's order 81 is re-derived ** -- *** the count here uses two
generators and confirms consistency ($27$ matrices, $81$ with phases), not P14's specific three-wall
construction. ***  ** Not that r2806 and r2811 are wrong ** -- *** they are RE-DERIVATIONS: correct, and
already in the paper with better reasons. ***  ** Not that `PO-5` moves ** -- *** the owed item is
discharged as ANSWERED-IN-CORPUS, which shrinks the debt without advancing the row. ***

** COMPUTES: the closure of $\\langle Z,C\\rangle$ with and without quotienting by phase.
*** $Z$ is a diagonal $\\mathbb Z_3$ element and $C$ the hinge 3-cycle. *** **

⌗ **ABSENCE CLAIMS IN THIS RECEIPT ARE MEASURED AT 8b8990c** *(per c54.220's rule, r2776).*

Written r2813.  Stated for reversal.
"""
import os
import re

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def flat_p14():
    raw = open(os.path.join(ROOT, 'corpus', 'matter_sector_paper.tex'),
               encoding='utf-8', errors='replace').read()
    return re.sub(r'\s+', ' ', '\n'.join(l for l in raw.split('\n')
                                         if not l.lstrip().startswith('%')))


def close(gens, mod_phase):
    def key(M):
        if mod_phase:
            k = int(np.argmax(np.abs(M.flat)))
            M = M/np.exp(1j*np.angle(M.flat[k]))
        return tuple(np.round(M.flatten(), 6))
    G = {key(np.eye(3))}
    fr = [np.eye(3, dtype=complex)]
    for _ in range(12):
        new = []
        for M in fr:
            for g in gens:
                P = M @ g
                if key(P) not in G:
                    G.add(key(P))
                    new.append(P)
        fr = new
        if not new:
            break
    return len(G)


def main():
    print()
    print("  B58 -- is r2811's owed question already answered in P14?")
    print()
    p14 = flat_p14()

    check('⛭⛭⛭ ⓵ P14 answers a STRONGER version: "the moduli space of flat connections consists of '
          'flat connections, so a deformation within it changes which flat bundle one has and not '
          'whether there is a field strength"',
          'consists of flat connections' in p14 and 'not whether there is a field strength' in p14)
    check('and says the dimension is not load-bearing: "But the dimension is a bonus and not the '
          'argument"',
          'the dimension is a bonus and not the argument' in p14)

    check('⓶ while the count is there with its reason: the class is "subregular, of dimension four '
          'rather than the regular six", and "the disjointness of the vantages\' supports is exactly '
          'what removes it"',
          'subregular' in p14 and "disjointness of the vantages" in p14)

    check('⛭⛭ ⓷ and the finiteness has the reason r2806 lacked: "necessarily so, since the holonomy '
          'is branching and a branch structure has finitely many sheets --- and a finite group in '
          'characteristic zero has vanishing first cohomology"',
          'a branch structure has finitely many sheets' in p14
          and 'vanishing first cohomology' in p14)

    # ⓸ the order
    w = np.exp(2j*np.pi/3)
    Z = np.diag([1, w, w**2])
    C = np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]], dtype=complex)
    n_mat, n_ph = close([Z, C], False), close([Z, C], True)
    check(f'⓸ and P14\'s order 81 checks out: $\\langle Z,C\\rangle$ closes at {n_mat} as matrices, and '
          f'$81={n_mat}\\times3$ with the full $\\mathbb Z_3$ centre of phases -- ** r2811\'s {n_ph} was '
          'an artefact of quotienting by phase on a two-generator set **',
          n_mat == 27 and n_ph == 18)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print('  VERDICT: ** answered in P14, and a stronger version than r2811 asked. **')
    print('  ⛭⛭⛭ ⓵ *** "The moduli space of flat connections consists of flat connections, so a')
    print('     deformation within it changes which flat bundle one has and not whether there is a')
    print('     field strength." ***')
    print('     ⇒ ** So even if a continuous direction existed it would not help: F is zero at every')
    print('     point of that space. **  r2811 asked the wrong question and P14 says so in advance.')
    print('  ⓶ ** And the count is there with its reason: ** zero-dimensional, because a wall\'s class')
    print('     is ** subregular (dimension four, not the regular six) ** and the disjointness of the')
    print('     vantages\' supports removes the two-parameter family three regular classes would give.')
    print('  ⛭⛭ ⓷ ** And the finiteness has the reason r2806 lacked: ** "a branch structure has')
    print('     finitely many sheets", and ** a finite group in characteristic zero has vanishing')
    print('     first cohomology **, so the representation does not deform.')
    print(f'  ⓸ ** And P14\'s order 81 checks out: ** ⟨Z,C⟩ closes at {n_mat} as matrices, 81 with the')
    print(f'     full centre.  ** r2811\'s {n_ph} was an artefact of quotienting by phase. **')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
