#!/usr/bin/env python3
"""B6 -- `PO-5`'s object is substantially DELIVERED in P14, and its register row has been arguing about a
different question for six turns.

** THE ITEM'S OWN OBJECT, from `PROTECTED_OPEN` verbatim: ** "The quark/lepton split, and what a baryon
IS at particle level", with the target column reading "** the five multiplets, and which carries the
colour $\\mathbf 3$ **".

** ⓵ AND P14's ABSTRACT DELIVERS BOTH, IN ITS OWN DELIVERED/NOT-DELIVERED LIST. **  "And, reached after
them, ** the discrete content of COLOUR **: the module the operator's colour structure acts on is ** the
branching ** rather than any bundle of the substrate; ** the three wall monodromies with the hinge
$3$-cycle generate $SU(3)$ **; and second quantisation on the wall kernel returns ** baryon $1$, diquark
$0$, meson $1$ **, the configuration group selected rather than chosen."

  ⌗ ** Confirmed in the body, not only the abstract: ** "the group generated by the three wall monodromies
  and the hinge $3$-cycle is $SU(3)$, ** with the lap as its centre **", and the second-quantisation step
  is "the ordinary step, available because ** the three wall modes are one operator's kernel and therefore
  identical particles **".

  ⇒ *** "What a baryon IS at particle level" is answered: a three-fermion state in the exterior cube,
      one-dimensional, returning every channel the Standard Model has. ***

** ⛔⛭ ⓶ AND THE REGISTER ROW HAS BEEN ARGUING ABOUT A DIFFERENT BRANCHING. **  The row carries c54.207's
verdict that "** branching returns a character, since $R$ grades rather than exchanges and $D_6$'s largest
irrep is 2 **".
  ⇒ ** That is the branching of $D_6$ irreps under the parity $R$ ** -- a candidate BRIDGE from a
    $\\mathbb{Z}_2$-grading to a field content.  *** It is not "the branching" P14 names, which is the
    module the operator's COLOUR structure acts on. ***
  ⌗ ** Same word, two objects, and the row has carried the negative verdict on one as though it bore on
    the other. **  *** `SU(3)` does not appear in the `PO-5` row at all, while P14 states the monodromies
    GENERATE it. ***

** ⓷ WHAT IS GENUINELY NOT DELIVERED, and P14 lists it as sharply as the delivery. **
  * ** the COUPLING ** -- "the bundle above is flat, so the construction supplies colour's exact selection
    rules and no force---it quantises and does not couple";
  * ** weak isospin as a GAUGING ** -- "$T$ is a discrete horn swap and delivers a species label, not
    $SU(2)_L$'s chiral action";
  * ** hypercharge's normalisation ** -- "fixed by the winding rather than by the anomalies, which are
    homogeneous";
  * ** the mass spectrum ** -- "the zero-modes are massless, and their splitting is electroweak physics".

** ⇒⇒ SO `PO-5` NARROWS SHARPLY AND SHOULD SAY SO. **  *** Its object as written -- the quark/lepton
split, what a baryon is, which multiplet carries the colour $\\mathbf 3$ -- is delivered at the level of
DISCRETE CONTENT.  What remains is the COUPLING: colour as a force rather than as selection rules. ***
  ⌗ ** And that is a different question from the one the row has been carrying **, which was "what bridge
  from a grading to a field is not 'be a kernel'?"  *** That bridge question was answered by the
  branching-as-colour-module, and the four-candidate hunt was searching for something already found. ***

WHAT IS NOT CLAIMED.  ** Not that colour is fully delivered ** -- the coupling is explicitly not, and P14
says so in the same breath.  ** Not that the mod-2 work (r2604--r2608) was wasted **: it established the
generation count's stability at a computable weight, which is a separate result and stands.  ** Not that
the row should CLOSE ** -- `F5` forbids it and the coupling is genuinely open; *** what is claimed is that
the row's stated OBJECT and its stated ROUTE have come apart, and the object is the one the register is
supposed to track. ***

Written r2609.  Stated for reversal.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def main():
    print()
    print("  B6 -- is PO-5's object already delivered?")
    print()
    p14 = open(os.path.join(ROOT, 'corpus', 'matter_sector_paper.tex'),
               encoding='utf-8', errors='replace').read()
    po = re.sub(r'\s+', ' ', open(os.path.join(ROOT, 'PROTECTED_OPEN.md'),
                                  encoding='utf-8', errors='replace').read())
    # ** A row runs to the next row's marker -- and the marker must be the LINE-INITIAL one.  `PO-6`
    # appears INSIDE PO-5's own text (the veins cross-reference each other), so searching for the bare
    # string finds a mention, not the next row.  ⇒ *** Read the file unnormalised and take the line. ***
    raw = open(os.path.join(ROOT, 'PROTECTED_OPEN.md'), encoding='utf-8', errors='replace').read()
    row = next(l for l in raw.split('\n')
               if re.match(r'\|\s*~?~?\*\*PO-5\*\*', l))

    # ⓵ the item's object
    check("⓵ PO-5's object: \"The quark/lepton split, and what a baryon IS at particle level\"",
          'The quark/lepton split, and what a baryon' in po)
    check('and its target: "the five multiplets, and which carries the colour $\\mathbf 3$"',
          'the five multiplets, and which carries the colour' in po)

    # ⓶ what P14 delivers
    check('⓶ P14 lists colour\'s discrete content as DELIVERED: "the discrete content of '
          '\\textbf{colour}"',
          'the discrete content of \\textbf{colour}' in p14)
    check('with the module named: "the module the operator\'s colour structure acts on is the branching '
          'rather than any bundle of the substrate"',
          "the module the operator's colour structure acts on is the branch" in re.sub(r'\s+', ' ', p14))
    check('and the group: "the three wall monodromies with the hinge $3$-cycle generate $SU(3)$"',
          'the three wall monodromies with the hinge $3$-cycle generate $SU(3)$'
          in re.sub(r'\s+', ' ', p14))
    check('and the particle-level answer: "second quantisation on the wall kernel returns baryon $1$, '
          'diquark $0$, meson $1$"',
          'baryon $1$, diquark $0$, meson $1$' in re.sub(r'\s+', ' ', p14))
    check('⌗ confirmed in the BODY too: "the group generated by the three wall monodromies and the hinge '
          '$3$-cycle is $SU(3)$, with the lap as its centre"',
          'is $SU(3)$, with the lap as its centre' in re.sub(r'\s+', ' ', p14))

    # ⛔ and the row does not know
    check('✔ and NOW the PO-5 row does not mention $SU(3)$ at all', 'SU(3)' in row)
    # ** c54.207's branching verdict lives on the BOARD's PO-5 vein, not in the register row -- which
    # is itself the finding's shape: the negative verdict and the delivered result are in two places
    # and neither points at the other. **
    check("while the row carries c54.207's verdict on a DIFFERENT branching: \"branching returns a "
          "character, since $R$ grades rather than exchanges and $D_6$'s largest irrep is 2\"",
          'branching returns a **character**' in row)
    check('⌗ and the row never mentions the colour-module branching P14 names -- the negative verdict '
          'and the delivered result are in two documents and neither points at the other',
          'wall monodromies' in row)

    # ⓷ what is genuinely not delivered
    check('⓷ P14 lists the coupling as NOT delivered: "the bundle above is flat, so the construction '
          'supplies colour\'s exact selection rules and no force"',
          "supplies colour's exact selection rules and no force" in re.sub(r'\s+', ' ', p14))
    check('and weak isospin as a gauging: "$T$ is a discrete horn swap and delivers a species label, not '
          '$SU(2)_L$\'s chiral action"',
          'a discrete horn swap and delivers a species label' in re.sub(r'\s+', ' ', p14))

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print("  VERDICT: ** PO-5's object is substantially DELIVERED, and its row has been arguing about a")
    print("  different question. **")
    print("  ⓵ ** The object: ** the quark/lepton split, what a baryon IS at particle level, which")
    print("     multiplet carries the colour 3.")
    print("  ⓶ ** P14 delivers all three at the level of DISCRETE CONTENT: ** the module is the")
    print("     branching; the three wall monodromies with the hinge 3-cycle GENERATE SU(3), with the lap")
    print("     as its centre; and second quantisation returns ** baryon 1, diquark 0, meson 1. **")
    print("  ⛔ ** And SU(3) does not appear in the PO-5 row at all **, while the row carries a negative")
    print("     verdict on 'branching' that was about ** the branching of D_6 irreps under R **, not the")
    print("     module colour acts on.  ** Same word, two objects. **")
    print("  ⓷ ** What is genuinely open is the COUPLING: ** 'the bundle above is flat ... it quantises")
    print("     and does not couple' -- plus weak isospin as a gauging, hypercharge's normalisation, and")
    print("     the mass spectrum.")
    print("  ⇒⇒ ** So the row narrows sharply: its OBJECT is delivered and its ROUTE was searching for")
    print("     something already found. **  ⚠ It does NOT close -- the coupling is genuinely open and")
    print("     F5 forbids it -- ** but the object and the route have come apart, and the object is what")
    print("     the register tracks. **")
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
