#!/usr/bin/env python3
r"""C1 -- the Cartan/holonomy bake.  P14 and P07 report that the residue pairing's holonomy about the
branch points, "adjoined to the walls' S_3, closes the Weyl group of the substrate's own complexified
isometry algebra -- so the excess is substrate-derived rather than assumed."  Computed from scratch by
analytic continuation, the closure is CONFIRMED and it is GENERIC TO CUBICS: five one-parameter cubic
families all return the same group of order 24.  What is special is the other side -- the match to
|W(so(6,C))| happens at D_3 ALONE, among every classical and exceptional Weyl group of rank two or more.

COMPUTES: the monodromy of the horizon cubic r^3-r+2M and of its per-root square root sqrt(f'(r_i)),
continued numerically around each Nariai branch point and around infinity; the group they generate,
its image on the roots, its kernel, and its element-order profile; the same for four other cubic
families; a negative control that must stay trivial and a one-generator control that must stay small;
and the Weyl orders of every classical family at ranks 2-6 against the computed 24.  Nothing is fitted.

** ⛭ ⓵ WHAT THE CORPUS SAYS, AND IT SAYS IT IN TWO PAPERS. **  *`P07`: the residue pairing "has a
holonomy about the branch points---a Klein four-group ... and adjoining it closes the Weyl group of
$\so(6,C)$".  `P14`: the same, with the verdict* ***"so the excess is substrate-derived rather than
assumed."***

** ⛭⛭ ⓶ COMPUTED FROM SCRATCH, THE CLOSURE IS EXACTLY RIGHT. **  *Continuing three roots and three
branches of $\sqrt{f'(r_i)}$ around the two Nariai points and around infinity generates a group of
order* **24**, *whose image on the roots is $S_3$ and whose kernel is precisely the Klein four-group
the corpus reports -- the sign patterns with an even number of minus signs.*
  ⇒ ** Its element-order profile is {1:1, 2:9, 3:8, 4:6}, which is $S_4$'s and no other group of
    order 24. **  *And $S_4 = W(A_3) = W(D_3) = W(\so(6,C))$.*
  ⌗ ** No group theory is put in. **  *A cubic, a square root, and continuation along loops.*

** ⛔⛭⛭ ⓷ AND IT IS GENERIC TO CUBICS, WHICH IS THE BITE. **  *The same computation on
$r^3-r+M$, $r^3-4r+M$, $r^3+r+M$ and $r^3-7r+3M$ returns order 24, root image $S_3$, kernel the Klein
four-group and the $S_4$ profile -- every time.*
  ⇒ *** THE HORIZON CUBIC IS NOT SPECIAL HERE.  Any one-parameter depressed cubic family, taken with
      its per-root square root, delivers this group. ***
  ⌗ ** And the control CAN distinguish: ** *one lasso alone returns a group of order 4, and a loop
    enclosing no branch point returns the identity -- so a genuine difference would have shown.*
  ⇒ ** So "substrate-derived rather than assumed" is sound about the DERIVATION -- the Klein four-group
    really does come from the residue pairing's square roots and is not put in by hand -- and it
    misplaces the surprise. **  *The group is forced by the cubic.  What is not forced is that the
    substrate's Weyl group is the same group.*

** ⛭⛭ ⓸ AND THAT MATCH IS $D_3$ ALONE. **  *$|W(D_n)| = 2^{n-1}n!$: rank 2 gives 4, rank 3 gives 24,
rank 4 gives 192.  $|W(A_n)|=(n+1)!$ gives 24 only at $A_3$.  $B/C$ never.  $G_2$ is 12, $F_4$ 1152,
and the $E$ series larger still.*
  ⇒ *** Among every classical and exceptional Weyl group of rank two or more, the cubic's 24 selects
      $A_3 = D_3$ and nothing else -- and the two coincide because $\so(6,C) \cong \sl(4,C)$, a
      low-rank exceptional isomorphism. ***
  ⇒ ** So the closure is a rank-three fact, in the same shape as `P03`'s `rem:dimension`: it holds
    where it holds and fails immediately on either side. **  *At $\so(8,C)$ the cubic still gives 24
    and the Weyl group gives 192.*

** ⌗ ⓹ AND THE HALF THAT LOOKED NEW IS HELD -- CAREFULLY. **  *The relation that the deck $S_3$ is
generated by the two Nariai transpositions, with the three-cycle at infinity their composite, is not
a finding: `P05` carries it as `prop:monodromy` and `rem:monodromy-group`, and states the condition
the naive version misses --* ***"Two transpositions generate $S_3$ only if they differ, so the
generation claim rests on the two Nariai monodromies transposing different pairs of sheets, which is a
computation."***  ⇒ ** A bounce, and the corpus is ahead of the field on it. **

** ⚠ ⓺ THE APPARATUS IS ABSENT AND THE CONCLUSION DEPENDS ON IT. **  *`Ambrose--Singer` ×0,
`principal bundle` ×0, `frame bundle` ×0, `structure equation` ×0, `covariant derivative` ×0,
`torsion` ×0, `G-structure` ×0, `reduction of structure group` ×0 -- against `holonomy` ×33 and
`monodromy` ×60.*  ⇒ ** Ambrose--Singer is the theorem that makes flat imply discrete holonomy, which
is what licenses reading monodromy AS holonomy -- the step every computation above relies on. **
*The corpus uses the conclusion throughout and carries neither the theorem nor the word.*

WHAT IS NOT CLAIMED.  ** Not that the corpus is wrong ** -- the group, the Klein four-group, the
$S_3$, and the closure are all confirmed by independent computation.  ** Not that "substrate-derived"
is false ** -- the derivation is genuinely from the residue pairing; what the genericity shows is that
the RESULT is not distinctive, so the weight belongs on the match rather than on the derivation.
** Not that the match is a coincidence in the dismissive sense ** -- it is a low-rank isomorphism, it
is exact, and it is exactly the kind of thing this programme takes seriously; the claim is only that
it is a fact about $\so(6,C)$ and not about the cubic.  ** Not that the missing apparatus is an error
** -- nothing computed here is wrong for want of it; what is owed is the name of the theorem the
argument turns on.  ** And not that the bake read the whole field ** -- the boundary is in the ledger.

    python3 receipts/L273_the_cartan_bake/C1_the_weyl_closure_is_generic_to_cubics_and_the_match_is_D3_alone.py

Written r3164, `L-273`.  Stated for reversal.
"""
import cmath
import os
import sys
from collections import Counter
from math import factorial

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []
IDENT = ((0, 1, 2), (1, 1, 1))
S4_PROFILE = {1: 1, 2: 9, 3: 8, 4: 6}
#: the families, FIXED BEFORE THE COMPUTATION and reported whole.  (label, coeffs(M), a, qcoef)
FAMILIES = [('r^3 -  r + 2M   [THE HORIZON CUBIC]', lambda M: [1, 0, -1, 2 * M], -1, 2),
            ('r^3 -  r +  M                      ', lambda M: [1, 0, -1, M], -1, 1),
            ('r^3 - 4r +  M                      ', lambda M: [1, 0, -4, M], -4, 1),
            ('r^3 +  r +  M   [a>0, no real merge]', lambda M: [1, 0, 1, M], 1, 1),
            ('r^3 - 7r + 3M                      ', lambda M: [1, 0, -7, 3 * M], -7, 3)]


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def branch_points(a, qcoef):
    """r^3 + a r + qcoef*M : the discriminant -4a^3 - 27 q^2 vanishes at q = ±sqrt(-4a^3/27)"""
    m = cmath.sqrt(-4.0 * a ** 3 / 27.0) / qcoef
    return [m, -m]


def track(cf, M0, loop, steps=30000):
    """continue the roots AND the three branches of sqrt(f'(r_i)) along the loop"""
    def fpr(cs, r):
        return complex(np.polyder(np.poly1d(cs))(r))
    r = np.roots(cf(M0))
    s = np.array([cmath.sqrt(fpr(cf(M0), x)) for x in r])
    r0, s0 = r.copy(), s.copy()
    for k in range(1, steps + 1):
        cs = cf(loop(k / steps))
        new = np.roots(cs)
        used, order = set(), []
        for x in r:
            j = min((j for j in range(3) if j not in used), key=lambda j: abs(new[j] - x))
            used.add(j)
            order.append(j)
        r = new[order]
        cand = np.array([cmath.sqrt(fpr(cs, x)) for x in r])
        s = np.where(abs(cand - s) <= abs(-cand - s), cand, -cand)
    perm = tuple(int(min(range(3), key=lambda j: abs(r0[j] - r[i]))) for i in range(3))
    sign = tuple(int(round((s[i] / s0[perm[i]]).real)) for i in range(3))
    return perm, sign


def compose(x, y):
    """x then y, in the group of (root permutation, sign vector) pairs"""
    px, sx = x
    py, sy = y
    return (tuple(py[px[i]] for i in range(3)),
            tuple(sx[i] * sy[px[i]] for i in range(3)))


def lasso(c, rad, base):
    def L(t):
        if t < .25:
            return base + (t / .25) * ((c + rad) - base)
        if t < .75:
            return c + rad * cmath.exp(1j * (t - .25) / .5 * 2 * cmath.pi)
        return (c + rad) + ((t - .75) / .25) * (base - (c + rad))
    return L


def about_infinity(R, base):
    def L(t):
        if t < .15:
            return base + (t / .15) * (1j * R - base)
        if t < .85:
            return 1j * R * cmath.exp(1j * (t - .15) / .7 * 2 * cmath.pi)
        return 1j * R + ((t - .85) / .15) * (base - 1j * R)
    return L


def generated(gens):
    G, frontier = {IDENT}, [IDENT]
    while frontier:
        x = frontier.pop()
        for y in gens:
            z = compose(x, y)
            if z not in G:
                G.add(z)
                frontier.append(z)
    return G


def order_of(x):
    y, n = x, 1
    while y != IDENT:
        y = compose(y, x)
        n += 1
        if n > 200:
            return None
    return n


def analyse(cf, a, qcoef, base=0.55j, rad=0.03):
    gens = [track(cf, base, lasso(c, rad, base)) for c in branch_points(a, qcoef)]
    gens.append(track(cf, base, about_infinity(80.0, base)))
    G = generated(gens)
    roots_img = {p for p, _ in G}
    kernel = {s for p, s in G if p == (0, 1, 2)}
    prof = dict(sorted(Counter(order_of(x) for x in G).items()))
    return gens, G, roots_img, kernel, prof



#: ** ⛭ THE BAKE'S BASELINE AT ITS OWN THROW (r3988), counted the way `TOTW` counts -- word-bounded,
#: ** raw and de-macroed, the larger taken -- because a baseline compared under a different
#: ** preprocessing is not a comparison.
_AT_THROW_CACHE = {}


def _at_throw_wordcount(term):
    #: ⌗ `reach_baseline` is imported inside `main()` in this file, not at module scope, so it is
    #:   imported here rather than assumed global.  *I assumed it was a module-level name because
    #:   the sibling station receipts bind it that way, and the assumption cost a five-minute run.*
    import re as _re
    import subprocess as _sp
    sys.path.insert(0, os.path.join(ROOT, 'corpus'))
    import reach_baseline as RB
    if not _AT_THROW_CACHE:
        for _tex, _key in RB.TEX2P.items():
            _raw = _sp.run(['git', 'show', f'b55c782f:corpus/{_tex}'], cwd=ROOT,
                           capture_output=True, text=True, errors='replace').stdout
            _b = '\n'.join(l for l in _raw.split('\n') if not l.lstrip().startswith('%'))
            _j = _b.find('\\begin{thebibliography}')
            _body = _re.sub(r'\s+', ' ', _b[:_j] if _j > 0 else _b)
            _AT_THROW_CACHE[_key] = (_body, RB.demacro(_body))
        assert len(_AT_THROW_CACHE) == len(RB.TEX2P), (
            'every paper must be readable at the throw, or the baseline is partial')
    pat = _re.compile(r'\b' + _re.escape(term) + r'\b', _re.I)
    return max(sum(len(pat.findall(v[0])) for v in _AT_THROW_CACHE.values()),
               sum(len(pat.findall(v[1])) for v in _AT_THROW_CACHE.values()))


def main():
    print()
    print('  C1 -- the Weyl closure is generic to cubics, and the match is D_3 alone')
    print()

    print('  ' + '=' * 74)
    print('  PART 1 -- ⛭⛭ THE HORIZON CUBIC, COMPUTED FROM SCRATCH')
    print('  ==========================================================================')
    cf, a, q = FAMILIES[0][1], FAMILIES[0][2], FAMILIES[0][3]
    bps = branch_points(a, q)
    print(f'      branch points at M = ±{abs(bps[0]):.9f}   (discriminant 4 - 108M^2)')
    gens, G, roots_img, kernel, prof = analyse(cf, a, q)
    for nm, g in zip(('γ+', 'γ-', 'γ∞'), gens):
        print(f'      {nm}  roots {g[0]}   sqrt-signs {g[1]}')
    print(f'      |G| = {len(G)}   root image order {len(roots_img)}   kernel order {len(kernel)}')
    print(f'      element-order profile {prof}')
    check(f'⓵ the two Nariai loops are TRANSPOSITIONS and the loop about infinity is a 3-CYCLE',
          all(len([i for i in range(3) if gens[k][0][i] != i]) == 2 for k in (0, 1))
          and len([i for i in range(3) if gens[2][0][i] != i]) == 3)
    rp = lambda x, y: tuple(y[x[i]] for i in range(3))
    check('⓵ᵇ and they satisfy the thrice-punctured sphere\'s relation on the roots: '
          'γ+·γ-·γ∞ = 1',
          rp(rp(gens[0][0], gens[1][0]), gens[2][0]) == (0, 1, 2))
    check(f'⓵ᶜ the group they generate has order {len(G)}, its image on the roots is S_3 (order '
          f'{len(roots_img)}), and its kernel has order {len(kernel)}',
          len(G) == 24 and len(roots_img) == 6 and len(kernel) == 4)
    check('⓵ᵈ ⛭ and the kernel IS the corpus\'s Klein four-group: exactly the sign patterns with '
          'an even number of minus signs, which is P05\'s unimodularity constraint arrived at by '
          'continuation rather than by algebra',
          kernel == {(1, 1, 1), (1, -1, -1), (-1, 1, -1), (-1, -1, 1)})
    check(f'⓵ᵉ ⛭⛭ and the element-order profile is S_4\'s and no other order-24 group\'s: {prof} '
          '-- so G ≅ S_4 = W(A_3) = W(D_3) = W(so(6,C)), with NO group theory put in',
          prof == S4_PROFILE)

    print()
    print('  ' + '=' * 74)
    print('  PART 2 -- ⌗ THE CONTROLS, BOTH DIRECTIONS')
    print('  ==========================================================================')
    triv = track(cf, 0.55j, lasso(1.5, 0.03, 0.55j))
    check(f'⓶ a loop enclosing NO branch point returns the identity {triv}, so the continuation '
          'is not manufacturing monodromy', triv == IDENT)
    one = generated([track(cf, 0.55j, lasso(bps[0], 0.03, 0.55j))])
    check(f'⓶ᵇ and ONE generator alone gives a group of order {len(one)}, not 24 -- so the method '
          'can tell a small group from a large one and 24 is a measurement',
          len(one) < 24)
    alt = analyse(cf, a, q, base=0.9j, rad=0.05)
    check(f'⓶ᶜ the answer is robust to the base point and the lasso radius: order {len(alt[1])}, '
          f'root image {len(alt[2])}, kernel {len(alt[3])} from a different base',
          len(alt[1]) == 24 and len(alt[2]) == 6 and len(alt[3]) == 4)

    print()
    print('  ' + '=' * 74)
    print('  PART 3 -- ⛔⛭⛭ AND IT IS GENERIC TO CUBICS, WHICH IS THE BITE')
    print('  ==========================================================================')
    print('      family                                  |G|  roots  kernel  = S_4?')
    results = {}
    for label, f, aa, qq in FAMILIES:
        _, GG, ri, kk, pp = analyse(f, aa, qq)
        results[label] = (len(GG), len(ri), len(kk), pp == S4_PROFILE)
        print(f'      {label}  {len(GG):3d}   {len(ri):3d}    {len(kk):3d}    {pp == S4_PROFILE}')
    check(f'⓷ ⛔ ALL {len(FAMILIES)} one-parameter cubic families return order 24, root image S_3, '
          'the Klein four-group kernel and the S_4 profile -- the horizon cubic is not special here',
          all(v == (24, 6, 4, True) for v in results.values()))
    check('⓷ᵇ ⛭ so "the excess is substrate-derived rather than assumed" is sound about the '
          'DERIVATION and misplaces the surprise: the Klein four-group really does come from the '
          'residue pairing rather than by hand, and the GROUP is forced by the cubic',
          results[FAMILIES[0][0]] == results[FAMILIES[3][0]])

    print()
    print('  ' + '=' * 74)
    print('  PART 4 -- ⛭⛭ AND THE MATCH IS D_3 ALONE')
    print('  ==========================================================================')
    print('      rank |  |W(A_n)|   |W(B_n/C_n)|   |W(D_n)|   matches 24')
    matches = []
    for n in range(2, 7):
        A, B, D = factorial(n + 1), 2 ** n * factorial(n), 2 ** (n - 1) * factorial(n)
        hit = [nm for nm, v in (('A', A), ('B/C', B), ('D', D)) if v == 24]
        matches += [(nm, n) for nm in hit]
        print(f'       {n}   |  {A:<9d}  {B:<12d}  {D:<9d}  {hit if hit else "-"}')
    check('⓸ among the classical families at ranks 2 through 6, exactly A_3 and D_3 have Weyl '
          'group of order 24 -- and they coincide because so(6,C) ≅ sl(4,C)',
          sorted(matches) == [('A', 3), ('D', 3)])
    exceptional = {'G2': 12, 'F4': 1152, 'E6': 51840, 'E7': 2903040, 'E8': 696729600}
    check(f'⓸ᵇ and no exceptional Weyl group has order 24 either {exceptional}',
          24 not in exceptional.values())
    check('⓸ᶜ ⛭⛭ SO THE CLOSURE IS A RANK-THREE FACT: at so(8,C) the cubic still gives 24 and the '
          f'Weyl group gives {2**3*factorial(4)} -- it holds where it holds and fails immediately '
          'on either side, which is the shape of P03\'s rem:dimension',
          2 ** 3 * factorial(4) != 24 and 2 ** 1 * factorial(2) != 24)

    print()
    print('  ' + '=' * 74)
    print('  PART 5 -- ⌗ THE HALF THAT LOOKED NEW IS HELD, AND HELD CAREFULLY')
    print('  ==========================================================================')
    sys.path.insert(0, os.path.join(ROOT, 'corpus'))
    import reach_baseline as RB
    p05 = RB.BODIES_TEX['P05']
    check('⓹ P05 carries the two-transposition generation as a proposition, not a remark in '
          'passing: "The monodromy of the horizon cubic about a Nariai branch point is the '
          'transposition exchanging the two roots that collide there"',
          'transposition exchanging the two roots that collide there' in p05)
    check('⓹ᵇ ⛭ and it states the condition the naive version misses: "Two transpositions generate '
          '$S_{3}$ only if they differ, so the generation claim ... rests on the two Nariai '
          'monodromies transposing different pairs of sheets, which is a computation"',
          'only if they differ' in p05 and 'different pairs of sheets' in p05)
    check('⓹ᶜ and it says the computation was run -- "Verified numerically by continuation in the '
          'complex $2M$-plane" -- so this is a BOUNCE and the corpus is ahead of the field on it',
          'Verified numerically by continuation' in p05)

    print()
    print('  ' + '=' * 74)
    print('  PART 6 -- ⚠ THE APPARATUS IS ABSENT AND THE CONCLUSION TURNS ON IT')
    print('  ==========================================================================')
    absent = ['Ambrose-Singer', 'principal bundle', 'frame bundle', 'structure equation',
              'covariant derivative', 'torsion', 'G-structure', 'reduction of structure group']
    rows = RB.survey(absent + ['holonomy', 'monodromy'])
    # ** WORD-BOUNDED, and that is not a detail: the loose count reported `G-structure` ×1 by
    #   matching inside `breakin**g-structure**`, in a sentence about symmetry breaking. **
    def TOTW(term):
        return max(sum(RB.word_counts(term).values()),
                   sum(RB.word_counts(term, tex=True).values()))
    TOT = {t: max(raw, dem) for t, raw, _, dem in rows}
    # ** ⛭⛭ RE-PINNED r3988, AND ONE TERM OF THE EIGHT HAS SINCE ARRIVED. **  This bake's finding is
    # ** that the corpus COMPUTES the holonomy invariant and carries none of the bundle apparatus
    # ** that names it.  `principal bundle` is in P12 now (×2), landed with the Atiyah-sequence work
    # ** at r3251 -- "the theatre results carried INTO the papers, which is what a bake is for" --
    # ** which is the neighbouring station Ⓖ being answered, not this bake being wrong.
    # **   ⇒ ** The baseline is pinned at this bake's own throw, where all eight were zero, and the
    # **     seven that are STILL zero are asserted live. **  *An absence measured before a throw is
    # **     a baseline; asserted after the throws land, it says nobody acted on any of them.*
    # **   ⌗ The finding is unchanged and ⓺ᵇ below carries it: `holonomy` and `monodromy` are
    # **     substantial while the apparatus is not, and one term arriving does not make an
    # **     apparatus -- which is why the count for it is REPORTED rather than merely tolerated.
    _AT_THROW = 'b55c782f'          # r3164 -- this bake's own throw
    _then = {t: _at_throw_wordcount(t) for t in absent}
    check(f'⓺ every term of the bundle apparatus was ×0 across the seventeen paper bodies at '
          f'{_AT_THROW}, de-macroed AND word-bounded: {_then}',
          all(v == 0 for v in _then.values()))
    _now = {t: TOTW(t) for t in absent if TOTW(t)}
    check(f'⓺ᵃ¹ ⛭ and {len(absent) - len(_now)} of the {len(absent)} are still ×0; what has arrived '
          f'is {_now} -- `principal bundle` with the Atiyah-sequence landing at r3251, which is '
          f'station Ⓖ being answered next door and not an apparatus appearing',
          len(_now) <= 1 and set(_now) <= {'principal bundle'}
          and all(TOTW(t) == 0 for t in absent if t != 'principal bundle'))
    check('⓺ᵃ ⚠ AND ONE OF THEM WAS A FALSE HOLE THE OTHER WAY: the substring count returned '
          '`G-structure` ×1, matching inside `breaking-structure` in a sentence about symmetry '
          'breaking -- the third substring artefact in this session, so the word-bounded report '
          'is now carried by `reach_baseline` itself rather than by each bake',
          TOT['G-structure'] > 0 and TOTW('G-structure') == 0
          and 'WORD-BOUNDED' in open(os.path.join(ROOT, 'corpus', 'reach_baseline.py'),
                                     encoding='utf-8', errors='replace').read())
    check(f'⓺ᵇ while `holonomy` ×{TOTW("holonomy")} and `monodromy` ×{TOTW("monodromy")} are '
          'substantial -- so the corpus computes the invariant and carries none of the structure '
          'it is normally defined in',
          TOTW('holonomy') > 20 and TOTW('monodromy') > 40)
    check('⓺ᶜ ⚠ and the missing theorem is the load-bearing one: Ambrose--Singer is what makes a '
          'FLAT connection have discrete holonomy, which is what licenses reading monodromy AS '
          'holonomy -- the step every computation in this receipt relies on',
          TOTW('Ambrose-Singer') == 0)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        for f in FAILED:
            print(f'    - {f[:160]}')
        return 1
    print('  VERDICT: ** the closure is confirmed, it is generic to cubics, and the match is')
    print('  D_3 alone. **')
    print('  *Continuing a cubic and its per-root square root around the two Nariai points and')
    print('  around infinity generates a group of order 24 whose root image is S_3 and whose')
    print('  kernel is the corpus\'s own Klein four-group — profile S_4 = W(so(6,C)), with no')
    print('  group theory put in.  The corpus is right.*')
    print('  ⛔ ** And four other cubic families give the same group. **  *So "substrate-derived')
    print('     rather than assumed" is sound about the derivation and misplaces the surprise:')
    print('     the group is forced by the cubic; what is not forced is that the substrate\'s')
    print('     Weyl group is the same group.*')
    print('  ⛭ ** That match is D_3 alone ** — among every classical and exceptional Weyl group of')
    print('     rank two or more, the cubic\'s 24 selects A_3 = D_3 and nothing else, the two')
    print('     coinciding by the isomorphism so(6,C) ≅ sl(4,C).  *At so(8,C) the cubic still')
    print('     gives 24 and the Weyl group gives 192.*')
    print('  ⌗ ** A bounce and an owed name: ** *P05 already holds the two-transposition')
    print('     generation, with the condition the naive version misses; and Ambrose–Singer, the')
    print('     theorem the whole reading turns on, appears nowhere in seventeen papers.*')
    print()
    return 0


if __name__ == '__main__':
    sys.exit(main())
