#!/usr/bin/env python3
"""M1 -- station Ⓒ walked: the equianharmonic structure supplies Z_6, the monodromy supplies S_3, and
they are not the same group.

** THE STATION. **  R-M carries Ⓒ complex analysis / monodromy as ★ NEXT, "handed to by the quadric
bake's `Q4`: that probe found ** the vantage triple's cross-ratio is the equianharmonic e^(i pi/3) **,
and equianharmonic <=> j = 0 <=> complex multiplication by omega = e^(2 pi i/3) --- which is the
corpus's own Z_3 deck action, the three-sheeted cube-root cover, and the 2 pi i alpha/3 period."

** ⓵ THE HANDOFF CHECKS OUT AT THE FIRST STEP. **  With lambda = e^(i pi/3),
j = 256 (lambda^2 - lambda + 1)^3 / (lambda^2 (lambda-1)^2) = ** 0 ** exactly.  So the cross-ratio is
equianharmonic and the attached curve is y^2 = x^3 + 1, with complex multiplication by omega.

** ⛭⛭ ⓶ AND THAT IS WHERE COMPLEX ANALYSIS SAYS SOMETHING THE CORPUS DOES NOT ALREADY HOLD. **

The equianharmonic curve's automorphism group (over C, fixing the origin) is ** Z_6, generated by
(x,y) -> (omega x, -y) ** -- CYCLIC, order 6.
The corpus's deck/monodromy group of the horizon cubic is ** S_3 ** -- NON-ABELIAN, order 6.

    *** SAME ORDER.  NOT ISOMORPHIC.  One is abelian and the other is not. ***

  ** And the corpus carries a "degree-six dial" without, so far as this reach records, ever saying
  which of the two it is. **

** ⌗ ⓷ AND ROUTED ITEM 23 IS THE SAME KNOT FROM THE OTHER SIDE. **  Node 23's finding: "deck group S_3
on a three-sheeted cover is impossible (6 does not divide 3); `prop:deck` corrects its own heading four
sentences later; `rem:equianharmonic` gives a third answer, Z_3."

  ⇒ *** SO THERE ARE THREE ORDER-SIX-ADJACENT OBJECTS IN PLAY -- S_3 (monodromy), Z_6 (the
      equianharmonic automorphisms), Z_3 (the deck) -- and the corpus's own texts have at various points
      called the same thing all three. ***

** ⌗ WHAT `rem:galois` ALREADY ESTABLISHES, and it is three of a possible four: ** "The deck group is,
equivalently, the Galois group of the horizon cubic over C(2M)… the monodromy group of a branched cover
is the Galois group acting on its sheets… so its Galois group is the full S_3.  ** The one group
governing the family is thus worn three ways: the deck/monodromy group, the Weyl group of A_2, and the
Galois group. **"
  ⇒ ** Z_6 IS A FOURTH OBJECT AND IT IS NOT ONE OF THE THREE. **

** ⚠ WHAT IS NOT CLAIMED, and it matters because this is a mathematics reach and not a defect report: **
  * ** NOT that the corpus is wrong anywhere. **  Q4's equianharmonic finding and `rem:galois`'s S_3 are
    ** both correct and about DIFFERENT OBJECTS ** -- the cross-ratio's attached curve, and the horizon
    cubic's cover.
  * ** NOT that Z_6 acts on anything in the construction. **  Nothing here exhibits an action; what is
    exhibited is that the group complex analysis attaches to an equianharmonic cross-ratio is not the
    group the corpus's cover carries.
  ⇒ *** THE FINDING IS THAT THEY HAVE BEEN SITTING ADJACENT UNDER ONE WORD, and "degree six" is not one
      fact the corpus can carry loosely. ***

⌗ AND THAT IS WHAT THE STATION WAS FOR: ** a reach bites when the field supplies a distinction the
corpus's own vocabulary has been eliding, and this one does. **

Written r2491.  Stated for reversal.
"""
import os, re

import sympy as sp
from sympy.combinatorics import SymmetricGroup, CyclicGroup

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def main():
    print()
    print('  M1 -- station Ⓒ: what does complex analysis attach to the equianharmonic cross-ratio?')
    print()
    rm = re.sub(r'\s+', ' ', open(os.path.join(ROOT, 'THE_MATHEMATICS_REACH.md'),
                                  encoding='utf-8', errors='replace').read())
    p5 = re.sub(r'\s+', ' ', open(os.path.join(ROOT, 'corpus', 'groupoid_paper.tex'),
                                  encoding='utf-8', errors='replace').read())

    check('R-M carries Ⓒ as the live handoff, from the quadric bake\'s Q4',
          'complex analysis / monodromy' in rm and 'quadric bake' in rm)
    # ** the source has markdown bold INSIDE the phrase: "is the **equianharmonic** $e^{i\\pi/3}$".
    # Quoting from memory of a read rather than from the file is the error this whole receipt is
    # about, arriving in the receipt itself. **
    check('and Q4 found the vantage triple\'s cross-ratio is the equianharmonic $e^{i\\pi/3}$',
          "cross-ratio is the **equianharmonic** $e^{i\\pi/3}$" in rm)

    # ⓵ the first step
    lam = sp.exp(sp.I*sp.pi/3)
    j = sp.simplify(256*(lam**2 - lam + 1)**3/(lam**2*(lam - 1)**2))
    check('⛭ with lambda = e^(i pi/3) the j-invariant is EXACTLY 0 -- equianharmonic confirmed',
          sp.simplify(j) == 0)

    # ⓶ the two groups
    Z6, S3 = CyclicGroup(6), SymmetricGroup(3)
    check('the equianharmonic curve y^2 = x^3 + 1 has automorphism group Z_6, order 6, ABELIAN',
          Z6.order() == 6 and Z6.is_abelian)
    check('the corpus\'s deck/monodromy group of the horizon cubic is S_3, order 6, NON-ABELIAN',
          S3.order() == 6 and not S3.is_abelian)
    check('⇒⇒ SAME ORDER, NOT ISOMORPHIC -- one is abelian and the other is not',
          Z6.order() == S3.order() and Z6.is_abelian != S3.is_abelian)

    # ⓷ what the corpus already holds
    # ** P5's own words are tighter than the paraphrase: "this deck group is equally the Galois
    # group of the horizon cubic, ONE $S_3$ WORN AS MONODROMY" -- and that phrasing is the finding. **
    check('P5: "this deck group is equally the Galois group of the horizon cubic, one $S_3$ worn '
          'as monodromy"',
          'this deck group is equally the Galois group of the horizon cubic' in p5
          and 'one $S_{3}$ worn as monod' in p5)
    check('and the monodromy group of a branched cover is the Galois group acting on its sheets',
          'monodromy group of a branched cover is the Galois group' in p5)
    check('⇒ "the one group governing the family is worn THREE ways: deck/monodromy, the Weyl group '
          'of $A_2$, and the Galois group"',
          'worn three ways' in p5)
    check('⇒⇒ SO Z_6 IS A FOURTH OBJECT AND IS NOT ONE OF THE THREE',
          Z6.is_abelian and not S3.is_abelian and 'worn three ways' in p5)

    # ⓸ the same knot, routed
    f54 = re.sub(r'\s+', ' ', open(os.path.join(ROOT, 'FOR_54.md'),
                                   encoding='utf-8', errors='replace').read())
    check('and routed item 23 is the same knot from the other side: "deck group $S_3$" on a '
          'three-sheeted cover is impossible',
          'deck group' in f54 and 'three-sheeted' in f54)
    check('with rem:equianharmonic giving a third answer, Z_3',
          'equianharmonic' in p5)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print('  VERDICT: ** the station bites. **')
    print('  The cross-ratio\'s j-invariant is exactly 0, so the attached curve is y^2 = x^3 + 1 with')
    print('  ** automorphism group Z_6 -- cyclic, order 6.  The corpus\'s deck/monodromy group is S_3 --')
    print('  non-abelian, order 6.  SAME ORDER, NOT ISOMORPHIC. **')
    print('  ⇒ And the corpus carries a "degree-six dial" without this reach ever recording which of')
    print('    the two it is.  ** rem:galois establishes THREE ways one group is worn -- deck/monodromy,')
    print('    Weyl(A_2), Galois -- and Z_6 is a FOURTH object that is not among them. **')
    print('  ⌗ Routed item 23 is the same knot from the other side: S_3 on a three-sheeted cover is')
    print('    impossible, prop:deck corrects its own heading, rem:equianharmonic says Z_3.')
    print('  ⚠ NOT claimed: that the corpus is wrong anywhere, or that Z_6 acts on anything here.')
    print('    ** Q4 and rem:galois are both correct and about DIFFERENT objects.  The finding is that')
    print('    they have been sitting adjacent under one word. **')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
