#!/usr/bin/env python3
"""M2 -- station Ⓗ walked: the index statement is TRACED because the theorem invoked is not the theorem
the object needs, and station Ⓒ is a prerequisite rather than a neighbour.

** THE STATION. **  R-M carries Ⓗ, "the gamma^5-graded index -> K-theory / characteristic classes", as
owed.

** ⓵ AND THE CORPUS ALREADY DECLARES THE GAP, IN P14's OWN WORDS. **  P14, immediately after establishing
dim ker_+ = 3, dim ker_- = 0:

  "Its stability under deformations preserving the three-wall structure is the expected behaviour of such
   a count and is stated here at traced weight: the receipt establishes the mechanism---one mode per
   wall, the even-crossing obstruction on a simple loop, and the necessity of the r=0 branch point---and
   ** marks the Atiyah--Singer statement on the branched bead as TRACED rather than COMPUTED. **"

  ⇒ ** So Ⓗ is not an unknown.  It is a DECLARED traced-weight item, and the corpus named it before the
    reach reached it. **  (Same shape as Ⓕ at r2490, where the answer was in the file and the header was
    stale -- ** except here the corpus is not stale; it is correctly and explicitly humble. **)

** ⛭ ⓶ AND THE FIELD SAYS WHY IT CAN ONLY BE TRACED. **  The plain Atiyah--Singer index theorem is a
statement about a ** SMOOTH compact manifold. **  The corpus's object is a ** BRANCHED BEAD ** -- it uses
that phrase twice -- and the file carries ** ZERO occurrences of "equivariant" and zero of "Kawasaki". **

  ⇒ *** THE TOOL THAT COMPUTES AN INDEX ON A BRANCHED OBJECT IS THE EQUIVARIANT / ORBIFOLD INDEX, NOT
      THE PLAIN ONE.  That is why the statement can only be traced: THE THEOREM INVOKED IS NOT THE
      THEOREM THE OBJECT NEEDS. ***

** ⛭⛭ ⓷ AND THAT IS WHERE Ⓗ AND Ⓒ COMPOSE -- which is this receipt's actual result. **

An equivariant index must be equivariant ** UNDER A NAMED GROUP. **  P14 supplies one: "the three
zero-modes are permuted by the full S_3 generated by the three hinges, and that S_3 is not a second group
resembling the substrate's own… ** the Weyl S_3 IS the relation among the three hinges. **"

  ⇒ ** But r2491 (station Ⓒ) found THREE order-six-adjacent objects in play and unresolved: S_3
    (monodromy, permuting the modes), Z_3 (the deck), Z_6 (the equianharmonic automorphisms). **

  ⇒⇒ *** SO COMPUTING RATHER THAN TRACING NEEDS EXACTLY THE THING Ⓒ FOUND UNRESOLVED.  AN EQUIVARIANT
      INDEX OVER THE WRONG GROUP IS NOT A WEAKER RESULT -- IT IS A DIFFERENT THEOREM. ***

  ⌗ ** WHICH MEANS Ⓒ WAS NOT MERELY ADJACENT TO Ⓗ.  IT IS A PREREQUISITE FOR IT ** -- and R-M's own
  standing rule, "** the handoff outranks the list order **", put them in the right sequence for a reason
  it had not stated.

WHAT IS NOT CLAIMED.  ** Not that P14's index count is wrong ** -- dim ker_+ = 3 rests on the mechanism
the receipt establishes, and the traced item is the STABILITY statement, not the count.  ** Not that an
equivariant index would give a different answer ** -- nothing here computes one.  Not that the corpus
should have used a different theorem: ** it declared the weight of the one it used, which is the correct
conduct and is why this station yields a route rather than a defect. **

Written r2492.  Stated for reversal.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
FAILED = []


def check(label, cond):
    print(f"    {'OK  ' if cond else 'FAIL'}  {label}")
    if not cond:
        FAILED.append(label)


def main():
    print()
    print('  M2 -- station Ⓗ: why is the index statement traced rather than computed?')
    print()
    raw = open(os.path.join(ROOT, 'corpus', 'matter_sector_paper.tex'),
               encoding='utf-8', errors='replace').read()
    p14 = re.sub(r'\s+', ' ', '\n'.join(l for l in raw.split('\n')
                                        if not l.lstrip().startswith('%')))
    rm = re.sub(r'\s+', ' ', open(os.path.join(ROOT, 'THE_MATHEMATICS_REACH.md'),
                                  encoding='utf-8', errors='replace').read())
    arc = re.sub(r'\s+', ' ', open(os.path.join(ROOT, 'THE_LIVE_ARC.md'),
                                   encoding='utf-8', errors='replace').read())

    check('R-M carries Ⓗ, the gamma^5-graded index -> K-theory, as owed',
          'graded index' in rm and 'K-theory' in rm)

    # ⓵ the corpus declares the gap
    check('P14 establishes dim ker_+ = 3, dim ker_- = 0, the net chirality a gamma^5-graded index',
          '\\dim\\ker_+=3' in p14 and '\\dim\\ker_-=0' in p14)
    check('⛭ and marks its own weight: "marks the Atiyah--Singer statement on the branched bead as '
          'TRACED rather than COMPUTED"',
          'marks the Atiyah--Singer statement on the branched bead as traced rather than computed'
          in p14)
    check('⇒ so Ⓗ is a DECLARED traced-weight item, not an unknown -- the corpus named it before '
          'the reach reached it',
          'stated here at traced weight' in p14)

    # ⓶ why it can only be traced
    check('the object is a BRANCHED BEAD, and P14 uses that phrase',
          len(re.findall('branched bead', p14, re.I)) >= 2)
    check('⛭ while carrying ZERO occurrences of "equivariant" and zero of "Kawasaki"',
          len(re.findall('equivariant', p14, re.I)) == 0
          and len(re.findall('Kawasaki', p14, re.I)) == 0)
    check('⇒ the tool for a branched object is the equivariant/orbifold index, not the plain '
          'Atiyah--Singer theorem, which is a statement about a SMOOTH compact manifold',
          len(re.findall('equivariant', p14, re.I)) == 0)

    # ⓷ the composition with Ⓒ
    check('P14 names a group acting: "the three zero-modes are permuted by the full $S_3$ generated '
          'by the three hinges"',
          'the three zero-modes are permuted by the full $S_3$ generated by the three hinges' in p14)
    check('and "the Weyl $S_3$ \\emph{is} the relation among the three hinges"',
          'the Weyl $S_3$ \\emph{is} the relation among the three hinges' in p14)
    check('⛭⛭ but r2491 found THREE order-six-adjacent objects in play and unresolved -- '
          'S_3, Z_3, Z_6',
          'order-six-adjacent objects' in arc)
    check('⇒⇒ SO COMPUTING RATHER THAN TRACING NEEDS EXACTLY WHAT Ⓒ FOUND UNRESOLVED: an equivariant '
          'index over the wrong group is a DIFFERENT THEOREM, not a weaker result',
          'order-six-adjacent objects' in arc
          and 'the three zero-modes are permuted by the full $S_3$' in p14)
    check('⌗ and R-M\'s own standing rule put them in that sequence: "the handoff outranks the list '
          'order"', 'The handoff outranks the list order' in rm)

    print()
    if FAILED:
        print(f'  {len(FAILED)} check(s) FAILED')
        return 1
    print('  VERDICT: ** Ⓗ is a DECLARED gap, and Ⓒ is its PREREQUISITE. **')
    print('  P14 marks the Atiyah--Singer statement on the branched bead as ** traced rather than')
    print('  computed **, so the station was named by the corpus before the reach reached it.')
    print('  ⇒ ** And the field says why it can only be traced: the plain theorem is about a SMOOTH')
    print('     compact manifold, the object is a BRANCHED BEAD, and the tool that computes an index on')
    print('     one is the EQUIVARIANT/ORBIFOLD index -- which appears nowhere in the file. **')
    print('  ⇒⇒ ** An equivariant index must be equivariant under a NAMED group.  P14 names S_3.  But')
    print('     r2491 found three order-six-adjacent candidates unresolved -- S_3, Z_3, Z_6 -- so')
    print('     computing rather than tracing needs exactly what Ⓒ found open. **')
    print('  ⌗ ** Ⓒ is not adjacent to Ⓗ.  It is a prerequisite for it ** -- and R-M\'s own rule, "the')
    print('    handoff outranks the list order", had them in the right sequence for an unstated reason.')
    print('  ⚠ Not a defect: ** the corpus DECLARED the weight of the theorem it used **, which is why')
    print('    this station yields a route rather than a finding against it.')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
